### ISSUE TITLE
Migration guide should mention DisplayRootViewFor

### ISSUE THREAD

**Issue by jdpilgrim** [Caliburn-Micro/Caliburn.Micro#116]
The ["Migrating Projects to 2.0.0" page on caliburn.com](http://caliburnmicro.com/documentation/migrating-to-2.0.0) should mention the requirement for a call to `DisplayRootViewFor`:

    protected override void OnStartup(object sender, StartupEventArgs e)
    {
        DisplayRootViewFor<ShellViewModel>();
    }

**Comment by tibel** [comment]
Thanks for the hint.
