### ISSUE TITLE
Marking as errors in IDE

### ISSUE THREAD

**Issue by shersh** [Caliburn-Micro/Caliburn.Micro#119]
Visual Studio marking Screen and other classes from Caliburn.Micro as errors but compile.

See screenshot:
![bug](https://cloud.githubusercontent.com/assets/376841/5891317/14e3b6cc-a49f-11e4-9331-6933e09b9831.jpg)

**Comment by shersh** [comment]
Windows Phone 8 project

**Comment by nigel-sampson** [comment]
How did you add the reference to Caliburn.Micro?

**Comment by shersh** [comment]
Via nuget package.
And tried download and compile iteself.

**Comment by nigel-sampson** [comment]
I've been trying to recreate this with no luck, can you confirm the paths that nuget is setting for the CM assemblies.

**Comment by tibel** [comment]
May you provide a sample project that shows the issue, please.

**Comment by nigel-sampson** [comment]
Unable to recreate and no further information given.
