### ISSUE TITLE
Caliburn Micro Conductor opening other conductors 

### ISSUE THREAD

**Issue by coding786** [Caliburn-Micro/Caliburn.Micro#121]
Please suggest some resource/sample to implement following scenario, using Caliburn Micro :

Main Page -Conductor A Main Page has two tabs - Each tab opens two conductors B and C 

Conductor B has two screens -Screen 1 and Screen 2 

Conductor C has two screens -Screen 3 and Screen 4

Screens 1,2,3,4 publishes events using EventAggergator to Conductor A based on which Conductor A decides to enable/disable the two tabs (activate/deactivate Conductors B and C)

**Comment by nigel-sampson** [comment]
I don't know of any samples that have that exact arrangement but I can't see anything immediately wrong with what you've described. Contact me if you're having any specific problems implementing this solution.

**Comment by nigel-sampson** [comment]
Answered on StackOverflow.
