### ISSUE TITLE
Cannot navigate to the view model that contains the name of the assembly

### ISSUE THREAD

**Issue by PaulDotNet** [Caliburn-Micro/Caliburn.Micro#124]
Problem:
If assembly name partially matches the name of the view model then navigation fails due to incorrect uri.
Example:
If assembly is called Monkey and view model name is MonkeyPageViewModel then 
navigationService.UriFor<MonkeyPageViewModel> will try to navigate to /Views/Page.xaml

Error location: ViewLocator.DeterminePackUriFromType 
Line: var uri = viewType.FullName.Replace(assemblyName, string.Empty).Replace(".", "/") + ".xaml";

**Comment by nigel-sampson** [comment]
That certainly looks like an issue, thanks.
