### ISSUE TITLE
Advanced Metro.Flyouts not being activated by Caliburn.Micro

### ISSUE THREAD

**Issue by JobaDiniz** [Caliburn-Micro/Caliburn.Micro#136]
I've created a repro project, please take a look: [google drive](https://drive.google.com/file/d/0B0eTPJd26KakN0h6UGFYY2pUa0k/view?usp=sharing)

I want to show in metro flyout the same views as I show in normal way. However, **Caliburn does not activate all of the views in the flyout**. It's rather complex to explain, that's why I've created de repro.

Follow these steps:

1. When you first open the app, you will see the main view, which contains 2 tabs (Dial Pad and Contact)
2. Navigate on those and you'll see everything works just fine. All views are activated.
3. In the Dial Pad view there is a button to open a flyout. Click on it.
4. A flyout will open with the same view structure.
5. Navigate on those and you'll see that **Contact will not be activated**. Only Dial Pad is activated.

The structure of views of my app (to help understand):

- `IShell`
  - Manages `IContainer` instances *- shows one at a time*.
  - Manages `IFlyout` instances *- shows one at a time*.

- `IContainer`
  - Acts like the current view showed by `IShell`
  - Can be anything, Conductor, Screen, Conductor.Collection...

- `IPhone`
  - Is an `IContainer`.
  - Manages `IPhoneScreen` instances *- shows multiple at a time*.

- `IPhoneScreen`
  - Acts like a view of `IPhone`.
  - Usually is a Caliburn `Screen`.

- `DialPadViewModel`
  - Is a simple `IPhoneScreen`.

- `IContact`
  - Is a complex `IPhoneScreen`.
  - Manages *contact* screens: list e edit screens for example.

- `IContactList`
  - Is one of the screens managed by `IContact`.

- `IContactEdit` **do not showed in the _repro_**
  - Is one of the screens managed by `IContact`.

**Comment by nigel-sampson** [comment]
So the reason the conductor tree isn't being activated in `PhoneViewModel''s children isn't that you're not actually activating `PhoneViewModel'`. In the `Open` method you're calling `OnActivate` which as the name suggests doesn't actually do any activation, but is simply called when the current screen / conductor is activated.

A quick and dirty fix is trimming `Open` down to:

``` csharp
public void Open()
{
    IsOpen = true;
}
```

and `ShowPhone` to 

``` csharp
public void ShowPhone()
{
    var phone = Flyouts.FirstOfType<IPhone>();

    ((IActivate)phone).Activate();
    phone.Open();
}
```

You'll most likely want to have `IFlyout` inherit `IActivate` or something similar. A more advanced solution is to use a custom Window Manager.

**Comment by JobaDiniz** [comment]
I can't believe this!
I've been trying for days... 

Thank you very much!
