### ISSUE TITLE
nlog + message.attach is some cases == "No actionable element for"

### ISSUE THREAD

**Issue by bondarenkod** [Caliburn-Micro/Caliburn.Micro#138]
Hi! 
I have code, which works well. 
 (no any logger references in project, etc)
...
 <DataGrid ItemsSource="{Binding Items}"
...
  cal:Message.Attach="[Event MouseDoubleClick] = [Action ItemSelectedCommand2]"
...
So, it works! 

But, when I attach my custom logger (1 class wrapper around nLog) or Caliburn.Micro.NLog, the ItemSelectedCommand2 will not call.

Without any added (just in reverences) logger (debug log) I see:
[Caliburn.Micro.ActionMessage] INFO: Action: ItemSelectedCommand2 availability update.

What's wrong?

**Comment by bondarenkod** [comment]
Can't reproduce in new project :(

**Comment by nigel-sampson** [comment]
Are you using the [nuget package](https://www.nuget.org/packages/Caliburn.Micro.Logging.NLog/) or a custom implementation of `ILog`? Also which platform are you seeing this on?

**Comment by bondarenkod** [comment]
No, I used standard debug log.
I tried to use NLogLogger - the problem is same. 
I have video for you, can you look? 
https://www.youtube.com/watch?v=QoQ7vO56YJM

**Comment by nigel-sampson** [comment]
One thing I noticed in the video is that you're not configuring `LogManager` for NLog? It appears as the Caliburn log output is using `DebugLog`. Are you doing any logging in the method wrapped by ItemSelectedCommand2?

**Comment by bondarenkod** [comment]
>>that you're not configuring  LogManager  for NLog

yes, but the error (the method doesn't calling by Caliburn) still same if I using configured NLog. 

I am about method, which Caliburn doesn't invoke when I just adding reference to NLog dll (and including the config file, of course). 

I have spend some time for this error and tried a lot different cases. I don't have any minds why isn't work properly. 

My next step - is debugging the Caliburn source. Maybe I will find something. Or not, because I can't reproduce this error in new project.

**Comment by nigel-sampson** [comment]
Sorry but I'm not following. 

 - Are you changing `LogManager.GetLog` at all? If so what to?
 - What does the logging call inside `ItemSelectedCommand2` look like?

**Comment by tibel** [comment]
Try using using the Caliburn.Micro integrated logger. This will/should always work.

Add the following line to your bootstrappers constructor before the `Initialize()` method:
```
LogManager.GetLog = type => new DebugLog(type);
```

I do not think there is any issue inside Caliburn.Micro with logging.

**Comment by nigel-sampson** [comment]
Closing as no further information given and doesn't appear to be an issue.
