### ISSUE TITLE
PCL navigation

### ISSUE THREAD

**Issue by tapanila** [Caliburn-Micro/Caliburn.Micro#139]
I have my ViewModels at PCL.
Currently I have Interface at PCL project and then implementation  in Windows 8.1 project.
Which use the NavigationService.

Would there be anyway to put all the logic into PCL?

**Comment by nigel-sampson** [comment]
Sorry I'm not following what the problem is.

**Comment by tapanila** [comment]
Currently I can't access INavigationService interface from PCL, since it's not part of the Caliburn.Micro.Core

Since I still want to do navigation inside of my ViewModels which reside in PCL. I have created a new interface in PCL and then implemented that in my Windows 8.1 project.

I was just wondering what's the reason that the INavigationService is not part of the Caliburn.Micro.Core?

Also is there some other way I should do the navigation in this case?

**Comment by nigel-sampson** [comment]
Ah ok, thanks for the clarification, clearly I need more coffee.

I have considered moving `INavigationService` to Caliburn.Micro.Core but there are a number of issues that I decided not to.

The biggest issue is that having in the PCL enforces the requirement that the signature be the same for all platforms. For the most part that's no problem, but examples where they differ are that Windows Phone 8.1 exposes the BackPressed event while Windows 8.1 lets you manipulate the back and forward stacks.

Having one interface over all platforms means exposing that functionality on all non implemented platforms most likely throwing a `NotSupportedException`.

I suspect this problem would be exacerbated even further if we add Xamarin into the mix.

At the moment your current solution is probably the best.

**Comment by tapanila** [comment]
Thanks for the information behind the decision.

I think it totally makes sense

**Comment by nigel-sampson** [comment]
Have been thinking about this some more and how I would go about this.

I would most likely have an application specific navigation service.
``` csharp
public interface IApplicationNavigation
{
    void ToProduct(Product product);
    void ToPurchase();
}
```
Where the implementation would use the platform specific navigation service.
``` csharp
public class ApplicationNavigation : IApplicationNavigation
{
    public void ToProduct(Product product)
    {
          navigationService.UriFor<ProductDetailsViewModel>()
              .WithParam(v => v.ProductId, product.Id)
              .Navigate();

        ...
    }
}

**Comment by tapanila** [comment]
I think that kind of interface makes way more sense than just creating an interface to act between NavigationService.

How would you handle the receiving of the parameter on ViewModel? Since it doesn't have access to NavigationService.

**Comment by nigel-sampson** [comment]
Caliburn will automatically populate that property `ProductId` with the correct value. 

Internally what happens is we pack the values into a uri that gets passed a the navigation parameter. The navigation service then unpacks them on the navigation completion and populates the properties.
