### ISSUE TITLE
Xamarin - Native & Forms

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#142]
Currently a place-holder issue for commits / branches and discussion about what adding support for the new platforms will look like.

### All platforms
- [x] Configure nuget packages
- [x] Caliburn.Micro.Platform.Mobile needs xml and build dir docs
- [x] Xml docs
- [x] It looks like we'll need to introduce a third assembly for shared platform types, breaking change for the ABI. Should we update all projects including ones that shouldn't be affected such as WPF and SL5? We can't have a PCL that covers .NET 4.0 and SL5 so may leave them as it.
- [ ] Website documentation
- [ ] More samples

### Xamarin.iOS

- [ ] Implement navigation service.
- [ ] Does the view model locator conventions make sense with the current bugs in the storyboard editor?
- [ ] Determine what should be in the extensions project.

### Xamarin.Android

- [ ] Implement navigation service.
- [ ] Determine what should be in the extensions project.

### Xamain.Forms

This is going to be interesting as it's essentially a platform on top of a platform. Most likely we'll treat it as a Platform assembly that's Portable across iOS and Android. This stuff may end up in it's own namespace so that works well with Xamarin native.

- [x] No progammatic access to the value of x:Name, [Confirmed](http://forums.xamarin.com/discussion/comment/112957#Comment_112957).
- [x] `VisualElement` does not have `Loaded`, `Unloaded` events. This can potentially cause some memory leaks as we can't clean up properly.
- [x] Doesn't appear to be a way to check to see if a `BindableProperty` is bound, [Confirmed](http://forums.xamarin.com/discussion/comment/112957#Comment_112957). Affects `Action.HasTargetSet`.
- [x] How do we structure this so we can have `ViewModelLocator` for both Xamarin Native & Xamarin Forms at the same time? We're using a multi platform approach where Xamarin.Forms classes live in Caliburn.Micro.Xamarin.Forms.
- [x] On `NavigationPage.Pushed` the `NavigationEventArgs.Page` and `CurrentPage` are the same, so we can't get access to the previous page for deactivate, potentially could store our own reference. Imagine the same will be with `Popped`.
- [x] `NavigationPage` doesn't have the concept of a navigation parameter, makes things interesting.
- [x] Triggers are a property on `VisualElement` and not an attached dependency property. This could have implications on where `cm:Message.Attach` could be used.
- [x] `TriggerAction<T>` doesn't inherit from `BindableObject`. While `ActionMessage` does have some dependency properties we may be able to get around them.
- [x] Doesn't appear that the `TriggerBase` passes any data to the `TriggerAction` via `Invoke`. This is very problematic as it means we won't have `ActionExecutionContext.EventArgs`.
- [ ] Xamarin Forms has a custom Application Delegate, would collide with what we've done for Xamarin Native. Technically the CaliburnApplicationDelegate doesn't actually need to inherit from UIApplicationDelegate but does it for completeness with the other platforms where we subclass Application. This does mean we can hack around it with just instantiating our second app delegate within the first. Crude and need a better solution for release. If we create a CaliburnApplicationDelegate that inherits from the correct Xamarin one then we would need a Caliburn.Micro.Platform.Forms.iOS assembly. Not ideal for one type. This could be ok if we start to get rid of the extensions assemblies.
- [ ] Have another look at `FormsApplication` is there a better way?
- [x] Navigation Service should handle the close guards.
- [x] Rename methods to be more consistent with the other navigation services.
- [ ] Determine what should be in the extensions project.
- [ ] How can we leverage `DependencyService` for those automatic registrations

**Comment by nigel-sampson** [comment]
Have a question. I'm considering adding something akin to `ViewLocator` for Xamarin.Android. This wouldn't be as fully featured as the normal `ViewLocator` as it would most likely just have the `LocateTypeForModelType` method. This would be very useful in a navigation service so that we can turn a request to navigate to `MyApp.ViewModels.SomethingViewModel` into `MyApp.Actitivies.SomethingActivity`.

The question is that while `Activity` takes the place of the xaml `Page` in the MVVM pattern should we call this class `ActivityLocator` or `ViewLocator`?

**Comment by altso** [comment]
Would be nice to have an example of usage of `INavigationService`. Hello.Forms contains only single view/view-model.

**Comment by nigel-sampson** [comment]
Yup, it's definitely on the list to improve the sample and add support for things like `UriFor<T>` (with potentially a better name).

**Comment by altso** [comment]
Ok, I figured out how to make a navigation to another page. You just need to use `Caliburn.Micro.Xamarin.Forms.INavigtionService` (with missing `a`, see PR #172) instead of `Caliburn.Micro.INavigationService`.

**Comment by nigel-sampson** [comment]
Thanks for the fix, right now the service just takes a single parameter and populates the `Parameter` property, full `UriFor<T>` support is coming.

**Comment by jonstelly** [comment]
From the blog post announcing 3.0, it really seems like a couple of the issues are candidates to take to the Xamarin folks.  i.e. no programmatic access to x:Name in Xamarin Forms.  That seems like it might be low-hanging-fruit for them to fix on their end.  Are you in touch with them, trying to work those sorts of issues?

**Comment by nigel-sampson** [comment]
I've contacted one of the Xamarin Forms devs a while ago about these, these were mentioned as low hanging fruit but haven't seen any progress yet.

**Comment by nigel-sampson** [comment]
Xamarin Forms support in 3.0.0 released.

**Comment by alexr422** [comment]
Could you guys explain how to use navigation?
