### ISSUE TITLE
DataContext not set for a view by convention

### ISSUE THREAD

**Issue by toozenbobel** [Caliburn-Micro/Caliburn.Micro#143]
Steps to reproduce:
1. Create new WPF project. (.net 4.5 vs2013)
2. nuget: Install-Package Caliburn.Micro
3. Implement basic AppBootstrapper (just like its implemented in tutorial)
4. Add View and ViewModel according to convention
5. Start application

Actual result:
View is shown, but its DataContext is null.

Expected result:
View is show with ViewModel as DataContext

Note:
I tried to update Caliburn.Micro on working application. It's not working now too.

**Comment by tibel** [comment]
May you attach a complete sample project to show the issue, please.
Also what tutorial are you referencing to.

**Comment by toozenbobel** [comment]
I written that sample.
One view with one view model and simple container. DataContext is null
https://onedrive.live.com/?cid=358e9da585573956&id=358E9DA585573956%2149603&ithint=file,zip&authkey=!AOELGKxxL0axZWE

**Comment by tibel** [comment]
There is only one issue in your bootstrapper, then it will work:
You have to call `Initialize()` instead of `StartRuntime()`.

``` C#
		public AppBootstrapper()
		{
            Initialize();
		}
```

What tutorial suggests that you should call StartRuntime?

**Comment by toozenbobel** [comment]
I don't remember exactly. I just copied that code from my another project. It worked fine till the update.

This tutorial for example:
http://www.cnblogs.com/zhouyongh/archive/2011/04/22/2018989.html

**Comment by mvermef** [comment]
That is really old code to reference, suggest the samples in the source
