### ISSUE TITLE
Design-time binding does not work with caliburn.micro 2.0.2

### ISSUE THREAD

**Issue by QuantumDeveloper** [Caliburn-Micro/Caliburn.Micro#144]
I want to use design-time binding in WPF with caliburn.micro version 2.0.2. I made simple test project and add neccessary settings for that:
```
<Window x:Class="CaliburnTest.MainView"
         xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
         xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
         xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
         mc:Ignorable="d" 
          xmlns:caliburn="http://www.caliburnproject.org"
          xmlns:caliburnTest="clr-namespace:CaliburnTest"
          d:DataContext="{d:DesignInstance caliburnTest:MainView, IsDesignTimeCreatable=True}"
        caliburn:Bind.AtDesignTime="True">
<Grid>
  <TextBlock Name="Test" Width="150" Height="50"/>
```
As a result I dont see value of textblock in design-time, but I see it after app starts. Could someone tell me what I am missing here? Maybe some additional settings?

**Comment by mvermef** [comment]
Are you viewfirst or viewmodel first?  You setting MainView as your instance

**Comment by QuantumDeveloper** [comment]
ViewModel first:
in botstrapper I do:

protected override void OnStartup(object sender, StartupEventArgs e)
      {
         DisplayRootViewFor<MainViewModel>();
      }

**Comment by mvermef** [comment]
MainViewModel would be your instance for viewmodelfirst

**Comment by mvermef** [comment]
d:DataContext="{d:DesignInstance caliburnTest:MainViewModel, IsDesignTimeCreatable=True}"

**Comment by sevenate** [comment]
Try to set `<TextBlock Name="Test" caliburn:Bind.AtDesignTime="True" Width="150" Height="50"/>`.

**Comment by QuantumDeveloper** [comment]
Everything is working - thanks. The problem was that Xaml designer works correctly in design mode only in release build configuration and not in debug unfortunately.
