### ISSUE TITLE
System.Windows.Interactivity missing in NuGet package

### ISSUE THREAD

**Issue by bluerobotch** [Caliburn-Micro/Caliburn.Micro#145]
The dependency System.Windows.Interactivity (Blend SDK) is missing in the version 2.0.2 NuGet package. This change wasn't mentioned in the release notes.

**Comment by tibel** [comment]
This is now included using nuget:
``` xml
<frameworkAssembly assemblyName="System.Windows.Interactivity" targetFramework="net40,net45,sl5,wp8" />
```

I think this is the preferred way in including `System.Windows.Interactivity`.

**Comment by bluerobotch** [comment]
System.Windows.Interactivity is part of the Blend SDK and not part of the standard .Net Framework. Therefore you have to install the Blend SDK first, which, by the way, is installed along with Visual Studio 2013.
I think the preferred way would be a dependency to the following nuget package https://www.nuget.org/packages/Expression.Blend.Sdk/

**Comment by tibel** [comment]
I'm using the described method in another project and it works like a charm with VS2013.

**Comment by bluerobotch** [comment]
The downside of this method is that in a continuous integration environment you have to install the Blend SDK on all of your build agents. This is something we don't want to do.
Our workaround at the moment is to add the expression blend sdk package.

**Comment by nigel-sampson** [comment]
I'd be a bit concerned taking on a dependency to a third party managed nuget package for a Microsoft assembly.

**Comment by DELUXEnized** [comment]
I am also using the workaround from tible. I am more concerned with having to install the Blend SDK on all our build agents.

**Comment by nazbrok** [comment]
Are ou going to readd it in the caliburn package ? as mentionned above, installing blend on the build server isn't something we want to do.

**Comment by nigel-sampson** [comment]
I've had a chat with some people at Microsoft and it doesn't look like we'll be seeing an official distribution of the Interactivity SDK via nuget. This leaves us with three options:

1. No change, reference via `frameworkAssembly` and require the assemblies on build servers via some mechanism.
2. Take a dependency on a third party distribution via nuget.
3. Revert the change and distribute the assemblies with the Caliburn.Micro packages.

I don't like 2, and while 1 is the recommended approach it feels like we may need to fall back to distributing again. I've noticed most of the other MVVM frameworks still do this.

**Comment by 2moveit** [comment]
Hi, I just felt into the trap with with point 1. So I need to install something on the server. If someone else checks out the sources the same problem might appear. I don't like the third party distribution either.
I think point 3 looks best right now.

**Comment by nigel-sampson** [comment]
We've reverted back to the old behaviour of including the packages on the 3.0.0-beta1 distribution.

Going forward we weren't going to be able to use powershell to add extension references in nuget v3 (at least for the moment). I've been involved in discussions in getting some of these things distributed via nuget rather than extensions.

**Comment by professor-k** [comment]
IANAL, but just checked EULA for Blend SDK. It requires redistribution to happen under conditions not lesser than original Blend SDK EULA. I believe that in this case Caliburn Micro (and respectively projects using it) can't be licensed under MIT, am I wrong?

**Comment by nigel-sampson** [comment]
You're most likely correct here IANAL.

Unfortunately none of the solutions I presented two years ago have got any better.

**Comment by Phyxion** [comment]
@nigel-sampson 
Several years later
https://blogs.msdn.microsoft.com/dotnet/2018/12/10/open-sourcing-xaml-behaviors-for-wpf/
It's now a NuGet package, would be nice if this could be used now 👍

**Comment by nigel-sampson** [comment]
Yup, it's on my list for 4.0.0.

**Comment by nietras** [comment]
I am using Caliburn.Micro 3.0.1 but can't get `System.Windows.Interactivity` working here. I get errors like:
```
The tag 'EventTrigger' does not exist in XML namespace 'http://schemas.microsoft.com/xaml/behaviors'. 
```
for code like:
```xml
                                               <ContentControl cal:View.Model="{Binding}">
                                                    <i:Interaction.Triggers>
                                                        <i:EventTrigger EventName="Click">
                                                            <cal:ActionMessage MethodName="SayHello">
                                                                <cal:Parameter Value="{Binding ElementName=Image}" />
                                                            </cal:ActionMessage>
                                                        </i:EventTrigger>
                                                    </i:Interaction.Triggers>
                                                </ContentControl>
```
I tried using nuget package which then removes this error, but the `cal:ActionMessage` does not appear to be compatible with `TriggerAction` anymore. If not using nuget package I have a reference:
```xml
    <Reference Include="System.Windows.Interactivity" />
```
which as mentioned errors with EventTrigger not existing. Is there any chance I can resolve this is some way. This is in Visual Studio 2022 and targeting `net47`.

**Comment by nietras** [comment]
Ah had to change reference to use dll directly instead of namespace:
```xml
        xmlns:i="clr-namespace:System.Windows.Interactivity;assembly=System.Windows.Interactivity"
```
