### ISSUE TITLE
CalburnApplication does not call AssemblySourceCache.Install()

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#147]
Just noticed that `CaliburnApplication` doesn't call `AssemblySourceCache.Install()` like `Bootstrapper`.

**Comment by nigel-sampson** [comment]
Been having some issues with AssemblySourceCache, need to double check all is good before adding it to the WinRT platforms.

**Comment by tibel** [comment]
In WPF `AssemblySourceCache` makes problems in DesignMode so it is used in RuntimeMode only.

**Comment by nigel-sampson** [comment]
Managed to track down my issues to my own stupid bug, should be all good to integrate into run time winrt.

**Comment by nigel-sampson** [comment]
This could be considered a breaking change as will affect the types returned from `ViewLocator` and `ViewModelLocator`.

**Comment by nigel-sampson** [comment]
Included in the 3.0.0 branch since this could introduce breaking changes to an app.
