### ISSUE TITLE
enumerator was not disposed

### ISSUE THREAD

**Issue by lobster2012-user** [Caliburn-Micro/Caliburn.Micro#150]
Example
DefaultCloseStrategy

**Comment by nigel-sampson** [comment]
Can you provide some more information about what you mean here?

**Comment by lobster2012-user** [comment]
Caliburn code does not call manually 'dispose' method of ienumerator<>

**Comment by KeldorKatarn** [comment]
This needs to be reopened. The using block is a major bug. If the guard callback is deferred it will call the Evaluate method on an already disposed enumerator. The current startegy of deferring the continuation of the loop to a callback is not working together with the using block.

**Comment by KeldorKatarn** [comment]
I recommand an approach that avoids the enumerator. Passing the enumerator out in a lambda that survived the using block will just not work. It's also inherently dangerous since the enumerable might actually change by the time the enumerator is called again. It might be invalid.

I suggest this instead:

`public void Execute(IEnumerable<T> toClose, Action<bool, IEnumerable<T>> callback)
        {
            var toCloseArray = toClose.ToArray();
            Evaluate(new EvaluationState() { StillToEvaluate = toCloseArray.Length }, toCloseArray, callback);
        }

        void Evaluate(EvaluationState state, IEnumerable<T> toClose, Action<bool, IEnumerable<T>> callback) {
            foreach (var closable in toClose) {
                var current = closable;
                var guard = current as IGuardClose;

                if (guard != null) {
                    guard.CanClose(canClose => {
                        if (canClose) {
                            state.Closable.Add(current);
                        }

                        state.FinalResult = state.FinalResult && canClose;
                        state.StillToEvaluate--;
                        Evaluate(state, new T[] { }, callback);
                    });
                } else {
                    state.Closable.Add(current);
                    state.StillToEvaluate--;
                }
            }

            if (state.StillToEvaluate == 0)
            {
                callback(state.FinalResult, closeConductedItemsWhenConductorCannotClose ? state.Closable : new List<T>());
            }
        }

        class EvaluationState {
            public readonly List<T> Closable = new List<T>();
            public bool FinalResult = true;
            public int StillToEvaluate = 0;
        }`

**Comment by nigel-sampson** [comment]
Can you provide a repro of the bug you're describing.

**Comment by KeldorKatarn** [comment]
The stress unit test in the conductor tests actually DOES reproduce it. But not all enumerators throw if disposed. The standard list enumerator doesn't seem to, since it doesn't hold any important resources. but if you implement your own enumerator, that does happen indeed. And on some platforms, like some versions of the mono runtime, the unit test fails because the enumerator DOES throw in their implementation. I only got it to throw in Unity's Mono runtime but using a disposed enumerator is bad, if it throws or not. If you step through that unit test you can see that the code is leaving the using block, leaving the enumerator disposed, then LATER the call to the DeferredCloseScreen.TryClose() method returns to the Evaluate method and it used the disposed enumerator with enumerator.MoveNext().

To reproduce the exception reliably I have to feed my own IEnumerable<> into the Execute method of the DefaultCloseStartegy. One that returns an IEnumerator<> that actually does throw if accessed after being disposed:

   public static void Main()
        {
            var strategy = new DefaultCloseStrategy<IGuardClose>();

            var conductor = new ScreenConductor();

            var screen1 = new DeferredCloseScreen();
            var screen2 = new DeferredCloseScreen();

            conductor.Screens.Add(screen1);
            conductor.Screens.Add(screen2);

            strategy.Execute(conductor, (b, closes) => { });

            screen1.TryClose();
            screen2.TryClose();
        }

    public class DeferredCloseScreen : Screen
    {
        Action<bool> closeCallback;

        public override void CanClose(Action<bool> callback)
        {
            this.closeCallback = callback;
        }

        public override void TryClose(bool? dialogResult = null)
        {
            if (this.closeCallback != null)
            {
                this.closeCallback(true);
            }
        }
    }

    public class ScreenConductor : IEnumerable<IGuardClose>
    {
        public List<IGuardClose> Screens = new List<IGuardClose>();

        /// <summary>Returns an enumerator that iterates through the collection.</summary>
        /// <returns>A <see cref="T:System.Collections.Generic.IEnumerator`1" /> that can be used to iterate through the collection.</returns>
        public IEnumerator<IGuardClose> GetEnumerator()
        {
            return new ScreenEnumerator(this);
        }

        /// <summary>Returns an enumerator that iterates through a collection.</summary>
        /// <returns>An <see cref="T:System.Collections.IEnumerator" /> object that can be used to iterate through the collection.</returns>
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public class ScreenEnumerator : IEnumerator<IGuardClose>
        {
            private readonly ScreenConductor conductor;
            private int index = -1;

            /// <summary>Initializes a new instance of the <see cref="T:System.Object" /> class.</summary>
            public ScreenEnumerator(ScreenConductor conductor)
            {
                this.conductor = conductor;
            }

            private bool _isDisposed;

            private void ThrowIfDisposed()
            {
                if (this._isDisposed)
                    throw new ObjectDisposedException("BUG!");
            }

            /// <summary>Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.</summary>
            public void Dispose()
            {
                _isDisposed = true;
            }

            /// <summary>Advances the enumerator to the next element of the collection.</summary>
            /// <returns>true if the enumerator was successfully advanced to the next element; false if the enumerator has passed the end of the collection.</returns>
            /// <exception cref="T:System.InvalidOperationException">The collection was modified after the enumerator was created. </exception>
            public bool MoveNext()
            {
                ThrowIfDisposed();
                return (++index < this.conductor.Screens.Count);
            }

            /// <summary>Sets the enumerator to its initial position, which is before the first element in the collection.</summary>
            /// <exception cref="T:System.InvalidOperationException">The collection was modified after the enumerator was created. </exception>
            public void Reset()
            {
                ThrowIfDisposed();
                index = -1;
            }

            /// <summary>Gets the element in the collection at the current position of the enumerator.</summary>
            /// <returns>The element in the collection at the current position of the enumerator.</returns>
            public IGuardClose Current
            {
                get
                {
                    ThrowIfDisposed();
                    return this.conductor.Screens[this.index];
                }
            }

            /// <summary>Gets the current element in the collection.</summary>
            /// <returns>The current element in the collection.</returns>
            object IEnumerator.Current
            {
                get
                {
                    ThrowIfDisposed();
                    return Current;
                }
            }
        }
    }
