### ISSUE TITLE
Action conventions for async methods

### ISSUE THREAD

**Issue by BrunoJuchli** [Caliburn-Micro/Caliburn.Micro#154]
The current conventions are like `x:Name="Delete"` ==> Binds to methods `Delete()` and guard property `CanDelete`.

The [guideline](https://msdn.microsoft.com/en-us/library/hh191443.aspx#BKMK_NamingConvention) for methods with `async` modifiers is to add an `Async` suffix to them. For example:

    public async Task DeleteAsync()

Now there's a question:
should the convention pick up `x:Name="Delete"` => `DeleteAsync()` or should we rename to `x:Name="DeleteAsync"`?

Also, the convention should accept guard methods which don't have an `Async` suffix. For example:

    public async Task DeleteAsync();
    public bool CanDelete { get; }

per guideline the property should not have an Async suffix because it's not `async`.

**Comment by nigel-sampson** [comment]
It's certainly something to discuss. I'm ok with what you're proposing here.

Not sure when I'll get to it however :-)

**Comment by BrunoJuchli** [comment]
thanks. If you can give me a pointer where the relevant code is located (roughly) i'll might be able to take a stab at it in the next few days or weeks :)

**Comment by nigel-sampson** [comment]
The code that does the matching is in [ViewModelBinder](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ViewModelBinder.cs#L121). 

What I would add is code to check if the return type of the method is assignable to `Task` and the method name ends in "Async". If so then remove the "Async" from the method name. Only if it can't find a correct match on the exact name.

**Comment by altso** [comment]
Is it ok in general to bind event handlers to methods that return `Task`? I see that any exceptions are swallowed if method returns `Task`, but got propagated to `Application.UnhandledException` if method is `void`.

    public Task DeleteAsync() {
        throw new Exception(); // you will never catch this
    }

    public void Delete() {
        throw new Exception(); // triggers CaliburnApplication.OnUnhandledException
    }

I can provide a working example if needed.

**Comment by BrunoJuchli** [comment]
@altso

Methods returning `Task` are treating by Caliburn.Micro like coroutines. When the Task throws an `Exception` you'll be informed by the `Coroutine.Completed` event. The `ResultCompletionEventArgs.Error` property will contain the `Exception`.

**Comment by nigel-sampson** [comment]
I'm not a 100% sold on that behaviour, while it sort of makes sense for coroutines and technically methods returning Task are usually coroutines by another name, but is it violating the principle of least surprise.

Frameworks swallowing exceptions can cause some nasty problems.

**Comment by nigel-sampson** [comment]
Resolved in #158 still considering changing the behavior of coroutines.
