### ISSUE TITLE
Canceling Property Changes from the View

### ISSUE THREAD

**Issue by andrewalex** [Caliburn-Micro/Caliburn.Micro#161]
I use controls such as ListBoxes for Navigation. This works pretty well except for in situations where the navigation needs to be canceled in some way (such as a Screen Close Guard).

Consider the following
```
	private string _SelectedProjectName;
        public string SelectedProjectName
        {
            get { return _SelectedProjectName; }
            set
            {
               var oldvalue = _SelectedProjectName;
                _SelectedProjectName = value;
                NotifyOfPropertyChange(() => SelectedProjectName);
		 // This gets fired inside the binding change so we cant revert the setting
                if(!ChangeProject(value))
                     _SelectedProjectName = oldvalue;
            }
        }
```

The big problem with this is if you change the project in spot there, the other side of the Binding doesn't pick it up (since it bindings ignore INPC until the 'set' has returned.

Of course this has uses other than navigation, such as validation, and other things..

I'm open to other patterns for this, but for me it seems the best way to do this would be to break out of this in some way (Execute.BeginOnUiThread maybe)

i'm hoping to use a standard/generic pattern.. The cleanest ways I see are:

1. NotifyOfPropertyChange doing an Execute.BeginOnUiThread before it calls propertychanged then hook the navigation into the propertychangedevent
2. create a ListenToProperty method that does this behavior can be used like  ListenToProperty(()=>SelectedProjectName, SelectedProjectNameChanged); 
3. Wrap the actual Field in a construct PropertyFieldHelper<string> that lets you modify behavior on such as  'try change' or make it almost a DependencyProperty like field.

1 and 2 are the simplest, but have the disadvantage of temporarily setting the field to the wrong thing..
3 is more complex. and I'm willing to put something together if this seems like the right way to go about this  (and the caliburn team is interested in it).

Of course I'm sure an option 4 is out there, which I'm happy to hear about

**Comment by nigel-sampson** [comment]
Can I ask the reasons that `ChangeProject` would return false?

**Comment by andrewalex** [comment]
An simple example is ChangeProject() is in a Conductor<Screen> and attempts to change the ActiveItem, however the the CloseGuard on the current ActiveItem prevents the swap (triggered by something such as user did not save).

I use this pattern with a number of controls. Another example is using a Calendar to navigate (Think outlook), where the screen requires being saved before

**Comment by nigel-sampson** [comment]
Is there any reason you can't check `ChangeProject` before updating the property?

``` csharp
private string selectedProjectName;

public string SelectedProjectName
{
    get { return selectedProjectName; }
    set
    {
         if(!ChangeProject(value))
            return;

        selectedProjectName = value;
        NotifyOfPropertyChange(() => SelectedProjectName);
    }
}

**Comment by andrewalex** [comment]
Your example would a desync with the UI.  If SelectedProjectName is bound to a ListBox, the new value will still be selected, not the old.

Keeping the View and ViewModel in sync is actually the big challenge..

Additionally, you cant set it back. Bindings ignore INPC that occur during the set.

**Comment by nigel-sampson** [comment]
Ah good point, you'll have to excuse the jet lagged thinking.

I don't think there's an easy to get around this short of using `Execute` to step outside the binding update.

I'm going to close this issue as it's not technically a CM bug, but I'd love to hear more about the solution you end up coming to so please feel free to update this when you do.

**Comment by andrewalex** [comment]
Wasn't supposed to be a bug, was supposed to be a feature request. Maybe I misclassified.

**Comment by nigel-sampson** [comment]
Not your fault, GitHub only has "issues" some of which we tag as possible enhancements, I didn't read what you had originally written has one of those and rather a bug, my fault.

I'll leave it like this and we can re-evaluate when depending on what you come up with.

Thanks.
