### ISSUE TITLE
Support for Eto.Forms

### ISSUE THREAD

**Issue by dealproc** [Caliburn-Micro/Caliburn.Micro#162]
Just a thought that the community may want to consider.

Curtis is building a pretty kick-ass tool suite for cross-platform development called [Eto](https://github.com/picoe/Eto) which may be beneficial to support in Caliburn Micro.  It may assist with getting #142 off the books too.

**Comment by nigel-sampson** [comment]
It's certainly a different library, looks very similar to Xamarin.Forms in conception but with a broader reach. 

Given it's functionality set it doesn't look like using this overtop of Xamarin would give us any benefits and could potentially hamper things like data binding and conventions.

Thanks for bringing it to my attention though I'll keep an eye on it.
