### ISSUE TITLE
does not updated datacontext in datatemplate

### ISSUE THREAD

**Issue by lobster2012-user** [Caliburn-Micro/Caliburn.Micro#163]
datagrid virtualizingmode=true x:name=list
datagrid.columns
templatecolumn
datatemplate
button x:Name="Cancel"/
...

If you add a lot of elements to the list, the panel will begin to use the cached containers and caliburn bindings will stop working.
I tried to use benaviour to catch  datacontext change, but I did not succeed.
DataContextChanged does raised not always.
Bind.Model={binding} did not help too.

Fix it please. Thanks

**Comment by nigel-sampson** [comment]
Am assuming this is for WPF? I haven't been able to recreate the bug, do you have a working example?

**Comment by lobster2012-user** [comment]
```
public class MainViewModel
    {
        public void Add()
        {
            var newItems = new List<ItemViewModel>();

            for (var i = 0; i != 10; ++i)
            {
                var item = new ItemViewModel
                {
                    CanDo = true,
                };
                newItems.Add(item);
                Items.Add(item);
            }

            var timer = new DispatcherTimer {Interval = TimeSpan.FromSeconds(5)};
            timer.Tick += delegate
            {
                timer.Stop();
                newItems.ForEach(x=>x.CanDo =false);
            };
            timer.Start();
        }

        private readonly ObservableCollection<ItemViewModel> _items = new BindableCollection<ItemViewModel>();
        public IList<ItemViewModel> Items { get { return _items; } }
    }

    public class ItemViewModel : Caliburn.Micro.PropertyChangedBase
    {

        private bool _canDo;
        public bool CanDo
        {
            get { return _canDo; }
            set { _canDo = value; NotifyOfPropertyChange(() => CanDo); }
        }

        public void Do()
        {

        }
    }
```

```
<Window x:Class="Caliburn.Bug.Wpf.MainView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:cal="http://www.caliburnproject.org"
        Title="MainView" Height="350" Width="525">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <Button x:Name="Add" Content="Add"></Button>
        <DataGrid x:Name="Items" Grid.Row="1" IsReadOnly="True" AutoGenerateColumns="False">
            <DataGrid.Columns>
                <DataGridTemplateColumn Header="Button">
                    <DataGridTemplateColumn.CellTemplate>
                        <DataTemplate>
                            <Button Padding="6,2"
                                    cal:Message.Attach="Do"
                                    >Do</Button>
                        </DataTemplate>
                    </DataGridTemplateColumn.CellTemplate>
                </DataGridTemplateColumn>
                <DataGridCheckBoxColumn Header="Can" Binding="{Binding Path=CanDo}"></DataGridCheckBoxColumn>
            </DataGrid.Columns>
        </DataGrid>
    </Grid>
</Window>
```

Button Add - create 10 new enabled items, throw 5 sec these button will be disabled, press oen time, wait 5 sec,press one time, scroll, wait 5sec, press one time, scroll, wait 5 sec. You will see new buttons sooner or later, that immediately disabled. Vertical size of window must be equal 10 items.

VirtualizingPanel.IsVirtualizing="False" fix it.

**Comment by nigel-sampson** [comment]
Ok, so looking at the same it appears the data context has changed correctly, but something in `ActionMessage` isn't being re-evaluated with the change. Will look into it.

**Comment by nigel-sampson** [comment]
So looking further into this brought me back to and old discussion on [Codeplex](https://caliburnmicro.codeplex.com/discussions/257005). 

Basically because the virtualization of the stack panel is reusing the Button, however the ActionMessage doesn't know when the underlying data context is changed using `Action.TargetWithoutContext` resolves this.

If you have the following xaml we have the correct behaviour, note you don't need to set it on every element, just the root element of the data template.

``` xml
<DataTemplate>
    <Button Padding="6,2" cm:Message.Attach="Do" cm:Action.TargetWithoutContext="{Binding}">Do</Button>
</DataTemplate>
```

**Comment by pjmagee** [comment]
I've been having issues with Caliburn SOMETIMES setting the property, but not always. It appears to be random that it may bind back to my View Model on changing a property in the DataGrid.

```XML

  <DataGridTemplateColumn Header="Ability ID" Width="*">
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <TextBox cal:Bind.ModelWithoutContext="{Binding}" Text="{Binding Id}" ToolTip="Click the Ability in the Logger window to copy it to Clipboard! Then Ctrl+V into here." />
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>

```

I have tried all the `cal:Bind` options to see if any of them make a difference. I only managed to get a Button in a DataTemplate working by adding `Action.TargetWithoutContext="{Binding}"`

Are there any known issues or work arounds to get caliburn working with DataGrid?
