### ISSUE TITLE
UAP HardwareButtons

### ISSUE THREAD

**Issue by mvermef** [Caliburn-Micro/Caliburn.Micro#165]
```C#
if (Windows.Foundation.Metadata.ApiInformation.IsTypePresent("Windows.Phone.UI.Input.HardwareButtons"))
            {
                Windows.Phone.UI.Input.HardwareButtons.BackPressed += HardwareButtons_BackPressed;
                Windows.Phone.UI.Input.HardwareButtons.CameraPressed += HardwareButtons_CameraPressed;
                //etc..
            }
```
If the app is going to be mobile then something like the above has to be included, either on the viewmodel associated with the action or at an app.cs level.  CM's handling of backbutton is probably sufficient but incorporating all hardware button options is something that would probably need to be addressed, or leave it up to the end developer to know this has to be handled, since app will die horribly if someone installs on desktop and it isn't handled.

**Comment by nigel-sampson** [comment]
I have that on the windows-10 branch at the moment https://github.com/Caliburn-Micro/Caliburn.Micro/blob/windows-10/src/Caliburn.Micro.Platform/win8/INavigationService.cs#L157 

The only reason we're handing the back button is we want to provide view models a way to intercept and cancel back button presses. The other hardware buttons can be handled by the developer in the normal way.

**Comment by mvermef** [comment]
Cool ok
