### ISSUE TITLE
2 of the 3 Nuget packages don't install on Visual Studio 2012

### ISSUE THREAD

**Issue by ifdhotqq** [Caliburn-Micro/Caliburn.Micro#166]
PM> Install-Package Caliburn.Micro.Start
Attempting to resolve dependency 'Caliburn.Micro (= 2.0.2)'.
Install-Package : 'Caliburn.Micro' already has a dependency defined for 'Caliburn.Micro.Core'.
At line:1 char:1
+ Install-Package Caliburn.Micro.Start
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
PM> Install-Package Caliburn.Micro
Attempting to resolve dependency 'Caliburn.Micro.Core (= 2.0.2)'.
Install-Package : 'Caliburn.Micro' already has a dependency defined for 'Caliburn.Micro.Core'.
At line:1 char:1
+ Install-Package Caliburn.Micro
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
PM> 

Not sure why this project is suggested when people talk about MVVM and WPF. It doesn't even install. Then if you manage to get it installed none of the documentation is up to date because someone went and deleted the BootStrapper<> class. 

How to use this stuff??

**Comment by mvermef** [comment]
Docs are up-to-date with respect to 2.0x, sounds like you are reading stuff from codeplex or somewhere else, docs are at caliburnmicro.com, bootstrapper<> was removed sometime ago, to better port over for the pcl and WINRT (which uses CaliburnApplication)  BootstrapperBase took its place.  Sounds like you read some docs from 1.52.

**Comment by nigel-sampson** [comment]
Can I ask what version of WPF and Nuget you're using. I've been unable to recreate your problem installing the packages.

It does look there's an issue where we're opening the old codeplex docs in the package, thanks for pointing that out.

**Comment by ifdhotqq** [comment]
Problem was a mix of a large amount of out of date documentation which is actually harmful to the cause, combined with the unstated requirement that a stock visual studio 2012 nuget cannot install caliburn micro. If it were me, I'd put in big bold block letters on the download page that you MUST upgrade nuget to be able to install this thing. Otherwise people are just going to get frustrated.

**Comment by nigel-sampson** [comment]
Looking closer at the old docs stuff it seems the problem was just the nuget version and the current nuget packages do point to the correct docs.

Will update the docs about updating nuget.
