### ISSUE TITLE
Caliburn Update - DataContext Of View No Longer Being Set

### ISSUE THREAD

**Issue by jayoub** [Caliburn-Micro/Caliburn.Micro#170]
Hi, I have an application using WPF and Caliburn.Micro for the MVVM framework. I recently upgraded from version 2.0.0 to 2.0.2.

When I ran my application after the upgrade, it seemed that CM was no longer setting the DataContext for my views to their view models. After looking at the source code, it seems that the DC is set in Caliburn.Micro.Action in OnTargetChanged, which calls SetTargetCore. The first line in this method is:

if (e.NewValue == e.OldValue || Execute.InDesignMode) {
                return;
            }

I found that this line was always preventing the DataContext from being set because Execute.InDesignMode was always returning true. This property of Execute delegates to PlatformProvider.Current.InDesignMode. By default, PlatformProvider uses an instance of DefaultPlatformProvider, and the InDesignMode property of DefaultPlatformProvider always returns true.

The result of this is that the DataContext of my views are never set. I was able to work around this by creating my own implementation of IPlatformProvider that returns false for this property, and setting PlatformProvider.Current to an instance of it in my bootstrapper. Once I did this, my application ran normally.

Is this a bug in v. 2.0.2? Or am I supposed to provide my own implementation of IPlatformProvider in the new version? It seems weird to me that a large bug like this would make it into a release, so maybe I'm missing something.

**Comment by nigel-sampson** [comment]
So the `DefaultPlatformProvider` is replaced by the `XamlPlatformProvider` ([source](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/XamlPlatformProvider.cs)) which defers to `View.IsInDesignMode` ([source](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/View.cs#L394)). 

The platform provider is set in the `Initialize` method of the `Bootstrapper` ([source](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/Bootstrapper.cs#L38)).

I'd check to see what the type of `PlatformProvider.Current` is after initialisation to see if that's being set correctly.

**Comment by jayoub** [comment]
We weren't calling Initialize in our bootstrapper constructor for some reason. We just called StartRuntime. I suppose that once we upgraded, the failure to call Initialize started causing issues. 

Thanks for your help.
