### ISSUE TITLE
Support newer versions of Xamarin.Forms

### ISSUE THREAD

**Issue by altso** [Caliburn-Micro/Caliburn.Micro#173]
Calibrun.Micro.Xamarin.Forms package doesn't support versions of Xamarin.Forms other than 1.4.2.6355. Please see Dependencies:

![image](https://cloud.githubusercontent.com/assets/1263018/7564937/2bc9624e-f7f4-11e4-9c25-18b8598bcaff.png)

**Comment by nigel-sampson** [comment]
I've updated the nuspec and will fully resolved next version of the alpha.

**Comment by altso** [comment]
Thank you
