### ISSUE TITLE
Does UriFor<T> make sense any more?

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#176]
The original `UriFor<T>` as part of `UriBuilder` was because Windows Phone internally does it's navigation via view uri. Other platforms such as WinRT (Windows 8, Windows 10, Windows Phone 8.1+) and Xamarin don't. Either using a Type or an instance of the view.

``` csharp
navigationService.UriFor<ProductDetailsViewModel>()
    .WithParam(v => v.ProductId, productId)
    .Navigate();
```

We still want the functionality of `UriFor` as a way to navigate to view models with multiple parameters, I'm just not sold on the name any more.

I'm proposing renaming `UriBuilder` to `NavigationHelper` and deprecrating `UriFor` for just `For`. This would be done as part of 3.0.0 with the idea of removing `UriFor` in some hypothetical 4.0.0 release.

``` csharp
navigationService.For<ProductDetailsViewModel>()
    .WithParam(v => v.ProductId, productId)
    .Navigate();
```
What do we all think?

**Comment by brainoffline** [comment]
How about    ForViewModel   
"For" is too generic

**Comment by nigel-sampson** [comment]
Thought about that but didn't like the repetition `ForViewModel<ProductViewModel>()`.

Having said that I can see the need to guidance in that it should be view models passed.

**Comment by mvermef** [comment]
Doesn't seem like For<> would be a bad a idea it would certainly streamline overall.

**Comment by nigel-sampson** [comment]
Done on the 3.0.0 branch.
