### ISSUE TITLE
How to change the Menu in the Shell View In Calliburn 2.0

### ISSUE THREAD

**Issue by Parmod-Kumar** [Caliburn-Micro/Caliburn.Micro#177]
Anyone can tell me how can we change the menu items in the shellview according to the views in the calliburn 2.0 in wpf.

**Comment by nigel-sampson** [comment]
Can you go into some more detail? Are you talking about a specific sample or tutorial?

**Comment by Parmod-Kumar** [comment]
Hi Nigel,

I want to change the menu items based on the view rendered in the view part of the ShellviewModel in calliburn. For example when the Login user control is the activated item in the shellviewmodel then the Login usercontrol specific menu came and so on.

Thanks,
Parmod

**Comment by nigel-sampson** [comment]
Currently on the branch `winrt-state` we have a [CachingFrameAdapter](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/winrt-state/src/Caliburn.Micro.Platform/win8/CachingFrameAdapter.cs) that caches view models and tries to reuse them during navigation. 

Needs some more testing, esp. when people start artificially manipulate history.

Was hoping some of this stuff would be fixed up in Windows 10, but after talking to Microsoft at Build it's clear the Frame caching behaviour won't be changing.

**Comment by nigel-sampson** [comment]
Ok, so I'm assuming a lot of things, first that you're using WPF? Is the Menu in your ShellView currently defined in the xaml?

If it is I'd suggest moving to dynamically generating it based on either your ShellViewModel or even it's ActiveItem which would meant that as the ActiveItem changes the menu changes.

**Comment by nigel-sampson** [comment]
Closing due to no more information received.

**Comment by Parmod-Kumar** [comment]
Thanks Niger..you can close the issue.
