### ISSUE TITLE
How to set custom DisplayName right-way in 2.0.0

### ISSUE THREAD

**Issue by dzaraev** [Caliburn-Micro/Caliburn.Micro#178]
Hi, in versions of CM before 2.0.0 I just set DisplayName="myname" in MyViewModel constructor, but now - it is virtual property and strictly speaking, i can't set virtual property in constructor (because there is no guarantee in costructor that my class fully initialized). And I can't set DisplayName in OnInitialized or OnActivated methods too, because sometimes I need to have DisplayName was setting before ViewModel will be activated first time. So what is right-way to set DisplayName property now? 
Thanks, and sorry for my bad english.

**Comment by remcoros** [comment]
You can just set it in the constructor.

The issue you are talking about is this: https://msdn.microsoft.com/en-us/library/ms182331.aspx

There's nothing special going on in the DisplayName setter and it doesn't rely on any other members. So it's safe to ignore this.

You can suppress the compiler warning like this:

#pragma warning disable 2214
DisplayName = "Yihaa";

**Comment by dzaraev** [comment]
Hi, thanks for reply. I know what going on in the Caliburn's DisplayName implementation, it is clear. But problem will be if someone will derive from my MyViewModel and then override DisplayName and write in it's setter code relying on something, that initialized in derived constructor. 
That guy can write in it's DisplayName setter implementation something like "this.displayName=value; _db.UpdateName(_data, value);" and he will assume that _db already initialized in his constructor. And when my class (which is base for him class) will call DisplayName set in my constructor - it is error occured.
I know that I can suppress warnigs, but it seems really helpful warning about really wrong situation, and I dont want to face such error in future.

**Comment by remcoros** [comment]
I see, if you want to anticipate on this use-case. I think you have to make the displayname sealed in your base class and force the user to use a different method to storing the displayname.

**Comment by dzaraev** [comment]
Thank you for advice, seems that it is the only one way to solve it.

**Comment by nigel-sampson** [comment]
`DisplayName` is a really awkward on in this regard, some people like yourself want to set it in the constructor, others need to override and calculate etc. Sadly there's no simple way to easily support both use cases.

If you are seriously concerned about the warning then I'd suggest moving away from using `DisplayName` for your own property or depending how much you're implementing your own `Screen` classes not set it to virtual.

**Comment by nigel-sampson** [comment]
Closing out as issue sort of resolved.
