### ISSUE TITLE
How can I cancel the Deactivation of a Screen?

### ISSUE THREAD

**Issue by rmnblm** [Caliburn-Micro/Caliburn.Micro#179]
I'd like to ask the user, if he wants to save unsaved changes he has made on a screen. He should have the possibility to answer the question with Yes (save changes), No (discard changes) and Cancel (to stay on the screen). Asking this question in the OnDeactivate(bool close) will be too late, no?

**Comment by nigel-sampson** [comment]
Caliburn.Micro supports this through the `IGuardClose` interface that `Screen` already implements. You should just need to override `CanClose`.

You would end up with something like:

``` csharp
public override void CanClose(Action<bool> callback)
{
    var result = ConfirmSaveChanges();
    
    if (result == Changes.Cancel)
    {
        callback(false);
        return;
    }

    if (result == Changes.Save)
        Save();

    callback(true);
}
```

**Comment by jimbobsmith** [comment]
You can deactivate a view without closing it (e.g. tabs) so this wouldn't apply

**Comment by rmnblm** [comment]
Thanks @nigel-sampson for your answer but I don't want to close the view, I'm just going to deactivate it. 
I'm thinking about a method like
`public override void CanDeactivate(Action<bool> callback)`

**Comment by nigel-sampson** [comment]
There shouldn't be any data loss on a Deactivate compared to a Close, as @jimbobsmith pointed our tabs are the best example here. 

- Moving to a new tab should deactivate the old tab without closing it. 
- Query to save changes when the tab is closed.

This is why we guard close and not deactivate.

If you are truly looking to stop deactivation you'd most likely need to create your own conductor (assuming we're deactivating child view models).

**Comment by nigel-sampson** [comment]
Closing out as issue answered.

**Comment by Hikerakashiya** [comment]
@nigel-sampson, @rmnblm makes a good case. I was searching for a solution to the same problem and stumbled across this issue. I have an interface that is made up of tabs. When the user navigates away from the Settings tab, if they have unsaved changes, I prompt them to save, however prompting the user inside OnDeactivate is already too late. Another screen is activated and is displayed while the prompt is showing. I want the prompt to pause the deactivation and possibly cancel the deactivation, so the prompt is shown while on the Settings screen, not a different screen. I believe this is the same issue @rmnblm was having. Having guards for Close and Deactivate makes a lot of sense in this regard. I think this issue should be revisited.

**Comment by jongleur1983** [comment]
Same issue here: Tabs where the active tab should only be deactivated when not pending changes exist. On Deactivation I would like to ask for save-or-revert.

**Comment by xiaxianzhong** [comment]
I also have the same issue, and I agree with @Hikerakashiya 's suggestion that reopen this issue.

**Comment by noamyogev84** [comment]
Same here. Please open and revise.

**Comment by nigel-sampson** [comment]
Ok, while I understand the reasoning behind this, it's no something I'd like to add to the framework. Having a clear distinction between deactivation and closure makes other discussions a lot easier.

Having said that if there's no current way for this behavior to be added in by the developers who want it then we definitely should address that and am happy to discuss that here.

A naive example would be to override `ChangeActiveItem` on your conductor to ask for save changes and close if required.

``` csharp
protected override void ChangeActiveItem(DocumentViewModel newItem, bool closePrevious)
{
    if (ActiveItem != null)
    {
        var result = MessageBox.Show(Application.Current.MainWindow,
            $"Do you want to close {ActiveItem.DisplayName}?", "Close?", MessageBoxButton.YesNo);

        if (result == MessageBoxResult.No)
            return;
    }

    base.ChangeActiveItem(newItem, closePrevious);
}
``` 

This works except for issue, the `TabControl` itself doesn't handle that change being cancelled, it thinks the new tab is selected while the view model thinks its the other. Trying to tell it otherwise is ignored as the code path is during the binding update and therefore ignored to stop loops.

**Comment by noamyogev84** [comment]
well that means your conductor entity is aware of its conducted items business.

**Comment by nigel-sampson** [comment]
The above example was only an illustration of a cut point where the check could go.

There's nothing stopping you pushing the decision and check into the child view model, it that case the conductor only needs to call the check and respond appropriately.
