### ISSUE TITLE
2.0.2 version binding crash

### ISSUE THREAD

**Issue by ievgeniy88** [Caliburn-Micro/Caliburn.Micro#181]
After updating from 2.0.1 to 2.0.2 all in projects isn't work. May be I'm miss some breaking changes?

**Comment by nigel-sampson** [comment]
Can you please give the error you're seeing and the platform you're on. I need more information that "isn't working" to help.

**Comment by ievgeniy88** [comment]
Excuse me. "All bindings in project not working". Without any error messages to output.

I have example project, but can't attach it to issue ("Unfortunately, we don't support that file type. Try again with a PNG, GIF, JPG")

Platform: Win7, .NET 4.5.2, WPF

**Comment by nigel-sampson** [comment]
When you say bindings are you referring to assembly bindings or xaml bindings?

**Comment by ievgeniy88** [comment]
xaml bindings

**Comment by nigel-sampson** [comment]
Can you provide an example of a binding that's stopped working?

**Comment by ievgeniy88** [comment]
sended to nigel.sampson@compiledexperience.com

**Comment by nigel-sampson** [comment]
So it looks like the issue is that in your `AppBootstrapper` constructor is calling `StartRuntime` instead of `Initialize`.

I'll need to look at why this was a breaking change, but you should definitely be calling `Initialize`.

**Comment by ievgeniy88** [comment]
Thank you!
