### ISSUE TITLE
How to transfer more than two parameters ?

### ISSUE THREAD

**Issue by gruan01** [Caliburn-Micro/Caliburn.Micro#182]
Hello , I'm CM fans.
Today I'm tring to use CM for Xamarin.Forms, try to transfer parameter from one ViewModel to another ViewModel:

```
this.NS.NavigateToViewModelAsync<ShowViewModel>(this.Username);
```

NS is INavigationService instance, injected from constructor.

In  Caliburn.Micro.Platform\xforms\NavigationPageAdapter.cs , Method TryInjectParameters,
You written like this : 

```
var property = viewModelType.GetPropertyCaseInsensitive("Parameter");
```

You mean only can set one parameter , and name must be "Parameter" ?

I set a property in my ViewModel

```
public string Parameter {
    get;
    set;
}
```

It's worked.
But, I think it's not useful in real scene .
How can I set more than 2 parameters ?

**Comment by nigel-sampson** [comment]
You're correct, currently it's only passing one parameter. What's happened in the past on the other platforms is that we build on top of this with `UriBuilder` which encodes multiple parameters into a `Uri` which gets unpacked and populates multiple properties. 

This sort of functionality was because some platforms only supported one parameter. 

What we'll most likely do is supporting taking an `IDictionary<string, object>` and unpacking that onto a view model (potentially rolling this out over all platforms).

In short, it is coming.

**Comment by nigel-sampson** [comment]
This is now on the 3.0.0 branch in two different flavours. If you pass a `IDictionary<string, object>` at the parameter, we'll expand on this over all properties on the view model.

You can also use the new `NavigationHelper` class to enable the following syntax.

``` csharp
navigationService.For<ProductViewModel>()
    .WithParam(v => v.ProductId, 42)
    .WithParam(v => v.CategoryId, 2)
    .Navigate();
```

**Comment by gruan01** [comment]
Hello , thanks for your working.
I'm trying this feature, it's worked fine.
But , need set the ViewModel as PerRequest or Singleton first.
If not not set, view can display, but seems viewModel not instanced , so view can't display viewModel's data.

**Comment by nigel-sampson** [comment]
The navigation service uses the view model locator to find the appropriate view model, this in turn uses IoC. 

If you're not wanting to use dependency injection and all your view models have parameterless constructors then you can pull out all of the container code and the framework will just new up the view model.

If you want to use dependency injection then you can choose to use the SimpleContainer that comes with Caliburn or your container of choice instead.

The behavior of SimpleContainer is to return null when being asked for a instance it doesn't know about (hence the registration). Other containers have different behavior for this, it's up to you which you want to use.

**Comment by dhswg20077** [comment]
can not use this in Caliburn.Micro.Xamarin.Forms `. For<ProductViewModel>()`

**Comment by nigel-sampson** [comment]
Can you elaborate @dhswg20077? this should be working in Xamarin.Forms.
