### ISSUE TITLE
Mark message of EventAggregator as handled

### ISSUE THREAD

**Issue by aamarber** [Caliburn-Micro/Caliburn.Micro#183]
My problem is that when I publish a message using EventAggregator every subscriber to the IHandle<MessageType> receives the message, even if I have handled the message anywhere else. There's a way to mark the message as handled or stopping the propagation of the message like standard .NET events with the 'Handled' flag?

**Comment by mvermef** [comment]
How are defining the ihandle on your view model?  Normally most will create a message specific class object for that event that occurred not just using IHandle<string> for everything, I will use something like IHandle<FlightlogMessage> which contains properties specific to handling events associated with FlightLogViewModel for example.

**Comment by nigel-sampson** [comment]
I'm very loath to add something like this as suddenly the order of subscribers called becomes important if you want to ensure a certain handler gets the message before another. This becomes complicated when different handlers can on different threads / async etc.

Typically I've found this requirement tends to show up when the messages being passed aren't specific enough and a lot of handlers are getting messages they don't care about.

There would be nothing stopping you adding a `Handled` property to your message class that's being passed around by the event aggregator, then each handler could check to see if it's already being handled.
