### ISSUE TITLE
Value is not a hop source in the route.

### ISSUE THREAD

**Issue by arcuri** [Caliburn-Micro/Caliburn.Micro#184]
Hello,
I have a problem with the following XAML code:

<TreeView x:Name="SettingsTree" BorderThickness="0">
        <TreeView.Resources>
            <SolidColorBrush Color="Transparent" x:Key="{x:Static SystemColors.HighlightBrushKey}"/>
        </TreeView.Resources>
        <TreeViewItem Header="???" IsExpanded="True">
            <Grid Margin="-20,0,0,0">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="Auto"/>
                    <ColumnDefinition Width="*"/>
                </Grid.ColumnDefinitions>
                
                <TextBlock Name="Range" Grid.Column="0" Text="{lex:Loc Range}" Style="{StaticResource TextBlock.PropertyEditor}"/>
                <TextBox Grid.Column="1" Text="{Binding BasicInstrumentSetting.Range,UpdateSourceTrigger=LostFocus}" ToolTip="{lex:Loc Voltage.ToolTip}" Style="{StaticResource TextBox.PropertyEditor}"
                         cal:Message.Attach="[Event GotKeyboardFocus] = [Action GotKeyboardFocus(Range.Text,$this.ToolTip)]"/>
            </Grid>
        </TreeViewItem>
    </TreeView>

StackTrace Image:
![caliburncrashpng](https://cloud.githubusercontent.com/assets/10706727/7880436/a362dd9a-05f9-11e5-8535-a474838b3b3a.png)

My application crash with this code!!!
But If I cancel in this row 
<TreeViewItem Header="???" IsExpanded="True">
->    IsExpanded="True"
In this way my application works.

Can I have any suggestions???

Regards,
Bernardo

**Comment by nigel-sampson** [comment]
Sorry for the delay in getting back to you, is there some code missing in your sample above, I can't see a line with `IsExpanded="True"`.

**Comment by arcuri** [comment]
![code](https://cloud.githubusercontent.com/assets/10706727/7953770/eb564ab0-09c8-11e5-87bd-d580319a292a.png)

This is my source code, IsExpanded is in TreeViewItem.

**Comment by nigel-sampson** [comment]
Thanks for the extra information, I'm still looking into the problem, to be honest this stuff was written before my time and I'm looking into why this is an error.

**Comment by nigel-sampson** [comment]
Had a chat with some of the older members of the team and it doesn't appear like there's any reason for that exception and I'm removing it. Will push the fix soon and will be available in nuget in the new release.

**Comment by arcuri** [comment]
Thank you very much!!!

**Comment by mittal-kkr** [comment]
if you pass any parameter without "$", then this problem occurs.
