### ISSUE TITLE
Exception in configure

### ISSUE THREAD

**Issue by lploumen** [Caliburn-Micro/Caliburn.Micro#188]
Hi,
How do you deal with exceptions in the Configure method of the Bootstrapper (WPF app)?
I'm instanciating some services in the Configure() method, it throws exceptions, I catch them in the Configure(), display a Messagebox .
Then in the OnStartup method, I check if the Configure method was succesful or not. If not, I simple return and don't display any view. But in this case, the process does not terminate.

Is there any good practice dealing with exceptions in the Bootstrapper ?

**Comment by mvermef** [comment]
probably going to be needing more information on this... Could you post some code of your configure() so we can see what you are doing?

**Comment by nigel-sampson** [comment]
This would really depend on the nature of the exception, typically when I've had scenarios like this where there could possibly be an exception in the setup process that's fatal I tend to navigate to a `LaunchFailedView` which highlights the error.

if you just want to exit the app then you need to use `Application.Current.Shutdown();` or similar as you've seen not selecting a view is not the same as existing the app.

**Comment by lploumen** [comment]
I realize my message first message is not so clear :)
I found out that displaying a messagebox inside the Configure method is not a really good idea (I guess the app is not fully initialized). I noticed that sometimes the OnStartup override is executed before the MessageBox in the Configure.
I ended up by having a flag, telling if the configure was successful or not, then in the OnStartup, show the Messagebox.
Not sure if it is the correct way but it works.

```
protected override void Configure()
{
        try
        {
            ...
        }
        catch (Exception ex)
        {
         // The app may not be initialized here, do not show messagebox.
            m_ExceptionMessage = ex.Message;
        }
}

protected override void OnStartup(object sender, StartupEventArgs e)
{
            if (!String.IsNullOrEmpty(m_ExceptionMessage))
            {
                MessageBox.Show(m_ExceptionMessage, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                
                Application.Shutdown();
                return;
            }
			...
}



```

**Comment by nigel-sampson** [comment]
It looks ok with me, I wouldn't say there is a *correct* way to do this given it's really up to you what you want to do when configure fails.
