### ISSUE TITLE
UAP10 SplitView control and Conductor<Screen>

### ISSUE THREAD

**Issue by Yurijj** [Caliburn-Micro/Caliburn.Micro#189]
Have one question to you. I'm developing windows 10 app with hamburger menu and using caliburn.micro for my app.
My main page view contains SplitView control and its viewModel is Conductor<Screen>. My idea is to use ActiveItem of Conductor<Screen> ViewModel as Content for SplitView. For instance:

```
<Grid x:Name="ParentGrid">
        <SplitView>
            <SplitView.Pane>
                <Grid>
                    <RadioButton ... ActivateItem(viewmodel_1)/>
                    <RadioButton ... ActivateItem(viewmodel_2)/>
                    <RadioButton ... ActivateItem(viewmodel_3)/>
                </Grid>
            </SplitView.Pane>
            <SplitView.Content>
                <ContentControl x:Name="ActiveItem" />
            </SplitView.Content>
        </SplitView>
</Grid>
```

But this is doens't work, I can't see any content at SplitView.Content which binds to viewModel1 or 2 or 3 as ActiveItem. But If I put the <ContentControl x:Name="ActiveItem" /> element at Grid, not as child of SplitView, everything works well. Working xaml looks like this:

```
<Grid x:Name="ParentGrid">
       <ContentControl x:Name="ActiveItem" />
        <SplitView>
            <SplitView.Pane>
                <Grid>
                    <RadioButton ... ActivateItem(viewmodel_1)/>
                    <RadioButton ... ActivateItem(viewmodel_2)/>
                    <RadioButton ... ActivateItem(viewmodel_3)/>
                </Grid>
            </SplitView.Pane>
            <SplitView.Content>
                   <!--empty-->
            </SplitView.Content>
        </SplitView>
</Grid>
```

So, my question is: what wrong with my XAML in case of ActiveItem is inside content of SplitView?

**Comment by nigel-sampson** [comment]
Are you using the Windows 10 branch of Caliburn.Micro or the distribution from nuget?

**Comment by Yurijj** [comment]
Ok, let's do it another way: does anyone have a working solution of SplitView MVVM implementation, where each ViewModel is one of elements of SplitView radio buttons and switch the content of SplitView dynamically just with help of changing current viewModel?

I'm trying to analyze few code examples:
by Jerry  http://blog.jerrynixon.com/2015/04/implementing-hamburger-button-with.html
by Igor Ralic http://igrali.com/2015/04/12/getting-started-with-splitview-control-in-universal-apps/

But anyone doesn't use Caliburn Micro and switching the ViewModels for SplitView container. So if somebody already has a working solution please share a piece of code or at least an idea how to switch current viewmodel for splitview content changing. My idea with SplitView control and its viewModel as Conductor<Screen> doesn't work.

**Comment by nigel-sampson** [comment]
@Yurijj You are correct, we can't yet distribute the Windows 10 stuff via nuget so you'll need to manually compile it.

In fact the changes to `BindingScope` are exactly what you need for the first sample to work. Another way would be to have a restyled `ListBox` in the `SplitView.Pane` bound to `Items`, as the selected item changes `ActiveItem` changes and you're away.

**Comment by mvermef** [comment]
````<Grid>
            <SplitView>
            <SplitView.Pane>
                <Grid>
                    <RadioButton ... cm:Message.Attach="[Event Tapped]=[Action ViewModel1()];" />
                    <RadioButton ... cm:Message.Attach="[Event Tapped]=[Action ViewModel2()];" />
                    <RadioButton ... cm:Message.Attach="[Event Tapped]=[Action ViewModel3()];" />
                </Grid>
            </SplitView.Pane>
            <SplitView.Content>
                      <ContentControl x:Name="ActiveItem" />
            </SplitView.Content>
        </SplitView>
</Grid>````

I have this working at present... not very neat but it works, with ShellView, holding grid above, ShellViewModel being the main navigation system.

**Comment by nigel-sampson** [comment]
Doesn't seem to be anything more to add here, will make sure `SplitView` is included in a sample for Windows 10.
