### ISSUE TITLE
Do the Extensions assemblies still make sense?

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#191]
Most of the code in the WinRT extensions projects is pretty much required for using CM and doesn't really below in the extensions assembly.

I believe the intention was good, but with more and more platforms we're creating more extensions assemblies as well. Given that platform already has folders for platform specific code these extensions could go there.

Would it make sense to shift the WinRT extensions into the core assembly leaving only WP8 (or do we do it all?) removing one assembly that isn't needed other than a code separation point of view.

Would be something to do as part of 3.0.0 since it breaks ABI but API.

**Comment by tibel** [comment]
This is a good idea to integrate the extensions in the platform assembly.

**Comment by nigel-sampson** [comment]
In 3.0.0 branch due to breaking changes.
