### ISSUE TITLE
Escape underscore in property name for deep property binding

### ISSUE THREAD

**Issue by Gigitsu** [Caliburn-Micro/Caliburn.Micro#192]
I have an entity with a field like `Sample_id` (name that I cannot modify) and this entity is stored in `Sample` ViewModel property. So in my view I need to bind a TextBox to `Sample.Sample_id` ViewModel property. By convention I need to use the underscore to get deep property binding but in this case how can I escape `Sample_id` property underscore?

**Comment by nigel-sampson** [comment]
I don't think there is a way to escape underscores for convention based bindings, I would recommend using standard `{Binding}` for instances like this.
