### ISSUE TITLE
[Phone] WinRT - Conductor and dealing with multiple AppBars

### ISSUE THREAD

**Issue by c0z** [Caliburn-Micro/Caliburn.Micro#193]
My main page contains a Pivot control and the ViewModel is a Conductor with two items. Each item has its own AppBar (now called CommandBar) with different buttons. 

When  I switch from the first item to the second item, the AppBar gets updated and the buttons of the second item are displayed. Switching back the first item does not cause any update and the buttons of the second item are still displayed.

So my question: Is it possbile to have different AppBars for each item (view)?

**Comment by nigel-sampson** [comment]
Is is on Windows Phone 8.1 or 10?

How are you doing about changing the app bar of the pivot page when the the active item changes?

**Comment by c0z** [comment]
It's Windows Phone 8.1

What do you mean with changing the app bar of the pivot page when the the active item changes?

**Comment by nigel-sampson** [comment]
Typically a command bar is defined on the root level `Page` as part of it's `BottomAppBar` property. This would be the `Page` that contains the `Pivot` control. I'm assuming you have some mechanism that as the currently selected `PivotItem` changes the `BottomAppBar` property is updated to reflect the newly selected item.

**Comment by c0z** [comment]
I haven't defined a `BottomAppBar` in my root `Page`, but I defined a `BottomAppBar` in each items `Page` (the view of the items are Pages, btw.). I have no specific mechanism to change the `BottomAppBar` when the `PivotItem` changes. The first switch (first item to second item) is done automatically, but when I switch back it does not work. That's the reason I was thinking this is supported by CM.

**Comment by nigel-sampson** [comment]
Do you have an example I could look at? There's nothing built into CM to support this, but I'm curious how you're doing it and there maybe something that can be done,

**Comment by c0z** [comment]
Yes, I've prepared a small sample, you can find it here: http://1drv.ms/1BOJ7OL

There are three views, one MainView with a Pivot control and two ItemViews with different AppBars. The first time you switch, the AppBar will change, but the second time, it won't be change back.

**Comment by nigel-sampson** [comment]
Thanks, I'm honestly surprised this works at all, I removed most of the Caliburn.Micro code in `MainViewModel` and it still works (in the buggy fashion) which makes me think it's some quirk of the platform.

There is nothing supported here in Caliburn.Micro, I would look at approaches where the `MainViewModel` exposes what it needs to to a comamnd bar in `MainView`, then change these when the ActiveItem changes.

This article from [MSDN](https://msdn.microsoft.com/en-us/library/windows/apps/hh394036(v=vs.105).aspx) may help, but it's a bit old.
