### ISSUE TITLE
AutoHandle Events?

### ISSUE THREAD

**Issue by sascha-schwegelbauer** [Caliburn-Micro/Caliburn.Micro#194]
Hi,

if an object that implements IHandle<> is created via DI, is it possible to make it implicitly subscribe to a EventAggregator or has this always do be done explicitly?

Thanks, Sascha

**Comment by nigel-sampson** [comment]
There is no implicit subscribe built into Caliburn.Micro you'd need to add this functionality yourself, the reason is that every app will have different ideas about when something should be subscribed.
