### ISSUE TITLE
Multiple instances of same View-type bound to a single-instance view-model

### ISSUE THREAD

**Issue by deepforest** [Caliburn-Micro/Caliburn.Micro#195]
Hi there,
I have an issue binding multiple instances of same View type to single-instance view-model (view-model first).

For example, I have a Parent view with two states: Normal, Expanded.
In Normal state I display a Child view called ImageView inside a tab item.
When flipping to Expanded state, the tab where ImageView is located should be removed from the tab-control, and the same view should be placed inside a border nearby other tabs.

To handle this I have two ContentControl's which are bound to the same view-model instance provided by the parent. One is visible and the other collapsed in its border. Flipping the states, collapse the visible one, and show the collapsed one, also morphs the layout.
Here is how each of both ContentControl's defined:
<ContentControl cal:View.Model="{Binding ImageVm}" />

The problem is that Caliburn creates only one View, which is for the last ContentControl in visual tree. Currently the collapsed one.

Any ideas (I don't want to use Context with different partial Views...)?

**Comment by nigel-sampson** [comment]
I'm not seeing any example code above, is something missing?

It's a bit hard to understand what you're describing, would it possible to get a small repro to show what you're describing.

I have an idea about a possible solution, but hard to tell if it's what you're after without some further information.

**Comment by deepforest** [comment]
I've found a workaround. Removing the view-model from the tab control from its parent view-model. Now I always have only one view of the same type in the same parent.
There's also an option to use context, but it's a bit awkward for such situation.

Thanks.
