### ISSUE TITLE
Guard method/property for Visibilty

### ISSUE THREAD

**Issue by c0z** [Caliburn-Micro/Caliburn.Micro#198]
It would be nice if Caliburn.Micro includes a guard method/property for Visiblity, like it does for IsEnabled with **CanXYZ**.

For example, **ShowXYZ** automatically binds to the Visiblity property of element **XYZ**.

I think is can be done easily with a new convention but I am not able to provide an implementation.

**Comment by nigel-sampson** [comment]
At the moment it wouldn't be able to be implemented with a new convention as a match between `ElementName` and `ShowElementName` would not be found.

`ViewModelBinder` does have an extension point `HandleUnmatchedElements` where you could start to hook in your logic. I don't think this convention is something we'd add to the functionality built into the library but it would certainly be an interesting plugin.
