### ISSUE TITLE
windows 10 Universal Windows run on Compile with .NET Native tool chain error

### ISSUE THREAD

**Issue by EDiaos** [Caliburn-Micro/Caliburn.Micro#199]
the universal windows app run on project build selected "Compile with .NET Native tool chain"

in the xmal i using like this :  
\<Button Margin="10" cal:Message.Attach="[Event Click]=[Action Click()]" Content="TestClick" \>

the error will throw:
Exception thrown: 'Windows.UI.Xaml.Markup.XamlParseException' in Win10Test.Interop.dll
Additional information: The text associated with this error code could not be found.
Failed to assign to property 'Caliburn.Micro.Message.Attach'. [Line: 14 Position: 33]
If there is a handler for this exception, the program may be safely continued.

i try catch the err on message.cs:
code ： newTriggers.OfType<DependencyObject>().Apply(allTriggers.Add);
err ：'Windows.UI.Xaml.Controls.Button' is missing metadata. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=392859

if un selected "Compile with .NET Native tool chain  the app run is successed."
my english is poor ,so any things don't know please tell me .

**Comment by nigel-sampson** [comment]
Is this using the Windows 10 branch?

**Comment by EDiaos** [comment]
Yes, the Windows 10 branch is also throw error

Date: Tue, 7 Jul 2015 12:51:51 -0700

**Comment by nigel-sampson** [comment]
I've been unable to recreate the error you're seeing on my Windows 10 setup. What version of Windows 10 and the Windows 10 SDK are you using?

**Comment by EDiaos** [comment]
Thanks for concerned about this issue.

I am using the Windows 10(10162) and the Windows 10 SDK(10158/10069),they are also throw error.(if not selected Compile with .NET Native tool chain it will run successed)

And i update my code to github.Hope that will reproduce the problem for this code.
https://github.com/EDiaos/CaliburnMicroFroWin10Test

TKS.

**Comment by EDiaos** [comment]
@nigel-sampson  Thanks for concerned about this issue.

My project using the Windows 10(10162) and the Windows 10 SDK(10158/10069).

I down your Window 10 setup demo。
If using Native that will throw this error on this code:
var chart = await sevenDigitalClient.GetReleaseChartAsync();(I try remove this coede and using 'Message.Attach' will run successed)

I try create a new Windows 10 Project using the NuGet to down Caliburn.Micro(2.0.2),and i try run the project, the error is also throw。

I don't know what different form two project. Both projects are similar comparative references.
I update my code to github.Hope that will reproduce the problem for this code.
(Need to Compile with .NET Native tool chain on project build)
GitHub: https://github.com/EDiaos/UWPCalinurnTest

TKS.

**Comment by nigel-sampson** [comment]
I've downloaded your sample and successfully compiled it in Release|ARM and Release|x86 with the Native tool chain enabled.

This was on Windows 10 10130 and Windows 10 SDK 10069.

**Comment by EDiaos** [comment]
@nigel-sampson 
I created new project , the error is also throw.  On my friend's pc run it ,will throw err also.
I found the output info is throw MissingMetadataException. Did you have any ideas to help me find this problem? 
TKS.

Output info:
Exception thrown: 'System.Reflection.MissingMetadataException' in System.Private.Reflection.Core.dll
Exception thrown: 'System.Reflection.MissingMetadataException' in App1.Interop.dll
Exception thrown: 'System.Reflection.MissingMetadataException' in App1.Interop.dll
Exception thrown: 'Windows.UI.Xaml.Markup.XamlParseException' in App1.Interop.dll
An exception of type 'Windows.UI.Xaml.Markup.XamlParseException' occurred in App1.Interop.dll but was not handled in user code
Additional information: The text associated with this error code could not be found.
Failed to assign to property 'Caliburn.Micro.Message.Attach'. [Line: 12 Position: 61]

**Comment by EDiaos** [comment]
I fix this problem in my project.
1. using your Window 10 setup demo  
2. move my project file to this demo 
3. run successed

There may be a problem in my xxx.csproj file.So using your demo will fix it.

I will close this issues,and  reset my Window10 and VS2015 and try new project at some time.
 
TKS.

**Comment by nolanw** [comment]
I'm getting what appears to be the same issue in a Universal Windows 10 app. Debug builds work fine, but Release builds throw a series of exceptions on launch. (The native compiler is only turned on in Release builds.) If I continue past the first couple exceptions I see one that leads me to the `Message.Attach` property:

> Exception thrown: 'System.Reflection.MissingMetadataException' in System.Private.Reflection.Core.dll
> Additional information: Arg_InvokeMethodMissingMetadata, System.EventHandler
> 
> Exception thrown: 'System.Reflection.MissingMetadataException' in MyApp.Interop.dll
> Additional information: Arg_InvokeMethodMissingMetadata, System.EventHandler
> 
> Exception thrown: 'System.Reflection.MissingMetadataException' in MyApp.Interop.dll
> Additional information: Arg_InvokeMethodMissingMetadata, System.EventHandler
> 
> Exception thrown: 'Windows.UI.Xaml.Markup.XamlParseException' in MyApp.Interop.dll
> An exception of type 'Windows.UI.Xaml.Markup.XamlParseException' occurred in MyApp.Interop.dll but was not handled in user code
> Additional information: The text associated with this error code could not be found.
> 
> Failed to assign to property 'Caliburn.Micro.Message.Attach'. [Line: 0 Position: 0]

The first lines in my XAML are:

```xaml
<UserControl
    x:Class="MyApp.Views.StageView"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:cm="using:Caliburn.Micro"
    xmlns:controls="using:MyApp.Controls"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    d:DesignHeight="300"
    d:DesignWidth="400"
    cm:Message.Attach="[Event EmbiggenPreview] = [Action OnEmbiggenPreview()]">
```

If I remove the `Message.Attach` attribute then the exceptions go away.

I've tried adding bits and pieces to the project's `Properties\Default.rd.xml` file (as mentioned [over here](http://blogs.msdn.com/b/dotnet/archive/2014/05/21/net-native-deep-dive-help-i-hit-a-missingmetadataexception.aspx)), but it's a game of guess-and-check and so far I haven't come up lucky. Apparently incorrect guesses include both the view type and the viewmodel type involved.

This is on Windows 10.0 build 10525, Visual Studio 14.0.23107.0, and Caliburn.Micro 3.0.0-beta1. If you need any other info please let me know.

**Comment by nigel-sampson** [comment]
This one is definitely a frustrating error as it totally depends on the app in question from what I can tell.

In terms of what to add to the `Default.rd.xml` file as per the article I would have guessed the same as you with the view model type.

I don't suppose there was a message on the `MissingMetadataException` giving any detail on the metadata that was missing?

Will keep reading up on this to see how I can help.

**Comment by nigel-sampson** [comment]
This could be a bit of a hack and overkill but something to start with.

I'm thinking we need to modify not your projects `.rd.xml` file but the one for Caliburn.Micro.

Could you try replacing the `Caliburn.Micro.Platform.UWP.rd.xml` with the following:

``` xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Library Name="Caliburn.Micro.Platform.UWP">
    <Assembly Name="Caliburn.Micro" Activate="Required All" Browse="Required All" Serialize="Required All" Dynamic="Required All" />
    <Assembly Name="Caliburn.Micro.Platform.UWP" Activate="Required All" Browse="Required All" Serialize="Required All" Dynamic="Required All" />
  </Library>
</Directives>
```

The comments by in the rd.xml file don't seem to gel with most of the blog posts around so still working through that.

**Comment by nolanw** [comment]
@nigel-sampson I'd installed 3.0.0-beta1 via NuGet, but I'm guessing I'll need to do something else in order to try what you're asking. Is there documentation anywhere about configuring a UWP project to use Caliburn.Micro from source?

**Comment by nigel-sampson** [comment]
The file in question is in the 3.0.0-beta1 package. If you look in the `lib\uap10.0\Caliburn.Micro.Platform.UWP\Properties` folder you should file it.

**Comment by nolanw** [comment]
Oh, forgot to answer your earlier question. The message on the `MissingMetadataException` is
> Arg_InvokeMethodMissingMetadata, System.EventHandler

---

When I use your suggested `Caliburn.Micro.Platform.UWP.rd.xml` contents I get no more exception!

Testing a bit, I found that the `<Assembly Name="Caliburn.Micro.Platform.UWP">` tag was the one I needed. I did not need the other `<Assembly>` you suggested to remain exception-free.

I then restored the file you mentioned and put the `<Assembly Name="Caliburn.Micro.Platform.UWP"…>` tag into my project's `Properties\Default.rd.xml` and all is well. (I don't really understand what these directives are doing, so maybe this is obvious.)

If you need me to test anything else, just let me know!

**Comment by nigel-sampson** [comment]
Thanks, I'm going to leave this open for the moment as the solution above is overkill and I'd like to refine it.

If you ever manage to run into the problem again in a solution you can share (I've yet to manage to repro this issue) then I'd love to get a hold of it.

**Comment by nolanw** [comment]
As you guessed, I cannot share this one, but I'll see what I can do.

**Comment by dandax** [comment]
I ran into a similar issue. For me I think it had to do with reflection but I really don't know. There's not much information out there yet.

Adding the directives mentioned above to my Default.rd.xml file seems to have worked. Is it possible to explain how? Or why?

**Comment by nolanw** [comment]
@dandax As I understand it, the .NET native compiler strips out a bunch of stuff that it thinks you aren't using. However, it doesn't know what you're doing at runtime (e.g. reflection), so it can strip out stuff you do actually use. Then you crash.

That `Default.rd.xml` file tells the native compiler "actually I'm using the metadata for these assemblies/types/whatevers, please keep it in".

I am not very confident in my understanding, so don't count on anything I've said here actually being true ;)

**Comment by dandax** [comment]
@nolanw That makes a lot more sense. Much appreciated!

**Comment by nigel-sampson** [comment]
@nolanw summed it up well.

The .NET Native compiler tries to work out what metadata it needs to keep such that Reflection would still work. It doesn't keep all because that heavily increase file size and compile time.

Sometimes however it gets it wrong with what it throws away. 

App developers can give it hints about what it should keep through the `.rd.xml` file for the app.

Library developers can also provide hints through the similar file that gets included in the nuget package.

The above xml is just such a hint, however it's pretty much the nuclear option in saying "preserve the metadata of anything interacting with Caliburn.Micro", ideally we'd like to bring this down to something a little closer to what's actually required, however the reflection heavy nature of Caliburn.Micro means this could be what we're left with.
