### ISSUE TITLE
Grandchild OnActivate() not activated

### ISSUE THREAD

**Issue by deepforest** [Caliburn-Micro/Caliburn.Micro#200]
Hi,
I have a 3-level tree of view-models and views:
Parent
    Child1
        GrandChild1
        GrandChild2
        GrandChild2
    Child2
    Child3

The parent is a one-active conductor, exposes all children via Items. So the ChildX.
GrandChild is a Screen.

On level one and two there is a TabControl, each child is a TabItem.
So we have TabControl with 3-TabItems, each TabItem has 3-TabItems.

Problem is that children on level 2 are activated, but children on level 3 are not.
Already tries .ConductWith extension method, on children of level 1 parent and level 2 parent, not working.

To work-around, I've bound the TabControl to ActiveItem, then manually called ActivateItem with child when changed.

Any idea why CM not calling OnActivate() automatically as expected?

Thanks

**Comment by nigel-sampson** [comment]
Sorry for the time to onto this.

How are you binding the Children to the TabControl?

Assume this is WPF?

**Comment by nigel-sampson** [comment]
No new information, closing.
