### ISSUE TITLE
Derriving an interface from IHandle<T> can cause NullReferenceException in EventAggregator

### ISSUE THREAD

**Issue by aKzenT** [Caliburn-Micro/Caliburn.Micro#203]
I derrived a custom IEventSubscriber<T> interface from the IHandle<T> interface like this:

```c#
    public interface IEventSubscriber<T> : IHandle<T>
        where T : class
    {
    }
```

This can randomly fail and cause a NullReferenceException in the EventAggregator class when a class implementing the new interface tries to subscribe to an event and this event is then raised.

The culprit is in the following code taken from the Handler constructor:

```c#
                var interfaces = handler.GetType().GetInterfaces()
                    .Where(x => typeof(IHandle).IsAssignableFrom(x) && x.IsGenericType());

                foreach(var @interface in interfaces) {
                    var type = @interface.GetGenericArguments()[0];
                    var method = @interface.GetMethod("Handle", new Type[] { type });
                    supportedHandlers[type] = method;
                }
```

In the interfaces list both the original IHandle<T> and IEventSubscriber<T> will show up as they both derrive directly or indirectly from IHandle. Both are also generic. However IEventSubscriber<T> does not have a method named "Handle" which is why GetMethod will return null.

This will cause a NullReferenceException as soon as the handler is trying to get called.

It should be noted that the behaviour depends on the order in which the interfaces are enumerated of course. If the IHandle interface is enumerated last, then the problem will not occur.

Easiest way to fix this should be to add a null check inside the foreach loop.

Thanks!

**Comment by nigel-sampson** [comment]
Resolved in pull request, thanks.
