### ISSUE TITLE
Messages making the app crash on device

### ISSUE THREAD

**Issue by igorkulman** [Caliburn-Micro/Caliburn.Micro#207]
I have a Windows Phone 8.1 XAML project using Caliburn 2. The project works fine in Emulator. When I run it on a device (I tried two different devices) it randomly crashes when I navigate around the app. I use buttons with  `micro:Message.Attach` for navigation. No error message or exception in Visual Studio.

I use a content control for side menu that is on all the pages and my suspicion is that it causes the problem. 

Here is a minimal solution to reproduce the problem (only phone project is buildable): https://dl.dropboxusercontent.com/u/73642/Ott.WindowsPhone_1.0.0.0_AnyCPU.appx. 

Run the app, tap the red rectangle in the top left corner, navigate to about, the to settings, it will crash somewhere along the way.

**Comment by nigel-sampson** [comment]
Just downloaded it and had a play, unfortunately can't tell which menu items are about and settings.

The crashes seem very random, on one launch a menu item navigates to another page but on next launch it doesn't.

However without the source I can't look into the problem much further than I have.

**Comment by igorkulman** [comment]
Sorry, wrong file, here is the source https://www.dropbox.com/s/5u81wtzu9jpppg7/ott-mob-win.zip?dl=0

**Comment by igorkulman** [comment]
I did some more testing. The app usually crashes without an exception as I said but sometimes it crahes with `No target found fo X`. 

For example, the Settings button has `micro:Message.Attach = "[Event Click] = [Action NavigateToSettings]"` attached to it. Tapping the buttons sometimes work, sometimes crashes the app without any exception and sometimes crashes the app with `No target found for NavigateToSettings`.

**Comment by altso** [comment]
I had exactly the same problem in one of the apps. "Solved" that by adding an `ICommand` implementation in view model.

**Comment by igorkulman** [comment]
I thought about using `ICommand` but it is a bit strange when you use Caliburn messaging everywhere else. My workaround is to remove the control causing the problem and add its components from code in a shared base view, which is not much better.

**Comment by nigel-sampson** [comment]
Finally had some time to look at this, from what I can tell it's because `AboutViewModel` and `SettingsViewModel` aren't registered with the container.

``` csharp
container.PerRequest<AboutViewModel>();
container.PerRequest<SettingsViewModel>();
```

After adding the above to `App.xaml.cs` the navigation worked correctly on the emulator and a device.

The problem is that the navigation service doesn't throw an error if a view model cannot be found for the view and just keeps going with a null view model.
