### ISSUE TITLE
UI not updated second time

### ISSUE THREAD

**Issue by OfekA** [Caliburn-Micro/Caliburn.Micro#208]
I have the **exact** same issue as described here: http://stackoverflow.com/questions/12068375/caliburn-micro-ui-not-updated-second-time

So i will just copy the contents:

I am running into a problem where the controls in the View are not getting updated the second time the View is opened. The first time the data binding works fine. 

When I step through the ViewModel the second time the View is invoked I can see that the data bound properties are getting new values and invoking NotifyOfPropertyChange() but the change is not reflected in the UI. Any ideas? My View inherits `Screen`

Below are my properties in view model

     public string Info
        {
            get { return _info; }
            set { _info = value; NotifyOfPropertyChange(() => Info); }
        }

        public IEnumerable<ComponentInfo> BondableComponents
        {
            get { return _bondableComponents; }
            set { _bondableComponents = value; NotifyOfPropertyChange(() => BondableComponents); }
        }

and Xaml

    <TextBox Name="Info" Grid.Row="0" Grid.Column="0" IsReadOnly="True"/>
    <DataGrid ItemsSource="{Binding BondableComponents}">

**Comment by mvermef** [comment]
IEnumerable<ComponentInfo> Bondable

.   BindableCollection<ComponentInfo> Bondable

**Comment by OfekA** [comment]
Same happens with BindableCollection.
What about the string? They are both working at the first time the view loads.

**Comment by mvermef** [comment]
where are you loading items?  OnInit or OnActivated?

**Comment by OfekA** [comment]
I am not explicitly defining it anywhere in my app.

**Comment by nigel-sampson** [comment]
I've been unable to recreate your problem.

Is it possible to create a small sample that shows the problem?

When you say "opening the view" what are you referring to? Are you opening a second window?

**Comment by OfekA** [comment]
Thank you for trying to help, I have tried to simplify the project and here is the full code that is relevant: https://drive.google.com/file/d/0B-mIoc5bdUsPNWxkZm05OEt4b2c/view?usp=sharing

Basically, if you go New > Project, and then switch between the Imperial and Metric checkboxes, the view will update accordingly.
Afterwards, if you click on New > Project again, it will stop updating, but the properties are actually updated in memory, it is just the view that isn't updating.

I am pretty sure that it has something to do with the fact that the method Handle in the file "ProjectEnvironmentalDataViewModel" is being called multiple times for some reason, cant figure out why..

Any help would be greatly appreciated, thanks in advance!

**Comment by mvermef** [comment]
from what I can see your ```public static string Unit``` property is the culprit... since you never change the baseproject from the code provided, I played with it for a while and even made some changes around but in the end the only thing that truly gave out the results that was expected (in this case only the updated textboxes) after a Unit type change.  Now for some other reason it doesn't maintain the correct values that are populated from I don't know where they are init'd but it will now update UI on event change by not using a static string type for your Unit tracking in your BaseProject.cs.

Also if you never used it ```LogManager.GetLog = type => new DebugLog(type);``` is great for finding bogus bindings.   

Found a few with x:Name on them with a binding on your TextBoxes, use one or the other don't do both.  It can cause confusion, even though CM tends to disregard those bindings.

**Comment by OfekA** [comment]
I couldn't solve the problem and ended up working without the events in this case.

Thanks for the help.

**Comment by nigel-sampson** [comment]
So there was a few problems compounding to cause this bug.

First was that you weren't unsubscribing from the event aggregator in `ProjectEnvironmentalDataViewModel`, which looks be why you have your handler counter functionality. What's happening is previous view models that hadn't yet been garbage collected were still receiving events. You can resolve this by switching up the constructor to the following:

``` csharp
public ProjectEnvironmentalDataViewModel(IEventAggregator events)
{
    _events = events;
}

protected override void OnActivate()
{
    _events.Subscribe(this);
}

protected override void OnDeactivate(bool close)
{
    _events.Unsubscribe(this);
}
```
The handler counter functionality can now be deleted in the `Handle` method.

The second which made the above problem worse was that your properties on `ProjectViewModel` where creating a new child view model on every access.

``` csharp
public Screen ProjectBasicDataViewModel { get { return new ProjectBasicDataViewModel(_events); } }
public Screen ProjectEnvironmentalDataViewModel { get { return new ProjectEnvironmentalDataViewModel(_events); } }
public Screen ProjectMaterialsViewModel { get { return new ProjectMaterialsViewModel(_events); } }
public Screen ProjectFooterViewModel { get { return new ProjectFooterViewModel(); } }
```
There was always going to be two "access" of that property, the first when you activate it, and the second when the `ContentControl` bound to it tries to read it. This gives you a double message on the event aggregator. Switching to

``` csharp
public Screen ProjectBasicDataViewModel { get; private set; }
public Screen ProjectEnvironmentalDataViewModel { get; private set; }
public Screen ProjectMaterialsViewModel { get; private set; }
public Screen ProjectFooterViewModel { get; private set; }
```
and the constructor to

``` csharp
public ProjectViewModel(IEventAggregator events)
{
    _events = events;

    ProjectBasicDataViewModel = new ProjectBasicDataViewModel(_events);
    ProjectEnvironmentalDataViewModel = new ProjectEnvironmentalDataViewModel(_events);
    ProjectMaterialsViewModel = new ProjectMaterialsViewModel(_events);
    ProjectFooterViewModel = new ProjectFooterViewModel();

    ActivateItem(ProjectBasicDataViewModel);
    ActivateItem(ProjectEnvironmentalDataViewModel);
    ActivateItem(ProjectMaterialsViewModel);
    ActivateItem(ProjectFooterViewModel);
}
```
stops this.

As @mvermef mentioned I suspect the static nature of Unit also compounded the problem with the double messages and so on.

After the above changes I think I hit the right behaviour.

**Comment by OfekA** [comment]
Thank you very much for your help, it solved my problem, I also didn't realize I need to unsubscribe from the EventAggregator on Deactivate.

**Comment by nigel-sampson** [comment]
You don't need to, the `EventAggregator` holds weak references to listeners so you won't leak memory, however it just means you may get messages you don't want so it's for the best.
