### ISSUE TITLE
Supported Visual Studio versions and Platforms

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#209]
Visual Studio 2015 has just come out and adds support for Universal Windows Projects #141 .

Support for building Windows 8 apps has been dropped by this version, I'm wondering if we should do the same at 3.0.0.

We'd still support Windows 8.1, Windows Phone 8 and Windows Phone 8.1.

We haven't been adding new features so there would be no functionality lost by keeping Windows 8 in the 2.0.x era.

Thoughts?

**Comment by mvermef** [comment]
Deprecating is tough since I am sure some are still reliant on that variant but with 2.0x still avail it wouldn't hurt to drop for the next release so we can make room for the massive changes encompassed by the move to the newer format.  What help would you need to make the restructure relative to comments in #141 as painless as possible?  Got one project in holding pattern for device(s) to be placed in everyone's hands.  Realized how much I would miss having a working CM library to use with that project for Win10 dev, its present form.

**Comment by nigel-sampson** [comment]
I've managed to get some time blocked out so doing the restructure at the moment to shared projects, will mostly likely remove Windows 8 in the 3.0.0 branch at the same time.

Will be adding UWP projects back in after that, hope to have it on the 3.0.0 branch some time today.

**Comment by nigel-sampson** [comment]
So I've managed to migrate everything to shared projects with only minor hassles and added a new UWP project (was going to be easier than trying to merge the windows-10 branch).

I'm going to hold off on pushing it tonight as I want to get the xamarin branch merged onto 3.0.0, right now it's hard to say whether the merge hell will be better before or after this restructure.

**Comment by nigel-sampson** [comment]
So I've been working on merging the xamarin work with the shared projects / uwp work and it's exposed some pretty major holes in how shared projects will work [summarised in a nuget issue](https://github.com/NuGet/Home/issues/1102).

While it kind of worked for the 3.0.0 branch pre xamarin it really falls down at this point due to a number of projects using a real subset of files.

I'm thinking a better approach till hopefully this is resolved is to use linked files for UWP.

**Comment by mvermef** [comment]
so are we on hold for the Xamarin inclusion to the framework or do we proceed with a separate release for UWP? or both??

**Comment by nigel-sampson** [comment]
Nope, I've just pushed xamarin and uwp on to 3.0.0, there's still a few days worth of things to get done before the next nuget release but we're on the way.

**Comment by mvermef** [comment]
Played with some of it to reference into a UWP there needs to be a check box checked in Build -> Output -> Generate library layout,  Then that whole thing will be created, properties folder, another folder called Caliburn.Micro.Platform.UWP, which will contain the Caliburn.Micro.Platform.UWP.rd.xml file need for building referenced projects.    reference: https://msdn.microsoft.com/en-us/library/dn600639(v=vs.110).aspx.

**Comment by nigel-sampson** [comment]
Yup, fixed that up and added a small sample for the moment.

**Comment by nigel-sampson** [comment]
Resolved on the 3.0.0 branch,
