### ISSUE TITLE
Someone with XP in Conductors, Confirm Conductor Screen Transition is set up correctly

### ISSUE THREAD

**Issue by Acaspita** [Caliburn-Micro/Caliburn.Micro#211]
Hi,
I've created a conductor and would like to know if it's configured correctly. I have my doubts about it, I think there could be a better way.
```
public class ShellViewModel : Conductor<IScreen>.Collection.OneActive, IShell
{
        ...
        public void ShowPageOne()
        {
            ActivateItem(new PageOneViewModel(_eventAggregator));
        }
}

class PageOneViewModel : Screen, IHandle<CultureInfo>
{
        ...
        /// <summary>
        /// Action to Go to Two.
        /// </summary>
        public void GoToTwo(object contact)
        {
            if (((BindableCollection<IScreen>)Conductor.GetChildren()).Count == 2)
            {
                Conductor.ActivateItem(((BindableCollection<IScreen>)Conductor.GetChildren())[1]);
            }
            else
            {
                Conductor.ActivateItem(new PageTwoViewModel(((UIContactData)contact).ContactSIP));
            }
        }
}

class PageTwoViewModel : Screen
{
        ...
        /// <summary>
        /// Action to Go to One.
        /// </summary>
        public void GoToOne()
        {
            Conductor.ActivateItem(((BindableCollection<IScreen>)Conductor.GetChildren())[0]);
        }
}
```

**Comment by nigel-sampson** [comment]
This could work and there's nothing wrong with it, there are obviously different ways you can go about this. Typically how I send up doing something like this is to use event aggregation and also hold references to the items.

By this I mean set up `PageOneViewModel` and `PageTwoViewModel` before hand and hold references to them in `ShellViewModel`. This way you're only switching activation not having to check how many children there are.

You could also use the event aggregator to send messages from the children to the parent. If that seems overkill you could have methods on the parent and just have the child cast to that, encapsulating the logic in the parent and not the children.

**Comment by Acaspita** [comment]
Thank you Nigel, very useful and clarifying..
