### ISSUE TITLE
How to bind action to nested ViewModel method?

### ISSUE THREAD

**Issue by BrainCrumbz** [Caliburn-Micro/Caliburn.Micro#213]
I have a WPF application, powered by Caliburn.Micro, view-model first approach. There's a command-bar type of control with its *CommandBarView.xaml* and bound *CommandBarViewModel*. Command-bar VM holds a number of nested VMs, one for each button control, all showing a common interface and having common behaviour. Command-bar VM expose them so they can be bound from view:

```c#
public interface IWarningButtonViewModel
{
    bool IsVisible { get; }
    bool CanShowWarning { get; }
    void ShowWarning();
}

public class CommandBarViewModel : PropertyChangedBase
{
    public IWarningButtonViewModel UserNotFoundWarning { get; private set; }
    public IWarningButtonViewModel NetworkProblemWarning { get; private set; }
    // ... initialization omitted for simplicity
}
```

This is a tentative XAML for a bit of CommandBarView:

```xaml
<Button x:Name="UserNotFoundWarning_ShowWarning"
        IsEnabled="{Binding UserNotFoundWarning.CanShowWarning}">
  ... 
  <DataTrigger Binding="{Binding UserNotFoundWarning.IsVisible}" Value="True">
  ...
</Button>
```

In this way I'm able to successfully bind the two properties (*CanShowWarning*, *IsVisible*) but I'm not able to bind the button command/action to *ShowWarning* method.

I tried with [deep property binding](https://joshearl.wordpress.com/2011/03/24/deep-property-databinding-with-caliburn-micro/) and that works again for properties, but not for action.  
I also tried with a mix of `cal:Model.Bind` and `cal:Message.Attach`:

```xaml
<Button cal:Model.Bind="{Binding UserNotFoundWarning}" 
        cal:Message.Attach="[Event Click] = [Action ShowWarning]"
        IsEnabled="{Binding CanShowWarning}">
  ... 
  <DataTrigger Binding="{Binding IsVisible}" Value="True">
  ...
</Button>
```

That seems to work at runtime, but *cal:Model.Bind* makes the VS designer completely unusable, UI controls are not shown.

I've searched around quite a bit, but I could not find an actual solution that let me also work with designer. It seems strange to me that I could only find examples of deep binding for properties, not for actions.

Any idea how to solve this?

We cannot seem to find an answer to this, so we're also posting it here after [SO](http://stackoverflow.com/questions/31991203/in-caliburn-micro-how-to-bind-action-to-nested-viewmodel-method).

Thanks for your time Sirs

**Comment by nigel-sampson** [comment]
You're correct the deep binding syntax is only for properties and not methods, that seems like an oversight, however I may need to talk to some of the original developers to see if there was a reason.

I'm surprised about the designer issue with `Model.Bind` as that would probably be the way I'd go about this. Are there any error messages shown? I'm wondering if it's actually triggering the data trigger with a false and hiding itself in the designer?

Just another helpful tip, you can trim down some of the syntax because of defaults. The `Click` event is the default by convention for buttons and attaching `ShowWarning` causes Caliburn to look for the `CanShowWarning` guard property. This allows the following syntax

``` xml
<Button cal:Model.Bind="{Binding UserNotFoundWarning}" 
        cal:Message.Attach="ShowWarning">
  ... 
  <DataTrigger Binding="{Binding IsVisible}" Value="True">
  ...
</Button>
```

**Comment by BrainCrumbz** [comment]
**Errata:** just for this issue thread, I wrongly typed `cal:Bind.Model` as `cal:Model.Bind`: that is only here in issue, the former was correctly used throughout in code.

<hr />

I tried again with the `Bind.Model` approach. I didn't check (again) if that actually works at runtime, but for the purpose of XAML designer, that single button being changed simply disappears from the command-bar button set. No error nor warning comes from designer nor Error List window.

> I'm wondering if it's actually triggering the data trigger with a false and hiding itself in the designer?

For completeness: at design time the "data" come from a `DesignTimeCommandBarVM`, modeled after the runtime one, and exposing in turn some `DesignTimeButtonVM` with their own const properties (e.g. IsVisible) and dummy methods (ShowWarning). That is usually working fine enough for designer.

For all dummy design-time buttons, IsVisible is set to true, and as a matter of fact if I change the design-time value I can see its effect in designer. But when I switch to Bind.Model it just disappears, so probably it cannot find the actual bound property and maps that to false.

Thanks for the Message.Attach hint: yes I know about that, it was just the effect of many tests one over the other. BTW, IsEnabled is bound to the guard so that we can change the look of button, apart from not allowing the action.

**Comment by nigel-sampson** [comment]
Can I just confirm the approach is working at runtime, but hiding the button in the designer?

**Comment by BrainCrumbz** [comment]
We tried with a partial change: apply *Bind.Model*, update *Message.Attach*, update *IsEnabled Binding* ... everything apart from *DataTrigger Binding*:

```xaml
<Button cal:Bind.Model="{Binding TechProblemPreWarning}" cal:Message.Attach="ShowWarning" IsEnabled="{Binding CanShowWarning}" fa:Awesome.Content="LightbulbOutlined">
    <Button.Style>
        <Style BasedOn="{StaticResource SymbolFunctionPushButtonStyle}" TargetType="{x:Type Button}">
            ...
            <Setter Property="Visibility" Value="Collapsed" />
            <Style.Triggers>
                <DataTrigger Binding="{Binding TechProblemPreWarning.IsVisible}" Value="True">
                    <Setter Property="Visibility" Value="Visible" />
                </DataTrigger>
            </Style.Triggers>
        </Style>
    </Button.Style>
</Button>
```

The designer shows the button, but at runtime opening the window shows 3 (non crashing) exceptions and the button stays not visible:

> System.Windows.Data Error: 40 : BindingExpression path error: 'CanShowWarning' property not found on 'object' ''OurCommandBarViewModel' (HashCode=36218857)'. BindingExpression:Path=CanShowWarning; DataItem='OurCommandBarViewModel' (HashCode=36218857); target element is 'Button' (Name=''); target property is 'IsEnabled' (type 'Boolean')
> System.Windows.Data Error: 40 : BindingExpression path error: 'TechProblemPreWarning' property not found on 'object' ''TechProblemPreWarningVM' (HashCode=10871268)'. BindingExpression:Path=TechProblemPreWarning; DataItem='TechProblemPreWarningVM' (HashCode=10871268); target element is 'Button' (Name=''); target property is 'Model' (type 'Object')
> System.Windows.Data Error: 40 : BindingExpression path error: 'TechProblemPreWarning' property not found on 'object' ''TechProblemPreWarningVM' (HashCode=10871268)'. BindingExpression:Path=TechProblemPreWarning.IsVisible; DataItem='TechProblemPreWarningVM' (HashCode=10871268); target element is 'Button' (Name=''); target property is 'NoTarget' (type 'Object')

Then we tried updating also the last bit, *DataTrigger Visibility Binding*:

```xaml
<Button cal:Bind.Model="{Binding TechProblemPreWarning}" cal:Message.Attach="ShowWarning" IsEnabled="{Binding CanShowWarning}" fa:Awesome.Content="LightbulbOutlined">
    <Button.Style>
        <Style BasedOn="{StaticResource SymbolFunctionPushButtonStyle}" TargetType="{x:Type Button}">
            ...
            <Setter Property="Visibility" Value="Collapsed" />
            <Style.Triggers>
                <DataTrigger Binding="{Binding IsVisible}" Value="True">
                    <Setter Property="Visibility" Value="Visible" />
                </DataTrigger>
            </Style.Triggers>
        </Style>
    </Button.Style>
</Button>
```

As expected, this makes the button not visible in designer (I don't even have to recompile, as soon as I edit it will disappear). At runtime we see other 3 exceptions when opening windows, in part different that before, but the button shows up when it should:

> System.Windows.Data Error: 40 : BindingExpression path error: 'CanShowWarning' property not found on 'object' ''OurCommandBarViewModel' (HashCode=25079257)'. BindingExpression:Path=CanShowWarning; DataItem='OurCommandBarViewModel' (HashCode=25079257); target element is 'Button' (Name=''); target property is 'IsEnabled' (type 'Boolean')

> System.Windows.Data Error: 40 : BindingExpression path error: 'IsVisible' property not found on 'object' ''OurCommandBarViewModel' (HashCode=25079257)'. BindingExpression:Path=IsVisible; DataItem='OurCommandBarViewModel' (HashCode=25079257); target element is 'Button' (Name=''); target property is 'NoTarget' (type 'Object')

> System.Windows.Data Error: 40 : BindingExpression path error: 'TechProblemPreWarning' property not found on 'object' ''TechProblemPreWarningVM' (HashCode=48172674)'. BindingExpression:Path=TechProblemPreWarning; DataItem='TechProblemPreWarningVM' (HashCode=48172674); target element is 'Button' (Name=''); target property is 'Model' (type 'Object')

**Comment by BrainCrumbz** [comment]
Hi there. Is there any update on this? Regards

**Comment by wstaelens** [comment]
"You're correct the deep binding syntax is only for properties and not methods, that seems like an oversight, however I may need to talk to some of the original developers to see if there was a reason."

Would like to see support for deep binding on methods! :-)

**Comment by nigel-sampson** [comment]
Nothing at the moment, however those binding error aren't entirely as `Bind.Model` sets the `DataContext` on the `Button`, this mean that initially when the bindings are evaluated the property ones are using the inherited data context of `CommandBarViewModel`.

**Comment by BrainCrumbz** [comment]
Sorry I did not get when you say *"... aren't entirely as ..."*. Is there some word missing?

**Comment by nigel-sampson** [comment]
Updated my above comment with some clarification on why the approach will see handled binding exceptions.

**Comment by BrainCrumbz** [comment]
Thanks a lot for explaining. So basically apart from those harmless binding exceptions, the only thing left is how to make VS Designer work again with this scenario

**Comment by Torvin** [comment]
@BrainCrumbz I'm pretty sure you could use `Bind.ModelWithoutContext` instead of `Bind.Model` to avoid designer problems, as it only sets the model for actions.

**Comment by Torvin** [comment]
@BrainCrumbz I've come up with the workaround. Check it at [SO](http://stackoverflow.com/a/33005816/332528)

**Comment by BrainCrumbz** [comment]
I'm not aware of that `Bind.ModelWithoutContext`: from what you say, I got that it only works with actions, but we also need to bind properties to nested view-models.

Your proposed workaround looks promising: you're customising the way CM binds to action starting from the passed string, so it should be ok. We customised CM already, in its view location strategy, in order to substitute design-time view-models in place of runtime ones and it worked reasonably good.

We'll try this solution in the next days.

**Comment by Torvin** [comment]
@BrainCrumbz, yes, `Bind.ModelWithoutContext` only works with actions. But you can bind properties the usual way, via dotted notation. Still, my solution is better, as it allow you to bind different actions to different nested viewmodels on the same element, while `Bind.ModelWithoutContext` sets the viewmodel for all actions.

**Comment by BrainCrumbz** [comment]
A (late) comment: as noted on StackOverflow question, @Torvin workaround did the trick

**Comment by nigel-sampson** [comment]
Interesting workround, thanks @Torvin, give the heavy limitations around things like the chain of objects in the method path changing I doubt this will be something we add to the frameworks.

**Comment by Torvin** [comment]
You can do it properly on your end without the limitations of my workaround. Just like how chains of properties are implemented now.

**Comment by nigel-sampson** [comment]
The property chaining works because the underlying binding infrastructure handles the limitations, all CM does its turn `SomeProperty_Value` into `{Binding SomeProperty.Value}`.

**Comment by Torvin** [comment]
I bet handler's parent object can be obtained via binding too.
