### ISSUE TITLE
DesignTime support breaks build

### ISSUE THREAD

**Issue by beachwalker** [Caliburn-Micro/Caliburn.Micro#217]
Caliburn.Micro has builtin support for designtime data. Larger applications are typically divided into several assemblies. When having separate assemblies for App, ViewModels and Views you need to override the SelectAssemblies() method in the Bootstrapper and add the assemblies containing the views (for viewmodel->view resolution). This method will load all required assemblies. This works as expected, but when using designtime ViewModels (e.g. display a View in a ContentControl as ActiveItem) they are not unloaded after displaying them. It seems some process keeps the app domain. As a result the next build (while having Visual Studio open) will fail because Visual Studio is unable to copy the new Assembly.

You have to close and reopen Visual Studio as a workaround.

This is my SelectAssemblies Method override:

        protected override IEnumerable<Assembly> SelectAssemblies()
        {
            // Todo: Find a better solution to take care that same assemblies aren't returned twice... maybe needs a fix within Caliburn.Micro at least
            var assemblies = new HashSet<Assembly>();
            if (Execute.InDesignMode)
            {
                var fileInfos = new List<FileInfo>();

                try
                {
                    //var path = Path.GetDirectoryName(this.GetType().Assembly.Location);

                    // loading all Assemblies that may contain views for design time
                    var path = @"D:\MyProject\build\Debug\bin";
                    if (!string.IsNullOrEmpty(path))
                    {
                        var di = new DirectoryInfo(path);
                        var files = di.EnumerateFiles("*.dll");
                        fileInfos.AddRange(files);
                    }
                }
                catch
                {
                    // ignored
                }

                foreach (var fileInfo in fileInfos)
                {
                    Assembly assembly = null;

                    try
                    {
                        assembly = Assembly.LoadFrom(fileInfo.FullName);
                        // oops, when do they get unloaded?
                    }
                    catch
                    {
                        // ignored
                    }

                    if (assembly != null)
                    {
                        assemblies.Add(assembly);
                    }
                }
            }

            foreach (var assembly in base.SelectAssemblies())
            {
                assemblies.Add(assembly);
            }

            return assemblies;
        }

**Comment by beachwalker** [comment]
The following code works for me right now:

        protected override IEnumerable<Assembly> SelectAssemblies()
        {
            // Todo: Find a better solution to take care that same assemblies aren't returned twice... maybe fix Caliburn.Micro at least
            var assemblies = new HashSet<Assembly>();

            if (Execute.InDesignMode)
            {
                foreach (var assembly in Assembly.GetExecutingAssembly().GetReferencedAssemblies())
                {
                    assemblies.Add(Assembly.Load(assembly));
                }
            }

            foreach (var assembly in base.SelectAssemblies())
            {
                assemblies.Add(assembly);
            }

            return assemblies;
        }

**Comment by beachwalker** [comment]
... is indeed still a probem in larger applications.

**Comment by nigel-sampson** [comment]
Personally I shy away from this sort of dynamism in `SelectAssemblies` as it's usually overkill. You should only need to provide the assemblies that contain views or view models. 

I typically have something like

``` csharp
protected override IEnumerable<Assembly> SelectAssemblies()
{
    yield return typeof(App).GetTypeInfo().Assembly;
    yield return typeof(LoginViewModel).GetTypeInfo().Assembly;
    yield return typeof(LoginView).GetTypeInfo().Assembly;
}
```

This way you're also not explicitly loading the assembly and just referencing the one already in the app domain.
