### ISSUE TITLE
Bug? Cannot find view for ...

### ISSUE THREAD

**Issue by wstaelens** [Caliburn-Micro/Caliburn.Micro#218]
I try to explain as good as possible (as I was not able to extract it to a sample application. It is a bit complex).

overview:

-ShellView, a conductor with collection one active.
-- ZooView
--- ZooView has ListBox with ItemTemplate of AnimalView
--OptionsView

-- NoDataView

1) ShellView is visible as ActiveItem it has ZooView.
   ZooView does not have a Zoo loaded so no animal data is available to show.
   Because no animal data is available to show, a trigger is activated in ZooView and it makes another view visible "NoDataView".

2) Because there is no data, we go to OptionsView.
   OptionsView is now ActiveItem of the ShellView.
   From the OptionsView we have an option to load Zoo-data with animals.

3) A Message is published on the UIThread because we loaded the Zoo-data here in the OptionsViewModel

4) The ZooViewModel accepts and IHandle the message and takes the zoo-data and sets it.
   This makes that the trigger is checked and this hides the "NoDataView" and shows the ListBox with "AnimalView" items.
   We still see the OptionsView, not yet the ZooView.

5) Now we click a button that returns us back to the "ZooView" via ActivateItem in the ShellViewModel.

   Here is the problem: "Cannot find view for SolutionProject.ViewModels.AnimalViewModel."

The problem seems to occur in a view that was first visible and while it is hidden its visual appearance changed. So while another view was visible, datacontext has changed so xaml triggers of the hidden view have changed, resulting in a different view (template or contentcontrol) being loaded.
When making that view visible again, the new view being loaded (because of the xaml triggers) is not found by caliburn.micro.
   

WPF / C# / .Net 4.5 / Caliburn.Micro 2.0.2

**Comment by nigel-sampson** [comment]
Can you provide the full types (including namespace and assembly) for `AnimalView` and `AnimalViewModel`?

The only place that error message occurs is when it cannot locate the view for a given view model. This is usually either because there's a naming mismatch or they're in different assemblies.

**Comment by wstaelens** [comment]
It is similar to this:
SolutionProject.ViewModels.AnimalViewModel
SolutionProject.Views.AnimalView

However finding the view, when working normally, is not a problem. It finds the view.
Only in the way I described above it doesn't find it, which makes me think it is a bug...

- ShellView (Conductor<object>.Collection.OneActive
- AView
- AInnerView
- BView

AView changes its appearance: when there is no data, AView has a trigger based on a proprety "HasData" in the AViewModel. If there is no data then AView shows a grid with "No data".
When there is data, the style trigger changed an AView shows "AInnerView".

Here is the thing: 
WHEN AView IS NOT VISIBLE: because of some action "NoData" property changes in AViewModel --> AView trigger changes xaml from "No Data" to "AInnerView" WHEN IT IS NOT VISIBLE and you return to AView, thus making AView and AInnerView visible it results in the problem: "Cannot find view for .....AInnerViewModel".

So I do like this:
Start up application --> NoData is shown --> I go to the options (BView as ActiveItem) --> I load data via BView --> this publishes messages and changes properties in datacontext --> I return to AView --> this should show me AView + AInnerView but result is that "Cannot find view for ... AInnerViewModel".

If I do this all is fine:
Start up application --> NoData is shown --> button on the NoData to load the data (thus not showing BView) --> AView changes from NoData to AInnerView --> all is ok and view is found.

Hope this helps.

**Comment by nigel-sampson** [comment]
To be honest this is such a complicated / convoluted scenario I doubt I'll be able to help much without a working repro.

**Comment by wstaelens** [comment]
emailed more info :-)

**Comment by wstaelens** [comment]
As emailed, the problem seems to be solved when removing this:

<ListBox.ItemTemplate>
      <DataTemplate>
        <ContentControl cal:View.Model="{Binding}" />
      </DataTemplate>
    </ListBox.ItemTemplate>


My guess is that changes in DataTriggers don't 'bubble up' to some nested controls when they are not visible.

**Comment by nigel-sampson** [comment]
Glad to here it's solved.

**Comment by wstaelens** [comment]
Well it is solved by disabling code that works 90% of the times, and also should work.
But I still think it is a bug because it should work when using an ItemTemplate.

**Comment by wstaelens** [comment]
I think you can close this one. Code was rewritten in a different way, never found the real source. Only that it might have to do with templates and things that do not 'bubble up'.
