### ISSUE TITLE
How to keep track of external windows (.Net InterOp)

### ISSUE THREAD

**Issue by nologinatgit** [Caliburn-Micro/Caliburn.Micro#219]
The scenario:

We develop a .Net program using Caliburn.Micro and this program opens _external_ windows using .Net Interop (the external program is developed with Delphi).
Unfortunately the opening process is quite complicated (and does not use CM) and the windows keep loosing focus and they stuck behind each other.

To avoid these situations, we keep the window handle IDs in a list, and try to refocus the windows with Windows API calls. However, these can create cumbersome situations and sometimes do not work properly.

Is there any way (or methodology) to use CM to handle external windows? What would you recommend for this particular situation?

**Comment by nigel-sampson** [comment]
Sorry but there is nothing built into CM to handle external windows.

I don't do enough WPF with that sort of featureset to give you any (good) recommendations.

**Comment by nologinatgit** [comment]
Well, we thought it would require some additional modification of CM but it would be nice to have any direction of which part of CM should handle the window handles (some sort of initialization when a new external windows is "added").
Any other suggestion is appreciated.

**Comment by nigel-sampson** [comment]
CM in WPF does have a Window Manager, but that's mostly for creating new WPF windows rather than external ones, but that may be the appropriate place to extend.

Beyond that, I can't really help.
