### ISSUE TITLE
Missing documentation for EnsureItem

### ISSUE THREAD

**Issue by bitbonk** [Caliburn-Micro/Caliburn.Micro#220]
What is the method parameter [newItem in EnsureItem](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/aabee7aa8e3105f7720463f88938629bd63d113f/src/Caliburn.Micro/ConductorWithCollectionOneActive.cs#L187) for?

**Comment by nigel-sampson** [comment]
Resolved by #221
