### ISSUE TITLE
[UAP] INavigationService w/ Frame and SplitView

### ISSUE THREAD

**Issue by mvermef** [Caliburn-Micro/Caliburn.Micro#224]
To be able to resume and suspend in the App.xaml.cs there is no way to do without affecting the INavigationService and how it is setup with the SplitView.  Right now I have it setup with some tweaks in the App.cs and ShellView as per the Basic Sample in the 3.0 repo.   But if you setup INavigationService in the App.cs with PrepareViewFirst() to get a working service the incorrect Frame is setup prior to the SetupNavigation in the ShellViewModel it will not have the correct "RootFrame" all navigation will succeed but actual navigation isn't shown as you would expect it.  The "Adjusted" (aka SetupNavigation() ) Frame in this case will never render the navigation request.

**Comment by nigel-sampson** [comment]
If you're using the approach in the sample I wouldn't recommend using `PrepareViewFirst` or `RootFrame` since as your saw you'll have the wrong `INavigationService`.

What you'll need to do is somehow propagate the suspending / resuming events into the `ShellViewModel` so that it can use the real navigation service.

For the suspending event you could just query the container since it should have been created by then. For resumption you can either pass the launch args into the ShellViewModel and it can decide whether to resume or simply pass a resume flag.

**Comment by mvermef** [comment]
I should have been more clear.  PrepareViewFirst() is bad, but I guess I don't know where to structure the OnSuspend, would that be in the shellviewmodel now as an override?

**Comment by nigel-sampson** [comment]
Since the `ShellViewModel` is registering the navigation service it can just retain access to (if you want to handle suspension there), if however you want to do it in App.xaml.cs then you have access to the container itself shouldn't need to use `IoC`.

**Comment by mvermef** [comment]
I am probably beating a dead horse or don't quite understand how this should work since its a little different start up and resume flow.  Where would you place the ResumeState? Placing it in the SetupNavigation is bad, since the container will freak out on the CacheFrameAdapter.

**Comment by nigel-sampson** [comment]
I've just updated the UWP sample to show what I mean.

**Comment by mvermef** [comment]
Thanks

**Comment by mvermef** [comment]
482             if (Window.Current.Content != frame) 
483                 Window.Current.Content = frame; 

in the INavigationService.cs in the FrameAdapter implementation this wipes out the "shellview" and replaces what ever was stored to content of the current window with the frame.  This is going to be potentially really hard to solve with the current method used.  Messaging solution works really well actually.

**Comment by nigel-sampson** [comment]
Ah good point, forgot that was in there, will think on it.

**Comment by mvermef** [comment]
would searching the visual tree and trapping for splitview be a solution to this particular issue.  Obviously it's a fringe use case.

**Comment by nigel-sampson** [comment]
I'm really hesitant to do anything around hunting the visual tree, experience has taught me that people will structure applications a lot differently than expected.

Most likely the solution will be an overload or parameter on ResumeState that sets the frame or not,

**Comment by mvermef** [comment]
I was looking over Template10, and they did something similar they actually checked to see if the contents of the Current Window were null or if it was set to a splash, from there if they also flow with inject content from developer.  This leads to not overwriting the content that may already be in the ShellView in this case, in either case they were saving state for each page viewed

**Comment by nigel-sampson** [comment]
I think the way to do this for the moment is just to check to see if it's not null before setting.

**Comment by mvermef** [comment]
That might work.

-----Original Message-----

**Comment by nigel-sampson** [comment]
Resolved in 3.0.0-beta2
