### ISSUE TITLE
BlockedFromReflection run-time exception in production with .NET Native compilation

### ISSUE THREAD

**Issue by sevenate** [Caliburn-Micro/Caliburn.Micro#226]
I have an universal Win 10 app in the store that use Caliburn.Micro as a core app framework. During debug everything works fine, but when I've checked production logs I've noticed few exceptions that were caught by global exception handler. If anyone from dev team could see something obvious and shed some light on the cause of this exception, I would be very grateful (please let me know if any other information could help).

Device: Dell XPS 12 9Q23 (laptop)
OS: Windows 10.0.10240.16463
CPU: x64
HResult: 0x80131543
Exception type:      $BlockedFromReflection_0_1f245f45

Failed method:

```
Caliburn.Micro.ConventionManager.SetBindingWithoutBindingOverwrite(Type viewModelType, String path, Reflection.PropertyInfo property, UI.Xaml.FrameworkElement element, Micro.ElementConvention convention, UI.Xaml.DependencyProperty bindableProperty)
```

Call stack:

```
   at MyApp!<BaseAddress>+0xbf915c
   at Caliburn.Micro.ConventionManager.SetBindingWithoutBindingOverwrite(Type viewModelType, String path, Reflection.PropertyInfo property, UI.Xaml.FrameworkElement element, Micro.ElementConvention convention, UI.Xaml.DependencyProperty bindableProperty)
   at Caliburn.Micro.ElementConvention.<>c.<.ctor>b__5_0(Type viewModelType, String path, Reflection.PropertyInfo property, UI.Xaml.FrameworkElement element, Micro.ElementConvention convention)
   at Caliburn.Micro.ViewModelBinder.<>c.<.cctor>b__8_0(Collections.Generic.IEnumerable<Windows.UI.Xaml.FrameworkElement> namedElements, Type viewModelType)
   at Caliburn.Micro.ViewModelBinder.<>c.<.cctor>b__8_3(Object viewModel, UI.Xaml.DependencyObject view, Object context)
   at MyApp!<BaseAddress>+0x748d53
   at Caliburn.Micro.Bind.<>c__DisplayClass7_0.<ModelChanged>b__0(Object <unknown>, UI.Xaml.RoutedEventArgs <unknown>)
   at MyApp!<BaseAddress>+0x79ee3e
   at Caliburn.Micro.View.<>c__DisplayClass8_0.<ExecuteOnLoad>b__0(Object s, UI.Xaml.RoutedEventArgs e)
   at MyApp!<BaseAddress>+0xab5527
```

and another one very similar

Failed method:

```
Caliburn.Micro.ActionMessage.<>c.<.cctor>b__32_1(Micro.ActionExecutionContext context)
```

Call stack:

```
   at MyApp!<BaseAddress>+0xbf915c
   at Caliburn.Micro.ActionMessage.<>c.<.cctor>b__32_1(Micro.ActionExecutionContext context)
   at System.Func<System.Object,System.Boolean>.Invoke(Object arg)
   at Caliburn.Micro.ActionMessage.UpdateAvailabilityCore()
   at Caliburn.Micro.ActionMessage.UpdateContext()
   at Caliburn.Micro.ActionMessage.ElementLoaded(Object sender, UI.Xaml.RoutedEventArgs e)
   at MyApp!<BaseAddress>+0x79ee3e
   at Caliburn.Micro.View.<>c__DisplayClass8_0.<ExecuteOnLoad>b__0(Object s, UI.Xaml.RoutedEventArgs e)
   at MyApp!<BaseAddress>+0xab5527
```

**Comment by nigel-sampson** [comment]
So both of these are failing with the same exception, without looking into in too much detail (I'm out of the office) it sounds like the framework may be trying to do something like write to a private or protected property and being blocked.

If you have a sample that's generating these errors I'd love to see it.

Thanks

**Comment by sevenate** [comment]
I'll surely cook up something simple after I'll be able to reproduce it locally. Thanks for response.

**Comment by sevenate** [comment]
So far I have a theory that problem could be in this line in ConventionManager.cs:

```c#
        /// <summary>
        /// Determines whether a particular dependency property already has a binding on the provided element.
        /// </summary>
        public static bool HasBinding(FrameworkElement element, DependencyProperty property) {
#if NET
            return BindingOperations.GetBindingBase(element, property) != null;
#elif WINDOWS_UWP
            var localValue = element.ReadLocalValue(property);

            if (localValue == DependencyProperty.UnsetValue)
                return false;
// ########################################################################
            return localValue.GetType().FullName == "System.__ComObject";
// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#else
            return element.GetBindingExpression(property) != null;
#endif
        }
```
But I'm up to test it on some sample project

**Comment by sevenate** [comment]
I have no idea how I've closed this issue, sorry :)

**Comment by nigel-sampson** [comment]
Can I double check which version of CM you're using? In 3.0.0 we've removed the Windows 8 (not 8.1) framework which means the source on that branch is:

``` csharp
public static bool HasBinding(FrameworkElement element, DependencyProperty property)
{
#if NET
    return BindingOperations.GetBindingBase(element, property) != null;
#else
    return element.GetBindingExpression(property) != null;
#endif
}
```

Which is nice and simple.

**Comment by sevenate** [comment]
Well, that is right question - I've used custom Caliburn.Micro build created from _windows-10_ branch a few month ago (when there was no official support for Windows 10 UWP projects yet I guess) and it was updated last time at the end of July 2015, so that may be the cause.

So I'll check if that issue happens with the "Caliburn.Micro 3.0.0-beta1" build.

**Comment by nigel-sampson** [comment]
Thanks for the information, if you were using that *windows-10* branch you may be right about that line.

One change I made between the *windows-10* branch and *3.0.0* is removing Windows 8 which simplified the code to what I posted.

Definitely check out the 3.0.0-beta1 and let me know how you go.

**Comment by nigel-sampson** [comment]
Closing this out due to lack of more information, assuming the new branch resolved it.

**Comment by sevenate** [comment]
Just want to update on this (kind of late, but anyway) - after switching to 3.0.0-beta1 release these kind of native exceptions no longer appear in production logs. Sorry for false alarm.

**Comment by nigel-sampson** [comment]
No worries, glad it's sorted.
