### ISSUE TITLE
ApplyUpdateSourceTrigger behavior

### ISSUE THREAD

**Issue by InlineAsm** [Caliburn-Micro/Caliburn.Micro#228]
Hello, since installing Caliburn.Micro 3.0 - beta1 in our WPF 4.5 project the ConventionManager.ApplyUpdateSourceTrigger no longer seems to apply UpdateSourceTrigger.PropertyChanged to the binding.

Manually applying this in the bootstrapper makes it work again:

ConventionManager.ApplyUpdateSourceTrigger = (bindableProperty, element, binding, info) => binding.UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged;

 Is this a bug?

**Comment by nigel-sampson** [comment]
If that's happening then this is a bug, I'm away from a machine where I can test / look into it.

**Comment by InlineAsm** [comment]
Thanks for your fast reaction.

To help you a bit I checked the compiled assembly in the net45 folder with reflector. The code is missing there. It seems the conditional compilation is missing a condition somewhere. Hope that helps.

No big problem to fix in our code however so no hurries!

**Comment by nigel-sampson** [comment]
Yup, definitely a stupid mistake on my part when removing Windows 8 as a platform.
