### ISSUE TITLE
WPF - Formatting of TextBox bound to double property by convention

### ISSUE THREAD

**Issue by SLEEP-MAN** [Caliburn-Micro/Caliburn.Micro#229]
Hello,

I have encountered strange behavior of TextBox that is bound to double property by convention - its formatting behaves completely different than in the case of binding by Binding.Path. I've prepared sample project to demonstrate the issue.

Sample project: https://github.com/SLEEP-MAN/CaliburnMicroBindingToDoubleFormatingTst

Description of 3 controls in the sample project behavior is below:

1. Bound by convention
    * You can write ‘123’, but then you cannot put decimal point in after ‘123’ (neither ‘,’ nor ‘.’) – it looks like ‘integer formatting’ is set
    * You can write ‘123’, and then add ‘abc’ (that gives ‘123abc’ in TextBox). Next you can put decimal point anywhere in the TextBox content - it looks like ‘string formatting’ is set after user enters ‘a’ letter
    * You can enter ‘.123’ in TextBox (‘0.123’ is displayed) and then modify content before and afetr decimal point
2. Bound by Binding.Path
    * Works properly
3. Bound by Binding.Path with formatting
    * Works properly and uses provided formatting

**Comment by nigel-sampson** [comment]
This is most likely the same behavior outline in #122 I suspect if you added `UpdateSourceTrigger=PropertyChanged` to the binding example you would see the same behavior as the first.

There's some solutions outlined in #122.

**Comment by SLEEP-MAN** [comment]
Hello Nigel,

Tkanks for quick reply! The most suitable solution to me is the one with ConventionManager.ApplyUpdateSourceTrigger. Do you see any potential danger in the configuration below (taken from http://stackoverflow.com/questions/5033308/caliburn-micro-how-to-set-binding-updatesourcetrigger):

ConventionManager.ApplyUpdateSourceTrigger = (bindableProperty, element, binding, propertyInfo) =>
            {
                if (element is System.Windows.Controls.TextBox)
                {
                    return;
                }

                binding.UpdateSourceTrigger = System.Windows.Data.UpdateSourceTrigger.PropertyChanged;
            };

**Comment by nigel-sampson** [comment]
The only thing to note here is that you're changing it regardless of the type of the property being bound as long as it's a TextBox control.

But if you're ok with that then this is fine.

**Comment by SLEEP-MAN** [comment]
Thank you for help!
