### ISSUE TITLE
Support for Inter-VIewModel-Communication and Generic Validation

### ISSUE THREAD

**Issue by bootson0250** [Caliburn-Micro/Caliburn.Micro#235]
Hi Guys, You are doing a wonderful job. I have started using CM very recently and it is amazing :)
I need some kind of support for viewmodel to viewmodel communication + built in generic validation (async using INotifyDataErrorInfo). I did some research, gone through existing other frameworks and come up with customized solutions.
(PFB code snippet) 
1. Inter-ViewModel-Communication
Developed with reference to Catel's interview model communication feature
![image](https://cloud.githubusercontent.com/assets/10563712/10538790/9f699b6a-7418-11e5-93a1-efc18028bed6.png)

2. Generic Validation
Custom development.
![image](https://cloud.githubusercontent.com/assets/10563712/10538816/cf1d631e-7418-11e5-82ff-deb1dad72c82.png)

I would love to add this feature as CM's core feature. Can we plan this in the next release?

**Comment by mvermef** [comment]
As a long time user of CM, no one has ever brought it up as necessity of Vm to Vm  in the core.  As for validation it was already left as part of the developers need.  Not everyone agrees how it should be done.  For that one of the methods I have recently looked at and adopted was Jerry Nixon's, IProperty/IModel since validation doesn't exist in WinRT out of the box, the primary reason for this was that IDataNotifyErrorInfo doesn't exist in WinRT therefore an all encompassing solution for any validation would have to take that into account as well.

**Comment by bootson0250** [comment]
Agreed, but I'm not talking anything related to making it mandatory integration of Vm to Vm and Validation in to the CM core. We can always provide a configurable option (in bootstrapper, or in Vm level). No body has ever brought it up doesn't mean that no body uses it. VM to VM is a very needed behavior, everybody uses this in one way or another. Till now I used to accomplish this with existing event aggregator, but poor implementation of EventAggregator (Sub and UnSubscribe part) leads memory leaks and even worse nightmare. 
I've created Validation and VM to VM features configurable, one can choose it according to his/her need. Just like the IoC container.
We can include all the version of the validator and ship it as the different nugget package all together (Caliburn.Core, Caliburn.etc and etc)
We can keep existing CM untouched just use the decorator to wire the VM to VM or Validation and based on the configuration dlls will be loaded.

**Comment by nigel-sampson** [comment]
Regarding the view model to view model communication, this does look a lot like event aggregation by another name. 

From the initial screenshots and the latest comments it sounds like the real issue for you is the usage of the event aggregator in that you find explicit subscribe and unsubscribe cumbersome.

To be honest, this isn't likely to change. A lot of people depend on that functionality and prefer it this way in complicated view model structures where they may choose that only active view models receive events or not.

The event aggregator won't leak memory if you're not unsubscribing as it's using weak references. However you may receive events on view models that are unexpected.

I have seen convention based event aggregation done before. The process was to create a view model factory that after the view model was created from the container examined for interfaces, attributes or methods. It then attached to the view models lifecycle events and subscribed / unsubscribed appropriately.

Regarding validation, I'm not seeing in your screenshot what the functionality requested actually is, if you could go into some detail that would be good.

**Comment by bootson0250** [comment]
1. VM to VM - This is indeed convention based event aggregation using Attributes. So basically all the redundant implementation of the EventAggregator is extracted from the common development stream and encapsulated as a core feature. This do take care of the sub-unsub of the events depending upon the life cycle and number of VMs opted as interested in. And it not just about the propertyChange, it does notify all the interested VM if any command is invoked. Think about this as getting rid-off all common boilerplate and giving it as core generic feature where user can opt for it.

2. Validation - Consider a very simple scenario where user wan to bind property to some textbox and also need a validation. PropertyChangedBase takes care of the binding part but for the Validation part developer may need to implement the IDataErrorInfo/InotifyDataErrorInfo and wire all event and validate based on the property change.

This is a very common scenario, almost every VM need some validation feature. What if, we provide validation as built-in feature of the core CM (just like PropertyChangedBase where we just invoke method NotifyPropertyChange) and if user needs a validation all he need is to write method having same property name (which bound to the view) having Validate as a prefix.

You can check with earlier snap shot, where MainViewModel is derived from ValidationBase, which is derived from the PropertyChangedBase and has the generic implementation of the INotiyDataErrorInfo, which internally check for property change and raises related Validation routine if available, it also support async method calls.

Just have a look at the all VMs in our daily development scenarios, almost every single of them have a implementation of the validation, each time we need to invest time into the same validation code, we can get rid-off this redundancy by providing generic validation built-in the Core CM.

Have a look at my ValidationBase file
![image](https://cloud.githubusercontent.com/assets/10563712/10569991/7340ce70-764b-11e5-84f0-973035879379.png)
![image](https://cloud.githubusercontent.com/assets/10563712/10570000/8a3502f4-764b-11e5-83ce-fd3a497957c2.png)

**Comment by nigel-sampson** [comment]
I'm loathe to add a validation system such as this into the framework when there are already good ones out there and trying to replace them would be an exercise in futility. Also different developers want different things in validation frameworks.

The convention manager already lights up functionality if the view model implements certain interfaces which IMO is a good boundary for a view model framework.

Neither of these are bad ideas, I just don't see them being added to the core framework. Validation is something that needs to be done really well or not at all, and the view model to view model communication is an opinionated extension to already existing functionality.

The good thing is that neither of these changes require core changes to the framework and could easily be built as plugins or supporting libraries.

If you did go ahead and implement them I'd have no worries highlighting them in the CM documentation.

**Comment by bootson0250** [comment]
I agree with your point, adding Validation or VM to VM is a very subjective. My goal is to make it as a plugin which can be enabled on demand. Let me work on the structure part. 

I will come up with the proper implementation where developer will have a choice to enable or override on demand.

**Comment by nigel-sampson** [comment]
Closing as a potential plugin by @bootson0250
