### ISSUE TITLE
[WinRT] Event Binding to Flyout

### ISSUE THREAD

**Issue by chriszirkel** [Caliburn-Micro/Caliburn.Micro#236]
It seems to be not possible to use the event binding on a Flyout control. I have already created a StackOverflow thread (http://stackoverflow.com/questions/33174177/winrt-caliburnmicro-event-binding-to-listpickerflyout) for this issue.

I could use an EventTriggerBehavior and a CallMethodAction as a workaround (already tested) but the default CM event binding would be nicer.

**Comment by nigel-sampson** [comment]
There's nothing stopping this from a platform point of view.

However too much of Caliburn.Micro is based on binding to the visual tree which the flyouts sit outside of (they don't inherit `FrameworkElement`).

There's already been some places where we've coded in exceptions for them, but I doubt we could do it everywhere.

**Comment by chriszirkel** [comment]
Do you plan to implement this for CM 3.0?

**Comment by chriszirkel** [comment]
Do you plan to implement this feature for the coming version of CM?

**Comment by nigel-sampson** [comment]
Potentially, it would be a lot of work and would mean a fracturing of the code base.

I've created a more accurate card for the work.
