### ISSUE TITLE
What could block PublishOnUIThread

### ISSUE THREAD

**Issue by nologinatgit** [Caliburn-Micro/Caliburn.Micro#239]
I have the following code in the main class:
<pre>
public class MainClass: IHandle<DetailStatus>
{
 public MainClass()
 {
  Utils.EventAggregatorInstance.Subscribe(this);
 }

 public void Handle(DetailStatus detailStatus)
 {
   if (detailStatus== DetailStatus.Moving)
     ExecuteMoving();
 }
}
</pre>
In the detail class:
<pre>
public class DetailClass
{
  public void CreateMoving()
  {
   Utils.EventAggregatorInstance.PublishOnUIThread(DetailStatus.Moving);
  }
}
</pre>

The EventAggregator instance:
<pre>
 public static EventAggregator EventAggregatorInstance
 {
   get
   {
     if (_eventAggregatorInstance == null)
        _eventAggregatorInstance = new EventAggregator();

     return _eventAggregatorInstance;
   }
 }
</pre>

On the first call, the Handle method is called normally.

On the second call, the Handle method is not called. I can break on the Utils.EventAggregatorInstance.PublishOnUIThread(DetailStatus.Moving) call, but the Handle is never called after that.

This is strange. How can the aggregation work _only once_?

What could block the aggregation?

**Comment by nigel-sampson** [comment]
It's certainly a strange one, I assume in the first code sample you're actually implementing `IHandle<DetailStatus >` ?

First thoughts would be something is up with the `EventAggregatorInstance` and the second publish is to a different event aggregator.

**Comment by nologinatgit** [comment]
I implement <pre>IHandle &lt;DetailStatus&gt;</pre>.

I also thought of the EventAggregator, but it is marked as static so it couldn't be changed. 

How could I make sure of it?

**Comment by nigel-sampson** [comment]
I would just a break point on `_eventAggregatorInstance = new EventAggregator();` to ensure you're not creating multiple instances.

**Comment by nologinatgit** [comment]
`PublishOnUIThread` works okay, my code was 'blocking' the aggregation by diverting the execution path. Thanks for the help.

**Comment by nigel-sampson** [comment]
Glad to hear it was resolved.
