### ISSUE TITLE
Caliburn "Sometimes" binding DataGrid ViewModels

### ISSUE THREAD

**Issue by pjmagee** [Caliburn-Micro/Caliburn.Micro#240]
I've been having issues with Caliburn SOMETIMES setting the property, but not always. It appears to be random that it may bind back to my View Model on changing a property in the DataGrid.

A partial of my `SettingsView.xaml` 

```XML

<DataGrid ScrollViewer.CanContentScroll="True" 
                      ScrollViewer.VerticalScrollBarVisibility="Auto"
                      ScrollViewer.HorizontalScrollBarVisibility="Auto" 
                      Height="150"
                      ItemsSource="{Binding AbilitySettingViewModels}"
                      AutoGenerateColumns="False" VirtualizingPanel.IsVirtualizing="False" 
                      AlternatingRowBackground="WhiteSmoke">
                <DataGrid.Columns>
  <DataGridTemplateColumn Header="Ability ID" Width="*">
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <TextBox cal:Bind.ModelWithoutContext="{Binding}" Text="{Binding Id}"  />
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>
 <DataGridTemplateColumn Header="Custom image" Width="*">
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <TextBox cal:View.Context="{Binding}" cal:Bind.ModelWithoutContext="{Binding}" Text="{Binding Image}" ToolTip="Provide a custom image to use for this Ability." />
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>
 <DataGridTemplateColumn Header="Ability Border" Width="*">
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <xctk:ColorPicker cal:View.Context="{Binding}" cal:Bind.ModelWithoutContext="{Binding}" ColorMode="ColorPalette" SelectedColor="{Binding Border, Mode=TwoWay}" DisplayColorAndName="True" />
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>
 <DataGridTemplateColumn Header="Delete" Width="*">
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <Button cal:Action.TargetWithoutContext="{Binding}" Padding="10,6" Content="Delete" cal:Message.Attach="Delete" />
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>
        </DataGrid.Columns>
 </DataGrid>
```

My `SettingsViewModel` contains the following property

```c#

// AbilitySettingViewModel is a row Item in the DataGrid
 public BindableCollection<AbilitySettingViewModel> AbilitySettingViewModels { get; set; }
```

I have tried all the `cal:Bind` and `cal:View`  options to see if any of them made a difference.

Originally I just had `{Binding ViewModelProperty}` but it wasn't working. Then saw another DataGrid Issue and managed to get the Button triggering the method on my View Model by adding `Action.TargetWithoutContext="{Binding}"`. But still no luck on the others.

Are there any known issues or work arounds to get caliburn working with DataGrid?

**Comment by nigel-sampson** [comment]
Can you go into some more detail about which binding is only sometimes happening.

Are you always seeing the rows correctly but the values in the TextBox's are incorrect or that updates in the UI aren't making it to the view model?

**Comment by pjmagee** [comment]
The updates in the UI are not being applied to the View Models. However, when I spam different values in different rows in different data columns SOMETIMES, they do get set and saved back to the View Model....it's really strange.

LOADING seems to work perfectly fine. So if I had the correct JSON data loaded and i create my VM's from that data, the DataGrid shows the correct data for Input Boxes and my colour picker control. 

It's only when editing.

**Comment by nigel-sampson** [comment]
This could be a couple of reasons:

- Some sort of type mismatch between the view model property something like #229 
- Because you're using the explicit bindings then you'll need to make sure properties like Mode and UpdateSourceTrigger are what you want. Important one there is that TextBox defaults to Lost Focus.

None of those extra properties you've tried would be the right answer here so probably best to get rid of them.

If you're still having problems and can recreate the problem in a small repo I'll be happy to look at it.

**Comment by pjmagee** [comment]
Hi mate, providing `Path= ` fixed it.

**Comment by nigel-sampson** [comment]
Glad to hear it was sorted.
