### ISSUE TITLE
Using Caliburn Micro in class library

### ISSUE THREAD

**Issue by nirajdoshi1985** [Caliburn-Micro/Caliburn.Micro#241]
I have a class library which contains several user controls. This library uses caliburn micro to bind the `UserControls` to their corresponding `ViewModels` using `x:Name` approach in the same class library.

Now I have an host application which hosts these `UserControls` in a Window. But this host application doesn't use Caliburn Micro at all. Then how can I initialize caliburn bootstrapper in the library itself.

HostApplication:

    <Window>       
      <ContentControl>
           <library:MainUserControl DataContext="{Binding MainUserControlViewModel}"/>
      </ContentControl>
    </Window>

Class Library

    <UserControl x:Class="MainUserControl">
           <ContentControl x:Name="OtherUserControlInSameLibrary"/>
    </UserControl>

I tried to inherit `Bootstrapper` base class like `AppBootstrapper: Bootstrapperbase` and passing false to constructor parameter `useApplication`. And then I called `Initialize()` method. But still conventions are not applied.

MainUserControlViewModel Constructor

    public MainUserControlViewModel()
    {             
         AppBootstrapper appBootstrapper = new AppBootstrapper();
         appBootstrapper.Initialize();
         if (Debugger.IsAttached)
                LogManager.GetLog = type => new DebugLog(type);            
    }

BootstrapperBase override

     public class AppBootstrapper : BootstrapperBase
        {
            public AppBootstrapper():base(false)
            {
            }
        }

I also tried to run caliburn debugger but nothing is showed in my output window.

**Comment by nigel-sampson** [comment]
It's certainly a different scenario, can I ask why are you aren't using CM in the main application?

The problem looks to be that there's nothing triggering the conventions to be applied. Normally CM handles this using the `ViewModelBinder` and it's associated attached properties.

You could try something like, but I can't guarantee CM is correctly set up with what you've done.

``` xml
<Window>       
  <ContentControl>
       <library:MainUserControl cm:Bind.Model="{Binding MainUserControlViewModel}"/>
  </ContentControl>
</Window>
```

**Comment by nirajdoshi1985** [comment]
Hi Neigel,

Thank you very much for reply. Actually I am designing an usercontrol which will be used by all the developers working on different projects throughout the company. Their projects may or may not use caliburn.micro, but ofcourse using WPF/XAML.

Your suggested code may work, but again I need to have a caliburn dependency to resolve `Bind.Model`.

After your inputs, I can deduce that it wont be a good approach to use cm independently in libraries, but can be adopted as a part of common architectural pattern across the organization.

**Comment by nigel-sampson** [comment]
I think you're correct with your conclusion, trying to build out a library that uses CM where the app may or may not will be fraught with problems.

**Comment by nigel-sampson** [comment]
Closing this out as it's resolved.

**Comment by LtKlaus** [comment]
I'm wondering if you were able to find a solution for this, or if it was even possible?

I have a WPF Class Library with a UserControl that's used by another application that's written in C++. In the Class Library I create an instance of my UserControl and use it in a HwndSource. The C++ application requests the Handle of the HwndSource and uses that to display my UserControl in a Window. 

Is it possible to use Caliburn Micro in this kind of scenario?

**Comment by nirajdoshi1985** [comment]
I don't think that's possible, unless you host these user controls within another WPF Application and your C++ app use it in a HwndSource. But directly hosting the library will not trigger the CM conventions.

**Comment by nigel-sampson** [comment]
While throwing C++ into the mix certainly complicates things, assuming you're able to host a normal WPF control correctly the approach above of manually instantiating the bootstrapper and using `Bind.Model` to kick of Caliburn should make it possible.

**Comment by tanaililing** [comment]
> Closing this out as it's resolved.

hello how to use CM in class libray ？I don't understand it

**Comment by tanaililing** [comment]
> I have a class library which contains several user controls. This library uses caliburn micro to bind the `UserControls` to their corresponding `ViewModels` using `x:Name` approach in the same class library.
> 
> Now I have an host application which hosts these `UserControls` in a Window. But this host application doesn't use Caliburn Micro at all. Then how can I initialize caliburn bootstrapper in the library itself.
> 
> HostApplication:
> 
> ```
> <Window>       
>   <ContentControl>
>        <library:MainUserControl DataContext="{Binding MainUserControlViewModel}"/>
>   </ContentControl>
> </Window>
> ```
> Class Library
> 
> ```
> <UserControl x:Class="MainUserControl">
>        <ContentControl x:Name="OtherUserControlInSameLibrary"/>
> </UserControl>
> ```
> I tried to inherit `Bootstrapper` base class like `AppBootstrapper: Bootstrapperbase` and passing false to constructor parameter `useApplication`. And then I called `Initialize()` method. But still conventions are not applied.
> 
> MainUserControlViewModel Constructor
> 
> ```
> public MainUserControlViewModel()
> {             
>      AppBootstrapper appBootstrapper = new AppBootstrapper();
>      appBootstrapper.Initialize();
>      if (Debugger.IsAttached)
>             LogManager.GetLog = type => new DebugLog(type);            
> }
> ```
> BootstrapperBase override
> 
> ```
>  public class AppBootstrapper : BootstrapperBase
>     {
>         public AppBootstrapper():base(false)
>         {
>         }
>     }
> ```
> I also tried to run caliburn debugger but nothing is showed in my output window.

hello ， Is Resolved your question ？Using Caliburn Micro in class library

**Comment by EsmailOuadghiri** [comment]
I have the same problem and I don't have any idea how I can fix it

**Comment by ottosson** [comment]
I'm as well in pursuit of building a class library using CM. In my case I build Revit add-ins which is loaded from a dll.
Is it at all possible? I can use some parts of CM, but others like ActivateItem does not work out of the box.
