### ISSUE TITLE
ContentControl only visible once in Windows XP

### ISSUE THREAD

**Issue by nologinatgit** [Caliburn-Micro/Caliburn.Micro#246]
I created an application using .Net 4.0 and CM.

It works perfectly on Windows 7 and onwards.
On Windows XP, it does not.

I have the following code:
```c#
  <ContentControl x:Name="SelectorDetail"
                                Grid.Row="1"
                                Grid.Column="0"
                                Grid.ColumnSpan="2"
                                MinHeight="10"
                                HorizontalAlignment="Stretch"
                                Content="{Binding Path=SelectorDetail,
                                                  UpdateSourceTrigger=PropertyChanged,
                                                  Mode=OneWay}" />

```
In the main ViewModel, I create its ViewModel:

```c#
SelectorDetail= new SelectorDetailViewModel(details1, details2);
```

When I open the view, I can see the selector. If I close and reopen it, it is _gone_.

I had a property that controlled the visibility of the selector:

```c#
   public Visibility VisibleSelectorDetail
    {
      get
      {        
        return SelectedType != 9 ?
                Visibility.Visible : Visibility.Hidden;
      }
    }
```
But I took it out. No change, it still appears only _once_.

What should I change?

**Comment by nigel-sampson** [comment]
That's very surprising, I haven't seen any bugs related to specific versions of Windows before, especially if they're using the same version of .NET.

The things I would start to look at platform specific so I'm not sure if they'd help.

Normally for this sort of issue I'd be looking into where the `SelectorDetailViewModel` is being created and ensuring that it's not null on the second opening on the view. This could happen with some odd arrangements of dependency injection 

If you're able to recreate this issue in a small app I'd be happy to look at it.

**Comment by nigel-sampson** [comment]
No more information received, closing out.
