### ISSUE TITLE
Throw exception if platform provider isn't configured

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#248]
Currently CM implements `DefaultPlatformProvider` which is used whenever the appropriate platform provider isn't configured.

There's almost no scenario where this platform provider is the correct one however. It would be better if we removed this and threw an exception when accessing `PlatformProvider.Current` before it's configured. An example of this problem is #244

This would be a breaking change.

**Comment by nigel-sampson** [comment]
Resolved in `3.0.0-beta2`

**Comment by sevenate** [comment]
So what is the recommended way to configure provider for design-time use in UWP project?
I have views defined in UWP project and view-models in portable project and in every xaml with:

```
d:DataContext="{d:DesignInstance Type=vm:MyViewModel, IsDesignTimeCreatable=True}"
```

there is warning now (guessing because of `Execute.InDesignMode` usage in VM):

```
PlatformProvider.Current is not set, ensure that Caliburn.Micro is correctrly initialized
```
Should I set `PlatformProvider.Current` into something like `new XamlPlatformProvider();` somewhere like ctor of app.xaml.cs or elsewhere?

In run-time all works fine, but design-time is now broken for me.

**Comment by nigel-sampson** [comment]
Ah bollocks, didn't think about design time. Thanks.

Will have a think,

**Comment by sevenate** [comment]
Any chance for quick 'n dirty workaround meanwhile?

I've tried to set the `PlatformProvider.Current` to original (recovered from history) version of `PlatformProviderInitializer`, but without luck. Also just not using `Execute.InDesignMode` in VM's code seems not enough to fix it.

**Comment by nigel-sampson** [comment]
Sorry, where are you setting `PlatformProvider.Current` to `DefaultPlatformProvider`?

**Comment by sevenate** [comment]
In portable project I've added:

```
public static class PlatformProviderInitializer
{
    static PlatformProviderInitializer()
    {
        PlatformProvider.Current = new DefaultPlatformProvider();
    }
}
```

**Comment by nigel-sampson** [comment]
What about the ctor of `app.xaml.xs`?

Sorry, currently away from a machine I can test this on.

**Comment by sevenate** [comment]
Its OK - I have mine machine here, no worries :)

Tried on work project in app.xaml.cs initially before static initialized and it didn't work as well.

Will try with blank project and let you know.

**Comment by sevenate** [comment]
Ok, I've tried with blank project it doesn't looks like

```
PlatformProvider.Current = new DefaultPlatformProvider();
```
at the first line of App ctor makes any difference.

The only way I could get design-time back is to wrap all `NotifyOfPropertyChange()` and `Execute.InDesignMode` in such view-models in try/catch blocks.

**Comment by nigel-sampson** [comment]
Thanks, for the moment then I'd suggest using `3.0.0-beta1` for the design time support.

**Comment by sevenate** [comment]
OK, thanks. Beta-1 will work for me as a workaround for sure.

**Comment by nigel-sampson** [comment]
On review I'm going to revert this decision. It was poorly thought out regarding the design time experience.
