### ISSUE TITLE
Standalone EventAggregator + Caliburn.micro

### ISSUE THREAD

**Issue by JobaDiniz** [Caliburn-Micro/Caliburn.Micro#251]
I have installed Caliburn.Micro nuget (https://www.nuget.org/packages/Caliburn.Micro/) in a WPF project.

I also have another standalone library that only uses EventAggregator, thus I have installed Caliburn.Micro EventAggregator (https://www.nuget.org/packages/Caliburn.Micro.EventAggregator/)

Now, I have to reference this standalone library in my WPF project, however, this will not work, will it? Because WPF Caliburn.Micro uses its own version of EventAggregator and not https://www.nuget.org/packages/Caliburn.Micro.EventAggregator/ version.

Any insights?

**Comment by JobaDiniz** [comment]
The problem is that EventAggregator class should be in a separated assembly and Caliburn.Micro should reference that assembly instead of creating its own EventAggregator class.

https://www.nuget.org/packages/Caliburn.Micro.EventAggregator/ package should not add classes to the project, instead it should add a reference of the EventAggregator assembly.

**Comment by mvermef** [comment]
that version of the EventAggregator is not an assembly at all, actually it is 2 .CS files with the code for the EventAggregator within.  The install-package should have created 1 folder named Caliburn.Micro which should contain those 2 files.  You shouldn't have to reference the EventAggregator in the main WPF project since it is built into the Caliburn.Micro.dll

**Comment by JobaDiniz** [comment]
You didn't understand...

We have a standalone library which is used across WPF and WinForm projects. This library makes use of standalone EventAggregator.
There is a class within that library which requires an instance of EventAggregator:

```
//ctor
public MyClass(IEventAggregator eventAgg) {...}
``` 

When I try to instaciate such class passing EventAggregator from Caliburn.Micro assembly, it doesn't work.. of course, they are different classes, one defined in Caliburn.Micro and one defined in my library assembly...

**Comment by nigel-sampson** [comment]
A couple of things, to be honest I thought we'd retired all those source packages. Given the nature of the 2.0 changes it didn't make practical sense to try and keep them up to date.

As @mvermef said, that package is a source file package in that just injects the source files for the `EventAggregator` in a folder Caliburn.Micro and in that namespace.This it what's causing your conflict.

The `EventAggregator` lives in the `Caliburn.Micro.Core` nuget package which you can reference in your library and use it from both.

**Comment by JobaDiniz** [comment]
I understood now...
Howver, will `Caliburn.Micro.Core` work on WinForm environment? I ask that, because our standalone library doesn't care about WPF or WinForm, we use it in both environments.

**Comment by nigel-sampson** [comment]
`Caliburn.Micro.Core` is a portable class library so should be able to referenced from a Windows Forms assembly with no problems (assuming .NET 4.5).

You may need to add some code to the initialization of the WIndows Forms environment to set up the `EventAggregator`, this is the WPF code in the [Bootstrapper](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/Bootstrapper.cs#L70) and I don't see any reason this shouldn't work there as well.

**Comment by JobaDiniz** [comment]
Ok, thanks.

**Comment by nigel-sampson** [comment]
No worries, glad I could help.
