### ISSUE TITLE
Support Microsoft.Xaml.Behaviors.Uwp.Managed

### ISSUE THREAD

**Issue by EDiaos** [Caliburn-Micro/Caliburn.Micro#254]
The new Behaviors for VisualStudio 2015 Update1 is Microsoft.Xaml.Behaviors.Uwp.Managed. 
The new Behaviors fix many bugs.
But our Caliburn.Micro can't using it ,because the new Behaviors just support UWP.

I found that the old behaviors sdk have many problem run on Window10-10586 in my project when  Release Native Build。

**Comment by nigel-sampson** [comment]
We just pushed `3.0.0-beta2` today which supports using `Microsoft.Xaml.Behaviors.Uwp.Managed` when targeting UWP. If you're not targeting UWP then we bundle the appropriate assemblies still in the package.

If you're having problems with this can you expand on the issue?

**Comment by EDiaos** [comment]
TKS, i update Caliburn.Micro 3.0.0-beta2  using PM> Install-Package Caliburn.Micro -Pre 
I found the Caliburn.Micro 3.0.0-beta2 missing Caliburn.Micro.Screen?
And the path "\.nuget\packages\Caliburn.Micro\3.0.0-beta2\lib\uap10.0" haven't Caliburn.Micro.dll

**Comment by nigel-sampson** [comment]
The package `Caliburn.Micro` depends on `Caliburn.Micro.Core` which has the Caliburn.Micro.dll.

Can you verify this is installed and up to date.

**Comment by nigel-sampson** [comment]
There is a known issue #257 in the Caliburn.Micro package definition, for the moment if you manually install the Caliburn.Micro.Core package this will be resolved.
