### ISSUE TITLE
Upgraded from 3.0.0-Beta1 to 3.0.0-Beta2 now some types are gone?

### ISSUE THREAD

**Issue by Petoj87** [Caliburn-Micro/Caliburn.Micro#257]
The types Screen, IEventAggregator, LogManager and a few more are missing and yield the following compilation error.

`The type or namespace name 'IEventAggregator' could not be found (are you missing a using directive or an assembly reference?)`

Im using visual studio 2015 update 1 and its a windows 10 universal project and i have tried to target both Windows 10 build 10240 and 10586.

What could be the problem?

I can't check if the types actually exist as visual studio dosen't seem to add the dll files to packages folder anymore..

**Comment by nigel-sampson** [comment]
Can you verify you're still referencing the `Caliburn.Micro.dll` from the `Caliburn.Micro.Core 3.0.0-beta2` package?

**Comment by Petoj87** [comment]
Thanks nigel-sampson. installing `Caliburn.Micro.Core 3.0.0-beta2` manually resolved the problem, don't ask my why it wasn't loaded automatically.

**Comment by Petoj87** [comment]
I tried to create a new project and add `Caliburn.Micro 3.0.0-beta2` same problem happened there.

**Comment by nigel-sampson** [comment]
Interesting, thanks for that. I'm seeing the same behavior for UWP projects on my version of Nuget  (3.2.60914.10516) and Visual Studio 2015 (no Update 1).

However it's working correctly if I add to a Window 8.1 project.

Ah, this looks like my bad in the [Caliburn.Micro.nuspec](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/3.0.0/nuget/Caliburn.Micro.nuspec), it doesn't apply both groups of dependencies matching both the framework and one with an unspecified framework.

I'll fix this up for the 3.0.0 release but I don't think it's worth pushing a beta3 package to resolve this for the moment.

**Comment by wstaelens** [comment]
Same problem i think.

The type 'SimpleContainer' is defined in an assembly that is not referenced. You must add a reference to assembly 'Caliburn.Micro, Version=2.0.2.0, Culture=neutral, PublicKeyToken=8e5891231f2ed21f'.

**Comment by nigel-sampson** [comment]
Resolve in 3.0.0
