### ISSUE TITLE
Starting the app from the startmenu while its running clears the view in my frame

### ISSUE THREAD

**Issue by Petoj87** [Caliburn-Micro/Caliburn.Micro#258]
I don't know if this is a bug or if i just am doing something wrong (most likely im doing something wrong).
if i start the project and then just use the start menu to start it again(while its running) the TestView just goes away?

The code can be found at: https://github.com/Petoj87/Caliburn.Micro.ResumeBug

**Comment by Petoj87** [comment]
Same thing happens on the phone emulator if you press the home screen and start the app again from the app menu.

**Comment by nigel-sampson** [comment]
Thanks, this is the curse of a simple sample.

In `OnLaunched` you should check to see either the `PreviousExecutionState` or `Window.Current.Content` to see if you should call `DisplayRootViewFor`.

Both will work, it's just whichever makes sense for you.

**Comment by Petoj87** [comment]
Just to make sure would this solve the issue without creating a new issue?
old:
```
    DisplayRootViewFor<ShellViewModel>();
    if (args.PreviousExecutionState == ApplicationExecutionState.Terminated)
        _eventAggregator.PublishOnUIThread(new ResumeStateMessage());
```
new:
```
    if (args.PreviousExecutionState != ApplicationExecutionState.Running)
        DisplayRootViewFor<ShellViewModel>();

    if (args.PreviousExecutionState == ApplicationExecutionState.Terminated)
        _eventAggregator.PublishOnUIThread(new ResumeStateMessage());
```

**Comment by nigel-sampson** [comment]
That should be all good.

**Comment by Petoj87** [comment]
Thanks for you help and great work with Caliburn.Micro.

**Comment by nigel-sampson** [comment]
No worries.
