### ISSUE TITLE
UWP sample not navigating

### ISSUE THREAD

**Issue by rado-r** [Caliburn-Micro/Caliburn.Micro#259]
When PreviousExecutionState == ApplicationExecutionState.Running. App will not show DeviceView but navigation was succesfull becouse backButton passes through backstack but view does not changed.

**Comment by nigel-sampson** [comment]
This sounds very similar to #258 can you see if that helps.

I'll be reviewing most of the samples over the Christmas holidays so will add it in then.

**Comment by rado-r** [comment]
Yes, it helped thank.
