### ISSUE TITLE
[UWP] Secondary CommandBar attaching action on every open

### ISSUE THREAD

**Issue by renemaat** [Caliburn-Micro/Caliburn.Micro#260]
I just updated to beta2 but this issue is probably not related. I noticed that when I use the x:Name convention on secondary commandbar buttons like this
```xaml
<CommandBar.SecondaryCommands>
    <AppBarButton x:Name="RefreshCommand" Label="{Binding RefreshLabel, FallbackValue='$Refresh'}"/>
</CommandBar.SecondaryCommands>
```
Each time when I open the overflow menu a event handler seems to be attached. This results in that when I open de overflow menu 3 times, that the RefreshCommand will be fired 3 times.
The normal commandbar buttons work correct.

Thank you for your time.
Kind regards,
René

**Comment by nigel-sampson** [comment]
Thanks, was able to recreate this.

What I suspect is happening is that internally the framework turns the `x:Name="RefreshCommand"` into `cm:Message.Attach="RefreshCommand"` and then every time the menu is opened the attached dependency property is being reevaluated and another attachment is made.

A bit surprising, but will look into it further.

**Comment by nigel-sampson** [comment]
On further testing this looks into be an issue in the [Xaml Behaviors SDK](https://github.com/Microsoft/XamlBehaviors).

The following code has the same problem without Caliburn.Micro. I'll raise an issue there.

```
<AppBarButton Label="Behavior" Icon="Refresh">
    <i:Interaction.Behaviors>
        <core:EventTriggerBehavior EventName="Click">
            <core:CallMethodAction TargetObject="{Binding}" MethodName="ClickTest"/>
        </core:EventTriggerBehavior>
    </i:Interaction.Behaviors>
</AppBarButton>
```

**Comment by nigel-sampson** [comment]
Raised in Microsoft/XamlBehaviors#55.
