### ISSUE TITLE
[UWP] Update 1 & Caliburn Projects

### ISSUE THREAD

**Issue by mvermef** [Caliburn-Micro/Caliburn.Micro#261]
Don't forget if you updated to Update 1, you will have to go in and make changes to the Caliburn UWP project if you didn't keep 10240 SDK installed when you updated to Update 1 which features 10586 SDK (aka TH2)

**Comment by nigel-sampson** [comment]
We should just need to update the min tested version (which is a soft limit) once I've fully tested it out.

The minimum version should still stay as 10240 to let people use that if they want. This should still let them use 10586 without having 10240 installed.

**Comment by mvermef** [comment]
Yes allowing for 10240 is a soft limit, when i installed update 1, I didn't think about keeping 10240, which was uncheckable during the install process.  Wasn't thinking about backwards comp.  I will probably go back and reinstall for side-by-side and project backwards comp.
