### ISSUE TITLE
Please implement INotifyDataErrorInfo on Screen/PropertyChangedBase (3.0?)

### ISSUE THREAD

**Issue by taori** [Caliburn-Micro/Caliburn.Micro#262]
This framework supports many platforms, so it would be great if it would also support the INotifyDataErrorInfo interface to offer custom validation through an async interface which wpf can bind to.

I am willing to contribute if you would consider this to be an option and are open for contributions.

I'll show what i've done so far. It works but apart from the _errorsChanged handler having a strong referenced handler right now

I think a built in solution would be great to have

	public class ValidationModelBase : PropertyChangedBase, INotifyDataErrorInfo
	{
		private Dictionary<string, List<ValidationResult>> _errors = new Dictionary<string, List<ValidationResult>>();

		bool INotifyDataErrorInfo.HasErrors => _errors.Keys.Any();

		[field:NonSerialized]
		private EventHandler<DataErrorsChangedEventArgs> _errorsChanged;

		event EventHandler<DataErrorsChangedEventArgs> INotifyDataErrorInfo.ErrorsChanged
		{
			add { _errorsChanged += value; }
			remove { _errorsChanged -= value; }
		}

		protected void RaiseErrorsChanged(string propertyName)
		{
			_errorsChanged?.Invoke(this, new DataErrorsChangedEventArgs(propertyName));
		}

		IEnumerable INotifyDataErrorInfo.GetErrors(string propertyName)
		{
			if (!_errors.ContainsKey(propertyName))
				yield break;

			foreach (var result in _errors[propertyName])
			{
				yield return result;
			}
		}

		private Dictionary<string, CancellationTokenSource> _validateCts = new Dictionary<string, CancellationTokenSource>();

		public bool SetValue<T>(ref T backingField, T value, string propertyName)
		{
			if (object.Equals(backingField, value))
				return false;

			backingField = value;

			var validationDelay = GetValidationDelay(propertyName);
			if (validationDelay > 0)
			{
				CancellationTokenSource source;
				if (_validateCts.TryGetValue(propertyName, out source))
				{
					source.Cancel();
					source = new CancellationTokenSource();
					_validateCts[propertyName] = source;
				}
				else
				{
					source = new CancellationTokenSource();
					_validateCts.Add(propertyName, source);
				}

				Task.Delay(validationDelay, source.Token).ContinueWith(d =>
				{
					ValidateProperty(value, propertyName);
					NotifyOfPropertyChange(propertyName);
				}, source.Token);
			}
			else
			{
				Task.Run(() =>
				{
					ValidateProperty(value, propertyName);
					NotifyOfPropertyChange(propertyName);
				});
			}

			return true;
		}

		private void ValidateProperty<T>(T value, string propertyName)
		{
			var validationResults = ValidationHelper.ValidateProperty(this, value, propertyName);
			OnValidateProperty<T>(value, propertyName, validationResults);
			if (validationResults.Count > 0)
			{
				AddErrors(propertyName, validationResults);
				RaiseErrorsChanged(propertyName);
			}
			else
			{
				ClearErrors(propertyName);
			}
		}

		protected virtual void OnValidateProperty<T>(T value, string propertyName, List<ValidationResult> validationResults)
		{
		}

		protected void AddErrors(string propertyName, List<ValidationResult> validationResults)
		{
			if (_errors.ContainsKey(propertyName))
			{
				_errors[propertyName] = validationResults;
			}
			else
			{
				_errors.Add(propertyName, validationResults);
			}
		}

		protected void ClearErrors(string propertyName)
		{
			_errors.Remove(propertyName);
		}

		protected virtual int GetValidationDelay(string propertyName)
		{
			var pi = this.GetType().GetProperty(propertyName);
			if (pi != null)
			{
				var delayAttr = pi.GetCustomAttribute<ValidationDelayAttribute>();
				if (delayAttr != null)
					return delayAttr.Delay;
			}

			return 0;
		}
	}

	[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
	public class ValidationDelayAttribute : Attribute
	{
		public ValidationDelayAttribute(int delay)
		{
			Delay = delay;
		}

		/// <summary>
		/// Delay in milliseconds
		/// </summary>
		public int Delay { get; }
	}

**Comment by mvermef** [comment]
#235,  His response to validation is at the bottom.  Alas UWP will not support this type of validation.  Silverlight (dying as it is) and WPF are the only 2 that do..

**Comment by taori** [comment]
@mvermef odd. didn't see that while searching for the interface in issues. Closing this since discussion already happened in the other issue. Thanks mvermef

**Comment by nigel-sampson** [comment]
Thanks for the contribution, as I briefly mentioned in #235 it's something I think best left the individual developer because there are a lot of good validation libraries out there and I'd prefer not to reinvent the wheel. As I also said, if you want to build this as a sort of support library / plugin I'd be happy to mention it on the website when I get around to updating the documentation.

I'm also curious, what's the purpose of `ValidationDelayAttribute`?

**Comment by taori** [comment]
@nigel-sampson Yup, i'm perfectly fine with your statement on that. It would just be a "nice to have" feature because validation is a very very common use case.

And anyone working with ValidationRules in views certainly learned that

- Validation ought to be easier than that 
- ValidationRules sitting the the view seems kind of out of place, even if you're providing it through a viewmodel 
- The restriction of ValidationRules not supporting Bindings (last time i worked with them) is a major nuisance

ValidationDelayAttribute is something i came up with to delay user input validation for a project i've been working with. Basically feeding input was supposed to calculate a significant amount of formulas whenever a certain set of values were changed. This would usually cause a whole set of validations to flicker like crazy on every key stroke. 

Back then i wasn't good enough with WPF to get a working DelayedBinding which would also have done the job and in hindsight i would probably not put that in a support library / plugin, since it's a very special requirement.

How exactly would you consider a plugin for this? I wasn't aware of Caliburn being a plugin oriented framework? But i would be glad to contribute since i'd appreciate it if some validation functionality is available in a nuget package. Even if it's just through some support library

**Comment by nigel-sampson** [comment]
Thanks for the insight, I've typically used something like Reactive Extensions to do that sort of throttling of user input.

Regarding plugins there's a specific plugin infrastructure, but a lot of functionality is built in a way to be extended. Most of the foundation methods aren't static methods but static `Func<>` that can be changed.

For example the validation convention right now is that we check to see if the view model implements `IDataErrorInfo` or `INotifyDataErrorInfo` and set propeties on the `Bindings`. This is done in `ConventionManager.ApplyValidation`, if you wanted to replace this with your own convention you'd have code like this in your application setup.

``` csharp
ConventionManager.ApplyValidation = (binding, viewModelType, property) => 
{
   ...
};
```

If you didn't want to replace the convention but extend it you'd want to hold a reference to existing one.

``` csharp
var baseApplyValidation = ConventionManager.ApplyValidation;

ConventionManager.ApplyValidation = (binding, viewModelType, property) => 
{
    baseApplyValidation(binding, viewModelType, property);
   ...
};
```

If all the plugins follow that sort of behavior then you can effectively chain them all together.

**Comment by taori** [comment]
ok i've browsed through the code of ConventionManager.cs and i guess i can see now how to provide a plugin based on that. I'm busy with other things right now but i'd probably work on it on the weekend and nudge you to have a look if i did it as you would have imagined this to be done (If that's ok with you.) ?

**Comment by nigel-sampson** [comment]
No worries.
