### ISSUE TITLE
Not throwing PlatformProvider.Current not initialized exception in the XAML designer

### ISSUE THREAD

**Issue by igorkulman** [Caliburn-Micro/Caliburn.Micro#263]
I upgraded an UWP project from 3.0.0-beta1 to 3.0.0-beta2. The design time data stopped working, the ViewModel is throwing an exception about PlatformProvider.Current not initialized in the designer.

I think this exception should not be thrown when the code is running in XAML designer, because Caliburn does not need to be fully initialized for the design time data to work.

**Comment by altso** [comment]
Just FYI. It's already reported in #248.

**Comment by igorkulman** [comment]
Sorry for the duplicity
