### ISSUE TITLE
UWP splash screen and SplitView

### ISSUE THREAD

**Issue by rado-r** [Caliburn-Micro/Caliburn.Micro#264]
What is the best way of creating a splash screen in which we need to retrieve some data from the server and then navigate to SplitView? Think about creating a classic ViewModel or use extended Splash as example in link without using ViewModel.

https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SplashScreen

**Comment by nigel-sampson** [comment]
I don't tend to use `SplashScreen` much, it's mostly provides image location information to seamlessly transition from the actual splash to yours, that's not to say that's useful.

For an extended splash that's going to be doing work like you say I'd want a property view model that can be tested properly.

That's not to stop you mixing both, using `SplashScreen` for the image display information while having the behavior in a view model.

**Comment by rado-r** [comment]
Yes I would have done it this way, but I do not know how to properly configure the navigation service. Currently in `OnLaunch` call `DisplayRootView <SplashScreenView> ();` in SplashScreenViewModel do server call and after navigating to ShellViewModel SetupNavigationService () method creates a different navigation service which continue to use. I do not know whether this is the right approach because the classic NavigationService not used at all. Is there any way to register a new frame instead of the original in the navigation service? Or is there a better way?

**Comment by nigel-sampson** [comment]
The easiest way would probably be use `DisplayRootViewFor<>` in the `App`. This doesn't set up a navigation service and would simply set the `Window.Current.Content` to the `SplashScreenView`.

At this point you wouldn't have a navigation service, so after the data is loaded you'd need to do the equivalent of `DisplayRootViewFor<>` yourself to re-set the window to `ShellView`. The code would look pretty much the following:

``` csharp
var viewModel = IoC.GetInstance(viewModelType, null);
var view = ViewLocator.LocateForModel(viewModel, null, null);

ViewModelBinder.Bind(viewModel, view, null);

var activator = viewModel as IActivate;
if (activator != null)
    activator.Activate();

Window.Current.Content = view;
Window.Current.Activate();
```

where `viewModelType` would equal `typeof(ShellViewModel)`.

**Comment by rado-r** [comment]
Thanks this helped.
