### ISSUE TITLE
ViewLocator cannot deal with names like "SomeItemOverviewViewModel"

### ISSUE THREAD

**Issue by taori** [Caliburn-Micro/Caliburn.Micro#267]
So basically whenever the name of a class which goes goes like "...viewViewModel" the ViewLocator goes haywire and can't find the corresponding view of a ViewModel.

works:
```
SomeItemsViewModel
SomeItemsView
```

does not work:
```
SomeItemOverviewViewModel
SomeItemOverviewView
```

**Comment by nigel-sampson** [comment]
Thanks for the report, will look into it.

**Comment by nigel-sampson** [comment]
Can you provide some more concrete examples. As a quick test the following code:

``` csharp
var names = ViewLocator.TransformName("TestApp.ViewModels.IssueOverviewViewModel", null);
```

The resultant names were `TestApp.Views.IssueOverviewView` and `TestApp.ViewModels.IssueOverviewView` which seem appropriate to me.

**Comment by taori** [comment]
Not sure if that makes a difference but my view/viewmodel was in a subfolder. Actually I think the problem started happening after I moved them into subfolders of view/viewmodels. My bad.  Should have added that detail

**Comment by nigel-sampson** [comment]
Potential issue here is that if you move them into sub folders their namespaces won't change.

So for instance you create `TestApp.ViewModels.IssueOverviewViewModel` and then move it into an *Issues* folder it will still have the same full name of `TestApp.ViewModels.IssueOverviewViewModel`.

You then go off and create a matching folder *Views/Issues* and create a view in there. It will have the correct namespace of `TestApp.Views.Issues.IssueOverviewView` but won't match the view model.

**Comment by taori** [comment]
@nigel-sampson Unfortunately you pointed at the correct error source. The x:Class class name in the view was incorrect. Sorry for wasting your time. Guess i'll have to raise a VS Bug Ticket then. At some point i also renamed the view name, which changed the codebehind class name + file names but not the x:Class content. 

Thank you

**Comment by nigel-sampson** [comment]
No worries, I use Resharper pretty heavily and it warns you if the namespace is out of sync with the project structure.
