### ISSUE TITLE
Screen IsInitialized, IsActive, etc need to be virtualized

### ISSUE THREAD

**Issue by mwpowellhtx** [Caliburn-Micro/Caliburn.Micro#269]
That in order to properly support extension libraries that expose into things like [PropertyGrid](http://msdn.microsoft.com/en-us/library/system.windows.forms.propertygrid.aspx), InspectorView, and so on. So that I can override and attach [BrowsableAttribute](http://msdn.microsoft.com/en-us/library/system.componentmodel.browsableattribute.aspx).

**Comment by mwpowellhtx** [comment]
Specifically:

```
Screen.IsActive
Screen.IsInitialized
PropertyChangedBase.IsNotifying
```

**Comment by nigel-sampson** [comment]
No problems with that, happy to take a pull request.

**Comment by mwpowellhtx** [comment]
Happy to contribute one. Thanks.

**Comment by mwpowellhtx** [comment]
Could probably add a backing field to IsNotifying and assign that in the ctor instead. However, basically, it is done and ready to merge. Let me know when it is and could expect a patch to be published. Thank you.

**Comment by nigel-sampson** [comment]
Resolved in #271

**Comment by mwpowellhtx** [comment]
Sir, what is the release schedule?

**Comment by nigel-sampson** [comment]
I'll probably do the final 3.0.0 release early in January.
