### ISSUE TITLE
How to manually bind TabControl (long form binding) in v2

### ISSUE THREAD

**Issue by waynebloss** [Caliburn-Micro/Caliburn.Micro#273]
I am trying to understand how to manually bind a `TabControl` to a VM that inherits from `Conductor<T>.Collection.OneActive`, so that I can use this knowledge to setup a binding for a custom third-party control that inherits from `Selector` *(namely, [ChromeTabs-Mvvm](https://github.com/sskodje/wpfchrometabs-mvvm))*.

Looking at the code for the `ConventionManager` [here](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/2.0.2/src/Caliburn.Micro.Platform/ConventionManager.cs#L259) (v2.0.2 code), my best guess is that I'm not setting the `ItemTemplateSelector` property since Caliburn seems to avoid setting up it's binding if that property is set...but I cannot see where Caliburn is setting that property anywhere.

The following standard, automatic binding works as you can see in the screenshots below:

```xml
<TabControl 
    Grid.Column="2"
    x:Name="Items">
    <TabControl.ItemTemplate>
        <DataTemplate>
            <TextBlock Text="{Binding DisplayName}" />
        </DataTemplate>
    </TabControl.ItemTemplate>
</TabControl>
```

![2015-12-17 16_53_16-try tabcontrol long form binding](https://cloud.githubusercontent.com/assets/623736/11883353/4ce0a7e6-a4e0-11e5-8bdc-8b49bc093c8e.png)

This is my attempt at manually binding the TabControl:

```xml
<TabControl 
    Grid.Column="2"
    ItemsSource="{Binding Items}"
    SelectedItem="{Binding ActiveItem, Mode=TwoWay}">
    <TabControl.ItemTemplate>
        <DataTemplate>
            <TextBlock Text="{Binding DisplayName}" />
        </DataTemplate>
    </TabControl.ItemTemplate>
    <TabControl.ContentTemplate>
        <DataTemplate>
            <ContentControl cal:View.Model="{Binding}" VerticalAlignment="Stretch" HorizontalAlignment="Stretch" IsTabStop="False" />
        </DataTemplate>
    </TabControl.ContentTemplate>
</TabControl>
```

And the results, showing the issues that I'm having:

![2015-12-17 16_50_38-try tabcontrol long form binding](https://cloud.githubusercontent.com/assets/623736/11883419/d3e498ce-a4e0-11e5-8dfa-b3d3e373a31c.png)

*FIXED: The issue shown in the next screenshot has been fixed by adding `IsTabStop` to the `ContentControl` in the `ContentTemplate`.*

![2015-12-17 16_50_56-try tabcontrol long form binding](https://cloud.githubusercontent.com/assets/623736/11883423/d81b1bac-a4e0-11e5-985c-0d81deabb172.png)

**Comment by waynebloss** [comment]
Also, the weird focus lines go away as soon as I click any tab header twice in a row (not a double-click though).

**Comment by nigel-sampson** [comment]
I'm unable to dig into this in too much detail at the moment right now.

The framework never sets `ItemTemplateSelector` but uses [`ApplyItemTemplate`](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ConventionManager.cs#L443) to set the item template to a `ContentControl` with `cm:View.Model="{Binding}", this in essence acts like a item template selector as the framework inserts the correct view into the content control based on the view model.

You can see on the definition of this [`DefaultItemTemplate`](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ConventionManager.cs#L73) it sets `IsTabStop="false"` which may help for you as well.

**Comment by waynebloss** [comment]
@nigel-sampson Thank you.

Setting `IsTabStop="False"` removed the issue with the focus lines around the content. Now the only problem *(shown in the 2nd screenshot above)* is that `SelectedItem` binding doesn't seem to be working.

**Comment by waynebloss** [comment]
I found a work-around. If I set `ActiveItem` manually from within the VM, things work as expected.

```csharp
Items.Add(new BasicReportViewModel());
Items.Add(new OtherReportViewModel());
Items.Add(new YAReportViewModel());
// The following line is not necessary when using Caliburn.Micro automatic binding.
ActiveItem = Items.FirstOrDefault();
```

**Comment by nigel-sampson** [comment]
Ah, what's happening is without the last line of code you're not explicitly setting the `ActiveItem`. In the convention based example the binding created to the `ActiveItem` is two way so in essence the tab control itself is activating the first item.

Your explicit binding isn't two way so nothing is being deemed active.

**Comment by waynebloss** [comment]
I can't find anywhere in the CM v2 code that `ActiveItem` is being set since there are many levels of abstraction there that I'm not familiar with.

However, the "work-around" that I stated earlier just seems like it should have been necessary for either binding situation, so I can live with that. I'm still curious about when and how CM sets `ActiveItem` automatically when I don't do it in the VM.

I just changed my manual binding to include `TwoWay` for `SelectedItem` binding and there is still no change (if I don't set `ActiveItem` in my VM, no tab is pre-selected).

**Comment by waynebloss** [comment]
@nigel-sampson I thought the same thing, but after changing it to `TwoWay`, it still doesn't work the same as the automatic binding.

**Comment by nigel-sampson** [comment]
You're correct, that it shouldn't be setting the `ActiveItem` anywhere by default, only thing I can think off the top of my head is that the convention binding will also have `UpdateSourceTrigger=PropertyChanged`.

**Comment by waynebloss** [comment]
No problem. I expected to have to set `ActiveItem` myself anyway.

Just one more tidbit for this issue - With either binding setup, I get the following errors when I close my window. So, maybe I'm doing something else wrong.

```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.TabControl', AncestorLevel='1''. BindingExpression:Path=TabStripPlacement; DataItem=null; target element is 'TabItem' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.TabControl', AncestorLevel='1''. BindingExpression:Path=TabStripPlacement; DataItem=null; target element is 'TabItem' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.TabControl', AncestorLevel='1''. BindingExpression:Path=TabStripPlacement; DataItem=null; target element is 'TabItem' (Name=''); target property is 'NoTarget' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.TabControl', AncestorLevel='1''. BindingExpression:Path=TabStripPlacement; DataItem=null; target element is 'TabItem' (Name=''); target property is 'NoTarget' (type 'Object')
```

**Comment by waynebloss** [comment]
Adding `UpdateSourceTrigger=PropertyChanged` to the `SelectedItem` binding didn't change anything - but that's OK because my main focus is going to be finding out what's causing those errors now.

**Comment by nigel-sampson** [comment]
I think that's internal to the tab control, as CM doesn't do anything with `RelativeSource`.

**Comment by waynebloss** [comment]
Yep looking at that error, it's internal the tab control. Sweet! Thanks for your help.
