### ISSUE TITLE
DataContext in Window's Loaded event is NULL in 2.0.2. Works fine in 2.0.1.

### ISSUE THREAD

**Issue by mattcotton-justgiving** [Caliburn-Micro/Caliburn.Micro#274]
Here is the basic code:

## ShellView.xaml.cs

private ShellViewModel _vm;

`public ShellView()`
`{`
`      Loaded += MyLoaded;`
`}`

`public MyLoaded(object sender, RoutedEventArgs e)`
`{`
`    _vm = DataContext as ShellViewModel;`
`}`

In the `MyLoaded` method DataContext is NULL in 2.0.2 but works in 2.0.1.

**Comment by nigel-sampson** [comment]
I'm assuming this is WPF. I'm unable to recreate this in 2.0.2 the following works correctly where context is an instance of `ShellViewModel`.

``` csharp
public partial class ShellView : Window
{
    public ShellView()
    {
        InitializeComponent();

        Loaded += OnLoaded;
    }

    private void OnLoaded(object sender, RoutedEventArgs e)
    {
        var context = DataContext;
    }
}
```
I would check a number of things.

1. If you're using a dependency injection container is `ShellViewModel` registered with it?
2. Is the namespace of `ShellView` correct? If you've been moving the view between different folders in the solution then it's likely the namespace may not reflect it's new location.
3. Same goes for the view model.

**Comment by nigel-sampson** [comment]
Closing out as no more information received.
