### ISSUE TITLE
Caliburn firing click events multiple times (UWP) (NavigationCacheMode="Required")

### ISSUE THREAD

**Issue by stephan7** [Caliburn-Micro/Caliburn.Micro#275]
Caliburn is firing multiple click events on UWP if the view has the property NavigationCacheMode set to "Required". The event is fired as often as the page has already been displayed.

To reproduce:
- install Caliburn Micro 3.0.0beta2 via Nuget
- create MainView with NavigationCacheMode="Required"
- create a SettingView
- open SettingView from MainView in XAML with
```
            <Button x:Name="ShowSettingsView">Switch to SettingsView</Button>
```
- in MainViewModel.cs
```
        public void ShowSettingsView()
        {
            Debug.WriteLine("enter ShowSettingsView");
            _navigationService.NavigateToViewModel<SettingsViewModel>();
            Debug.WriteLine("leave ShowSettingsView");
        }
```
Observation:
- when you switch the first time to SettingsView you need to press only one time the back key to go back to MainView
- when you switch the second time from MainView the event fires two times, therefore ShowSettingsView is called two times, therefore you need to press two times the back key to go back MainView
- and so on

Root Cause:
It's actually not a bug in Caliburn itself. The root cause is in Microsoft.XamlBehaviors. It is already fixed with the commit 'Fixed 55: Ensured EventTriggerBehavior unregisters the event handler' (December 7th, 2015). There is still no version of https://github.com/Microsoft/XamlBehaviors/  with this fix.

If that's helpful: I wrote a minimal app which reproduces the problem as well a minimal app that uses the current XamlBehaviors to demonstrate that the bug is gone then. Simply drop me a note if I should send you the test cases.

Stephan
https://twitter.com/sw7com

**Comment by nigel-sampson** [comment]
Thanks for the report, it's something we're aware of (I raised the initial report), I've tested with the build of that library from source and it resolves the problem.

At the moment I'd suggest building from the source as well.

**Comment by stephan7** [comment]
Ok, cool! :-)

**Comment by lyling** [comment]
so how to fix it if XamlBehaviors not release new version. acutally, the lastest version 1.0.3 still have this problem.

**Comment by stephan7** [comment]
XamlBehaviors is also on Github (https://github.com/Microsoft/XamlBehaviors/). My Solution was to build Microsoft.Xaml.Interactions and Microsoft.Xaml.Interactivity as well as Caliburn.Micro, Caliburn.Micro.Platform.Core and Caliburn.Micro.Platform.UWP using these dlls from source. The resulting dlls are now used temporarily in the UWP app project until there is a new version available via Nuget. 

I guess this currently the only solution.

Stephan
https://twitter.com/sw7com

**Comment by nigel-sampson** [comment]
@stephan7 is correct, until there's 1.0.4 release of Xaml Behaviors you'll need to build from master there and used the assemblies locally. You may be able to get away with not rebuilding Caliburn.Micro but can't guarantee it.
