### ISSUE TITLE
Looking for multi-document docking panel

### ISSUE THREAD

**Issue by mwpowellhtx** [Caliburn-Micro/Caliburn.Micro#276]
Hello,

I am looking for an open source (?) docking panel, possibly project/solution style, multi-document support. Does anything like that exist from CM itself? Or does anyone know of anything similar?

I have been following Gemini for a little while now, but it seems to be falling over on itself over customized menu requests. To be fair, the author is entrenched over "declarative menus". That's not the only issue, and given the attitude he presents, not inclined to want to be that dependent on whether those issues will be resolved, with or without my contributing.

So... Looking for alternative solutions, either from CM itself, or similar WPF-based solutions.

Thanks!

**Comment by nigel-sampson** [comment]
Caliburn.Micro is an MVVM framework so we try to stay away from adding in UI controls or the like.

If you're looking for just a docking panel you could try [AvalonDock](http://avalondock.codeplex.com/).

**Comment by mwpowellhtx** [comment]
Yes, I started with AD, but apparently the story there is sullied, in as gentle way as I can phrase it; at worst, troubled. I stumbled upon a thing called Gemini, which sort of gets the job done, but not without its growing pains.

Though, I'm confused, doesn't the "View" in MVVM represent UI controls? Or, do you mean stopping short of deciding whether web, desktop, or other? Haven't looked that closely, yet, but I'm sure there are extension libraries out there.

**Comment by nigel-sampson** [comment]
You are right that the view in MVVM represents UI controls, however most MVVM frameworks typically focus on the view models themselves and supporting good patterns and practices there with the view and the model being present but nothing too crazy there.

It's about doing one thing and one thing well and trying to build control libraries on top of all the platforms CM supports would be a mammoth effort, especially when you're talking about controls such as a docking panel. 

If AD doesn't help perhaps a paid solution from one of the control vendors.
