### ISSUE TITLE
Could you change PropertyChangedBase.PropertyChanged to virtual?

### ISSUE THREAD

**Issue by taori** [Caliburn-Micro/Caliburn.Micro#279]
Hi,

As most people who already dealt with memory leaks in c# it is known that the most common cause of this is event handlers, which under certain circumstances retain a reference and keep it from being collected by the GC. 

Since i don't want to ask you to change all event handlers to a weak referenced implementation, i thought that you might consider changing the event itself to virtual, so it's possibly to override the implementation to a weak one in a custom derived class.

If changing the implementation to weak referenced handlers would be an option i could share the implementation i've used in https://www.nuget.org/packages/WeakEvent/  (which is PCL compatible)

This implementations performance is 7x that of ordinary events, but offers the convencience of not having to carefully attach/detach handlers in order to get a non leaking software.

Would one of those 2 options be acceptable to do for you?

**Comment by nigel-sampson** [comment]
I'm happy to take a pull request setting the event on `PropertyChangedBase` virtual.

**Comment by taori** [comment]
@nigel-sampson Alright, I suppose doing the same with Screen would be alright too? What's your stance on setting virtual for BindableCollection too? Pretty much the same reason. If it's ok with you i could have look at it in general. 

However those are the 3 most common classes i can think of which are subject to potential leaky code because of their usage (BindableCollection because i often find myself subscribing to list change events in order to subsequently adding PropertyChanged handlers. 

According to https://msdn.microsoft.com/en-us/library/ms973852.aspx there seems to be no harm in doing so (oddly enough it improves (well... nanoseconds... but whatever) performance slightly).

I would only have a look into events in general for doing so, if that's alright with you? Obviously i don't want to skip ahead if it's not in your interest :)

**Comment by nigel-sampson** [comment]
Yup I'd be happy with `Screen` and `BindableCollection` having their events being made virtual as well.

**Comment by taori** [comment]
I think i messed up when attempting to provide 2 pull requests so you can decide on whether to accept changes for other classes as well. Unfortunately this is my first pull request i'm doing, so i pretty much have little idea of what i'm doing and the process as Github for Windows suggest, does not work (i understand why, so i went the fork way).

Sorry for the inconvenience.

**Comment by nigel-sampson** [comment]
No worries, congrats on the first pull request, I've made some comments on it for some minor changes, but otherwise all good.
