### ISSUE TITLE
[UWP] Navigation from secondary tile or Cortana

### ISSUE THREAD

**Issue by renemaat** [Caliburn-Micro/Caliburn.Micro#281]
I recently enriched my app with secondary tiles and Cortana support and I noticed some strange behavior. The app is similar to the HelloUWP sample with a shellview containing a splitview. From the tile or Cortana call I simply want to go to a different menu path then the one normally shown from startup. This issue will only occur on actual phone devices, on desktop or the emulator it does work.

When the app is not in memory I save the tile/Cortana arguments and go into normal app startup (I need some server data) once that is done I navigate to the required screen based on these arguments and this works well on all devices. Now when I leave the app in memory and start it via the secondary tile/Cortana I don't need the initialization (the app is still there, just not on the correct page), so in the App.xaml.cs I get the INavigationService and try to directly navigate from there but nothing happens. When the app is then shown the navigation works as normal.

I also tried to hook into the lifecycle events of the Shellview But the only event I got was the OnViewAttached and navigating from there also didn't seem to work.

I can make a sample project to show this issue if needed. 

I have the feeling I'm doing something wrong or missing something. At least thanks in advance for your effort.

**Comment by nigel-sampson** [comment]
I'm happy to look at a sample project and try and help.

**Comment by renemaat** [comment]
I created a sample based on the hellouwp. You can find it here: http://1drv.ms/1RIPRTF
I tried to mimic our own code within the sample. The working scenario is:
- Open the app and after the initial load is done, open and pin page 1 and 2.
- Now close the app and remove it from memory.
- Tap one of the secondary tiles and see that the app starts with that page.

To get the issue, you need to:
- Open the app and after the load is done keep it on the home screen.
- Use the windows key to go to the start screen
- Tap on one of the secondary tiles and see that you don't navigate to the correct page.

Note that this only goes wrong on a actual Windows 10 phone while the debugger is not attached. On the desktop, the emulator or on the device while debugging it all works.

Thanks again for your time and effort.

**Comment by nigel-sampson** [comment]
Sorry, I'm not seeing issue, following these steps

1. Open the app from the start menu.
2. Open the start menu again and tap a secondary tile for page 1.
3. Expect to see the app navigate to page 1.

**Comment by nigel-sampson** [comment]
Just realised you may have been testing on the phone while I tested the desktop. We did find some weird behavior in #277 where the phone acts differently to the desktop regarding view creation. 

Adding the same code as mentioned in #277 looks to resolve this issue here to.

**Comment by renemaat** [comment]
This solution indeed fixes it for the sample I wrote. It still doesn't work for my project, but that's something I need to fix (The Shellviewmodel is registered as a singleton and behaves differently).

Thanks again for the fast reply and help in solving this.
