### ISSUE TITLE
can't attach attached/routed event

### ISSUE THREAD

**Issue by hustlei** [Caliburn-Micro/Caliburn.Micro#284]
I want attach “TreeViewItem.Expanded” event on treeview element, code like this:
```xaml
<TreeView ItemsSource="{Binding Nodes}"
             [Event TreeViewItem.Expanded]=[Action Expanded($dataContext)];
             [Event TreeViewItem.Collapsed]=[Action Collapsed($dataContext)]">
    <TreeView.ItemTemplate>
         <HierarchicalDataTemplate ItemsSource="{Binding Nodes}">
          ...
         </HierarchicalDataTemplate>
     </TreeView.ItemTemplate>
 </TreeView>
```
while it doesn't work.  it seems that i:EventTrigger doesn't support reouted event(or attached event). could caliburn.micro support it?

**Comment by hustlei** [comment]
<TreeView ItemsSource="{Binding Nodes}"
             [Event TreeViewItem.Expanded]=[Action Expanded($dataContext)];
             [Event TreeViewItem.Collapsed]=[Action Collapsed($dataContext)]">
     <TreeView.ItemTemplate>
         <HierarchicalDataTemplate ItemsSource="{Binding Nodes}">
              <TextBlock Text="{Binding Text}" Tag="{Binding Name}"></TextBlock>
          </HierarchicalDataTemplate>
     </TreeView.ItemTemplate>
 </TreeView>

**Comment by nigel-sampson** [comment]
Internally Caliburn.Micro turns 

``` xml
<Button cm:Message.Attach="[Event Click] = [Action Test]" />
```
into
``` xml
<Button>
    <i:Interaction.Triggers>
        <i:EventTrigger EventName="Click">
            <cm:ActionMessage MethodName="Test" />
        </i:EventTrigger>
    </i:Interaction.Triggers>
</Button>
```

As you noted, `EventTrigger` doesn't support attached events. A quick look around brought up [How to attached an MVVM EventToCommand to an Attached event](https://sergecalderara.wordpress.com/2012/08/23/how-to-attached-an-mvvm-eventtocommand-to-an-attached-event/) which shows how to create a `RoutedEventTrigger` that you could plug into the full syntax.

**Comment by hustlei** [comment]
Thanks a lot.

In addition, If Calibrunmicro use RoutedEventTrigger insteadof EventTrigger, it should be more convenient.^_^

**Comment by valhentai** [comment]
Is this issue solved now? Does it work when the event is not in the default namespace?
I am trying to attach to a custom routed event but it is not working.
I wrote `cal:Message.Attach="[Event dd:DragAndDrop.CanDrop] = [Action CanDropTask($eventArgs)]"` where CanDrop is a custom routed event.
If I write `MouseEnter` instead of my event, It is working. It goes inside my function.

**Comment by nigel-sampson** [comment]
As stated above the problem isn't one with the Caliburn.Micro. `EventTrigger` doesn't support attached events. If you use the full syntax above you can replace `EventTrigger` with one of your own.
