### ISSUE TITLE
Java.Lang.ClassNotFoundException: md5282f1122c1313907b9bf274dd2c2f344.PlatformRenderer

### ISSUE THREAD

**Issue by janniksam** [Caliburn-Micro/Caliburn.Micro#286]
Any idea whats wrong?

It is being thrown @ IoC.Get<SimpleContainer> (see the screenshot attached)

![unbenannt](https://cloud.githubusercontent.com/assets/15337798/12425068/61fc2c1a-bed3-11e5-95d2-eb0339367777.png)

**Comment by mvermef** [comment]
Yeah how could get IOC to pull what IOC is pulling from.  Meaning IOC gets its information from SimpleContainer, only way to get "copy", would be to pass as a dependency to viewmodel at creation of the viewmodel constructor.  IOC would only know about SimpleContainer if it were registered, which would pretty much defeat having an IOC at all...

**Comment by mvermef** [comment]
Do you this in you configure method anywhere in project

    protected override void Configure()
        {
            container = new SimpleContainer();
            container.Instance(container);
        }

**Comment by janniksam** [comment]
Yes, I do have, the class looks like this:

public class App : FormsApplication
    {
	    private readonly SimpleContainer m_container;

        public App(SimpleContainer container)
	    {
	        m_container = container;
	    }

	    protected override void OnStart()
		{
            m_container.PerRequest<LoginViewModel>().PerRequest<LobbyViewModel>().PerRequest<CreateTableViewModel>().PerRequest<TableViewModel>();
            m_container.Singleton<IEventAggregator, EventAggregator>();
	        m_container.Singleton<ICommunicationService, CommunicationService>();
	        m_container.Singleton<IConfigurationManager, ConfigurationManager>();
            Initialize();

	        var eventAggregator = IoC.Get<IEventAggregator>();
            eventAggregator.Subscribe(this);

            DisplayRootViewFor<LoginViewModel>();
        }

	    
	    protected override void OnSleep ()
		{
			// Handle when your app sleeps
		}

		protected override void OnResume ()
		{
			// Handle when your app resumes
		}
    }

**Comment by mvermef** [comment]
Something else is up... Is this compiled source or nuget?

**Comment by janniksam** [comment]
Oh, well, that sound not good. :D

It is nuget. It worked before, but it could be a problem with the newest beta 2, cause it worked a few days ago, but I upgraded it and it seems to have broken it now... Or maybe something else is missing now, maybe any reference I delete by accident?.

**Comment by mvermef** [comment]
Exactly. Try rolling back to beta 1, see if it is still an issue.  Might trying grabbing source, after that and try with compiling yourself.

**Comment by nigel-sampson** [comment]
These two discussions may help.

- [Unable to instantiate application xyz.App_Start: java.lang.ClassNotFoundException: xyz.App_Start](https://forums.xamarin.com/discussion/40303/unable-to-instantiate-application-xyz-app-start-java-lang-classnotfoundexception-xyz-app-start)
- [Get Java.Lang.ClassNotFoundException on the out of box-project on Forms](https://forums.xamarin.com/discussion/39456/get-java-lang-classnotfoundexception-on-the-out-of-box-project-on-forms)

**Comment by nigel-sampson** [comment]
Closing out as doesn't appear to be a framework issue.
