### ISSUE TITLE
Windows UWP Name Conventions doesn't work with VS15 Update 1 in debug

### ISSUE THREAD

**Issue by khamitimur** [Caliburn-Micro/Caliburn.Micro#287]
Hi!

In Windows UWP project after update 1 of VS15 conventions are not working for me in debug. I'm using ContentControl on a MainPageView like this:

```xaml
<ContentControl x:Name="UsersList"/>
```

And on MainPageViewModel I've got property:

```c#
private UsersListViewModel _usersList;
public UsersListViewModel UsersList
{
   get { return _usersList; }
   set
   {
      if (Equals(value, _usersList)) return;
      _usersList= value;
      NotifyOfPropertyChange("UsersList");
   }
}
```

And the code:

```c#
public MainPageViewModel()
{
   UsersList = new UsersListViewModel();
}
```

Everything worked fine before VS15 update 1. After it I don't see anything to be binded to ContentControl when in debug. But when build is set to release everything is fine again. I tried to reinstal/fix VS but no success. Even after Windows reinstall this issue still in it's place.

**Comment by nigel-sampson** [comment]
Can you provide a sample that illustrates your problem. At the moment I cannot recreate this issue, I'm able to see convention based bindings to a `ContentControl` in both Debug and Release using VS 2015 Update 1.

**Comment by nigel-sampson** [comment]
Just had a though, can you test using the latest from the `3.0.0` branch? There was a recent fix to a bug which may be related.

**Comment by khamitimur** [comment]
@nigel-sampson, I had this issue on two PCs recently but on 3rd it works fine. The only defference between them is that 3rd had VS15 installed before update 1 others two had VS15 installed it with update 1. I will test 3.0.0, not sure if this will help cause I had tried it nearly month ago with no luck.

**Comment by khamitimur** [comment]
I tried 3.0.0 beta 2. Issue is still there. One thing I noticed is convention works if I got it like this:
```c#
<ContentControl Content="{Binding UserName}" FontSize="90" Foreground="Black"/>
```
But if I bind my UserControl like this ContentControl will just show it's name.

**Comment by nigel-sampson** [comment]
Sorry, not `3.0.0-beta2` but the latest from the `3.0.0` branch. You'll need to build from source yourself.

**Comment by khamitimur** [comment]
I'm afraid I can't do that. I downloaded source but I have zero understanding how to build it as long as I got over 2K errors while trying to do that.

**Comment by khamitimur** [comment]
I'd managed to compile from 3.0.0 branch. The issue is gone. Debug and Release are both good right now. But it raised lots of questions about modifying the app for 3.0.0.

Like I used to clear BackStack like this:
```c#
while (Frame.CanGoBack)
   Frame.BackStack.RemoveAt(0);
```

And now the Frame is null I have no idea how to do that. Maybe there is migration instuctions somewhere that I missed?

**Comment by nigel-sampson** [comment]
There shouldn't be any breaking changes currently between `3.0.0-beta2` and the latest from source.

**Comment by khamitimur** [comment]
Yes, but I used 2.0.2 and when I tested 3.0.0-beta 2 I just commented problemed places in code.

**Comment by nigel-sampson** [comment]
Ah, `2.0.2` didn't have any explicit support for UWP, however the Windows 8.1 version continued to work.  You can see some of the breaking changes listed on the [Releases page](https://github.com/Caliburn-Micro/Caliburn.Micro/releases).

I can't think of any off the top off my head that would cause this though. Where is above code located?

**Comment by khamitimur** [comment]
It's located on MainPageView Loaded event. User can be navigated to this page directly or after registration so I'm checking if there is something in BackStack and removing it.

**Comment by nigel-sampson** [comment]
Weird, that's definitely not an intended breaking change, hard to say the cause without a repro. Especially since that property is in a view which the framework doesn't touch.

**Comment by khamitimur** [comment]
I will try to reproduce this issue on sample project in 24 hours. I will write about results.

**Comment by khamitimur** [comment]
I took UWP Sample app and modified it a litle bit:
```c#
public ShellView()
{
   InitializeComponent();

   while (Frame.CanGoBack)
      Frame.BackStack.RemoveAt(0);
}
```

Frame is null there as well.

**Comment by khamitimur** [comment]
This is only if using ViewModel First approach. With View First I don't see this issue.

**Comment by nigel-sampson** [comment]
Ahh, that makes sense. when you use View First the framework sets the root window content to be a `Frame`. When using view model first we set the root window content to be the view itself.

Therefore `ShellView` isn't in a `Frame` and therefore the property would be null. You'll notice that the `ShellView` contains a `Frame` so the other pages will have the property set.
