### ISSUE TITLE
Design time content control resolution

### ISSUE THREAD

**Issue by vladimirdjurdjevic** [Caliburn-Micro/Caliburn.Micro#290]
Hi,

I am trying to get my content control rendered at design time, but i get "Can not find view..." message. I tried overriding `ViewLocator.LocateTypeForModelType` to return type based on custom attribute i made, but it doesn't work. Here is code for that:

`var oldLocator = ViewLocator.LocateTypeForModelType;

            ViewLocator.LocateTypeForModelType = new Func<Type, DependencyObject, object, Type>((Type type, DependencyObject dpobj, object obj) =>
            {
                Type targetType = oldLocator(type, dpobj, obj);

                if (targetType == null)
                {
                    AssociatedViewAttribute attribute = Attribute.GetCustomAttribute(type, typeof(AssociatedViewAttribute)) as AssociatedViewAttribute;

                    if (attribute != null)
                        targetType = attribute.ViewType;
                }

                return targetType;
            });`

I also tried overriding `BootstrapperBase.SelectAssemblies` to add executing assemblie manually in design time, but it's not working. Here is code:

`protected override IEnumerable<Assembly> SelectAssemblies()
        {
            List<Assembly> assemblies = new List<Assembly>(base.SelectAssemblies());

            if (Execute.InDesignMode)
                assemblies.Add(GetType().Assembly);

            return assemblies;
        }`

Is it bug or is it just me? :D

**Comment by nigel-sampson** [comment]
Something doesn't seem right, the design time experience is always a little flaky due the xaml designer itself. However that fact you're seeing "Cannot find view for ... " would indicate that the design time code is at least executing.

The normal reason for view / view models not being found is due to namespace changes. When a view or view model is moved in Visual Studio it's namespace won't be updated to reflect the new location.

**Comment by vladimirdjurdjevic** [comment]
Is it fixable or i should let it go? Could this be enhancement suggestion for next release?

**Comment by nigel-sampson** [comment]
It's hard to say what the root cause is right now. From your description it appears that the design time code is executing but not finding the view. There are a lot of reasons for this, most of them are in the application code as I mentioned above where the view / view model namespaces don't match.

**Comment by nigel-sampson** [comment]
Can you provide the full name of the view and view model not being found?

**Comment by vladimirdjurdjevic** [comment]
It's something with designer executing code in different environment.. It's can't be view - view model name miss match since i you same class for both runtime and design time. I just have default constructor with:
`public class MyViewModel
{
     public MyViewModel()
    {
          if (Execute.InDesignMode)
                 LoadDesignTimeData();
     }
}`

At runtime everything works fine. That is why i tried with custom view resolution with custom attribute as i described in question. Second taught was that app running in designer is not aware of it's assembly, that is why i tried to override SelectAssemblies.

**Comment by nigel-sampson** [comment]
If you can send through a repro I'd be happy to look at it.

**Comment by vladimirdjurdjevic** [comment]
Give me few minutes to create repo, and sample app..

**Comment by vladimirdjurdjevic** [comment]
https://github.com/vladimirdjurdjevic/caliburntestrepo
Here, i created simple test sample.

**Comment by nigel-sampson** [comment]
Just had a look at the sample, the design time view for `SliderView` looks correct, I'm seeing the following for `MainWindow`. While it's not showing "Cannot find view for ..." it's not showing the design time data for the instantiated `SliderView`. I'm not 100% confident that scenario is supported given this was all written before my time. 

![design](https://cloud.githubusercontent.com/assets/1256017/12771185/1affd8ba-ca8c-11e5-8f7e-f065b70e8e2b.png)

**Comment by vladimirdjurdjevic** [comment]
Well that is strange.. Here is screenshot from my PC. 
![caliburn](https://cloud.githubusercontent.com/assets/16327103/12776363/b5589ff0-ca55-11e5-8755-68acaae84b9f.png)

Which VisualStudio you use? Could it be 2015 Community Edition bug?

**Comment by nigel-sampson** [comment]
This was with Visual Studio 2015 Enterprise.

**Comment by vladimirdjurdjevic** [comment]
I installed Enterprise edition, but now another problem occurs.. Now i got "Cannot add instance of type 'ActionMessage' to a collection of type 'TriggerActionCollection'. Only items of type 'T' are allowed." It's not sample app, it's my real project (works fine in community designer).

**Comment by vladimirdjurdjevic** [comment]
And i also get this: "The type 'ActionMessage' from assembly 'Caliburn.Micro.Platform' is built with an older version of the Blend SDK, and is not supported in a Windows Presentation Framework 4 project."

**Comment by vladimirdjurdjevic** [comment]
Ok, i give up. Don't wanna bother you guys any more, it's not caliburn, it's VisualStudio. In 2013 everything works great, so i will not push it any more with 2015.. Thank you for response anyway.

**Comment by nigel-sampson** [comment]
No worries, the design time stuff in all honesty has always been a bit flaky, mostly due the designers themselves.

If something comes up that means we can revisit this I'll let you know.
