### ISSUE TITLE
Problem when closing/reopening app on Xamarin Forms

### ISSUE THREAD

**Issue by winterdouglas** [Caliburn-Micro/Caliburn.Micro#298]
When app is closed using back button and reopening it, Caliburn register two instances of each type in the container resulting in an exception "Sequence contains more than one element".
I'm getting this exception when calling "container.GetInstance<AnyType>()" on App.cs

When inspecting container instances, it has two instances of each type.

I'm using release 3.0 but it was happening on 3.0 beta2 too. Testing on Visual Studio Emulator for Android and Asus Zenfone.

**Comment by nigel-sampson** [comment]
Thanks, do you know if it's happening on the other Xamarin.Forms platforms.

**Comment by winterdouglas** [comment]
Hi Nigel.
I'm testing on Windows Phone 8.1 and Windows 10 Mobile too but on these plataforms it isn't happening.

I've attached the Hello.Forms sample from Caliburn referencing release 3.0 from nuget.
[Hello.Forms.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/155481/Hello.Forms.zip)

Thank you!

**Comment by nigel-sampson** [comment]
So it looks like the problem is the Android `Application` is kept around after leaving the app (and therefore retaining the `SimpleContainer`. However relaunch recreates `MainActivity` which in turn recreates `App` causing the double registration.

A fast fix is some checks in `App`.

``` csharp
public class App : FormsApplication
{
    private readonly SimpleContainer container;

    public App(SimpleContainer container)
    {
        this.container = container;

        if (!container.HasHandler(typeof (LoginViewModel), null))
        {
            container
                .PerRequest<LoginViewModel>()
                .PerRequest<FeaturesViewModel>();
        }

        Initialize();

        DisplayRootView<LoginView>();
    }

    protected override void PrepareViewFirst(NavigationPage navigationPage)
    {
        if (container.HasHandler(typeof(INavigationService), null))
            container.UnregisterHandler(typeof(INavigationService), null);

        container.Instance<INavigationService>(new NavigationPageAdapter(navigationPage));
    }
}

There may be some other approaches we can add to make this better long term though.
```

**Comment by nigel-sampson** [comment]
Just came up with a better solution that leaves `App` untouched.

If you register the `App` as a singleton in the Android application.

``` csharp
protected override void Configure()
{
    container = new SimpleContainer();
    container.Instance(container);

    container.Singleton<App>();
}
```

and update `MainActivity` with

``` csharp
LoadApplication(IoC.Get<App>());
```

you don't see the exception.

**Comment by winterdouglas** [comment]
Hi Nigel.
I have tested another solution like the first one and I had problems with Caliburn's default services but I wasn't unregistering handlers.

Registering app as singleton seems to be a simple and better option. It's working like a charm :)

Thank you!

**Comment by lploumen** [comment]
I have the same problem with UWP Mobile application.
I temporary fixed it with this by checking the previous state in the OnLaunched event : 
```C#
protected override void OnLaunched(LaunchActivatedEventArgs args)
{
   Xamarin.Forms.Forms.Init(args);
   if (args.PreviousExecutionState == ApplicationExecutionState.Terminated || 
                args.PreviousExecutionState == ApplicationExecutionState.NotRunning)
                DisplayRootView<MainPage>();
   Window.Current.Activate();
}
```

**Comment by nigel-sampson** [comment]
I've updated the sample to reflect this change.
