### ISSUE TITLE
Increment AsssemblyVersion

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#299]
Missed out in `3.0.0`.

**Comment by kasperhj** [comment]
This is causing some issues with Paket and Visual Studio referencing. It appears that after updating (with Paket/nuget) to 3.0.0, Visual Studio is complaining that version 2.0.2 should be referenced. Maybe this alone could constitute 3.0.1 so that it can resolve this issue?
