### ISSUE TITLE
problem with app after it reopened

### ISSUE THREAD

**Issue by bondarenkod** [Caliburn-Micro/Caliburn.Micro#307]
Hi!
I have a problem with CM in my UWP application. 
When I navigate back until app go minimize, and after I (re)open the application I see empty screen (black or white, it depends on phone theme) screen (with hamburger of course).
I have checked CM 'hello uwp' sample and find the same bug.

https://youtu.be/7s5Frcay9Os

**Comment by bondarenkod** [comment]
app has PreviousExecutionState=Suspended state when it reopened. 

When the frame is loaded we setting up the nav svc (SetupNavigationService).
But the container already has previous INavigationService instance:
_container.GetInstance<INavigationService>() != null, but should (or not). 

So, calling the  _container.RegisterNavigationService(frame) just return to us old navigation svc instance, but we have a new instance of Frame, so. that mean content of actual frame is empty.  

Temporary fix for me - add to the OnLaunched method -
            if (args.PreviousExecutionState == ApplicationExecutionState.Suspended)
            {
                _container.UnregisterHandler(typeof(INavigationService), String.Empty);
                return;
            }

That's need additional investigating.

**Comment by nigel-sampson** [comment]
Apologies this one looks to have fallen through the cracks. It's come up once before in #277 but I didn't update the UWP sample.

As @bondarenkod mentioned what's happening on the phone (compared to the tablet) is the view being recreated, we then need to update the navigation service to use the new `Frame` control.

Adding the following to the top of `SetupNavigationService` will resolve this. I'm in the process of updating the samples so will make sure this is added.

``` csharp
if (_container.HasHandler(typeof(INavigationService), null))
    _container.UnregisterHandler(typeof(INavigationService), null);
```
