### ISSUE TITLE
Native solution for ContentDialogs

### ISSUE THREAD

**Issue by bjoernfi** [Caliburn-Micro/Caliburn.Micro#309]
I'm using the Windows UWP `ContentDialog` with some business logic that needs to be encapsulated in a ViewModel. Since I haven't found a native solution in the framework, I would like to suggest implementing support for `ContentDialog`s.

As a work around I have written the following extension for the `INavigationService` interface:

```
public static async Task<ContentDialogResult> ShowDialog<TDialog, TViewModel>(this INavigationService navigationService)
    where TDialog : ContentDialog, new()
    where TViewModel : ViewModelBase, new()
{
    var dialog = new TDialog();

    // inherits the theme from the opening window
    dialog.RequestedTheme = ((FrameworkElement) Window.Current.Content).RequestedTheme;
    dialog.DataContext = new TViewModel();

    // inject services into view model
    IoC.BuildUp(dialog.DataContext);

    return await dialog.ShowAsync();
}
```

While this works, there are some major flaws in this approach:

- OnInitialize, OnActivate, OnDeactivate is not called, a virtual member call in the constructor is required
- Although the IoC injects all installed services into the ViewModel, I would like to have the default constructor convention
- Binding works but needs to be improved. Especially when capturing the `PrimaryButtonClick` event, the following code breaks the concept of MVVM when using asynchronous code in the callback because the close action needs to be deferred until the code has processed:

View:
``micro:Message.Attach="[Event PrimaryButtonClick] = [Action Purchase($eventArgs)]"``

ViewModel:
```
public async void Purchase(ContentDialogButtonClickEventArgs e)
{
    var deferral = e.GetDeferral();
    await something();
    e.Cancel = true; // for cancelling the close action
    deferral.Complete();
}
```

Any thoughts on this?

**Comment by nigel-sampson** [comment]
Hi, sorry it's taken me so long to get to this one.

I agree a proper Window Manager needs to come to the WinRT / UWP projects. It's certainly easier to do in UWP with things like `ContentDialog` but we may need to use `Popup` as well. I have something in a few of my projects but it's definitely not "framework ready".

What you've written is to what I have, some rough code is

``` csharp
 public async Task<ContentDialogResult> ShowDialog<TViewModel>()
 {
     var viewModel = IoC.Get<TViewModel>();
     var view = ViewLocator.LocateForModel(viewModel, null, null);

     ViewModelBinder.Bind(viewModel, view, null);

     var dialog = new ContentDialog
     {
         Content = view
     };

     ScreenExtensions.TryActivate(viewModel);

     var result = await dialog.ShowAsync();

     ScreenExtensions.TryDeactivate(viewModel, true);

     return result;
 }
```

The above has the following features:
- Uses the container to create the view model to inject any services into it.
- Uses the default conventions to find the view for that view model.
- Binds them together to the normal conventions / bindings apply.
- Sets the view to be the content of the dialog.
- Activtates and Deactivates the view model as the dialog opens and closes.

You'll need to modify this to customize the actual `ContentDialog` itself but it should give you some way to go.

**Comment by bjoernfi** [comment]
Thank you very much, Nigel. This seems like a good solution to me. Would be great if we get this feature into the framework because it's quite common to use `ContentDialog`s and `Popup`s.

**Comment by nigel-sampson** [comment]
Yup, it's certainly something on my mind. Working with `ContentDialog` isn't too bad. But `Popup` has a lot of caveats if you want to deal with things like position, screen size changes and the on screen keyboard. 

Dealing with all of these in a way that works for all apps is difficult.
