### ISSUE TITLE
migration to 3.0.0

### ISSUE THREAD

**Issue by abadolon** [Caliburn-Micro/Caliburn.Micro#311]
Hello
I have problem with my project, In version 2.0.0.3 have only 1 method and 1 ctor in AppBootstrapper.
In version 3.0.0.0 have 3 methods and 1 ctor, wtf ? Can't run project :/ Do you have documentation about new methods ?
Can you give me any example how I can do  AppBootstrapper?

**Comment by nigel-sampson** [comment]
There wasn't any major breaking changes in `3.0.0`, can you please provide some more information, specifically what platform you're working on and what your current bootstrapper looks like?

**Comment by abadolon** [comment]
I come back to last version. (in CM 2.0.0.3)

    class AppBootstrapper : BootstrapperBase
    {
        public AppBootstrapper()
        {
            Initialize();
        }
        protected override void OnStartup(object sender, StartupEventArgs e)
        {
            DisplayRootViewFor<PrimaryWindowViewModel>();
        }
    }
}

I working on Visual Studio 2015, c#.

I want work with 3.0.0.0 version. Do you tell me how does AppBootstrapper look like  ?

**Comment by nigel-sampson** [comment]
I just tested the above bootstrapper with no problems. What's the exact error you're seeing?

**Comment by nigel-sampson** [comment]
No extra information received. Closing
