### ISSUE TITLE
Button click is not working in non debug mode

### ISSUE THREAD

**Issue by ynrajasekhar** [Caliburn-Micro/Caliburn.Micro#312]
Hi All,

When i run program in debug mode the button clicks are working, but when i run using Start without Debugging then button clicks are not working in the log i can see 
2016-04-06 11:54:43,256 [1] Caliburn.Micro.ViewModelBinder Action Convention Applied: Action NewQuery on element NewQuery.
**xaml**
 ```
<Button x:Name="NewQuery">
                <StackPanel Orientation="Horizontal">
                    <Image Source="/xxx;component/Images/document_add_16.png" Width="16" Height="16" Margin="0,0,3,0"></Image>
                    <TextBlock Text="New Query"></TextBlock>
                </StackPanel>
            </Button>
```

**AppViewModel**
```
public void NewQuery()
        {
            New(null);
        }
```

in my boostraper onstartup i am doing this
            `DisplayRootViewFor<AppViewModel>();`
Thanks & Regards
Rajasekhar

**Comment by nigel-sampson** [comment]
I don't see anything immediately wrong with what you're doing and obviously similar code works for me.

Can you provide a project that recreates the problem?

**Comment by nigel-sampson** [comment]
Closing as no new information provided.
