### ISSUE TITLE
MasterDetailPage support

### ISSUE THREAD

**Issue by sorochan** [Caliburn-Micro/Caliburn.Micro#315]
Hi! 
In the Master-Detail scenario I'm was faced with some troubles.
In Android an app can not contain more then one NavigationPage. Then I use navigation without NavigationPage in iOS don't working a hamburger menu. Can you help to fix thats bug?

Thank you!

**Comment by nigel-sampson** [comment]
Is this for Xamarin.Forms?

**Comment by sorochan** [comment]
Excuse me, forget about platform. Yes, Xamarin.Forms. 
If I use DisplayRootView<MainView>(); in Android catch the exception:
System.Exception: Android only allows one navigation page on screen at a time

MainView is MasterDetailPage

In iOS menu work but without "hamburger" icon... 

If I use DisplayRootViewFor<MainViewModel>() - not working navigation, because 

protected override void PrepareViewFirst(NavigationPage navigationPage)
        {
            container.Instance<INavigationService>(new NavigationPageAdapter(navigationPage));
        }
not calling, and RootNavigationPage not setted.


Can you add example, how to make MasterDetailPage interface with my lovely Caliburn.Micro framework? :) Thank you for answer!

**Comment by nigel-sampson** [comment]
You should use `DisplayRootView` to use a view first navigation pattern and set up the services.

`DisplayRootViewFor` only finds the view for the specified view model and sets it as the Main Page

**Comment by jlucaspains** [comment]
This is still a problem in iOS. If I call DisplayRootView<T>(), it will show the master detail page but the hamburguer icon won't show. The reason for this is because DisplayRootView<T> will always create a new NavigationPage and then navigate to the MasterDetail view inside of it. For this to work, the MasterDetail should be made MainPage and the content of MasterPage.Detail should be made the navigation context (NavigationPage). @nigel-sampson, what do you think?

**Comment by nigel-sampson** [comment]
This makes sense, the current implementation of `INavigationService` as you've noticed is simply a wrapper around `NavigationPage`.

You should be able to do something similar to what you've described, but it's a bit more work.  Typically it's as follows:

1. Use `DisplayRootViewFor<>` with your "shell" view model. This view model becomes the root conductor for your application and it's view will be the main window content.
2. Your "shell" view will contain the `NavigationPage`.
3. You can then create  `NavigationPageAdapter` around that page and register it as the navigation service. into your container for use in other view models.
4. This approach leaves the "shell" view on the screen at times.

To be honest, I've never tried it in Xamarin.Forms, but you can see an [example here in UWP](https://github.com/nigel-sampson/talks/tree/master/ignite-2016/Ignite.Features). Check out `ShellView / ViewModel`.

**Comment by jlucaspains** [comment]
Awesome. Thanks for the help. Here is a quick and dirty example that works:

```
public class App : FormsApplication
    {
        private readonly SimpleContainer container;

        public App(SimpleContainer container)
        {
            Initialize();

            this.container = container;

            container.PerRequest<HomeViewModel>();

            DisplayRootViewFor<HomeViewModel>();
            var mainPage = (HomeView)MainPage; //HomeView is MasterDetailPage     
            container.Instance<INavigationService>(new NavigationPageAdapter((NavigationPage)mainPage.Detail)); // MasterDetailPage.Detail is a NavigationPage
        }
    }
```

**Comment by nigel-sampson** [comment]
Nicely done. Thanks for providing a sample.

**Comment by Wilsmor** [comment]
> Awesome. Thanks for the help. Here is a quick and dirty example that works:
> 
> ```cs
> public class App : FormsApplication
>     {
>         private readonly SimpleContainer container;
> 
>         public App(SimpleContainer container)
>         {
>             Initialize();
> 
>             this.container = container;
> 
>             container.PerRequest<HomeViewModel>();
> 
>             DisplayRootViewFor<HomeViewModel>();
>             var mainPage = (HomeView)MainPage; //HomeView is MasterDetailPage     
>             container.Instance<INavigationService>(new NavigationPageAdapter((NavigationPage)mainPage.Detail)); // MasterDetailPage.Detail is a NavigationPage
>         }
>     }
> ```

Hi, I'm trying to use it in xamarin.forms, but i  don't know how to do it works. 
Could you post the HomeView.XAML code?

Thank you.

**Comment by jlucaspains** [comment]
Sorry @Wilsmor, I don't have the code for this anymore. Are you able to share the code you have and doesn't work? Maybe I can help.
