### ISSUE TITLE
Bootstrapper inherits from Windows.UI.Xaml.Application instead of wrapping it

### ISSUE THREAD

**Issue by godrose** [Caliburn-Micro/Caliburn.Micro#316]
I know this is a bit old, but this a rather breaking change, making some of the methodologies incompatible with WinRT and UWP platforms.
For instance, I am not able to instantiate the bootstrapper anywhere but in the actual package assembly. This drastically limits my testing options.
In NET 4.5 I used to have a ``useApplication`` flag which did the trick and allowed me test the view models logic regardless of their view. 
Is there any plan to restore wrapping instead of inheritance?

**Comment by nigel-sampson** [comment]
It would have been nice to be consistent across all platforms, the trouble is the that the `Application` in WinRT / UWP doesn't expose it's lifecycle in the same way as in WPF / Silverlight and you end up needing more method overloads in the application,
