### ISSUE TITLE
Unhandled exception in UWP when using ToolbarItem in Xamarin.Forms

### ISSUE THREAD

**Issue by lploumen** [Caliburn-Micro/Caliburn.Micro#317]
Hi,
I'm doing some experiments with Xamarin.Forms and Caliburn.micro.
I took the Hello.Xamarin sample project, added an UWP project. Then I took the LoginView.xaml and added a ToolbarItem
`  
<ContentPage.ToolbarItems>
    <ToolbarItem Text="coucou"></ToolbarItem>
  </ContentPage.ToolbarItems>
`

On Android I can see the toolbar menu. But on UWP, it crashes on startup with an UnhandledException.
If I create a new Xamarin.Forms projects, without using Caliburn, I am able to launch the UWP project even it it contains a ToolBarItem.
I'm using Xamarin.Forms 2.1.0.6529.
I attached the project in case someone wants to have a look at it.
[Hello.Forms-TestToolBarItem.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/233634/Hello.Forms-TestToolBarItem.zip)

**Comment by nigel-sampson** [comment]
It looks like the UWP `ToolbarItem` crashes if an `Icon` isn't specified. Changing your sample to the following resolved the crash.

``` xml
<ToolbarItem Text="coucou" Icon="Image.png" />
```

As an FYI, whenever you report an exception it's helpful to include the exception details in the report. Thanks
