### ISSUE TITLE
File not found exception with Xamarin.Forms

### ISSUE THREAD

**Issue by larrybeall** [Caliburn-Micro/Caliburn.Micro#318]
I'm trying to create a Xamarin project using Caliburn, but I can't seem to get by just adding the projects.  When I add Caliburn to the portable project I get errors that Caliburn.Micro.Xamarin.Forms isn't referenced.  So I add the packages to the iOS and Droid projects and I get the below error:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Caliburn.Micro.Platform.Core, Version=2.0.2.0, Culture=neutral, PublicKeyToken=8e5891231f2ed21f'. 

From what I can tell looking @ the nuspec files the platform assembly is not included in any of the packages.  Am I doing something wrong?

**Comment by nigel-sampson** [comment]
For Xamarin.Forms projects you should add the `Caliburn.Micro` and `Caliburn.Micro.Xamarin.Forms` packages.

If you have a Portable Class Library for the shared code (such the view and view models), it should have references to `Caliburn.Micro.Core` and `Caliburn.Micro.Xamarin.Forms`.

I just check the nuget packages and they do contain `Caliburn.Micro.Platform.Core.dll`.

**Comment by larrybeall** [comment]
That did it.  Sorry for the false alarm.  I didn't even think of looking @ that as a possibility.  I would have expected it to come down as a dependent package.

**Comment by nigel-sampson** [comment]
No worries, because the nuspec has a wild card like

``` xml
<file src="..\bin\net40\Release\Caliburn.Micro.*.*" target="lib\net40" />
```

it includes both `Caliburn.Micro.Platform.dll` and `Caliburn.Micro.Platform.Core.dll`
