### ISSUE TITLE
$selectedItem does not appear to be implemented

### ISSUE THREAD

**Issue by Yakyyaky** [Caliburn-Micro/Caliburn.Micro#319]
Hi, I am using CM for Xamarin Forms for android and iOS with Autofac as DI replacement.

I went through http://caliburnmicro.com/announcements/3.0.0 and in there was a snippet of using ListView with selected item.
`<ListView ItemsSource="{Binding Features}" HasUnevenRows="True"
          cm:Message.Attach="[Event ItemSelected] = [ShowFeature($selectedItem)]">`

I found that $selectedItem is not working and upon further inspect, I can concluded it's not implemented at all in MessageBinder. For the moment I have added the following to get it working.
`MessageBinder.SpecialValues.Add("$selecteditem", context =>
            {
                var lv = context.Source as ListView;
                return lv?.SelectedItem;
            });`
Using safe cast instead of reflection because afaik ListView is the only with this property.

Is this feature deprecated/remove/missed/incorrectly documented/implemented/some other? or have I missed something?
Thanks.

**Comment by nigel-sampson** [comment]
You're right it's not currently implemented in the base library and I lifted it from [a sample](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/samples/samples/features/Features.Forms/Features.Forms/FormsApp.cs#L17) it's something I think we'll add in a upcoming version.

Thanks for bringing this to my attention.

**Comment by Yakyyaky** [comment]
Awesome, I look forward to it.
The sample you linked looks mighty useful for review as well. Thanks for that.

**Comment by StephenWard** [comment]
this fix would be more broadly applicable

`MessageBinder.SpecialValues.Add("$selectedItem", context => {`
`    if (context.Source == null)`
`        return null;`
`    return ((dynamic)context.Source).SelectedItem;`
`});`

**Comment by nigel-sampson** [comment]
There's one major problem with implementing `$selectedItem` in Xamarin.Forms.

`TriggerAction<T>` doesn't receive the arguments from the appropriate trigger. All the XAML platforms support this and by convention the event trigger passes through the event args. 

We can do it with `ListView.SelectedItem`, however you also need to support deselecting the item which may not be something you want.

**Comment by nigel-sampson** [comment]
I've implemented `$clickedItem` in WinRT projects for now. Not comfortable at the moment tackling Xamarin.Forms here.

**Comment by gregbty** [comment]
What's the current workaround for XForms? The syntax is still referenced in the updated samples: https://github.com/Caliburn-Micro/Caliburn.Micro/blob/79724b8dbeda556e1462f9ceec5ae8d81a8d2ded/samples/features/Features.Forms/Features.Forms/Views/MenuView.xaml

**Comment by mvermef** [comment]
Believe it should be all lower case it is defined in FormApp.cs constructor, might also be  typo.

Sent from my Windows 10 phone

**Comment by nigel-sampson** [comment]
The sample itself creates the implementation in [`FormsApp`](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/79724b8dbeda556e1462f9ceec5ae8d81a8d2ded/samples/features/Features.Forms/Features.Forms/FormsApp.cs#L17) which you're free to copy.

I'm not keen on adding it to the framework due to the stateful nature of `SelectedItem`, what tends to happen if people aren't careful is that they forget to clear it and going back and hitting the same item doesn't change the value and trigger the event.

I'll double check this in later versions of the Forms across multiple platforms and if it's good then I'll add it in.

**Comment by gregbty** [comment]
Thanks! I missed the added special value configuration.

**Comment by gregbty** [comment]
Is there a reason why the event args can not be used? Is this also not supported with Caliburn + XForms? The value of `EventArgs` in the context seems to always be null.

```xaml
forms:Message.Attach="[Event ItemSelected] = [NavigateToItemAsync($selectedItem)]"
```

```csharp
MessageBinder.SpecialValues.Add("$selecteditem", c =>
{
  var eventArgs = c.EventArgs as SelectedItemChangedEventArgs;
  return eventArgs?.SelectedItem;
});
```

**Comment by nigel-sampson** [comment]
Yup, first a bit of internals. They way Caliburn.Micro works is taking the string `[Event ItemSelected] = [NavigateToItemAsync($selectedItem)]`, parsing it and producing something like
```
<EventTrigger Event="ItemSelected">
    <cm:ActionMessage MethodName="NavigateToItemAsync">
        <cm:Parameter Value="$selectedItem" />
    </cm:ActionMessage>
</EventTrigger>
```

Where `EventTrigger` is the implementation that comes with the platform in question. We do this for a number of reasons.

1. Allows developers to extend the parser to create their own triggers.
2.. Allows developers to fall back to the extended synxtax above if they have complicated requirements not workable in the parser.
3. Separates the trigger from the action.

One of the differences between [Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/blob/74cb5c4a97dcb123eb471f6b1dffa1267d0305aa/Xamarin.Forms.Core/Interactivity/TriggerAction.cs#L30) and the [others](https://github.com/Microsoft/XamlBehaviors/blob/master/src/BehaviorsSDKManaged/Microsoft.Xaml.Interactivity/IAction.cs#L17) (such as UWP) is the interface between the trigger and the action. Specifically on the Microsoft developed platforms there's an optional argument passed to the action (which we enter into `EventArgs`). Xamarin.Forms however doesn't have that parameter. The interface itself doesn't allow this to be passed between the two.

It's unfortunate but it will require a change to Xamarin.Forms to deal with this.
