### ISSUE TITLE
Ambiguity in UWP

### ISSUE THREAD

**Issue by godrose** [Caliburn-Micro/Caliburn.Micro#320]
``Ambiguous invocation:
  System.Collections.Generic.IEnumerable<System.Type> GetExportedTypes(this System.Reflection.Assembly) (in class ExtensionMethods)
  System.Type[] GetExportedTypes(this System.Reflection.Assembly) (in class AssemblyExtensions)
match``

when using the following line of code in a UWP project:
``assembly.GetExportedTypes()``

**Comment by nigel-sampson** [comment]
Looks like a conflict between an extension method in the base framework and one in Caliburn.Micro.

I would just fully qualify the method call. `Caliburn.Micro.ExtensionMethods.GetExportedTypes(assembly)` or remove one of the namespaces if it's not being used.

**Comment by godrose** [comment]
Thanks for the reply. I found a workaround. Still this feels like something
that should have never been exposed by the framework. Of course if the
extension methods are platform-specific.

**Comment by nigel-sampson** [comment]
Yeah, normally it's not something I'd want to expose, trouble is that it's in a separate assembly `Caliburn.Micro.Platform.Core` because it's used by a number of platforms (at the same time).

Using `InternalsVisableTo` is a bit of hack.
