### ISSUE TITLE
App does not resume using Xamarin Windows Phone Silverlight

### ISSUE THREAD

**Issue by lploumen** [Caliburn-Micro/Caliburn.Micro#322]
When using the sample Hello.Forms and the Xamarin.Forms version from the sample, a Windows Phone Silverlight application can be suspended by using the Windows button.
When launching the app again, it resumes correctly.
However, when Xamarin.forms is updated to the latest version (2.2.0.31), the app does not resume and shows the "Resuming..." message for an infinite time.
Yeah I know that almost nobody uses Windows Phone Silverlight anymore ;)

**Comment by nigel-sampson** [comment]
I can't recreate this on my machine at the moment, can you provide some exact steps. Thanks

**Comment by lploumen** [comment]
Actually I did nothing special.
- Take the Hello.Forms sample.
- Deploy and run on emulator.
- Click the "Windows" button
- Go to app list and launch the app again.
==> OK, it resumes correctly
![withoriginalxamarin](https://cloud.githubusercontent.com/assets/11539944/15246779/befe0190-190f-11e6-97fc-b56752074954.gif)


- Update the Hello.Forms sample with latest Xamarin.Forms version.
- Deploy and run on emulator.
- Click the "Windows" button
- Go to app list and launch the app again.
==> Not OK, it shows "Resuming..." forever.

![withlatestxamarin](https://cloud.githubusercontent.com/assets/11539944/15246787/cb37ce3c-190f-11e6-864a-b3002a10f89e.gif)

Hope it helps...

**Comment by nigel-sampson** [comment]
Just ran through your walk through without being able to recreate, there's been a minor change in the sample https://github.com/Caliburn-Micro/Caliburn.Micro/commit/337c2ecfb04d4bb66e0079a9131f8669a85d24a2 that could have resolved it. Could you retest with this commit.

**Comment by lploumen** [comment]
Hi,
Tried with latest github version and the problem is still there.
Also tried deploying to W10M emulator but the problem is also present.
Am I the only one having this problem ? How could that be explained ?

**Comment by nigel-sampson** [comment]
Not sure to be honest, which emulator were you using?

I've tested with the 8.1 WVGA and Windows 10 10.0.10240 WVGA

**Comment by lploumen** [comment]
I tested with same emulators as you + others and problem exist on all I tested.
I'm also using VS2015 update 2 if it matters...

**Comment by lploumen** [comment]
It looks like it's a Xamarin.Forms bugs.
see https://bugzilla.xamarin.com/show_bug.cgi?id=41076 and https://github.com/xamarin/Xamarin.Forms/commit/4cbe7e61e51198455bb18266ebbcb58ff23916c7
@nigel-sampson it's strange that you cannot reproduce it...

**Comment by nigel-sampson** [comment]
Weird, thanks for finding that, only difference I can see between what's in Bugzilla and the test above is back button vs home button.

**Comment by rohitvipin** [comment]
i have this issue when i use "AppointmentManager.ShowAddAppointmentAsync" to show an appointment in the native platform using DI. After the appointment is saved the app gets stuck on the "resuming" screen. This was working fine prior to XF 2.2

**Comment by lploumen** [comment]
Hi,
It is not a Caliburn micro issue. This is Xamarin Forms related, see my comment above. It doesn't seem to be fixed in the latest Xamarin Forms nuget package, but I tried using the latest version from GitHub and it worked.

**Comment by rohitvipin** [comment]
For me it works fine on 2.1 pre 4 of Xamarin forms.
