### ISSUE TITLE
MenuItem.RaiseEvent doesn’t invoke Caliburn-bound command until the item is once clicked with a mouse.

### ISSUE THREAD

**Issue by Const-me** [Caliburn-Micro/Caliburn.Micro#324]
See the minimal repro solution (as you see, it uses the latest 3.0.1 from nuget).

[CaliburnBug.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/260073/CaliburnBug.zip)

Steps to repro:
1. Launch
2. Click "Test" button near the center of the window.
Expected result: "Test Message" message box.
Actual result: nothing happens.

Note that once you clicked that item with a mouse and saw the message, "Test" button starts to work OK.

P.S. That’s not a new bug, version 2.0.2 does the same.

**Comment by Const-me** [comment]
Forgot to mention, the platform is Windows desktop, WPF, .NET 4.5.2.

**Comment by Const-me** [comment]
Looks like caliburn micro is too lazy, it saves CPU time by running that binding as late as possible.
In most scenario that’s good, sometimes it’s not.

Tried to fix CM, tried a few manual methods to refresh the binding, but failed.
So I’ve implemented a workaround.
Very limited, only supports small subset of Caliburn's binding functionality I use with my menu items. But it works for my app and might be useful to someone else.
 

		// Same as MenuItem.RaiseEvent, but plays nicely with Caliburn Micro-attached handlers.
		static void simulateClick( this MenuItem mi )
		{
			// Handle manual message attach, like cal:Message.Attach="[Event Click] = [Action actOpen]"
			string triggerText = Message.GetAttach( mi );
			do
			{
				if( triggerText.isEmpty() ) break;

				// Unfortunately, CM's built-in method, Parser.Parse, returns array or TriggerBase objects that are impossible to trigger programmatically.
				// That's why we have to use own method here, that only handles small subset of that message attach syntax.
				string triggerDetail = triggerText.Replace( "[", string.Empty )
					.Replace( "]", string.Empty )
					.Replace( "Event", string.Empty )
					.Trim();

				string[] arr = triggerDetail.Split( new char[ 1 ] { ' ' }, StringSplitOptions.RemoveEmptyEntries );
				if( arr.Length < 2 ) break;
				if( arr[ 0 ].notEqual( "Click" ) )  // Shortcut for !String.Equals( x, y, StringComparison.OrdinalIgnoreCase );
					break;

				string methodName = arr.Last();
				Caliburn.Micro.Action.Invoke( mi.DataContext, methodName, mi );
			}
			while( false );

			// Handle conventions, like x:Name="actOpen" causing actOpen method to invoke when clicked.
			string name = mi.Name;
			if( !String.IsNullOrEmpty( name ) )
			{
				Caliburn.Micro.Action.Invoke( mi.DataContext, name, mi );
			}
		}

**Comment by nigel-sampson** [comment]
Thanks for the information and the workaround, will look into it soon.

**Comment by nigel-sampson** [comment]
You're right in Caliburn.Micro deferring the binding to after the loading of the element.

Another possible work around may be doing something that triggers the `Loaded` event of the menu items.

I just tried switching over to 

``` xml
<MenuItem Header="_Test" x:Name="Test" cal:Action.Target="{Binding child}" cal:Message.Attach="Test" />
```

`Action.Target` doesn't have the view Loaded deferral that `Bind.Model` does, yet still seeing the same result. So the platform itself includes some laziness here too.

**Comment by nigel-sampson** [comment]
Did you come to a solution?

**Comment by Const-me** [comment]
Only my very limited workaround I've posted above.

Don’t you think it would be nice to expose some generic method to programmatically invoke caliburn-attached handlers?
Not only it’s helpful for my scenario (which is application-global hotkeys defined in the menu’s XAML), also stuff like automated testing and accessibility.

**Comment by nigel-sampson** [comment]
Potentially, ideally for automation you'd automate the UI layer directly. Though that's normally for tests rather than in the app directly.

For your work around you could use reflection to trigger the `TriggerActions`.

I wonder if there's a different way to architect this so that you don't need to use the menus directly. Having some tree of command models that get bound to the menu can be used directly when there's a keyboard shortcut. You get the same affect that the keyboard shortcut is only defined in one place but in a hard to use UI element.

**Comment by Const-me** [comment]
Reflection breaks type safety, i.e. the compiler stops checking those method names and parameter types. If the implementation will change, the exception will only happen in runtime. I’d rather want such CM change to break my build.

Even if I will use reflection, my own implementation is still limited compared to what’s possible inside CM. Too fragile. If you’ll slightly change the mechanism how CM maps events to VM’s method, my Parser.Parse + reflection code will fail.

The WYSIWYG designer (Expression Blend) will not edit my custom tree of command models. It edits menus just fine, and I’d like to keep using it.

**Comment by nigel-sampson** [comment]
Having a tree of command models means you define that in code and bind it the menu for auto generation of the menu structure.

After some more thought this would be my recommended approach.

**Comment by Const-me** [comment]
Using Blend instead of C# editor (a) saves time: you open MyView.xaml, immediately see that menu, can select items with mouse, can edit them with nice property editor GUI (b) allows non-developers to edit menus and change those hotkeys (c) is generally safer because XAML only has data but not code.

Just for those hotkeys you recommend to drop MS Blend for menus, and instead define that whole UI programmatically in C# code?

With your recommended approach, a previously trivial GUI change, like adjust font or color, will require some non-trivial code modifications.

**Comment by nigel-sampson** [comment]
Adjusting things like font / colour or anything UI related would still be done via Blend.

**Comment by Const-me** [comment]
Then I don’t exactly understand your recommended approach.

You either define those menu items in XAML — that’s what I’m doing, but ideally, I need to be able to programmatically invoke CM-attached handlers, and I can’t reliably do that now.

Or I can define items in code — that’s what I thought you recommend.

You can also define them in XAML but handle hotkeys separately in code.
If yes, the problem with this, you’ll have to specify the same hotkeys twice: in XAML in InputGestureText attribute (because menu items display hotkeys so user can see them) and in C# (in the code that processes those hotkeys). Very likely, as you work on the software, the two will go out of sync, and then users will see “Test: Ctrl+T” in the menu but Ctrl+T wont work.

Or you can use data binding for items. Hierarchical data templates aren’t exactly simple to implement. Also those items can be different: checkboxes/radios, different fonts/colors for different items, so the item model class will be too complex, and/or you might need data template selector for those — too much complexity for relatively simple problem.

Or you mean something else?

**Comment by nigel-sampson** [comment]
The last approach, define a structure of command models in C# and bind it to the menu. These can define the keyboard shortcuts and are used by the data templates.

Intercept key presses as you currently do, but instead of looking through the menu for the right menu item look through the tree of commands and execute it there.
