### ISSUE TITLE
Upgrading caliburn micro 1.5.2 to 3.0

### ISSUE THREAD

**Issue by vijayakl** [Caliburn-Micro/Caliburn.Micro#325]
The type 'Caliburn.Micro.PropertyChangedBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Caliburn.Micro, Version=1.5.2.0, Culture=neutral, PublicKeyToken=null'.	 

Error	314	The type 'Caliburn.Micro.BindableCollection`1<T0>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Caliburn.Micro, Version=1.5.2.0, Culture=neutral, PublicKeyToken=null'.	c:\X2Rmdc_win10 - caliburn\Energy.Cgi.Com.Fdc.Mobility.Wpf\Energy.Cgi.Com.Fdc.Mobility.Wpf\ViewModels\SearchViewModel.cs	60	58	Energy.Cgi.Com.Fdc.Mobility.WinRT

Hi, I am encountering above error after making all the relevant changes as per the document. Not sure why it thinks of 1.5.2 after upgrading to 3.0.  I have upgraded through nuget.

**Comment by godrose** [comment]
It looks like you have some old references. Try to search for the exact
version in the packages.config file or remove and add the references
manually.

**Comment by vijayakl** [comment]
I had removed all the references.

**Comment by nigel-sampson** [comment]
It looks like a reference potentially in another library is still hanging around. Not sure I can add much to what @godrose has already said.

**Comment by nigel-sampson** [comment]
Closing as no further information provided.
