### ISSUE TITLE
Caliburn.Micro Visual Studio Project Templates

### ISSUE THREAD

**Issue by Noemata** [Caliburn-Micro/Caliburn.Micro#328]
I will be releasing a Visual Studio project template pack for Caliburn.Micro that targets a range of UWP development categories.  I need some beta testers and was wondering how to best get the word out?

The project template pack consists of:

Blank App
Grid App
Hub App
SplitVIew App
Pivot App
Win2D App

Each app template features a full complement of support modules for things like Dialogs, utility extensions, converters, etc.

The plugin will be released as "buy me a beer" ware.  Free, with a "buy me a beer" button to support further development/enhancement.

Suggestions for getting the word out can be made by contacting me through the GitHub ID used for this message.

**Comment by nigel-sampson** [comment]
Excellent, I'd be happy to take a look and make some suggestions.

It's something I've been considering as well, more of a starter Blank Apps for each of the different platforms.

Once released will mention it on the website.

**Comment by Noemata** [comment]
Sent you an email to your nigel....pson@compile... address regarding uploading content to somewhere.

Please have a look at the email so we can make arrangements.

**Comment by nigel-sampson** [comment]
Closing as taken offline.
