### ISSUE TITLE
Is there any way to call method on control from ViewModel?

### ISSUE THREAD

**Issue by AnderssonPeter** [Caliburn-Micro/Caliburn.Micro#329]
One way would be to bind a event to the control method?

But is there support for this kind of binding and how would I go about to do it?

I'm using `Hardcodet.Wpf.TaskbarNotification` and its `TaskbarIcon` has the following method `public void ShowBalloonTip(string title, string message, BalloonIcon symbol)` if I define a event with the same arguments I would like to call the method on the control when I raise the event.

Any idea how to solve this?

**Comment by kdbcinco** [comment]
Assuming your ViewModel extends a class that implements ViewAware and that your control is named, I think you can use GetView() to get the view and call the ShowBalloonTip() method of TaskbarIcon. I'm not quite sure if it's the right way to go though.

**Comment by AnderssonPeter** [comment]
@kdbcinco yes that would work but it would also be a bad solution as it would go against the mvvm pattern. (the view and ViewModel should be decoupled)

**Comment by nigel-sampson** [comment]
There's quite a few different ways you can do this, all are a trade off in terms of effort, *purity* of MVVM and testability etc.

The *pure* way is something like what you originally described @AnderssonPeter. Your view model can expose an event, the view in it's `Loaded` event can subscribe to the event and call the method. During `Unloaded` it should then unsubscribe. The view model can be accessed via the `DataContext` on the view. This way means the view model has no dependence on the view model.

At the other end of the spectrum is the method talked about by @kdbcinco using the `GetView` method on the view model and find the control to call the method. As mentioned by everyone this tightly couples the view and view model and makes the view model a pain in the ass to test.

An approach I've used before is something in the middle, your view can implement an interface. The view model can cast the `GetView` result to the interface and call methods on that.

This means in testing you can inject a stub view.

**Comment by AnderssonPeter** [comment]
Incase anyone is interested in doing the same thing I did the following:
I created a CustomBehavior that mapped together the event with the Method, now this is not 100% perfect as you need to match with the exact same parameter types and in my case this results in some dependency of the TaskbarNotification type.

So you just write 
```
<tb:TaskbarIcon>
    <i:Interaction.Behaviors>
        <ex:BindEventBehavior EventName="ShowBallonTip" MethodName="ShowBalloonTip" />
    </i:Interaction.Behaviors>
    .....
</tb:TaskbarIcon>
```
And it automatically Binds the Event `ShowBallonTip` in your view with the method `ShowBalloonTip` on the `TaskbarIcon`.

BindEventBehavior: (this is VB.net but it should be easy to convert to C# if needed)
```
Public Class BindEventBehavior
    Inherits Behavior(Of FrameworkElement)

    Private Shared mLogger As Logger = LogManager.GetCurrentClassLogger()
    Private mDataContext As Object
    Private mEventInfo As EventInfo
    Private mHandler As [Delegate]

    Public Property EventName As String

    Public Property MethodName As String

    Private Sub UnbindEvent()
        mLogger.Trace($"Unbinding {EventName} to {MethodName}")
        If (mEventInfo IsNot Nothing AndAlso mHandler IsNot Nothing AndAlso mDataContext IsNot Nothing) Then
            mEventInfo.RemoveEventHandler(mDataContext, mHandler)
        End If
        mHandler = Nothing
        mEventInfo = Nothing
        mDataContext = Nothing
    End Sub

    Private Sub BindEvent()
        mLogger.Trace($"Binding {EventName} to {MethodName}")
        mDataContext = AssociatedObject.DataContext
        If (mDataContext Is Nothing) Then
            mLogger.Warn("DataContext is nothing!")
            Return
        End If
        Dim dataContextType As Type = mDataContext.GetType()
        mEventInfo = dataContextType.GetEvent(EventName)
        If (mEventInfo Is Nothing) Then
            mLogger.Warn("Failed to bind to event, as it was not found!")
            Return
        End If
        Dim invokeMethodInfo As MethodInfo = mEventInfo.EventHandlerType.GetMethod("Invoke")
        Dim parameters As Type() = invokeMethodInfo.GetParameters().Select(Function(p) p.ParameterType).ToArray()
        Dim methodInfo As MethodInfo = AssociatedObject.GetType().GetMethod(MethodName, parameters)
        If (methodInfo Is Nothing) Then
            mLogger.Warn("Failed to bind to event, method not found!")
            Return
        End If
        mHandler = [Delegate].CreateDelegate(mEventInfo.EventHandlerType, AssociatedObject, methodInfo)
        mEventInfo.AddEventHandler(mDataContext, mHandler)
    End Sub

    Protected Overrides Sub OnAttached()
        mLogger.Trace("OnAttached")
        AddHandler AssociatedObject.DataContextChanged, AddressOf AssociatedObject_DataContextChanged
        MyBase.OnAttached()
    End Sub

    Private Sub AssociatedObject_DataContextChanged(sender As Object, e As DependencyPropertyChangedEventArgs)
        UnbindEvent()
        BindEvent()
    End Sub

    Protected Overrides Sub OnChanged()
        mLogger.Trace("OnChanged")
        RemoveHandler AssociatedObject.DataContextChanged, AddressOf AssociatedObject_DataContextChanged
        AddHandler AssociatedObject.DataContextChanged, AddressOf AssociatedObject_DataContextChanged
        MyBase.OnChanged()
    End Sub

    Protected Overrides Sub OnDetaching()
        mLogger.Trace("OnDetaching")
        RemoveHandler AssociatedObject.DataContextChanged, AddressOf AssociatedObject_DataContextChanged
        MyBase.OnDetaching()
    End Sub

End Class
```

I prefer to have a reusable `Behavior` instead of repeating code in my view.
Just a note I'm not 100% sure there are no memory leaks as this is the first time I subscribe to a event via reflection so use with care!
