### ISSUE TITLE
Is it possible to use any other types of Pages apart from NavigationPage in Xamarin Forms

### ISSUE THREAD

**Issue by fenix2222** [Caliburn-Micro/Caliburn.Micro#330]
Hi,

As per sample project I can setup navigation page as a atartup page in Xamarin forms
```
        public App(SimpleContainer container)
        {
            this.container = container;

            container
                .PerRequest<LoginViewModel>()
                .PerRequest<FeaturesViewModel>();

            Initialize();

            DisplayRootView<LoginView>();
        }

        protected override void PrepareViewFirst(NavigationPage navigationPage)
        {
            container.Instance<INavigationService>(new NavigationPageAdapter(navigationPage));
        }
```

But what if my loginview is not a NavigationPage, what if I just want to show ContentPage for login screen or CarouselPage (i.e. no navigation bar) as my first page. Is it possible? Can find any documentation, PrepareViewFirst(NavigationPage navigationPage) assumes NavigationPage

**Comment by nigel-sampson** [comment]
It definitely is possible, using `DisplayRootView` is "view first" which means the framework expects the flow of the application to be done via a navigation page. If you don't want to do "view first" then the approach is "view model first" where you're responsible for what the root window is and how other screens are displayed. 

You can trigger this mode by using `DisplayRootViewFor<T>` where T is the view model you want to start with.

**Comment by fenix2222** [comment]
Do I still need to override PrepareViewFirst? If not, can I still use navigation service later on. So my scenario is: first show login page, which is a standalone page without any navigation bars. Once user is logged in, then I want navigation pages and use navigation service from Caliburn

**Comment by nigel-sampson** [comment]
If you do you won't need to override `PrepareViewFirst` because it won't be called.

You won't have access to the navigation service as it's simply a wrapper around that navigation page.

However if later in the app you need to set all this up you can set the root window content to the be a navigation page and setup the navigation service then.
