### ISSUE TITLE
The issue with static IOC

### ISSUE THREAD

**Issue by rohits79** [Caliburn-Micro/Caliburn.Micro#331]
[IoC.cs](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro/IoC.cs) defines GetInstance and GetAllInstances as type static. 

I use Prism primarily, and required to load multiple instance of the same module with in the same app/process-space. In the module I author (which uses CM), I have defined custom type resolution in the bootstrapper via GetInstance and GetAllInstance, but as these methods are static, the last module upon instantiation overwrites the first module's IOC registration.

I've asked this on [Stackoverflow](http://stackoverflow.com/questions/18743899/dealing-with-caliburn-micros-static-ioc), and the workaround though works. is bit hacky, and won't be acceptable in an enterprise application. I know this is going to be a breaking change but it would be better if the framework could support a fix out of the box so multiple instances of CM module can be loaded without overwriting internal IOC type registration.

```
    /// <summary>
    /// Gets an instance by type and key.
    /// </summary>
    public static Func<Type, string, object> GetInstance = (service, key) => { throw new InvalidOperationException("IoC is not initialized."); };

    /// <summary>
    /// Gets all instances of a particular type.
    /// </summary>
    public static Func<Type, IEnumerable<object>> GetAllInstances = service => { throw new InvalidOperationException("IoC is not initialized."); };
```

**Comment by nigel-sampson** [comment]
Ok, so just to clarify.

1. You have an application with multiple bootstrappers.
2. They're all initialized in the application.
3. Each overrides `IoC.GetInstance` to use their specific container.
4. This gives you a last initialized wins scenario where requests to `IoC` go.

Was the code in your post supposed to be a suggested fix? I couldn't find a difference between it and what's currently deployed.

**Comment by rohits79** [comment]
@nigel-sampson 

- Yes point 1-4 is right
- The code is for reference only (so others who are not aware of it can understand)
- I am not suggesting a fix in any way, I am highlighting a shortcoming in the current implementation. I can understand a fix will be a breaking change and would entail a thorough review if this going to be fixed anytime.

**Comment by nigel-sampson** [comment]
Ok, thanks.

There's been a few issues lately around apps using multiple bootstrappers. I don't believe it was ever thought about during initial conception.

In your scenario have you already (before 1.) reconfigured `IoC.GetInstance` to something that's an aggregate over all the applications?

A low impact change might be having the bootstrapper check to see if it's already been changed from the default and if it has leave it alone.

There may also need to be some impacts of multiple bootstrappers not covered here.

**Comment by rohits79** [comment]
As IOC.GetInstance registration in module 2 overwrites the registration in module 1, module 1 gets corrupted with state info from module 2's DI. 

I think CM does not play so well with the module concept, take another instance of EventAggregator, it is a pub sub bus, when i want to send message from one VM to another VM but only within one module, I can't do that. I have to tag all messages with sender's info (GUID) so module 1 and module 2 do not cross talk, react and corrupt.

**Comment by nigel-sampson** [comment]
I assume in your multi-module app you're directly instantiating the bootstrapper in order to initialize it? Thinking of some possible ways to use child containers to help with things like `EventAggregator`.

You're right, I don't think it was considered (before my time) in depth.

It may be a better idea to split your configuration out from the bootstrappers so you only need to initialize it within the single use application and not when used within a module based application.
