### ISSUE TITLE
How to config Caliburn.Micro to Xamarin.Forms?

### ISSUE THREAD

**Issue by heyixiaoran** [Caliburn-Micro/Caliburn.Micro#332]
Xamarin.Forms already updated to 2.2. So I installed Caliburn.Micro to Xamarin.Forms . I found a demo in samples. I installed Caliburn.Micro and Caliburn.Micro.Xamarin.Forms in NuGet package manager. But I found already no Caliburn.Micro.Platform.Core.dll. I try to install Caliburn.Micro.Core . It's failed. I don't know how to config Caliburn.Micro to Xamarin.Forms . And  it's already update to UWP in VS2015 Update 2 . Can you add a new solution to samples to show how to config Caliburn.Micro to Xamarin.Forms( Droid, IOS, UWP ) ?

software envirment: VS2015 Update 2 , Xamarin 4.0.4.4,  Android SDK 23

**Comment by nigel-sampson** [comment]
I've tested working in projects with a more up to date version of Xamarin.Forms with no problems.

Can you clarify what problems you're having with the sample at https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/samples/Hello.Forms ?

**Comment by shaunmarx** [comment]
I hope you don't mind me chiming in here, but after more or less trying exactly what @heyixiaoran suggested I got the same results. If you get the samples in isolation and try install the associated Caliburn NuGet packages, then things still fail to compile. It seems to require the 'Caliburn.Micro.Platform` and `Caliburn.Micro.Platform.Core` assemblies which I am assuming there isn't a NuGet package for yet? The samples seem to require you to compile Caliburn from source to get those or maybe I have missed something...

**Comment by nigel-sampson** [comment]
Ok thanks for the clarifications. I'm currently working on new samples / documentation so I'll make this more clear. 

For now:
- Install the package `Caliburn.Micro` into to the platform projects (Droid, iOS, UWP etc).
- Install the package `Calburn.Micro.Xamarin.Forms` into the platform projects and any PCL's that will have view models in them.

**Comment by shaunmarx** [comment]
Thanks for the clarification @nigel-sampson. I think this was more of an issue in the samples. Installing the NuGet packages in those didn't fix the references as it simply kept pointing to the parent solution's output folders. Probably a bad assumption on my part thinking NuGet would update those references to the Package folder. All good though and thanks for all your efforts on the framework.  :+1:

**Comment by nigel-sampson** [comment]
No worries, the problem is the samples tend to have two functions. If you're using the nuget packages you'll definitely need to remove the references to the assemblies first.

1. A sample to show how things work, they should use the nuget packages in order to properly demo this.
2. A test bed for changes been made to the library. Here they should reference the project output.

The new samples being built (preview on the `samples` branch) has explicit setup samples for each platform. Given this discussion I'll update these to use the packages.

**Comment by heyixiaoran** [comment]
Hi @nigel-sampson  I just down the code .Then open the sample named Hello.Forms. Set WinPhone project to startup project. F5. Two errors come.

1. Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'FormsApplication' is defined in an assembly that is not referenced. You must add a reference to assembly 'Caliburn.Micro.Platform.Xamarin.Forms, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null'.	Hello.Forms.WinPhone	C:\Users\heyix\Desktop\Caliburn.Micro-master\samples\Hello.Forms\Hello.Forms\Hello.Forms.WinPhone\Views\MainView.xaml.cs	16	Active

2. Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'Hello.Forms.App' to 'Xamarin.Forms.Application'	Hello.Forms.WinPhone	C:\Users\heyix\Desktop\Caliburn.Micro-master\samples\Hello.Forms\Hello.Forms\Hello.Forms.WinPhone\Views\MainView.xaml.cs	16	Active

And I saw the Caliburn.Micro.Platform.Core in the portable project is useless reference and  Caliburn.Micro.Platform.Xamarin.Forms in the Windows Phone 8.0 project is useless reference.Droid and IOS are also have some errors. Yes. I agree with @shaunmarx . I found the dll about Caliburn are all useless .So I install with Nuget.

Actually .I installed VS2015 Update 2 and Xamarin 4.0.4.4. So After I create a new solution.There're five projects. Protabe, Droid, IOS, UWP, Windows 8.1 and WinPhone 8.0. So I want to use Droid , IOS, UWP. Windows 8.1 and WinPhone 8.0 will not use in my  plan.  The sample is base on 2.0. Now it's 3.0. So If a new sample can update . It's the best. Wait for your sample. Thanks a lot.

**Comment by nigel-sampson** [comment]
As stated above the samples reference the build output of the main project, once the main project is built all the samples build. We'll update some of the samples (particularly the getting started ones) to use the nuget packages and for the others we'll update the docs.
