### ISSUE TITLE
Using Caliburn.Micro to author VSIX plugins

### ISSUE THREAD

**Issue by Noemata** [Caliburn-Micro/Caliburn.Micro#333]
I have developed an approach for using Caliburn.Micro when creating WPF based VSIX plugins.  Is anyone else interested in such an animal?  I may consider polishing this up and making it generally available if there is enough interest.

**Comment by nigel-sampson** [comment]
Closing out as not an actionable issue.

**Comment by malus91** [comment]
@Noemata Whats the approach to do this ? I am trying to use caliburn micro for a VSIX component. 
any pointers are much appreciated.
