### ISSUE TITLE
Navigation service not reacting to the XBox One back button

### ISSUE THREAD

**Issue by igorkulman** [Caliburn-Micro/Caliburn.Micro#334]
When I deploy a Caliburn app to XBox One and press the back button on the XBox controller (red B) navigation service does not try to navigate back as it should.

A workaround is listening to `Window.Current.CoreWindow.KeyUp` for `VirtualKey.GamepadB` but I think it should be a part of the navigation service for UWP so it just works on the XBox One (like the Back button on Phone just works)

**Comment by nigel-sampson** [comment]
Not sure it's something that should be baked into the navigation service, not all apps want `B` as a back button. The Hardware back button however does make sense.

**Comment by nigel-sampson** [comment]
Just watched [Building Great Universal Windows Platform (UWP) Apps for Xbox](https://developer.microsoft.com/en-us/windows/projects/events/build2016/building-great-universal-windows-platform-uwp-apps-for-xbox) which recommends listening for `SystemNavigationManager.BackRequested` that the navigation service already does.

**Comment by igorkulman** [comment]
I have seen the video and I also thought it would work because of `SystemNavigationManager.BackRequested`. But it does not, at least in the current SDK.

**Comment by nigel-sampson** [comment]
Yeah it looked like it was something for the Anniversary Update for XBox.
