### ISSUE TITLE
Xamarin ToolbarItem and Message.attach does not seems to work

### ISSUE THREAD

**Issue by lploumen** [Caliburn-Micro/Caliburn.Micro#336]
Hi,
I'm using Xamarin Forms on Windows Phone 8.1 Silverlight.
I tried to have a method called on my viewmodel when the user click a toolbar item but I cannot make it work.
I also try the commented line.
Is it supposed to work ?

```C#
 <ContentPage.ToolbarItems>
    <!--<ToolbarItem Text="Menukk1" forms:Message.Attach="ToolbarTest">-->
    <ToolbarItem Text="Menukk1" forms:Message.Attach="[Event Clicked] = [ToolbarTest()]">
      <ToolbarItem.Icon>
        <OnPlatform x:TypeArguments="FileImageSource" WinPhone="Assets/appbar.location.circle.png" />
      </ToolbarItem.Icon>
    </ToolbarItem>
  </ContentPage.ToolbarItems>
```

**Comment by nigel-sampson** [comment]
From the top of my head it's because `ToolBarItem` isn't an element that supports Xamarin.Forms version of Behaviors.

If we wanted to support it explicitly we'd need to do something like what was done for Windows Phone 7/8 which was creating our own custom `ToolbarItem`

**Comment by nigel-sampson** [comment]
I just dug into this some more to make sure I had the types right.

While `EventTrigger<T>` has a generic restriction to just `BindableObject`, the `Triggers` property is on `VisualElement`.

Since `ToolbarItem` doesn't inherit from `VisualElement` we can't attach our triggers to it.

**Comment by vlesierse** [comment]
@nigel-sampson What is the proposed solution to make this work? Create your own ToolbarItem with a Button?

**Comment by nigel-sampson** [comment]
I'd probably just fall back to an event handler. There's an example of this in the partially complete new samples [ConductorView.xaml](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/samples/samples/features/Features.Forms/Features.Forms/Views/ConductorView.xaml) and [ConductorView,xaml.cs](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/samples/samples/features/Features.Forms/Features.Forms/Views/ConductorView.xaml.cs), just excuse the weird formatting.

**Comment by vlesierse** [comment]
That works great, thnx!

**Comment by lploumen** [comment]
I would probably better use the Command property of the ToolbarItem. This way, the ToolbarItem can be disabled if CanExecute returns false.

**Comment by nigel-sampson** [comment]
Yup binding to `Command` would work just as well.
