### ISSUE TITLE
Removing Pivot item when scrollable fails.

### ISSUE THREAD

**Issue by Noemata** [Caliburn-Micro/Caliburn.Micro#337]
I have a Pivot control with the following xaml setup:

        <Pivot x:Name="Items" x:FieldModifier="public" >
            <Pivot.HeaderTemplate>
                <DataTemplate>
                    <StackPanel cm:Bind.Model="{Binding}" Orientation="Horizontal">
                        <TextBlock x:Name="DisplayName" />
                        <Button VerticalAlignment="Top" x:Name="Close" FontSize="5" FontFamily="{ThemeResource SymbolThemeFontFamily}" Content="&#xE106;" />
                    </StackPanel>
                </DataTemplate>
            </Pivot.HeaderTemplate>
            <Pivot.ItemTemplate>
                <DataTemplate>
                    <ContentControl cm:View.Model="{Binding}"/>
                </DataTemplate>
            </Pivot.ItemTemplate>
        </Pivot>

In the ShellVIew, I have a message handler as follows:

        public void Handle(CloseTabMessage message)
        {
            int i = Items.IndexOf(message.Tab);
            Items.RemoveAt(i);
        }

Everything works well while the Pivot control does not show its scroll buttons.  I can add and remove items at will.

As soon as the Pivot control needs to show its scroll buttons, removing items fails.  It's as if the Pivot control loses sync with itself when an item needs to be scrolled into view after another visible item has been removed.

**Comment by nigel-sampson** [comment]
Which platform is this on?

**Comment by Noemata** [comment]
Sorry Nigel, should have mentioned that.  It's Win 10 UWP.  You can get the same result with your code by doing as follows (comment out flyout button with simplified button handler):

                        <Button VerticalAlignment="Top" x:Name="Close" FontSize="5" FontFamily="{ThemeResource SymbolThemeFontFamily}" Content="&#xE106;" />
                        

I used your code as the reference for how to do this, but it has the same problem.

**Comment by nigel-sampson** [comment]
Given the behavior it appears to be an issue with the `Pivot` control, can you reproduce it without involving CM?

**Comment by Noemata** [comment]
I'm inclined to agree.  I was hoping this was a known issue with a known workaround.  It's a drag being one of the first to discover such things.

**Comment by nigel-sampson** [comment]
Not a known issue. However one weird thing I remember from my Windows 8 days was that some collections had issues when the last item in the collection was removed. Don't suppose this is the case for you?

**Comment by Noemata** [comment]
Moving the close action into the ShellView code behind resolves this problem, so unfortunately, this is a Caliburn.Micro bug.

My pivot code is as follows:

        <Pivot x:Name="Items" x:FieldModifier="public">
            <Pivot.HeaderTemplate>
                <DataTemplate>
                    <StackPanel x:Name="StackContainer" cm:Bind.Model="{Binding}" Orientation="Horizontal">
                        <TextBlock x:Name="DisplayName" />
                        <Button VerticalAlignment="Top" Click="Button_Click" FontSize="5" FontFamily="{ThemeResource SymbolThemeFontFamily}" Content="&#xE106;" />
                    </StackPanel>
                </DataTemplate>
            </Pivot.HeaderTemplate>
            <Pivot.ItemTemplate>
                <DataTemplate>
                    <ContentControl cm:View.Model="{Binding}"/>
                </DataTemplate>
            </Pivot.ItemTemplate>
        </Pivot>

The code behind for the ShellView has this Click handler:

        private void Button_Click(object sender, Windows.UI.Xaml.RoutedEventArgs e)
        {
            if (sender != null && this.DataContext != null)
            {
                ShellViewModel svm = this.DataContext as ShellViewModel;

                if (svm != null)
                {
                    int i = Items.SelectedIndex;

                    svm.Close(i);
                }
            }
        }

And in the ShellViewModel, I have:

        public void Close(int i)
        {
            //int i = _view.Items.SelectedIndex;

            Items.RemoveAt(i);
        }

So it's not a "weird thing" with Win 10.  The scroll behavior is a bit odd on the delete depending on what item you remove, but it does work as expected.

**Comment by nigel-sampson** [comment]
In your code behind version are you just removing the Item from the Pivot?

I suspect it's a data binding issue in the Pivot, not directly related to CM but can't test at the moment.

**Comment by Noemata** [comment]
A slight adjustment to my previous message above given the SelectedIndex does not correspond to the index of items in the Items list as items are removed.  The code above works, but happens to remove the wrong item.

The ShellViewModel code should have been:

        public void Close(int i)
        {
            PivotItem pi = _view.Items.ContainerFromIndex(i) as PivotItem;

            DocumentViewModel dvm = pi.DataContext as DocumentViewModel;

            if (dvm != null)
            {
                int idvm = Items.IndexOf(dvm);

                Items.RemoveAt(idvm);
            }
        }

Though I'm still seeing some odd behavior when the scroll buttons are on during deletes.  I use the RemoveAt(idvm) approach to highlight that idvm != SelectedIndex != i.

**Comment by Noemata** [comment]
Doh!!  The ShellView code behind should be this:

        private void Button_Click(object sender, Windows.UI.Xaml.RoutedEventArgs e)
        {
            if (sender != null && this.DataContext != null)
            {
                ShellViewModel svm = this.DataContext as ShellViewModel;

                Button btn = e.OriginalSource as Button;

                object obj = btn.DataContext;

                if (svm != null)
                {
                    int i = Items.SelectedIndex;

                    svm.Close(obj);
                }
            }
        }

And the ShellViewModel Close should be this:

        public void Close(object obj)
        {
            DocumentViewModel dvm = obj as DocumentViewModel;

            if (dvm != null)
            {
                int idvm = Items.IndexOf(dvm);

                if (idvm != _view.Items.SelectedIndex) Debug.WriteLine("Diff index!");

                Items.RemoveAt(idvm);
            }
        }

And the odd behavior is gone.  So now we need to figure out what's wrong on the Caliburn.Micro side.

**Comment by nigel-sampson** [comment]
Ok, so what are the differences? The initial code is being invoked the event aggregator, the later code directly by an event handler. Both remove the item from the bound collection by index.

How are you publishing the message on the event aggregator?

If you can post a link to repro of this I can potentially look at it tonight.

**Comment by nigel-sampson** [comment]
I've had an experiment with the sample that was emailed through to me, the problem appears to be that when the Pivot gets large enough a problem occurs where the bound method doesn't get called when the button is clicked. The click event handler is working correctly however.

Internally a button that looks like this:
``` xml
<Button cm:Message.Attach="[Event Click] = [Close($dataContext)]"  />
```
gets transformed into something like
``` xml
<Button>
  <i:Interaction.Behaviors>
    <ic:EventTriggerBehavior EventName="Click">
      <cm:ActionMessage MethodName="Close">
        <cm:Parameter Value="{Binding}" />
      </cm:ActionMessage>
    </ic:EventTriggerBehavior>
  </i:Interaction.Behaviors>
</Button>
```
which didn't work as well. At this point my suspicion is that the `EventTriggerBehavior` isn't firing correctly.

Switching to the following also didn't work.
``` xml
<Button>
  <i:Interaction.Behaviors>
    <ic:EventTriggerBehavior EventName="Click">
      <cm:ActionMessage MethodName="Close">
        <ic:CallMethodAction MethodName="CloseFirst" TargetObject="{Binding ElementName=LayoutRoot, Path=DataContext}" />
      </cm:ActionMessage>
    </ic:EventTriggerBehavior>
  </i:Interaction.Behaviors>
</Button>
```

From this it appears that when the `Pivot` get's big enough something is causing the `EventTriggerBehavior` to detach and then not fire when the button is clicked. 

Given this can be reproduced with the above code I'd recommend putting together a repro that doesn't involve Caliburn.Micro at all (to not complicate root causes) and log it at [Microsoft/XamlBehaviors](https://github.com/Microsoft/XamlBehaviors).

Let me know if you need some help creating that repro.

**Comment by Noemata** [comment]
Hi Nigel,

Nice bit of sleuthing.  Thanks for pinning this down.  From what I was 
observing it looked like there's something different about how the 
visual tree gets processed when an item is about to become visible.  If 
you have just one item outside the visible area, deleting any visible 
item will trip the problem.  From then on, bindings for all current 
pivot items are broken.  Newly added pivot items work, but you can trip 
the problem for those by repeating the issue that causes it.



In the above case, deleting "Document-1" trips the problem since 
"Document-3" is out of view.  "Document-1" will get removed, but after 
that bindings for all the rest are broken.  I should have written this 
up better when I sent you the code.  I was quite tired at that point, 
was 2am at my end.

I'm not surprised this is likely to be a XAML behaviors issue.

I'm heading to Croatia tomorrow for a vacation.  I'm unlikely to find 
any time for this today as I need to get myself ready.  I was hoping to 
get the Pivot template project working before my departure so I could 
finally publish the Caliburn.Micro Templates VSIX.  I have a feeling 
I'll be doing that while on vacation.  I would appreciate you pushing on 
Microsoft for this.  You'll have more sway than I.  I suspect if you 
mention that you're the coordinator of Caliburn.Micro, they will take 
notice.  I think Caliburn.Micro has always been one of the main 
consumers of Xaml behaviors.  Certainly the most creative user of them.

Thanks again,

Mario
