### ISSUE TITLE
WinPhone 8.1 project with Xamarin.Forms and Caliburn.Micro failes to create view

### ISSUE THREAD

**Issue by nologinatgit** [Caliburn-Micro/Caliburn.Micro#343]
I have a Xamarin.Forms project with a WinPhone 8.1 project that uses Caliburn.Micro.

When I try to run that project, I get an exception:

 

> Could not find Windows Runtime type 'Windows.Foundation'.":"Windows.Foundation

> 
>    at System.StubHelpers.WinRTTypeNameConverter.GetTypeFromWinRTTypeName(String typeName, Boolean& isPrimitive)
>    at System.StubHelpers.SystemTypeMarshaler.ConvertToManaged(TypeNameNative* pNativeType, Type& managedType)
>    at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter)
>    at Caliburn.Micro.CaliburnApplication.DisplayRootView(Type viewType, Object paramter)
>    at Caliburn.Micro.CaliburnApplication.DisplayRootView[T](Object parameter)
>    at MyProject.WinPhone.App.OnLaunched(LaunchActivatedEventArgs args)

Further details (and code) can be found [here.](http://stackoverflow.com/questions/38140198/winphone-8-1-project-with-xamarin-forms-and-caliburn-micro-failes-to-create-view)

Can you tell me what to do?

**Comment by nigel-sampson** [comment]
Can I ask why the overload of `SelectAssemblies` to return a system assembly?

This method is help provide the framework with the assemblies where your views and view models are located, I can't see a need to provide a system assembly.

From some cursory searches it looks the exception you're encountering is when something about the xaml view gets disconnected from it's codebehind.

**Comment by nologinatgit** [comment]
I added the system assembly because I thought it missed some classes that are inside the mscorlib.dll. If I remove it, I still get the same error.

Do you need a download link for the project to test it?

**Comment by nigel-sampson** [comment]
It would be best if you can link to a public GitHub repository I can look at.

I don't believe this is a Caliburn.Micro issue but most likely something to do with a miss-configured or corrupted project.

**Comment by nologinatgit** [comment]
This project is not available in GitHub, but I uploaded it to [here.](https://mab.to/nAGOkW0lY)

**Comment by nologinatgit** [comment]
It is strange (but maybe relevant) that when I run the UWP project, I get an exception at the same line:

`DisplayRootView<MainView>();`

The exception:

> Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by nigel-sampson** [comment]
It sounds like something is corrupted with that view.

To find out the part of the view causing the issue I'd remove as much as possible until it works and slowly add parts back in.

This doesn't sounds like an issue related to Caliburn.Micro.

**Comment by nologinatgit** [comment]
I have created a brand new project and added Caliburn.Micro.

The issues are the same. Does it show those issues when you run it?

I'll try to remove Caliburn.Micro and see what it does.

**Comment by nologinatgit** [comment]
It works like magic _without_ Caliburn.Micro.

So when I add CM, then something goes south.

I followed the [Hello.Forms](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/3.0.0/samples/Hello.Forms/Hello.Forms) project files and the [Working with WinRT](http://caliburnmicro.com/documentation/windows-runtime) article and also an [UWP article](http://bartwullems.blogspot.hu/2015/11/caliburnmicro-windows-10-uwp-apps.html) .

What could break my projects?

**Comment by nigel-sampson** [comment]
Your linked project above won't compile for me, but a quick glance highlights

``` csharp
LoadApplication(new PszichomotorosFejlodesXamarin.App(null));
```

Passing null in for the container, and then trying to use in the constructor of `App` will definitely be a null reference exception. That could be the underlying problem.

**Comment by nologinatgit** [comment]
Those classes are unloaded from the projects, as the UWP and WinPhone projects should use the MainView in the PCL project and not creating some custom view inside the UWP or WinPhone project.

What are the compilation errors on your side?

**Comment by nigel-sampson** [comment]
I'm talking about the one in MainPage.xaml in your UWP project.

This is a vital part of a Xamarin.Forms project and shouldn't be removed.

**Comment by nologinatgit** [comment]
Hmm, I don't quite get it.

If I create a MainView in my PCL project (and I like to be presented first), then why should I create another Page (?) int the UWP app to present...what? :)

In the WinPhone app, should I also create a Page?

**Comment by nigel-sampson** [comment]
All Xamarin.Forms apps are "hosted" in a native app for each platform. That host app also contains a host "view", for Windows that's a xaml page that inherits from `Xamarin.Forms.Platform.UWP.WindowsPage` for other platforms like Android it's an Activity.

This host page calls `LoadApplication` which starts off Xamarin.Forms in that view.  The whole thing won't work without it.

I'd suggest reading [Adding a Universal Windows Platform (UWP) App](https://developer.xamarin.com/guides/xamarin-forms/platform-features/windows/installation/universal/), especially the parts about editing MainPage.xaml.

**Comment by nologinatgit** [comment]
Well, I tried everything, I followed both the Xamarin.Forms documentation, and the Working with WinRT article.

I modified the working project into a Caliburn-based project and the WinPhone projects still throws an exception.

Sorry for the inconveniences.

Can you test this project (download [here](https://mab.to/V3FV3wr8Z))? I hope it'll get compiled, I unloaded the UWP and Windows projects (the Android project is fine).

**Comment by nologinatgit** [comment]
I figured it out.

I was using the **PCL's MainView** as the parameter for DisplayRootView and not the **_local hosting view_.**

So I modified this:

` DisplayRootView<MainView>();`

Into this:

` DisplayRootView<MainPage>();`

I guess, adding a Windows Phone 8.1 and an UWP project to the Hello.Forms sample could save lives... :)

Thanks for pointing into the right direction.

**Comment by nologinatgit** [comment]
Also very importan not to register ViewModels more than once :)
