### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by MarcoBeltramini** [Caliburn-Micro/Caliburn.Micro#344]
I have this exception when I navigate through pages in the Android project.
I'm using as reference the Hello.Forms sample.

**Comment by nigel-sampson** [comment]
It sounds like you're trying to navigate while off the UI thread.

You can use `Execute.OnUIThread` or it's overloads to dispatch callbacks to the UI thread which should help.
