### ISSUE TITLE
Conductor.ZeroOrOneActive

### ISSUE THREAD

**Issue by jongleur1983** [Caliburn-Micro/Caliburn.Micro#345]
Hi.
I tried to use Conductor<MyViewModel>.OneActive for my use case (WPF application), but I have to be able to deactivate the item (set ActiveItem to null).
This doesn't work as Conductor.OneActive doesn't deactivate all children once one has been active before.

Is there any way to get that with the existing caliburn.micro features?
If yes: How do I do it?
If no: Any interest in a Conductor.ZeroOrOneActive implementation? (I would perhaps try to contribute it).

Kind regards
jongleur1983

**Comment by jongleur1983** [comment]
Additional note: I don't know if it was my own fault in my code, but for the Conductor.OneActive it seems to be inconsistent, that the initial selected item may be NULL. 
If by design there has to be always one active item, for any non-empty Item-collection ActiveItem must be not null. This seems not to be ensured initially (but afterwards).

**Comment by mvermef** [comment]
If I remember correctly , when selected with OneActive as conductor setting it will only activate that one item. I believe children are included but it's a function of your code.  Can you post some or a sample of what you are trying to do?  The only other option is AllActive, which is more like an IDE or dashboard.  And dependent how you fill the items collection also plays into the result and what container you are using

**Comment by jongleur1983** [comment]
To be more precise in my question:
In Conductor.OneActive, should there be always exactly one ActiveItem? Or, if not: When can it happen that no item is active (and ActiveItem is null)?

IMHO there are two different consistent variants, both not yet fulfilled (if I didn't make a mistake):

- "ExactlyOneActive": Whenever Items is not empty, ActiveItem is always not-null. In that case there should be a fallback to any, e.g. the first item (which seems not to be always the case).
- "ZeroOrOneActive": It's possible to have no ActiveItem. In that case it should be possible to deactivate the ActiveItem with a result of ActiveItem == null, something that's not the case for OneActive either.

About my container:
My outer ViewModel is a Conductor.OneActive. Items is filled with a list of MyItemViewModel in OnInitialize, where MyItemViewModel inherits from Screen. The XAML view contains a Combobox (that allows the null-value) binding to Items and a MyItemView binding to ActiveItem.

Initially ActiveItem is null and the MyItemView's datacontext is null as well. 
Selecting any item in the combobox correctly updates the MyItemView to reflect the selected item.
Clearing the combobox (selecting the null-item) calls ActivateItem() with null as a parameter, with no effect as that is ignored. 
Thus it's not possible to turn back to the initial state by setting ActiveItem.

**Comment by nigel-sampson** [comment]
Obviously the scenario there the conductor has no items is one method for not having an `ActiveItem`, but I don't believe the *one* part of OneActive is ruthlessly enforced, more high lighting a difference between it and `AllActive`.

It's been a while since I've looked into this so apologies if I'm off base. If the conductor ends up with a null `ActiveItem` the behavior usually falls back the control that it's bound to (if any)

Some controls can deal with no item being active, while others will select one themselves which then updates the conductor.

**Comment by jongleur1983** [comment]
I wrote a test method now to check my claim, and I have to apologize: I was wrong.
The following test passes, so setting the active item to null does what I expected it to do, so the issue I had has to be my own and be located in my own code.

```
[Fact]
        public void ActiveChildIsNullAfterSetAsNull() {
            var conductor = new Conductor<IScreen>.Collection.OneActive();
            var conducted = new Screen();
            conductor.Items.Add(conducted);
            conductor.ActivateItem(conducted);
            Assert.Equal(conducted, conductor.ActiveItem);
            conductor.ActivateItem(null);
            Assert.Equal(null, conductor.ActiveItem);
        }
```

Sorry again for the trouble.

Thanks
jongleur

**Comment by nigel-sampson** [comment]
No worries, you can get changes from the behavior you verified with your testing when the conductor is bound to a control so I'd watch out for that.
