### ISSUE TITLE
Caliburn for UWP in Xamarin.Form

### ISSUE THREAD

**Issue by saprile** [Caliburn-Micro/Caliburn.Micro#351]
Hi,

I've downloaded the project to run the example of the caliburn on xamarin form. The example is correct but about windows project the UWP is missing. Can you add an example to configure UWP in Xamarin Forms ?

Thanks a lot

**Comment by nigel-sampson** [comment]
I don't have a sample yet for the main repository, but I have one here in my [talks](https://github.com/nigel-sampson/talks/tree/master/ndc-sydney) that will eventually make it's way to the samples.

**Comment by dhswg20077** [comment]
https://github.com/nigel-sampson/talks/tree/master/ndc-sydney
this link was invalid, is there any other samples for UWP in xamarin?

**Comment by rossvegas** [comment]
I have done up a UWP sample as part of the V4 upgrade in task #450, its not working quite yet and Nigel hasn't had time to look at it since he has been busy getting ready for NDC. Hopefully he can get some time to look at it soon.

**Comment by dhswg20077** [comment]
https://github.com/nigel-sampson/talks/tree/master/ndc-sydney-2016/NDC.Build.Forms.App.UWP

this sample is very helpful to me ,thanks
