### ISSUE TITLE
Caliburn Micro requires stickers ;)

### ISSUE THREAD

**Issue by ghuntley** [Caliburn-Micro/Caliburn.Micro#353]
https://www.stickermule.com/

**Comment by nigel-sampson** [comment]
![ddelto3voaaigt4](https://user-images.githubusercontent.com/1256017/27785925-3bdd15f0-6033-11e7-9b18-14a4bbd82987.jpg)

Come find me at NDC Sydney or any other group I'm speaking at. 😄

**Comment by ghuntley** [comment]
👍

**Comment by beachwalker** [comment]
Nice, does this exist as badge or something similar to put on a site, e.g. like "We are reactive".
... made with Caliburn.Micro ;-)

**Comment by nigel-sampson** [comment]
Not yet, but something I'll think about. the svg used for the stickers is at https://github.com/Caliburn-Micro/caliburn-micro.github.io/tree/master/design if you want to use it.
