### ISSUE TITLE
What is the suggested pattern for subscribing to messages using IEventAggregator inside view models connected to UserControl views?

### ISSUE THREAD

**Issue by nathan-alden** [Caliburn-Micro/Caliburn.Micro#354]
I have many `UserControl` views that are connected to view models that inherit from `Screen`. I'd read elsewhere that the recommended pattern for subscribing and unsubscribing to messages using `IEventAggregator` is this code:
```
protected override void OnActivate()
{
    EventAggregator.Subscribe(this);
}

protected override void OnDeactivate(bool close)
{
    EventAggregator.Unsubscribe(this);
}
```
Unfortunately, it does not seem that `OnActivate` and `OnDeactivate` are called for view models connected to `UserControl` views. I have been doing the following in the meantime, but I'd really like to call `Unsubscribe` explicitly:
```
protected override void OnViewLoaded(object view)
{
    EventAggregator.Subscribe(this);
}
```
What I want to do is subscribe to messages when the `UserControl` loads and unsubscribe when it unloads. Do you have any recommendations?

**Comment by nigel-sampson** [comment]
Having `OnActivate` and `OnDeactivate` being called depends a little on how the view (the user control) is being bound to the view model.

Are you manually setting the user controls `DataContext` the view model?

**Comment by nathan-alden** [comment]
I'm using the `<ContentControl x:Name="MyUserControlViewModelProperty"/>` method. The parent `DataContext`'s `MyUserControlViewModelProperty` is being populated in the constructor of `ParentViewModel`.

**Comment by nigel-sampson** [comment]
Excellent, so the lifecycle here for the child view models isn't being handled by the root view model.

If you're just instantiating it then it won't have lifecycle beyond the view being attached / loaded.

If you don't want your root view model to be a conductor of some sort you can use.

``` csharp
MyUserControlProperty = new MyUserControlViewModel();
MyUserControlProperty.ConductWith(this);
```

What `ConductWith` does is wire a one time activation / deactivation from the root view model to the child view model.

**Comment by nathan-alden** [comment]
Cool! I had no idea that that wiring needed to occur. Would it make sense to add this as an improvement somehow to the `<ContentControl>` architecture so that it automatically happens, or perhaps provide a way where I can opt in in the XAML somehow? Maybe an attached property on `<ContentControl>`?

Anyway, thanks for the clarification. I'll try this right away.

**Comment by nigel-sampson** [comment]
I've thought about it a few times but I'm generally of the impression that the root "conductor" manages the lifecycle of the child view models.

Sometimes this conductor inherits from `Conductor<T>` etc which makes life easier, sometimes the conductor is the navigation service so it happens automatically and other times it's just an ad-hoc arrangement like your example.

Having `View.Model` trigger the lifecycle (which is what happens under the covers in convention based binding to `ContentControl`) works for the last example but could cause problems in the others.

**Comment by nathan-alden** [comment]
Hmm, yeah, I can see how separation of concerns would be an issue. It does not make sense for the view to be orchestrating this kind of configuration.

I will stick with calling `ConductWith(this)` for now. Thanks for the advice!
