### ISSUE TITLE
DesignTime support bindings getting weird

### ISSUE THREAD

**Issue by beachwalker** [Caliburn-Micro/Caliburn.Micro#359]
I have an application that is split up in several libraries (containing views and models). However, the execution of the application is ok. This is the simple test result:

![image](https://cloud.githubusercontent.com/assets/2715897/17944288/69066c60-6a3f-11e6-965b-dd09e6856a4b.png)

This shows a Container that has a property containing another Screen that needs to be resolved at runtime.

I have added two DesignTime ViewModels (one for Child and one for Container).

```
public class DesignContainerViewModel : Screen, IContainerViewModel
{
    public DesignContainerViewModel()
    {
        this.Text = "DesignTime Container";
        this.Child = new DesignChildViewModel(); // adding another DesignTimeViewModel manually
    }

    public string Text { get; set; }

    public IScreen Child { get; set; }
}
```

When selecting the ChildView everything seems to work:

![image](https://cloud.githubusercontent.com/assets/2715897/17944439/068e2a2c-6a40-11e6-9868-9a4c537221a8.png)

When selecting the Container (with the ChildView inside):

![image](https://cloud.githubusercontent.com/assets/2715897/17944473/2cacefea-6a40-11e6-9840-db99d45d288d.png)

The DesignViewModel for the Child can't be resolved to the corresponding View. Sounds ok, cause there is no existing mapping (have to figure out how to replace "DesignTime" in namespace and "Design" in ViewModel name... however if I change the code above to contain the real model instead of the DesignTimeViewModel:

```
public class DesignContainerViewModel : Screen, IContainerViewModel
{
    public DesignContainerViewModel()
    {
        this.Text = "DesignTime Container";
        this.Child = new ChildViewModel(); // using real model in designtimeviewmodel now
    }

    public string Text { get; set; }

    public IScreen Child { get; set; }
}
```

... it looks like this:

![image](https://cloud.githubusercontent.com/assets/2715897/17944603/cc010324-6a40-11e6-8898-35b94ed838fc.png)

nice... **BUT WAIT**... there is something wrong. There is written "DesignTime Container" in both labels but there should be "DesignTime Child" in the lower one.

```
public class DesignChildViewModel : Screen, IChildViewModel
{
    private readonly string text;

    public DesignChildViewModel()
    {
        this.text = "DesignTime Child"; // not shown!?
    }

    public string Text
    {
        get
        {
            return this.text;
        }
    }
}
```

I use VS 2013 and WPF for this. This is the sample to reproduce this behavior.
[CaliburnMicroDesignTimeSupport.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/435514/CaliburnMicroDesignTimeSupport.zip)

**Comment by beachwalker** [comment]
When I change the code of the DesignTimeViewModels slightly and use OnViewAttached overrides like this:

        protected override void OnViewAttached(object view, object context)
        {
            base.OnViewAttached(view, context);
            this.Child = new ChildViewModel();
        }

... the complete Designer of VS2013 gets broken (VS app is hanging and needs to be killedin the taskmanager). Here is the changed code to reproduce this:
[CaliburnMicroDesignTimeSupport.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/435546/CaliburnMicroDesignTimeSupport.zip)

**Comment by beachwalker** [comment]
Maybe the following is more like a feature requres / improval:

I find it reasonable not using "real" ViewModels in other DesignTime ViewModels and use their DesignTime counterparts to keep dependencies cleaner. Maybe others do... Anyway, I think, it should be a default convenient mapping hat DesignTimeViewModels should be resolved to their ViewModel counterpart Views, too.
This can be by default like this:

SomeNamespace.SomeViewModel => SomeNamespace.DesignTimeSomeViewModel => SomeNamespace.SomeView
SomeNamespace.SomeViewModel => SomeNamespace.DesignTime.SomeViewModel => SomeNamespace.SomeView
SomeNamespace.SomeViewModel => SomeNamespace.DesignTime.DesignTimeSomeViewModel => SomeNamespace.SomeView

Maybe it is a good Idea to have something like ViewLocator.DesignNameTransformer.AddRule...
or DesignViewLocator.NameTransformer?

**Comment by beachwalker** [comment]
When I change the name of the Text property for the ChildViewModel (from Text to OtherText

    public interface IChildViewModel : IScreen
    {
        string OtherText { get; } // name was Text before
    }

... and updated the Binding in the ChildView

    <Grid>
            <Label Content="{Binding OtherText}"></Label>
    </Grid>

... the Label is not shown anymore. Maybe another explicit way is required to set to the right DataContext? But this seems Caliburn.Micro specific problem or not?

![image](https://cloud.githubusercontent.com/assets/2715897/17946168/75e7f78e-6a47-11e6-8939-2135805d1e8a.png)

**Comment by beachwalker** [comment]
This sample is the same as before but uses Autofac as IoC-Container. Everything else shows the same behaviour as with the examples before. This is set to have different names for the Text Property so there is no "lucky" match between parent and child property name.

[CaliburnMicroDesignTimeSupportWithAutofac.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/435615/CaliburnMicroDesignTimeSupportWithAutofac.zip)

**Comment by eogas** [comment]
I think I've run into (essentially) this same issue.  I have created a really basic reproducer here: https://github.com/eogas/CaliburnMicroDesignTimeNestedBindingBug

Basically it's just a root window that contains a child view, which itself contains another child view.  It takes a bit of building to get the XAML window to render everything, but once it's stable, this is what I see.

### ChildItemView
![image](https://cloud.githubusercontent.com/assets/143012/19351700/c9ed14cc-912a-11e6-99aa-7eb38e5f7969.png)

### ItemView
![image](https://cloud.githubusercontent.com/assets/143012/19351725/db332b7c-912a-11e6-9140-ecebfbf8e3ea.png)

### ShellView
![image](https://cloud.githubusercontent.com/assets/143012/19351740/e61b9c9a-912a-11e6-9624-e15b5793cb0b.png)


ItemView is able to render ChildItemView correctly as far as the hardcoded portions are concerned, however it doesn't render the bindings to ChildItemViewModel.  Similarly, in ShellView, we can see the hardcoded portions of ItemView, but its bindings, including the ChildItemView, are not resolved at design time.

But everything works fine at runtime:
![image](https://cloud.githubusercontent.com/assets/143012/19351852/634814c8-912b-11e6-8d18-9913aa9671c0.png)

**Comment by eogas** [comment]
Is this the same issue as #214 ?

**Comment by beachwalker** [comment]
At least it seems very similar. I had the issues with Vs2013 but Vs2015 was not yet tested by myself together with Cm. The described behavior makes it somewhat uncomfortable and difficult to build more complex applications. This is why I decided to upload the example with classes spread over different assemblies. Most Caliburn examples are somewhat simple and everything is in one single assembly... but that is not the case in most real life apps. Hope the attached example will help to find and solve the problem.

**Comment by beachwalker** [comment]
Oh, this is indeed a duplicate of a one year old bug that is still there... #214

**Comment by nigel-sampson** [comment]
The fix related to #379 should resolve it.

In terms of design time naming conventions is certainly an interesting idea that's worth pursuing if you want to discuss it further.

**Comment by beachwalker** [comment]
Yes, it would be nice if Caliburn.Micro would support design time naming conventions. Should we open up a separate issue for that?

**Comment by nigel-sampson** [comment]
@superware has created #388 to discuss it, feel free to add your ideas.
