### ISSUE TITLE
Implementing a Splash Screen with Caliburn-Micro

### ISSUE THREAD

**Issue by superware** [Caliburn-Micro/Caliburn.Micro#360]
Since a Splash Screen is a fairly common requirement in most applications, and since I couldn't find much about this in a Caliburn-Micro context, what's the best practice to implement a Splash Screen mechanism with the following requirements:
1. Independent Window, Topmost true, ShowInTaskbar false.
2. Show as soon as possible (ShowWindow from the bootstrapper's OnStartup?)
3. Stay visible up until the MainViewModel is initialized (close it from OnInitialize? how to reference it properly?)

Any help would be greatly appreciated, and should probably go straight into the samples folder :)

Thanks!

**Comment by nigel-sampson** [comment]
It would totally depend on which platform you're looking at, most mobile platforms already have some sort of splash screen system built in with some having an extended splash for initialization purposes.

**Comment by superware** [comment]
I was actually referring to WPF :) Can you please help? What is the most "correct" pattern/architecture for this?

**Comment by MoiraG** [comment]
There are so many ways of doing this.  For example:

Use the OnStartup method in your bootstrapper. Show your splashsreen with the windowmanager and load your data.  As soon as the data are loaded, close the splashscreen (TryClose on the SplashViewModel) and invoke DisplayRootViewFor<ShellViewModel>();

**Comment by superware** [comment]
Well, the whole point is to keep the Splash Screen visible as long as the startup VM/modules are still loading, meaning one of the VMs should invoke the Splash Screen window closing, right? but how?

**Comment by MoiraG** [comment]
I think you should ask your question on stackoverflow. You will get there more response. It's not a problem with caliburn.micro.

I think you should show your splashscreen from OnStartup in your bootstrapper with the windowmanager. and then start the loadingprocess with a service (different class). After the process finished, call TryClose on your SplashViewModel and show your ShellViewModel --> Everything in the bootstrapper. 

Here is a similiar approach: https://stackoverflow.com/questions/25141186/custom-caliburn-micro-splashscreen-with-shell-screen-conductor 

Replace the Backgroundworker with your own logic and call a service or something else.

**Comment by JobaDiniz** [comment]
@superware well, one other simpler approach [How to: Add a Splash Screen to a WPF Application](https://msdn.microsoft.com/en-us/library/cc656886%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396)

Add a image to your project and set the _Build Action_ to **SplashScreen**.

**Comment by MoiraG** [comment]
The problem with this approach is the point 3) "Stay visible up until the MainViewModel is initialized (close it from OnInitialize? how to reference it properly?)"

The splashscreen don't waits for the initialization

**Comment by nigel-sampson** [comment]
The best way to think about this is not to think about it as splash screen but just another window.

Then the problem can become show a Window with a view / view model pair, this pair can handle a lot of the initialization logic for the app. Once it's done it hands off to the next view / view model to use the data. You'll probably need to customize the window manager for your requirements on the window but it doesn't look particularly difficult.

**Comment by nigel-sampson** [comment]
Closing out as no issue here.
