### ISSUE TITLE
OnViewLoaded not called

### ISSUE THREAD

**Issue by lploumen** [Caliburn-Micro/Caliburn.Micro#364]
Following the issue #342, I wanted to bypass the OnActivate logic by using the OnViewLoaded override.
Problem is it seems it is never called.
My project has nothing special, just a button navigating to a ViewModel (which inherits from Screen) where I expected the OnViewLoaded override to be called.

**Comment by nigel-sampson** [comment]
Not sure what you mean by "by the OnActivate logic", can you elaborate on what you mean here and also which platform?

**Comment by lploumen** [comment]
Hi Nigel,
As you already noticed on bug #342, I have a problem with OnActivate, you provided a way to fix it but it does not work (see the thread).
As I need the OnActivate method to work, I though a workaround would be to use the OnViewLoaded override for this purpose. I though it should mimic the OnActivate method (Is it right?). Then I overrode the OnViewLoaded method in my vm but it is never called. Shouldn't it be called ?
I am using Caliburn on Xamarin Forms.
Regards,

**Comment by nigel-sampson** [comment]
@lploumen with the fixes discussed in #342 can you verify whether this is still an issue?

**Comment by lploumen** [comment]
Hi,
I though fixing #342 would also fix this one but it's not the case. OnViewLoaded is still not called.

**Comment by nigel-sampson** [comment]
Hmm, closer look this is a separate issue. The current Android and iOS Platform Providers don't deal with Xamarin.Forms, looks like a Xamarin.Forms specific one will be need to be created.
