### ISSUE TITLE
Setup Xamarin Forms with UWP & Caliburn Micro.

### ISSUE THREAD

**Issue by RikardoPons** [Caliburn-Micro/Caliburn.Micro#365]
Hello!
I spent a lot of time trying to setup correctly caliburn micro with Xamarin Forms and UWP & Android.
I did this steps:
I added Caliburn micro Xamarin Forms to Xamarin Portable project
I added Caliburn micro to UWP project

I followed the example "Hello.Forms" from this repository(caliburn-micro)
I created my app.cs in Xamarin Portable project
` public class App : FormsApplication
    {
        private readonly SimpleContainer container;

        public App()
        {

        }
        public App(SimpleContainer container)
        {
            this.container = container;

            container
                .PerRequest<MainViewModel>();

            Initialize();
            DisplayRootViewFor<MainViewModel>();

        }

        protected override void PrepareViewFirst(NavigationPage navigationPage)
        {
            container.Instance<INavigationService>(new NavigationPageAdapter(navigationPage));
        }`

I created my App.cs in my UWP app with this:

`public sealed partial class App
    {
        private WinRTContainer container;
        private IEventAggregator eventAggregator;

        private INavigationService mainNavigationService = null;
        public App()
        {
            InitializeComponent();
            Initialize();
        }

      
        protected override void Configure()
        {
            container = new WinRTContainer();
            container.RegisterWinRTServices();

            container.Singleton<FightZone.Core.App>("XamarinApp");

        
           
        }

        protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
            base.OnLaunched(e);
            Xamarin.Forms.Forms.Init(e);
            //I wrote this becuase is never called by Caliburn micro.
            var xamarin = container.GetInstance(typeof(FightZone.Core.App), "XamarinApp");

          
        }

        protected override IEnumerable<Assembly> SelectAssemblies()
        {
            var assemblies = base.SelectAssemblies().ToList();
            assemblies.Add(typeof(FightZone.Core.ViewModels.MainViewModel).GetTypeInfo().Assembly);
       
            return assemblies;

        }

        protected override object GetInstance(Type service, string key)
        {
            var instance = container.GetInstance(service, key);

       
            return instance;
        }

        protected override IEnumerable<object> GetAllInstances(Type service)
        {
            return container.GetAllInstances(service);
        }

        protected override void BuildUp(object instance)
        {
            container.BuildUp(instance);
        }

        
    }`

I tested my application and the viewModel and the view is created correctly but the view (MainView) is not showed. 

I posted here because I think it could be a bug of caliburn because all the code run fine. 

thank you for your help.

**Comment by nigel-sampson** [comment]
You can find a [UWP Forms samples](https://github.com/nigel-sampson/talks/tree/master/ndc-sydney) here, the important projects are .Core, .Forms.Core and .Forms.App.UWP.

I can't tell from your sample code if you're including a "host" xaml page. Xamarin.Forms for UWP requires a host page that inherits from WindowsPage.

It's there you call `LoadApplication` passing the application resolved from the container.

Check `HostView.xaml` and `HostView.xaml.cs` in the link above.
