### ISSUE TITLE
Few events like SizeChanged, ViewChanged doesn't work

### ISSUE THREAD

**Issue by ngducnghia** [Caliburn-Micro/Caliburn.Micro#367]
It seems that not all events are working and bindable to ViewModel, I tried SizeChanged and ViewChanged it gives me "Caliburn.Micro No target found for method" error. This is for ScrollView, Grid, etc.

**Comment by nigel-sampson** [comment]
Can you elaborate on which platform you're having this problem on? 

Given the error message this doesn't sound like one related to the event but more about an incorrect view model (or an issue bubbling the action). 

Can you show the xaml attaching the method to the event?

**Comment by nigel-sampson** [comment]
Closing this with no further information received.
