### ISSUE TITLE
[UWP] Navigation in <Frame> element

### ISSUE THREAD

**Issue by BitawareUnleashed** [Caliburn-Micro/Caliburn.Micro#369]
I have made a little application with four pages with CM. According the example at the following link 

https://channel9.msdn.com/Series/Windows-10-development-for-absolute-beginners/UWP-019-Working-with-Navigation

I've tried to implement the navigation in the <Frame> element but I wasn't able to show the new page. I've tried with adding a code behind file (.xaml.cs) for each page and in this manner the pages are shown in the Frame container. The problem is that I can't use the Caliburn ViewModel to control the page because is not linked. 
Someone have suggestions?
Thanx

**Comment by nigel-sampson** [comment]
The [Windows RT 8.1 sample](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/samples/Caliburn.Micro.HelloWinRT81) shows scenarios similar to the above video. It has a root frame control wrapped with a navigation service that allows view model navigation.
