### ISSUE TITLE
Transition Caliburn.Micro.Core from profile based PCL to .Net Standard based PCL

### ISSUE THREAD

**Issue by ItayPodhajcer** [Caliburn-Micro/Caliburn.Micro#371]
At the moment, when a PCL project is changed from using profiles to using .Net Standard versions, the Caliburn.Micro.Core NuGet package cannot be added to it.
Probably caused by the package not being updated to the new package dependencies model.

**Comment by nigel-sampson** [comment]
Was hoping to leave this until the teams sorted out the whole `project.json` fiasco, but it looks like we may not.

**Comment by ItayPodhajcer** [comment]
Would be happy to PR this to help make it happen faster.
If the code is already profile based compatible (no #IF directives), then it's only a matter of targeting .Net Standard 1.4 or lower (to support UAP) and adding the relevant Microsoft packages (such as System.ComponentModel).

**Comment by nigel-sampson** [comment]
Just pushed the work on the `dev/4.0.0` branch doing this transition for `Caliburn.Micro.Core`, still need to do `Caliburn.Micro.Platform.Core`.

**Comment by nigel-sampson** [comment]
We now have `Caliburn.Micro.Core` and `Caliburn.Micro.Platform.Core` targeting .NET Standard 1.0 (ensures we can still work 4.5).

`Caliburn.Micro.Platform` is not a multi-targeted project with the following frameworks `netstandard1.4;net45;uap10.0;MonoAndroid10;Xamarin.iOS` (where `netstandard1.4` will be Xamarin.Forms).

This is definitely the first rough cut. There's some work to be done getting the samples working against these as well as the packaging story.

**Comment by godrose** [comment]
@nigel-sampson Any update on the nuget package release/pre-release date?

**Comment by nigel-sampson** [comment]
Not sure, I was loathe to distribute the new asemblies via nuget until we had the functionality changes 4.0.0.

But if people are keen we can do a 4.0.0-alpha with the knowledge that would be heavy breaking changes between that and 4.0.0-beta.

**Comment by godrose** [comment]
+1

**Comment by joaomatossilva** [comment]
With the latest update to VisualStudio, we can't create PCL based projects with Xamarin.Forms. I think at least an Alpha version should be out there...

**Comment by nigel-sampson** [comment]
Good to know, I'll up the priority on a very early alpha. but will come with some heavy warnings that there will be breaking changes.
