### ISSUE TITLE
SimpleContainer not using the default constructor.

### ISSUE THREAD

**Issue by adupontxpertdoc** [Caliburn-Micro/Caliburn.Micro#372]
Hi,

SimpleContainer is calling the wrong constructor should call AddinOptionsModel() instead of AddinOptionsModel(string filename). Example of code:

```
public class AddinOptionsModel
{
    // Expected constructor to be called.
    public AddinOptionsModel()
        : this("Default")
    {
        // ...
    }

    // Actual constructor called with fileName = null crashing the application. 
    public AddinOptionsModel(string fileName)

    {
        // ...
    }

}
```

// In Bootstrap Configuration
            this._container.Singleton<AddinOptionsModel, AddinOptionsModel>();

// In our code
            this.AddinOptionsModel = IoC.Get<AddinOptionsModel>();

Regards

**Comment by nigel-sampson** [comment]
Right now `SimpleContainer` is as the name says pretty simple. It simple matches on the public constructor with the most parameters irregardless of whether it can fulfill those dependencies.

It wouldn't be difficult to change this. I'd look at the `SelectEligibleConstructor` method of `SimpleContainer`. Happy to take a PR on this.

**Comment by jongleur1983** [comment]
What's the best strategy to implement here?
If I understand the current SimpleContainer implementation correct, it's currently using the constructor providing the most number of parameters.

```static ConstructorInfo SelectEligibleConstructor(Type type) {
    return (from c in type.GetConstructors().Where(c => c.IsPublic)
                    orderby c.GetParameters().Length descending
                    select c).FirstOrDefault();
        }```

This is the best selection when we don't know anything about the parameters provided as it promises the largest flexibility to use all arguments.

But as far as I understand the SimpleContainer we know all parameters that can be reliably resolved.
While trying to implement that solution, I'm therefore happy to get feedback on this proposed strategy:

*When selecting the right constructor (SeletEligibleConstructor), I propose to choose the public one with least unregistered parameters (types).*

This is in fact a breaking change to what happens now, but if this issue should be implemented at all, I don't see how that should be possible without breaking changes at all.

**Comment by nigel-sampson** [comment]
I agree with the proposal around which constructor to use, also agree that it's a breaking change so will shift it to `4.0.0`.
