### ISSUE TITLE
Enable SimpleContainer to resolve multiple parameters of same type

### ISSUE THREAD

**Issue by jongleur1983** [Caliburn-Micro/Caliburn.Micro#375]
The SimpleContainer is what it's called: quite simple.
Nevertheless I propose to extend it slightly to better support more than one parameter of the same type.
Consider a constructor with the following signature

```public Point(int x, int y)```

Without knowing the internal implementation it's clear that x and y may have to be different values. Currently it's possible to register one instance per type (e.g. int) without a key, or different ones with different keys, where a key is a string value.
These keys are not considered by the constructor resolution, yet.

I propose to change this as follows:
For each constructor argument look for registered instances of matching type. If there's one where the key matches the arguments name, take it, else take another (as it has been done before).

**Comment by nigel-sampson** [comment]
Not sold on this at the moment.

I feel like we're straying away from **Simple** with this change and that if this sort of functionality is desired then a more fully featured container is the better path to go down.

I don't want to bit by bit add more and more functionality to `SimpleContainer` and find ourselves in a years time supporting a fully featured container.

But having said that we have to draw the line somewhere, is it here?

**Comment by jongleur1983** [comment]
Good point.
As I wrote before I never saw SimpleContainer in real use, but I consider constructors with two parameters of the same type a common task.

For Caliburn, where we mostly talk about constructing ViewModels we had (although using another DI container) several cases of "comparison view models" at work, where some screen compares two items of the same type.

Perhaps SimpleContainer is in fact not useful for many scenarios - and probably you're right and it shouldn't be, but in that case I don't get why it's implemented at all yet (no offense intended), as real scenarios require something more sophisticated, and easy scenarios do not require DI at all.

**Comment by nigel-sampson** [comment]
It depends a lot on where you're using the container. Mentally I tend to divide view models into two distinct groups.

1. Page view models, usually inherit from `Screen` and their dependencies are normally application services behind interfaces.
2. Model view models, usually inherit from `PropertyChangedBase` and their dependencies are normally model objects they represent.  These one's don't tend to be created by the container but in the form of code such as:

``` csharp
var products = productsService.GetOnSaleProducts().Select(p => new ProductListViewModel(p));
```

With this approach I don't tend to have multiple values of the same type in the container and so `SimpleContainer` works well.

Would love you to expand on your example as it's not something I'd considered.

**Comment by jongleur1983** [comment]
My example is only a slight variation of yours, splitting your first group into two subgroups:

1. "leaf" screens - that's what I think you had in mind
1. comparison screens: something between conductors and "leaf screens". It's a bad name, but the most descriptive use case I see. Let's consider a screen that compares two entities side by side. Both are modelled by the same class with slight variation of parameters ("left" vs "right" or "mine" vs. "theirs"). The main - and probably only descriptive use case I imagine is the broader issue of versioning: Views, that allow to compare two versions of the same type, like in Git, Svn etc or in any software that has versioning of entities built in.

For two major projects I work on built in version control on entities is a core requirement, so I might be a little bit wrong when looking on generality in this case.

Nevertheless some more use cases I found:

1. Local vs. remote views on "transfer software" like FTP, SSH and other server based hosting stuff
1. Preview vs. current state (okay, that's basically a special case of the versioning)

**Comment by nigel-sampson** [comment]
Interesting, so you're adding the two entities you're comparing into the container?

**Comment by jongleur1983** [comment]
in fact we use Autofac as our DI container together with Caliburn.Micro, and here we resolve it as 
```Func<ComparisonEntity, ComparisonEntity, ComparisonScreenViewModel>```.
The Autofac configuration us set up to ensure that LeftEntity is used for the first parameter in the resolved constructor
```new ComparisonScreenViewModel(new ComparisonItemViewModel(leftComparisonEntity), new ComparisonItemViewModel(rightComparisonEntity))```

So we don't add the two entities into the autofac-Container, but we inject them into the resolution logic to be used when wiring everything together.

**Comment by nigel-sampson** [comment]
Thanks, makes sense when using the capabilities of Autofac (use it in my day job).

Given this I think it makes sense to leave it out of `SimpleContainer`.

**Comment by jongleur1983** [comment]
I agree and close this issue, thanks for the discussion
