### ISSUE TITLE
Copyright year in DLL version

### ISSUE THREAD

**Issue by Const-me** [Caliburn-Micro/Caliburn.Micro#377]
![caliburn-dll-version](https://cloud.githubusercontent.com/assets/925112/19292360/d064961e-901b-11e6-8a74-be2ae6ae93d5.png)

The value is taken from `[assembly: AssemblyCopyright("Copyright © 2010")]` in src/GlobalAssemblyInfo.cs

**Comment by nigel-sampson** [comment]
Thanks

**Comment by nigel-sampson** [comment]
Just realised why this can't be done since we have can't have dynamic values in attributes (yay).

It's something that can be revisited when / if we setup a CI / build server.
