### ISSUE TITLE
Exception "no target found for method" on click of row grid view

### ISSUE THREAD

**Issue by NhatDuy1407** [Caliburn-Micro/Caliburn.Micro#378]
Hi All,

My WPF application got an exception "no target found for method EditRow"
My code:
`<DataTemplate x:Key="a">`
        `<Grid>`
            `<StackPanel Orientation="Horizontal" HorizontalAlignment="Right">`
                `<Button Background="Transparent" BorderBrush="Transparent" BorderThickness="0" Margin="0 0 2 0" Visibility="Hidden"
                        x:Name ="editTemplate" caliburn:Bind.Model="{Binding  RelativeSource={ RelativeSource FindAncestor, AncestorType=telerik:RadGridView}, Path=DataContext, Mode=TwoWay}"
                    caliburn:Message.Attach="[Event Click] = [Action EditRow($executionContext)];" caliburn:Action.TargetWithoutContext="{Binding DataContext, ElementName=editTemplate}"
                              >`
                    `<Image Source="~\Edit.png" />`
                `</Button>`
           `</StackPanel>`
        `</Grid>`
   `</DataTemplate>`

I tried to fix as https://github.com/Caliburn-Micro/Caliburn.Micro/issues/242
But it does not work.

Regards,

**Comment by nigel-sampson** [comment]
You're using a lot of different features of the framework on that one button many of which aren't making sense when used in that manner. Can you expand on what you're trying to achieve?

**Comment by NhatDuy1407** [comment]
Hi nigel-sampson,

- I have a gridview and set EnableRowVirtualization="True".
- On each row of grid view, have an edit button on last column with designed template as above code.
- On click of the edit button, i want row be expanded.
- Currently, it works but if have many rows on grid view, sometime, when scrolling and on click of the edit button will show an error message "no target found for method EditRow".

I think the root cause is EnableRowVirtualization = "True". If you have any suggestion, please let me know.

Thanks a lot!

**Comment by nigel-sampson** [comment]
Ok, I don't think setting `TargetWithoutContext` is going to help here since `Bind.Model` sets both the `DataContext as well as Target so there's a lot of repetition there. I'd start by removing that.

Testing without `EnableRowVirtualization` would help as well.

Actions should naturally bubble out of the DataTemplate up to one that can handle the message. So there shouldn't need to be anything but the `Message.Attach`.

If you can provide a small sample of the problem I can probably look a bit closer at it.

**Comment by NhatDuy1407** [comment]
Thanks for your help. Let me prepare a sample of problem.

**Comment by nigel-sampson** [comment]
Closing out as not extra information received.
