### ISSUE TITLE
DataContext not set for child views at design time.

### ISSUE THREAD

**Issue by kayle** [Caliburn-Micro/Caliburn.Micro#379]
I'm starting to investigate various design-time problems. I found https://github.com/Caliburn-Micro/Caliburn.Micro/commit/4d2aaf7e2b9a2334ef792a1f6d9f1790c9a02a7a prevents the DataContext from being set.

Sample Wpf project setup:
ShellView.xaml (with )

```
     xmlns:cal="clr-namespace:Caliburn.Micro;assembly=Caliburn.Micro.Platform"
     cal:Bind.AtDesignTime="True"
     d:DataContext="{d:DesignInstance Type=local:ShellViewModel,IsDesignTimeCreatable=True}"

  <StackPanel Background="White">
    <TextBlock x:Name="Text"></TextBlock>
    <ContentControl x:Name="Child"></ContentControl>
  </StackPanel>
```

ChildView.xaml

```
<TextBlock x:Name="Text"></TextBlock>
```

and the following simple view models:

```
  public class ShellViewModel : PropertyChangedBase
  {
    public string Text { get; set; } = "Shell Text";
    public ChildViewModel Child { get; set; } = new ChildViewModel();
  }

  public class ChildViewModel : PropertyChangedBase
  {
    public string Text { get; set; } = "Child Text";
  }
```

The designer for ShellView.xaml incorrectly shows
![image](https://cloud.githubusercontent.com/assets/1664776/19388455/bad93128-91ed-11e6-8690-32981c2e1193.png)
whereas it should match the runtime behavior:
![image](https://cloud.githubusercontent.com/assets/1664776/19388465/c8ac3638-91ed-11e6-9f9c-b5d3919495a4.png)

I think the simplest fix is to change the fix from @brendankowitz to 

```
if (e.NewValue == e.OldValue || (Execute.InDesignMode && e.NewValue is string)) {
    return;
}
```

**Comment by eogas** [comment]
Potentially related issues #214, #358, and #359

**Comment by eogas** [comment]
No idea if this is the right fix or not, but FWIW, this fixes the issue in my reproducer case here: https://github.com/eogas/CaliburnMicroDesignTimeNestedBindingBug

**Comment by superware** [comment]
I also accidentally stumbled upon this faulty behavior. Very simple to reproduce, and frankly quite annoying.

Is there any project that doesn't have nested View Models and doesn't need to visualize them cascading in the designer? a strange one.

**Comment by eogas** [comment]
@superware The change at the end of @kayle's report is what I'm referring to.

```
if (e.NewValue == e.OldValue || (Execute.InDesignMode && e.NewValue is string)) {
    return;
}
```

I don't know enough about the project to say whether or not that is a "correct" solution, but it does fix the specific issue mentioned in the bug.

**Comment by nigel-sampson** [comment]
Sorry guys, have been living out of a suit case without internet for the last few weeks.

Will take a closer look into this.

**Comment by superware** [comment]
Hi Nigel, have you managed to reproduce this issue?

**Comment by superware** [comment]
In the meantime, what is the minimal code required to also support DesignTimeMyViewModel -> MyView convention without breaking default naming conventions? thanks.

**Comment by nigel-sampson** [comment]
Just pushed that change (thanks @brendankowitz). Hoping to have `3.0.2` out in a few days. Apologies for the delays.
