### ISSUE TITLE
Add a Set<T> method to Screen and PropertyChangedBase

### ISSUE THREAD

**Issue by PhilPJL** [Caliburn-Micro/Caliburn.Micro#38]
Would it be sensible to add something similar to the MVMM Light ViewModelBase.Set method(s)?

e.g.
````csharp
    protected bool Set<T>(string propertyName, ref T field, T newValue)
    {
        if (EqualityComparer<T>.Default.Equals(field, newValue))
            return false;
        field = newValue;
        this.NotifyOfPropertyChange<T>(propertyName);
        return true;
    }
 
    protected bool Set<T>(
         ref T field, T newValue, [CallerMemberName] string propertyName = null)
    {
        return Set(propertyName, ref field, newValue);
    }

    ... lambda version etc
```

Usage
````C#
    class SomeClass : Screen
    {
        private int _someProp;
        public int SomeProp 
        {
            get{ return _someProp; }
            set{ Set( ref _someProp, value ); }
        }
    }
```
Or add an extension method
````C#
    internal static class NotifyPropertyChangeExtensions
    {
        public static bool Set<T>(
            this INotifyPropertyChangedEx notifier, ref T field, 
            T newValue, [CallerMemberName] string propertyName = null)
        {
            if (EqualityComparer<T>.Default.Equals(field, newValue))
            {
                return false;
            }

            field = newValue;
            notifier.NotifyOfPropertyChange(propertyName);

            return true;
        }
    }
```
Usage
````C#
    class SomeClass : Screen
    {
        private int _someProp;
        public int SomeProp 
        {
            get{ return _someProp; }
            set{ this.Set( ref _someProp, value ); }
        }
    }
````

**Comment by evnik** [comment]
Could it be implemented even without ReSharper support? Actually, I don't use ReSharper, but I just want to call Set methods, like I can do it with other MVVM frameworks.

**Comment by nigel-sampson** [comment]
@evnik you can create an extension method with Set functionality with no problems at all. The R# discussion is just about ways to *inform* R# that this method exists for auto-refactoring options.

Given that most people want different things from methods like this I'd still thinking it should be an external extension method that people can do what they want with.

Opinions can change though.

**Comment by evnik** [comment]
@nigel-sampson Yes, I can write an extension method (or non-extension method in my derived classes) and copy it into each of my project. But I don't understand why couldn't we have a single implementation inside the framework?

**Comment by nigel-sampson** [comment]
@evnik mainly because from just in this thread there are four different implementations and I know of about four others from chatting with people. Everyone has a different opinion on what this method should look like so in my opinion it's best left to the individual developer.

Personally I use [Fody.PropertyChanged](https://github.com/Fody/PropertyChanged).

This is the sort of method that ends up in every companies core assemblies and doesn't end up being copied.
