### ISSUE TITLE
DataGridTextColumn with ContentMenu

### ISSUE THREAD

**Issue by pawelszulik** [Caliburn-Micro/Caliburn.Micro#380]
Hello
I have got a problem.
In Datagrid -> DatagridColumn (header) -> I need a ContentMenu with caliburn.micro.
It doesn't work with action cm:Message.Attach
After click I have got an exception:
"An unhandled exception of type 'System.Exception' occurred in WindowsBase.dll
Additional information: No target found for method ContextMenu2."

`<DataGridTextColumn Binding="{Binding Path=Name}">
                                    <DataGridColumn.Header>
                                        <TextBlock Text="Nazwa">
                                            <TextBlock.ContextMenu>
                                                <ContextMenu>
                                                    <MenuItem  Header="lololol" cm:Message.Attach="[Event Click]=[Action ContextMenu2]"></MenuItem>
                                                </ContextMenu>
                                            </TextBlock.ContextMenu>
                                        </TextBlock>
                                    </DataGridColumn.Header>
                                </DataGridTextColumn>       `

**Comment by mvermef** [comment]
Just do a search for caliburn.micro & context menus, it's related to visualtree not seeing the menu till you spawn it.

**Comment by pawelszulik** [comment]
I changed line MenuItem and this do not work.
 <MenuItem  Header="lololol" cm:Message.Attach="ContextMenu2" cm:Action.TargetWithoutContext="{Binding }"/>

I dont understand this.
I do not know why not connected to viewmodel.

**Comment by mvermef** [comment]
Like I said this one has been beaten to death do a search in your favorite search engine and you shall be amazed at the result

http://stackoverflow.com/questions/28256065/caliburn-micro-and-contextmenu-results-in-target-not-found

**Comment by pawelszulik** [comment]
need add to View (xaml file): 
`<Grid.Resources>
<classes:BindingProxy x:Key="Proxy" Data="{Binding}" />
</Grid.Resources>`

in DataGrid:
`<DataGridTextColumn Binding="{Binding Path=Name}">
                                    <DataGridColumn.Header>
                                        <TextBlock Text="Nazwa" >
                                            <TextBlock.ContextMenu>
                                                <ContextMenu >
                                                    <MenuItem x:Name="Item" Header="lololol" cm:Message.Attach="ActionContextMenu2" cm:Action.Target="{Binding Source={StaticResource Proxy}, Path=Data}"/>
                                                </ContextMenu>
                                            </TextBlock.ContextMenu>
                                        </TextBlock>
                                    </DataGridColumn.Header>
                                </DataGridTextColumn>`

New class and binding this in View (xaml file)
`public class BindingProxy : Freezable
{
    protected override Freezable CreateInstanceCore()
    {
        return new BindingProxy();
    }

    public object Data
    {
        get { return (object)GetValue(DataProperty); }
        set { SetValue(DataProperty, value); }
    }

    public static readonly DependencyProperty DataProperty =
        DependencyProperty.Register("Data", typeof(object), typeof(BindingProxy), new UIPropertyMetadata(null));
}`

!! thx
