### ISSUE TITLE
The dependency property target is invalid

### ISSUE THREAD

**Issue by rubgithub** [Caliburn-Micro/Caliburn.Micro#381]
Hi, I'm trying Calibur and facing this issue:

![sem titulo](https://cloud.githubusercontent.com/assets/3399476/19503335/e2c965ea-9580-11e6-9ad5-8586c118af06.png)

How to solve this problem?

Ps: 
Caliburn configuration it's OK because my app it's navigating between pages
I'm using HamburgerMenu components from UWPCommunityToolkit (https://github.com/Microsoft/UWPCommunityToolkit) in my app

**Comment by nigel-sampson** [comment]
From the times I've seen this it's been a transient designer error that hasn't affected the actual execution.

Can you verify this is happening for you?

**Comment by rubgithub** [comment]
@nigel-sampson  I'm not familiar with the term ` transient designer` Can you explain how can I verify this?

**Comment by nigel-sampson** [comment]
Sorry, the times I've seen it were only errors in the Visual Studio xaml designer and disappeared either after later xaml changes, re-opening the file or restarting Visual Studio.

It didn't impact the compile or execution of the application itself.

Can you verify this is the same for you as well?

**Comment by rubgithub** [comment]
Trying to run got this error `Failed to assign to property 'Caliburn.Micro.Message.Attach'. [Line: 114 Position: 25]"`

**Comment by kdbcinco** [comment]
It will help if you indicate what version of Visual Studio you are using.

**Comment by rubgithub** [comment]
VS 2015 Update 3
Application info:
Target Version: 10.0; Build 14393
Min Version: 10.0; Build 10586

**Comment by rubgithub** [comment]
Sorry, it was my fault, there is no `MouseEnter` event in the `UWP`.
Replaced to `Click` and now works fine.
