### ISSUE TITLE
NotifyOfPropertyChange might throw TaskCanceledException while application shutting down

### ISSUE THREAD

**Issue by superware** [Caliburn-Micro/Caliburn.Micro#385]
Hello,

I have a standard ViewModel property calling NotifyOfPropertyChange at relatively high rate, once every 3-4 times it throws TaskCanceledException while the application is shutting down.

```
A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Caliburn.Micro.XamlPlatformProvider.OnUIThread(Action action)
   at Caliburn.Micro.PropertyChangedBase.NotifyOfPropertyChange(String propertyName)
   at Client.ViewModels.InstrumentsViewModel.set_RelativeValue(Nullable`1 value)
   at Client.ViewModels.InstrumentsViewModel.Update(IData data)
   at Client.ViewModels.InstrumentsViewModel.Service_DataChanged(Object sender, DataEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Model.Services.MockService.Timer_Callback(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```

I know I'm using a Timer that does all this in a different thread, possibly after the UI dispatcher can't handle Execute.OnUIThread (or similar condition). But still, IMHO this shouldn't happen, raising INotifyPropertyChanged.PropertyChanged shouldn't throw in any case. If one of the subscribers has a problem, there's nothing the publisher can do about it anyway.

Thanks!

(Ps. might be related to [this discussion](http://caliburnmicro.codeplex.com/discussions/470714))

**Comment by nigel-sampson** [comment]
How often is "a relatively high rate"?  Which platform is this on?

**Comment by superware** [comment]
WPF, something like 20Hz. But it's a matter of probability, this can also happen at 1Hz.

Why Execute.OnUIThread on WPF in the first place?

Thanks Nigel!

**Comment by nigel-sampson** [comment]
Pre 4.5 not all bindings could handle property changed notifications off the UI thread. Even if we weren't doing that you may still run into issues in that somewhere else will have to marshall that notification over to the UI thread to update the UI leading to similar issues.

You could try doing you own marshalling (Caliburn will check if you're already on the UI thread) to see if there are any issues there.

We may be able to change that when obsoleting some of the older platforms.

**Comment by superware** [comment]
Why not use compiler directives now? :)

**Comment by nigel-sampson** [comment]
Certainly an option, definitely a breaking change though.

**Comment by superware** [comment]
Why "definitely a breaking change"? From the caller's perspective, NotifyOfPropertyChange will still notify about the property change per INotifyPropertyChanged. IMHO, there might be rare occasions on which this change will break something (if any on 4.5+), but on the other hand it will handle this nasty shutdown bug (I encountered it after using CM for ~2 hours).

**Comment by nigel-sampson** [comment]
If anyone is wiring up manually to the property changed notifications then suddenly shifting which thread it's on could break their application.

**Comment by superware** [comment]
You are right, but this shutdown bug (have you managed to reproduce it?) should have at least a workaround. How about the following:

```
public static bool IsMarshalToUIThread = true;
```

and

```
if (IsNotifying && PropertyChanged != null) {
  if (IsMarshalToUIThread)
    Execute.OnUIThread(() => OnPropertyChanged(new PropertyChangedEventArgs(propertyName)));
  else
    OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
}
```

Thanks!

**Comment by nigel-sampson** [comment]
Haven't been able to recreate it yet, how are you triggering the shut down and which timer class are you using? Is there any reason you're not gracefully shutting down the timer from firing events on application shutdown? I imagine at the moment this is being caused by the high frequency of your timer causing a dispatch while the UI thread is being shut down.

That would seem the most appropriate work around since even if we weren't dispatching then the binding attached to your property may trigger the same thing.

**Comment by superware** [comment]
Well, I'm simply hitting Alt+F4 to close the application. The bootstrapper's OnExit is disposing all Model services (including that timer), but since the UI thread is disposing everything, the pending NotifyOfPropertyChange can't execute. It will execute eventually but then it will be too late (TaskCanceledException).

Regarding your second point, when I implement INotifyPropertyChanged directly and raise PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(MyProperty))) instead of NotifyOfPropertyChange(), I never get that TaskCanceledException.

By the way, 10 Hz isn't that high, it can also happen at 1 Hz since it's a timing issue.

**Comment by nigel-sampson** [comment]
Hmm, not seeing any exceptions when shutting down the app with a 40 Hz timer. Which timer are you using?

Interesting, thanks for the extra information.

**Comment by superware** [comment]
Here's a simple example:

```
public class AppBootstrapper : BootstrapperBase
{
	public AppBootstrapper()
	{
		Initialize();
	}

	protected override void OnStartup(object sender, StartupEventArgs e)
	{
		DisplayRootViewFor<ShellViewModel>();
	}

	protected override void OnExit(object sender, EventArgs e)
	{
		var vm = (ShellViewModel)this.GetInstance(typeof(ShellViewModel), null);

		vm.Dispose();

		// since this runs in the UI thread, any currently executing NotifyOfPropertyChange can't complete because of Execute.OnUIThread

		base.OnExit(sender, e);
	}
}

public class ShellViewModel : PropertyChangedBase, IDisposable
{
	private Timer _timer;
	private int _counter;
	private int _count;

	public ShellViewModel()
	{
		_timer = new Timer(Timer_Callback, null, 0, 1); //1000Hz
	}

	private void Timer_Callback(object state)
	{
		Count = ++_counter;
	}

	public int Count
	{
		get { return _count; }
		set
		{
			if (_count != value)
			{
				_count = value;
				NotifyOfPropertyChange(); //this might throw if the UI has already shutdown.
			}
		}
	}

	public void Dispose()
	{
		_timer.Dispose(InvalidWaitHandle.Instance); //block until no pending callbacks
	}
}

public sealed class InvalidWaitHandle : WaitHandle
{
	private readonly static InvalidWaitHandle _instance = new InvalidWaitHandle();

	private InvalidWaitHandle()
	{
	}

	public static WaitHandle Instance
	{
		get { return _instance; }
	}
}

<Window x:Class="WpfApplication1.ShellView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="clr-namespace:WpfApplication1"
        Width="525" Height="350">
    <Grid>
		<TextBlock Text="{Binding Count}"/>
	</Grid>
</Window>
```

Keep in mind the Timer in my case belongs to the Model, it can't be a UI-oriented timer for that matter.

Thank you for your help.

**Comment by nigel-sampson** [comment]
Whoops, wrong button.

Thanks for the sample, was able to create the issue. One thing I noticed and this could be just a side effect of the sample is the disposal. Since the sample isn't using any sort of container then the behavior of GetInstance will be to create a new view model. So instead of stopping the timer bound to the UI it creates a new one and disposes of it, leaving the UI bound one to keep going.

I switched the sample to use a container where `ShellViewModel` is a singleton (for ease of testing) and when disposing of the correct timer I was unable to recreate the bug.

**Comment by superware** [comment]
I think you are absolutely right, thank you very much.

**Comment by nigel-sampson** [comment]
Glad I could help, will certainly look at the need for dispatching on platforms when we deal with `4.0.0`

**Comment by meron1122** [comment]
Hi!
Coulud you provide a modified example?
I have this issue too, and i don't know how to fix this.
