### ISSUE TITLE
UWP launch

### ISSUE THREAD

**Issue by jkattestaart** [Caliburn-Micro/Caliburn.Micro#386]
Hi,

I want to create a second entrypoint in my Caliburn UWP app, by defining a separate protocol:
eg. URI: launch-contactperson://ContactPerson/Path1?param1=This is param1&param1=This is param2

But i cannot use the activation procedure as used in de the example form MS

 var protocolEventArgs = args as ProtocolActivatedEventArgs;
        //Switch to a view by Scheme
        switch (protocolEventArgs.Uri.Scheme)
        {
          //under case is the protocol scheme in the Package.appxmanifest
          //Navigate to target page with Uri as parameter
          case "launch-contactperson":
             DisplayRootViewFor<ShellViewModel>();
            break;
        }

The OnLauched in app.xaml,cs seems not activated....

Does anyone has done this before.  An example would be nice

**Comment by nigel-sampson** [comment]
`OnLaunched` is called when your app is launched, if your app is already open then `OnActivated` is called.

You'll need to do some work here depending on what state your app is in (whether you want to preserve history etc).

I notice you're using a view model first approach, typically when I do this I have `OnActivated` publish an event on the `EventAggregator` that `ShellViewModel` can respond to in terms of the type of activation.

**Comment by jkattestaart** [comment]
thx

John Kattestaart
jkattestaart@gmail.com

2016-11-08 1:51 GMT+01:00 Nigel Sampson <notifications@github.com>:
