### ISSUE TITLE
Xamarin Forms Android not Creating and Binding ViewModel for View

### ISSUE THREAD

**Issue by veryhumble** [Caliburn-Micro/Caliburn.Micro#389]
Hi, 

I am using Caliburn.Micro 3.0.1 in a Xamarin Forms Project for iOS and Android, while the iOS Version Works as expected, I have a problem with the Android App. After calling `DisplayRootView<StartupView>();` the view is shown correctly, but no corresponding ViewModel is created and binded to the View thus resulting in a `No target found for method ContinueWithLogin.` Exception. This works in iOS.

I am using the following Versions:
Android 6.0.1 / 7.0 
iOS 10.1
Xamarin Forms 2.3.2.127

Linker Behavior is set to `Don't Link`

I followed the samples branch for setting up the Android Application, Activity and the SimpleContainer. But I cannot figure out whats the issue here and would appreciate any advice.

**Comment by nigel-sampson** [comment]
The two most likely reasons for this are:

1. There's been a refactor and either the full class name of the view or view model hasn't updated properly. Important thing here is that it's the class name not the file name, It's perfectly valid for your xaml file to be named one thing and the `x:Class` to be something else entirely.
2. The view model locator doesn't know about the assembly that has the view models. This would affect you if you're using Portable Class Libraries (as opposed to a Shared Project), [this sample](https://github.com/nigel-sampson/talks/blob/master/ndc-sydney) shows using this approach. The important part is the `SelectAssemblies` override in the [Application](https://github.com/nigel-sampson/talks/blob/master/ndc-sydney/NDC.Build.Forms.App.Droid/Application.cs).
3. The view model hasn't been registered with the container and can't create it. 

Given that it's working for iOS and not Android I think we can discount the first, if you're using shared libraries you can discount the second.

If neither of these approaches work I can look at a sample if you have one.

**Comment by veryhumble** [comment]
Hi Nigel,

Thanks for your response. It helped, i could resolve the problem by overriding and implementing the `SelectAssembies()` Method. Totally forgott that step.

Thanks very much!
