### ISSUE TITLE
Class inherited from PropertyChangedBase can not be used with SignalR

### ISSUE THREAD

**Issue by 0ndrej** [Caliburn-Micro/Caliburn.Micro#393]
If your class is inherited from PropertyChangedBase, this class will have all properties set to their default values when you transfer it from SignalR hub to client in desktop WPF application.

Same class which is not inherited from PropertyChangedBase works fine (properties have correct values set in hub after transfer to client).

**Comment by nigel-sampson** [comment]
It sounds like the values aren't being deserialized, what's the underlying serialization format for Signalr? Are you using the same type on both the client and server?

**Comment by 0ndrej** [comment]
Yes - used type is in assembly shared by hub (server) and client. SignalR is using JSON for serialization and WebSocket for transfer of data.

**Comment by nigel-sampson** [comment]
Interesting if you're referencing Caliburn.Micro on the server as well. Could mean there's an issue with either serialization or deserialization.

Are you seeing the data on the wire with something like Fiddler?

**Comment by 0ndrej** [comment]
I cant get Fiddler to work with localhost communication...

**Comment by nigel-sampson** [comment]
Will make it a bit harder to tell if the problem is on the client or server. I'd suggest creating a new class of the same "shape" as the one inheriting from `PropertyChangedBase` and using it on the server. If this doesn't work it would suggest the problem is on the client, otherwise on the server.

If you can create a same repro here on GitHub that would be most welcome.

**Comment by 0ndrej** [comment]
Here is VB.NET solution with simple SignalR communication without Caliburn usage (works) and with Caliburn usage (does not work).
[Tests.SignalRCaliburn.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/636101/Tests.SignalRCaliburn.zip)

**Comment by nigel-sampson** [comment]
Tracked it down, using Fiddler could tell it was a serialization issue. `PropertyChangedBase` has the [`DataContact`](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro/PropertyChangedBase.cs#L10) attribute applied to it, to help support some forms of serialization the underlying json.net serializer respects it and therefore you'll need to apply `DataMember` to the properties you wish to transport.
