### ISSUE TITLE
WindowConductor doesn't notify parent

### ISSUE THREAD

**Issue by Torvin** [Caliburn-Micro/Caliburn.Micro#394]
Let's say I want to allow my app to have multiple windows. Each window is represented by this VM:

```
class MyWindowViewModel : Screen
{
}
```

Now I want to control the lifetime of these windows using a conductor:

```
class MultiWindowConductor : Conductor<MyWindowViewModel>.Collection.AllActive
{
    IWindowManager _winMgr;
    public MultiWindowConductor (IWindowManager winMgr)
    {
        _winMgr = winMgr;
    }

    // opens a new window
    public void Open()
    {
        var vm = new MyWindowViewModel();
        ActivateItem(vm);
        _winMgr.ShowWindow(vm);
    }
}
```

That works. My VM gets `MultiWindowConductor` assigned as its `Parent`.

Now, if I call `TryClose()` from within the VM, it closes the view (window) and correctly notifies the conductor about that and removes itself from conductor's `Items`. But if instead I close the window using Alt+F4 or X button in the titlebar -- the parent conductor never gets notified about that and will have the closed VM in its `Items` forever. At the same time, VM's `OnDeactivate` gets called in both cases. Looks like a bug to me.

**Comment by nigel-sampson** [comment]
Typically items being conducted like this don't close themselves but are closed by the conductor which is the class responsible for their life cycle.

I could see a couple of ways to deal with this.

1. A custom window manager, probably a bit overkill for this.
2. In `Open` attach to the view models `Deactivated` event, when it's closed remove it from the Items collection.
