### ISSUE TITLE
Upgraded from 3.0.1 to 3.0.2, Bootstrapper crash on GetInstance

### ISSUE THREAD

**Issue by rgutierrezatx** [Caliburn-Micro/Caliburn.Micro#396]
instance is null for the ShellView.  This works fine in 3.0.1.   In 3.0.2, it cannot find the service for ShellView.  I reverted back to 3.0.1 and all is well.
`

**Comment by rgutierrezatx** [comment]
[Bootstrapper.txt](https://github.com/Caliburn-Micro/Caliburn.Micro/files/634837/Bootstrapper.txt)

attached file

**Comment by nigel-sampson** [comment]
Thanks, looks like I missed a change in the notes. This commit (8e9b2fa) makes `ViewLocator` work in a way consistent with `ViewModelLocator` which is to call `GetInstance` to see if the container can resolve the view. If it can't it will fall back to manually instantiating the view.

I'd suggest updating `GetInstance` to not throw an exception if the service type is assignable `UIElement`.

**Comment by rgutierrezatx** [comment]
aha!  thanks!

**Comment by nigel-sampson** [comment]
Thank you for the catch, I've updated the release notes to include the change.

**Comment by PhilPJL** [comment]
I had the same issue.  Can you point me at the release notes?

**Comment by nigel-sampson** [comment]
[Release notes](https://github.com/Caliburn-Micro/Caliburn.Micro/releases/tag/3.0.2). Still need to update the main website.

**Comment by PhilPJL** [comment]
So is this something you need to fix, or something I need to fix in my code?

**Comment by nigel-sampson** [comment]
It was a bug that we weren't going to the container for views (well we were but just via `GetAllInstances`) and not `GetInstance`. 

It's something that you'll need to deal with on your end if you're throwing exceptions for null resolution.
