### ISSUE TITLE
Can't get Caliburn.Micro.Start 3.0.2 to work with the current documentation

### ISSUE THREAD

**Issue by mika-s** [Caliburn-Micro/Caliburn.Micro#397]
I am trying to use Caliburn.Micro in an application and using [this](http://caliburnmicro.com/documentation/nuget) procedure on how to set it up. After following all the steps the application crashes at start up with the following exception: System.InvalidOperationException: Could not locate any instances. This happens in GetInstance() in AppBootstrapper.cs.

I've used version 3.0.1 in another small application before and then it worked fine. I also tried downloading that version now and it worked fine when I followed the steps in the procedure I linked to. So it seems something changed in the latest version.

Is there something else we have to do in the latest version?

**Comment by nigel-sampson** [comment]
Yup, one small change (bottom one in the [Release Notes](https://github.com/Caliburn-Micro/Caliburn.Micro/releases/tag/3.0.2)) has had a larger impact than I expected.

Will look into it soon and push a solution.

**Comment by mika-s** [comment]
I guess I should've read the release notes. Thanks for the answer (and future fix).

**Comment by nigel-sampson** [comment]
I've made an update to the Start package content which will got out in the next update.

For now replace `GetInstance` in `AppBootstrapper` with

``` csharp
protected override object GetInstance(Type service, string key) {
    return container.GetInstance(service, key);
}
```
