### ISSUE TITLE
Tab Control EvenTrigger

### ISSUE THREAD

**Issue by Olegna** [Caliburn-Micro/Caliburn.Micro#399]
From TabablzControl of Dragablz.
```
<dblz:TabablzControl x:Name="MainTab" ItemsSource="{Binding ViewModelList}">
	<i:Interaction.Triggers>
		<i:EventTrigger EventName="SelectionChanged">
			<cm:ActionMessage MethodName="SetView">
				<cm:Parameter Value="List"/>
			</cm:ActionMessage>
		</i:EventTrigger>
	</i:Interaction.Triggers>
</dblz:TabablzControl>
```
ViewModelList is a collection of Screen
Those Screens are:
- BranchViewModel
- DepartmentViewModel
- CategoryViewModel

The View of BranchViewModel has a TabControl inside.
when i switch tabs on this view. the MainTab or the dblz:TabablzControl 
SelectionChanged EventTrigger gets fired.
i dont know were is the issue here.. is it on CM or Dragablz control. can you please help me out. 
Thank you.

**Comment by nigel-sampson** [comment]
Is it possible for you to upload a repro of this problem to GitHub to help me track down the problem?

**Comment by nigel-sampson** [comment]
Closing out as not extra information received.
