### ISSUE TITLE
Add control naming conventions

### ISSUE THREAD

**Issue by Athari** [Caliburn-Micro/Caliburn.Micro#40]
From [StackOverflow question](http://stackoverflow.com/questions/23696056/control-naming-conventions-in-caliburn-micro-framework):

Caliburn.Micro allows configuring naming conventions for views and view models, but I couldn't find how to configure matching between controls and methods/properties. I know I can just use `Message.Attach` attached property, but I'd like to rely on conventions if it's possible.

Caliburn.Micro's conventions say that methods must be named the same as controls. But here lies a problem: they are often named differently. For example, `Save` and `Cancel` are good names for methods, but bad names for buttons. `SaveButton` and `CancelButton` are good names for buttons, but bad names for methods. Considering XAML is less strictly typed than C#, Hungarian notation can be useful too, but names like `btnSave` and `btnCancel` are unacceptable for methods.

It would be nice if Caliburn.Micro supported custom rules for control naming conventions. For example, rules could be used to remove suffixes like `Button` and `List`, or remove Hungarian prefixes like `btn` and `lst`.

**Comment by nigel-sampson** [comment]
Going to close this out as I don't think it's something that should be added to the framework itself.

If someone does want this there is an extension point to help enable it.
