### ISSUE TITLE
3.0.1 -> 3.0.2 SimpleContainer GetInstance issue

### ISSUE THREAD

**Issue by johnernaut** [Caliburn-Micro/Caliburn.Micro#400]
After upgrading from 3.0.1 to 3.0.2, the `GetInstance` override in my custom `BootstrapperBase` class throws an error saying it can't find the specified view model. 

![capture](https://cloud.githubusercontent.com/assets/504361/21511078/ad069276-cc61-11e6-8ebb-b7912527d1ee.PNG)

If I downgrade back to 3.0.1, the issue goes away.  I wish I could give more details but I'm not sure how to debug this as I'm new to WPF in general.  I've created a skeleton sample project where this issue can be observed [on GitHub](https://github.com/johnernaut/MegaImport).

**Comment by nigel-sampson** [comment]
Hi,

There was an unintended breaking change (I'm considering rolling it back) where views are attempted to be resolved from the container.

Your code above is failing if the container can't resolve the view.

Adding similar code to this commit (23e8a6d) will resolve it,

**Comment by johnernaut** [comment]
Thanks for the information.  I really appreciate you taking the time to look at this.
