### ISSUE TITLE
OnDeactivate being called twice by the conductor

### ISSUE THREAD

**Issue by heldercosta90** [Caliburn-Micro/Caliburn.Micro#405]
Hi all,

I'm facing an issue on the OnDeactivate method from Screen on caliburn version 3.0.1.
So, having a condutor (OneActive) with some items on it, the OnActivate/OnDeactivate methods are called correctly every time I switch the ActiveItem. But when I deactivate the condutor, all the of the items are being deactivated, even those that are already deactivated, with the close flag set to true.

If the item i already deactivated, why calling the deactivation method again?
This is bug or is intended to work this way?

Regards,
Hélder Costa

**Comment by nigel-sampson** [comment]
It's intended to work this way, with the conductor as you move between active items it will deactivate the previously active time as expected (with close set to false).

When the conductor itself is closed then it will close the child view models (all of them).

This gives you a chance for the view model to clean up any resources that it's holding etc.

Essentially the two calls are the difference between not being shown at the moment but could be later on and being closed / disposed.
