### ISSUE TITLE
Best way for themes support?

### ISSUE THREAD

**Issue by rolikoff** [Caliburn-Micro/Caliburn.Micro#406]
I'm working on WPF application (`ViewModel` first) which should be able to switch themes on the fly. By themes I mean the `ViewModels` remain the same but the `Views` represent a theme. I read all the documentation several times but still can't find a good way to do this. I could use `ViewModelBinder` but not sure if there's a way to refresh the screen after that. Here's the example of what's needed:
The app has the next viewmodels

**ViewModels**
 - ShellViewModel.cs
 - LoginViewModel.cs
 - DashboardViewModel.cs
 - InfoViewModel.cs

**Views**
 - **Theme1**
    - **Login**
       - NotLogged.xaml
       - LogginIn.xaml
    - ShellView.xaml
    - LoginView.xaml
    - DashboardView.xaml
    - InfoView.xaml
 - **Theme1**
    - **Login**
       - NotLogged.xaml
       - LogginIn.xaml
    - ShellView.xaml
    - LoginView.xaml
    - DashboardView.xaml
    - InfoView.xaml

LoginView has ContentControl  `<ContentControl cal:View.Context="{Binding State} cal:View.Model={Binding}">` when `State` is either `LoggingIn` or `NotLogged`. 

What would be the best approach for this?

**Comment by nigel-sampson** [comment]
Just to clarify, you have completely separate views per theme?

What you may want to do is to modify the `ViewLocator` use the current theme as part of view location.

The method you're looking to modify will be `TransformName`, something akin to.

``` csharp
var defaultTransformName = ViewLocator.TransformName;

ViewLocator.TransformName = (typeName, context) =>
{
    var defaultViews = defaultTransformName(typeName, context);
    var themedViews = new List<string>();

   foreach(var defaultView in defaultViews)
   {
       var themedView =  ... // add theme information

      themedViews.Add(themedView);
   }

   return themedViews;
};
```

**Comment by rolikoff** [comment]
>Just to clarify, you have completely separate views per theme?
Yes and no, ShellView can be shared between themes because this is basically a window with `<ContentControl >`. I can bind a style for ShellView and change it depends on what theme is selected. 
Actually, I have already resolved my issue. I have ShellView which has the default namespace for views: `MyApp.Views.ShellView`. Here's the code that allows to load the right theme on startup:
```class ShellViewModel : Conductor<object>.Collection.OneActive, IShell
...
        protected override void OnViewAttached(object view, object context)
        {
            base.OnViewAttached(view, context);

            TypeMappingConfiguration config = new TypeMappingConfiguration();
            config.DefaultSubNamespaceForViewModels = "ViewModels";
            config.DefaultSubNamespaceForViews = "Views.Theme1";

            ViewLocator.ConfigureTypeMappings(config);
            ViewModelLocator.ConfigureTypeMappings(config);
        }
```

There's a method in ShellViewModel:

```
public void SwitchTheme(string theme)  {
            TypeMappingConfiguration config = new TypeMappingConfiguration();

            config.DefaultSubNamespaceForViewModels = "ViewModels";
            config.DefaultSubNamespaceForViews = "Views.{theme}";

            ViewLocator.ConfigureTypeMappings(config);
            ViewModelLocator.ConfigureTypeMappings(config);
            
            DependencyObject view = ViewLocator.LocateForModel(viewModel, null, null);
            ViewModelBinder.Bind(viewModel, view, null);

            ActivateItem(viewModel);
}
```
The code above reconfigures the type mapping for views and 'reload' the view.

**Comment by nigel-sampson** [comment]
An interesting way to do it, glad you managed to solve it.

If you weren't already using context for something else I'd suggest using it for the theme. That way as the context changes the views automatically updated

**Comment by rolikoff** [comment]
well I'm using `cal:View.Context` for some child views, also I have TabControl on one of the views.
If I set a new context in ShellView for ContentControl, e.g.:
```
<ContentControl cal:View.Context="{Binding Theme}" cal:View.Model={Binding}">
```
how can the context be changed for child views then? e.g.
LoginView.xaml:
```
...
<ContentControl cal:View.Context="{Binding LoginState}" cal:View.Model={Binding}">
...
```
LoginState should also be aware of what Theme is being used right now. I could write a converter, something like: 
```
namespace MyApp.ValueConverters
{
    class ViewNamespaceConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            
            return $"{(string) parameter}.{value}";
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}
```
And then use the next for LoginView ContentContol:
```
 <ContentControl cal:View.Context="{Binding LoginState, Converter={StaticResource ViewNamespaceConverter}, ConverterParameter='Theme1'}" cal:View.Model="{Binding}" />
```
This would work but things are getting funky if I use TabContent in one of child views. That said, changing the default namespace in ShellViewModel is a bit hacky but workable way to separate the views for each theme. 

Anyways, I'm not sure if there's a better way to handle themes.

**Comment by nigel-sampson** [comment]
One problem with using context would be make sure all bindings to `cm:View.Context` are updated.

Having the source of context binding to something else (a global resource could be the best way.

Using the converter to "amend" the context is an approach I hadn't thought of.
