### ISSUE TITLE
[WPF] Message.Attach is disabling ListBoxItem, but it shouldn't.

### ISSUE THREAD

**Issue by JobaDiniz** [Caliburn-Micro/Caliburn.Micro#410]
I have a `Message.Attach` in the *MouseDoubleClick* event:
```
 <Style TargetType="ListBoxItem" BasedOn="{StaticResource {x:Type ListBoxItem}}">
     <Setter Property="cal:Message.Attach" Value="[Event MouseDoubleClick] = [Action EditItem($dataContext)]"/>
```

I have `EditItem` and `CanEditItem` in the ViewModel, however it shouldn't disable the ListBoxItem. If `CanEditItem` returns false, Caliburn shouldn't disable the entire ListBoxItem... I can't even right-click in the ListBoxItem.

Why it is disabling ListBoxItem? Is that a bug? How can I overcome this problem without removing `CanEditItem` from ViewModel (it is used elsewhere)?

**Comment by nigel-sampson** [comment]
The framework by design disables the control, this is intended for controls such as `Button`, a longer explanation is on #411 .
