### ISSUE TITLE
WPF, cal:Message.Attach disable DataGrid when it should not.

### ISSUE THREAD

**Issue by adupontxpertdoc** [Caliburn-Micro/Caliburn.Micro#411]
I have a property bool CanEdit, which is not used by any cal:Message.Attach statements in my XAML file.
But the CanEdit properties is called by Cabliburn and disable the complete control.

XAML:
<Controls:MetroWindow x:Class="Xpertdoc.Designer.WordAddin.Views.TestCaseManagerView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:Controls="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:res="clr-namespace:Xpertdoc.Designer.WordAddin.Properties"
             xmlns:local="clr-namespace:Xpertdoc.Designer.WordAddin.Views"
             xmlns:vw="clr-namespace:Xpertdoc.Designer.WordAddin.ViewModels"
             xmlns:Converters="clr-namespace:Xpertdoc.Designer.WordAddin.Views.Converters"
             xmlns:Helpers="clr-namespace:Xpertdoc.Designer.WordAddin.Helpers"
             xmlns:cal="http://www.caliburnproject.org"
             cal:Message.Attach="[Gesture F3] = [FindNextGestureKey];
                                [Gesture Shift+F3] = [FindPreviousGestureKey];
                                [Gesture Alt+F3] = [ReplaceGestureKey];
                                [Gesture Alt+A] = [ReplaceAllGestureKey];
                                [Gesture Ctrl+Shift+F] = [FindGestureKey];
                                [Gesture Ctrl+Shift+H] = [ReplaceGestureKey]"

             EnableDWMDropShadow="True"
             BorderThickness="1"
             mc:Ignorable="d"
             TitleForeground="Black"
             Width="600"
             Height="400"
             WindowStartupLocation="CenterScreen"
             d:DesignHeight="300" d:DesignWidth="300">
    <Controls:MetroWindow.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary>
                    <Converters:InvertBoolConverter x:Key="InvertBoolConverter"/>
                    <Converters:BooleanAndConverter  x:Key="BooleanAndConverter"/>
                    <BooleanToVisibilityConverter x:Key="BoolToVisibility"/>
                </ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Controls:MetroWindow.Resources>
    <Controls:MetroWindow.IconTemplate>
        <DataTemplate>
            <Grid Width="{TemplateBinding Height}"
                  Height="{TemplateBinding Height}"
                  Background="{DynamicResource HighlightBrush}">
                <Rectangle Height="{TemplateBinding Height}"
                               Width="{TemplateBinding Height}"
                               Margin="3"
                               Fill="{DynamicResource WhiteBrush}">
                    <Rectangle.OpacityMask>
                        <VisualBrush Visual="{StaticResource appbar_settings}" Stretch="Uniform" />
                    </Rectangle.OpacityMask>
                </Rectangle>
            </Grid>
        </DataTemplate>
    </Controls:MetroWindow.IconTemplate>
    <Border Margin="0,-2,0,0"
            BorderThickness="0,2,0,0"
            BorderBrush="{DynamicResource DarkBrush}">
        <Grid Margin="10">
            <Grid.RowDefinitions>
                <RowDefinition Height="*"/>
                <RowDefinition Height="auto"/>
            </Grid.RowDefinitions>
            <DataGrid x:Name="Assemblies"
                      Grid.Column="0"
                      HorizontalAlignment="Stretch"
                      VerticalAlignment="Stretch"
                      ItemsSource="{Binding }"
                      SelectedItem="{Binding SelectedItem, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                      AutoGenerateColumns="False"
                      Margin="0,0,0,4"
                      IsReadOnly="True"
                      VirtualizingPanel.ScrollUnit="Pixel">
                <DataGrid.Columns>
                    <DataGridTemplateColumn x:Name="Default" Width="auto">
                        <DataGridTemplateColumn.CellTemplate>
                            <DataTemplate>
                                <Grid>
                                    <Image x:Name="DefaultImage"
                                       Source="{Binding IsDefault, Converter={Converters:DefaultImageConverter}}"
                                       Height="16"
                                       Width="16"
                                       Stretch="None"/>
                                </Grid>
                            </DataTemplate>
                        </DataGridTemplateColumn.CellTemplate>
                    </DataGridTemplateColumn>
                    <DataGridTextColumn Width="*"
                                        Header="{x:Static res:Resources.TestCase_Name}"
                                        Binding="{Binding TestCaseName}" />
                </DataGrid.Columns>
                <DataGrid.RowStyle>
                    <Style TargetType="DataGridRow" BasedOn="{StaticResource MetroDataGridRow}">
                        <Setter Property="cal:Message.Attach" Value="[Event MouseDoubleClick] = [Action Edit]"/>
                        <Setter Property="MinHeight" Value="26"/>
                        <Style.Triggers>
                            <DataTrigger Binding="{Binding Path=IsMouseOver, RelativeSource={RelativeSource Self}}" Value="true">
                                <Setter Property="Foreground" Value="White" />
                            </DataTrigger>
                        </Style.Triggers>
                    </Style>
                </DataGrid.RowStyle>
            </DataGrid>
            <StackPanel Height="30" Grid.Row="1" Orientation="Horizontal" Margin="2" HorizontalAlignment="Right">
                <Button x:Name="SetDefault"
                        IsDefault="True"
                        Style="{DynamicResource CustomSquareButtonStyle}"
                        Controls:ButtonHelper.PreserveTextCase="True"
                        Margin="4,0,0,0"
                        IsEnabled="{Binding HasSelectedItem, UpdateSourceTrigger=PropertyChanged}"
                        Width="80"
                        Content="{x:Static res:Resources.Common_SetDefault}"/>
                <Button x:Name="Add"
                        IsDefault="True"
                        Style="{DynamicResource CustomSquareButtonStyle}"
                        Controls:ButtonHelper.PreserveTextCase="True"
                        Margin="4,0,0,0"
                        Width="80"
                        Content="{x:Static res:Resources.Common_Add}"/>
                <Button x:Name="Remove"
                        IsDefault="True"
                        Style="{DynamicResource CustomSquareButtonStyle}"
                        Controls:ButtonHelper.PreserveTextCase="True"
                        Margin="4,0,0,0"
                        Width="80"
                        Content="{x:Static res:Resources.Common_Delete}"/>
                <Button x:Name="Save"
                        IsDefault="True"
                        Style="{DynamicResource CustomSquareButtonStyle}"
                        Controls:ButtonHelper.PreserveTextCase="True"
                        Margin="4,0,0,0"
                        Width="80"
                        Content="{x:Static res:Resources.Common_Ok}"/>
                <Button x:Name="Cancel"
                        IsCancel="True"
                        Controls:ButtonHelper.PreserveTextCase="True"
                        Width="80"
                        Margin="4,0,0,0"
                        Content="{x:Static res:Resources.Common_Cancel}"/>
            </StackPanel>
        </Grid>
    </Border>
</Controls:MetroWindow>

**Comment by mvermef** [comment]
Ahh the beauty of convention because you merely declared Edit method in your DataGridRow template and happen to have matching property called CanEdit.  CM automatically kicks in whether you call it or not, by convention and wires it up.

**Comment by adupontxpertdoc** [comment]
I was expecting that the action is disable not the UserControl.

**Comment by nigel-sampson** [comment]
@mvermef is correct here, when the guard method / property returns false the convention will disable the control. This makes sense for controls such as `Button` but can cause problems when applied to containers such as `DataGridRow`.

To avoid this you would need to rename `CanEdit` to something else (and check it explicitly in `Edit`).

I wonder if an attached property such as `cm:DisableGuardDisable="true"` (with a much better name) makes sense?

**Comment by JobaDiniz** [comment]
Could you dig in details how one can implement such attached property? I need that. 😊

**Comment by nigel-sampson** [comment]
You'd be modifying the behavior of the framework using [`ActionMessage.ApplyAvailabilityEffect `](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ActionMessage.cs#L343).

A really simple solution to the above instance would be

``` csharp
var defaultApplyAvailabilityEffect = ActionMessage.ApplyAvailabilityEffect;

ActionMessage.ApplyAvailabilityEffect  = context =>
{
    if (context.Source is DataGridRow)
        return true;

    return defaultApplyAvailabilityEffect(context);
};
```

You could of course make the injected logic as complicated as you want.

**Comment by JobaDiniz** [comment]
> I was expecting that the action is disable not the UserControl.

Exactly @adupontxpertdoc . Some actions don't make sense to disable the control, `MouseDoubleClick` is one of them.

**Comment by nigel-sampson** [comment]
The action itself is decoupled from the trigger. 

By "action is disabled" I assume you mean that action is not called.

Trouble with any convention is that people will have different scenarios where `MouseDoubleClick` makes perfect sense to have the control disabled. I don't think we'd ever have logic based around the trigger as it's far too subjective, you're more likely to have configuration based around the type of control.

**Comment by adupontxpertdoc** [comment]
In general, action  shall not disable any control when Can properties exist. For example with KeyGesture:
**cal:Message.Attach="[Gesture F3] = [FindNextGestureKey]"**.
If my View model contains CanFindNextGestureKey presently the framework will disable all the control. The expected behaviour is that F3's action will not be called when the user press F3 if CanFindNextGestureKey returns false but the control is still enabled.

**Comment by nigel-sampson** [comment]
Respectfully disagree here, we've found it's more common that controls should be disabled for actions where the guard property / method returns false such as `Button` etc.

There are circumstances such as your example above where it's not the desired behavior and you can disable it if you wish but I don't see this changing (it would be a major breaking change if it was).

If you want to disable it application wide setting the following in your startup code will do the trick.

``` csharp
ActionMessage.ApplyAvailabilityEffect  = context => true;
```

**Comment by JobaDiniz** [comment]
I agree with you @nigel, but wish it would be a bit easier to override this behavior for specific actions, such as *MouseDoubleClick*, not by context.Source.

**Comment by nigel-sampson** [comment]
It would be a big of a hack but you could filter on `context.EventArgs` which would be `KeyEventArgs` for gestures.
