### ISSUE TITLE
[WPF] How to implement suspend/resume when an IResult is executing?

### ISSUE THREAD

**Issue by zhaosih** [Caliburn-Micro/Caliburn.Micro#412]
I have  a loop in Execute(CoroutineExecutionContext context). Is there a method let it to listen to  an signal, to suspend or resume the execution

**Comment by nigel-sampson** [comment]
There isn't a mechanism in coroutines to support suspension / resumption.

However as long as you're using `yield` within the coroutine you get lazy evaluation. You could have a boolean property on your view model that;s hooked up to your pause / resume actions. Checking that property in the loop would work, however you'd want to introduce a delay, a tight loop would be a bad idea.

**Comment by zhaosih** [comment]
Then is it possible to make coroutine run a separated thread by default?  After I clicked the pause button to reset ManualResetEvent, the main thread is suspended, and can't accept any button click on UI

**Comment by nigel-sampson** [comment]
It would be difficult, you may want to more away from coroutines entirely and just deal with the threading by yourself. You'd especially not want to block the UI thread.
