### ISSUE TITLE
Fantastic Job

### ISSUE THREAD

**Issue by Noemata** [Caliburn-Micro/Caliburn.Micro#415]
Because there is no other place to say this that is close to the repository, I would like give Nigel Sampson a BIG thank you for doing a fantastic job of carrying the Caliburn.Micro sword forward!

His efforts have helped mine greatly and I suspect the work of many others.

**Comment by tanwarsatya** [comment]
Yes, a very big thanks for helping us all.

**Comment by nigel-sampson** [comment]
Thanks, for the kinds words, feels odd to close this 👍
