### ISSUE TITLE
Event Aggregator marshaller set by subscription

### ISSUE THREAD

**Issue by jozefizso** [Caliburn-Micro/Caliburn.Micro#416]
Is it viable to have IEventAggregator where the subscriber will specify the type of thread marshaller it supports (UI thread vs background job) and the event aggregator Publish() method will be thread agnostic?

For example, MvvmCross `IMvxMessenger` interface has these methods:

```
Subscribe()
SubscribeOnMainThread()
SubscribeOnThreadPoolThread()
Publish()
```

Can this pattern be used with Caliburn? Or are there some specifics why Caliburn requires the Publisher to set the thread?

**Comment by nigel-sampson** [comment]
At the moment this wouldn't be possible with extensions to the `EventAggregator`, there aren't any specific reasons why it was done this way (publisher specifying the threading rather than the subscriber).

**Comment by nigel-sampson** [comment]
Thinking about this some more, it should be easy to follow the `Publish` pattern and have an overload of `Subscribe` that takes a marshaling method.

Extensions for the examples above could then all be provided.

**Comment by nigel-sampson** [comment]
Realised this will need to be a breaking change on the `IEventAggregator` interface and should be in `4.0.0`.

**Comment by nigel-sampson** [comment]
This is done now as part of `4.0.0` and #496
