### ISSUE TITLE
The WPF Control [Frame]'s Convention doesn't work. 

### ISSUE THREAD

**Issue by ipooov** [Caliburn-Micro/Caliburn.Micro#417]
Hi,
I am studying Caliburn.Micro  and meet a question.
I write some code like below in WPF, but it can't work successful:
`    <Frame x:Name="ActiveItem" NavigationUIVisibility="Hidden"  />`

ActiveItem is in the view's ViewModel . It bind some Page. And I have already use AddElementConvention method add Frame's convention ,like ContentControl.

I tried to get a answer:
In the method SetContentPropertyCore (in View.cs line 398)
```
   var contentProperty = type.GetAttributes<ContentPropertyAttribute>(true)
                                          .FirstOrDefault() ?? DefaultContentProperty;

        type.GetProperty(contentProperty.Name)
                    .SetValue(targetLocation, view, null);
```

here contentProperty.Name is null but contentProperty is not null.

Maybe because Frame has its own ContentPropertyAttribute but has no name  :

```
[ContentProperty]
[DefaultEvent("Navigated")]
[DefaultProperty("Source")]
[Localizability(LocalizationCategory.Ignore)]
[TemplatePart(Name = "PART_FrameCP", Type = typeof(ContentPresenter))]
public class Frame : ContentControl, INavigator, INavigatorImpl, IJournalNavigationScopeHost, INavigatorBase, IDownloader, IJournalState, IAddChild, IUriContext

```

Please help resolve it and publish in next version, thanks a lot .

**Comment by nigel-sampson** [comment]
Yup, that looks to be the problem (`ContentPropertyAttribute` with no name).

Thanks for reporting that.

**Comment by ipooov** [comment]
Thanks.
I tried to add Frame's ContentPropertyAttribute Name, And it works well.
