### ISSUE TITLE
AssemblySource not extracting view types in NET45

### ISSUE THREAD

**Issue by smischke** [Caliburn-Micro/Caliburn.Micro#419]
Since "ExtractTypes" is defined like this...
```
        /// <summary>
        /// Extracts the types from the spezified assembly for storing in the cache.
        /// </summary>
        public static Func<Assembly, IEnumerable<Type>> ExtractTypes = assembly =>
            assembly.GetExportedTypes()
                .Where(t =>
#if !CORE
                    typeof(UIElement).IsAssignableFrom(t) ||
#endif
                    typeof(INotifyPropertyChanged).IsAssignableFrom(t));
```
... and taken from "Caliburn.Micro.Platform.Core" in NET45 where "CORE" is defined (as opposed to NET4 where it's taken from "Caliburn.Micro.Platform.NET40"), view types are not extracted in NET45. One can easily fix this by setting one's own "ExtractTypes" function, but the default behavior is inconsistent between NET4 and NET45.

**Comment by nigel-sampson** [comment]
Thanks for the bug report.

**Comment by smischke** [comment]
Please ignore and close this issue. It was all my fault because I did not call "Initialize()" in my derived "AppBootstrapper : BootstrapperBase" but "StartRuntime()". There is no bug.

**Comment by nigel-sampson** [comment]
Good to hear :-) thanks,
