### ISSUE TITLE
How to apply conventions to external hosting view (DXDialog)

### ISSUE THREAD

**Issue by nologinatgit** [Caliburn-Micro/Caliburn.Micro#420]
I have a `DXDialog `WPF component (it is a Window descendant with public Button objects): [DXDialog](https://documentation.devexpress.com/#WPF/clsDevExpressXpfCoreDXDialogtopic)

I have created a custom `View `and `ViewModel` for its `Content `and it works.

The dialog has public buttons, one of them is called `OkButton`.

I intend to have a public method called `OkButton `in my custom `ViewModel`.

Unfortunately, when I call the following code, it does not apply any convention (like if it skipped the hosting control, and only the "inner" view is processed).

This is how I try to force the use of conventions:

```csharp
 protected override Window CreateWindow(object rootModel, bool isDialog, object context, IDictionary<string, object> settings)
    {
      var tmpWindow = base.CreateWindow(rootModel, isDialog, context, settings);
      DXDialog dialog = new DXDialog();
      dialog.Content = tmpWindow.Content;
      dialog.DataContext = rootModel;
      dialog.MinHeight = 150;
      dialog.MinWidth = 300;
      dialog.SizeToContent = SizeToContent.WidthAndHeight;
      dialog.ResizeMode = ResizeMode.NoResize;
      dialog.WindowStartupLocation = WindowStartupLocation.CenterOwner;
      dialog.SetValue(View.IsGeneratedProperty, false);
      dialog.SetValue(View.ApplyConventionsProperty, true);

      dialog.Loaded += (x, y) => { SetItems(dialog); ViewModelBinder.Bind(rootModel, dialog, context); };
      tmpWindow = null;
      return dialog;
    }
```
My ViewModel:

```csharp
public class CustomViewModel: ViewAware, IClose
{
   public void OkButton()
   {
    //Do something
   }
}
```

I can see this in the log:

> CM_INFO: Binding DevExpress.Xpf.Core.DXDialog and MyProject.ViewModel.CustomViewModel.
> CM_INFO: Setting DC of DevExpress.Xpf.Core.DXDialog to MyProject.ViewModel.CustomViewModel.
> ...
> CM_INFO: Action Convention Not Applied: No actionable element for OkButton.

Any idea how I could make it work?

**Comment by mvermef** [comment]
I would expect this to fail, instead I would've created a custom IWindowManager extension class to get what you are looking for from the control.  

Secondly modifying that one method had consequences when used for other dialogs later.

Lastly, conventions aren't something applied to 3rd party controls unless you create the convention in your Bootstrapper.  Most built in controls have conventions some don't, higher complexity of the control is usually the cut off (DataGrid for example).

**Comment by nologinatgit** [comment]
The hosting DXDialog has _SimpleButton_ buttons which are _descendants_ of the basic Button class. I would expect them to be handled like "regular" buttons.

What convention should I apply?

I found [here ](http://putridparrot.com/blog/caliburn-micro-convention-based-binding/)the following as the inner convention of the button click:
`AddElementConvention<ButtonBase>(ButtonBase.ContentProperty, "DataContext", "Click");`

Should I add this to my ConventionManager?
`AddElementConvention<SimpleButton>(SimpleButton.ContentProperty, "DataContext", "Click");`

**Comment by a5rGithub** [comment]
Note that there is already a basic devexpress conventions library. Did You give that a try? https://calmicrodevexpress.codeplex.com/

**Comment by mvermef** [comment]
That might work what I have a feeling might also be part of the issue is that the buttons being part of that 3rd party control set, even if they are base class controls they are buried deep and could be a visualtree issue.  That convention might work since they are creating their own namely SimpleButton.  Worst case it doesn't work and best case of course you have success :).

**Comment by nologinatgit** [comment]
Well, it didn't work :)

Here is the fill source code of what I have tried: http://pastebin.com/xNn23q1s

As you can see, I did a workaround to make the 3rd party buttons work:

```csharp
      foreach (var button in buttons)
      {
        button.Template = controlTemplate;
        Message.SetAttach(button, $"[Click] = [{button.Name}]");
      }
```
It "looks" like it works via a convention, as I can create an _OkButton_ methon in my viewmodel and it will call that(though it is not so elegant).

However, there still are 2 major issues (one of the has a not-so-nice workaround):

1. I can't control the closing of the dialog with _CanClose_.
 I guess the problem this:
   - I create a well-decorated window (it can be controlled via _CanClose_) but _I don't use it_, as I create a brand new window(_DXDialog_) and copy _its content only_:


```csharp
     var tmpWindow = base.CreateWindow(rootModel, isDialog, context, settings);
     dialog.Content = tmpWindow.Content;
     dialog.DataContext = rootModel;
```

   - So the closing mechaninsm stays in _tmpWindow_, and my dialog will be close no matter what.

2. I can't control the _IsEnabled_ state of _OkButton_ and _YesButton_. I created a workaround for that by adding a binding path to the window settings but it seems like a hack:

```csharp
   if (bindingContext != null && !string.IsNullOrEmpty(bindingPath))
   {
     binding = new Binding(bindingPath) { Source = bindingContext };
     OkButton.SetBinding(IsEnabledProperty, binding);
   }
```   

I did a failed attempt to copy the _whole content_ of the dialog into tmpWindow, but the _FindVisualChild_ method does not find anything, so I didn't pursue that...

So, can you give me any advice how I could make this code more Caliburn-like? Can I add some _CanClose_ guarding without copying the source from the Screen class?
Any hit is much appreciated :)

**Comment by nigel-sampson** [comment]
It's certainly an interesting one, the problem appears to be the discovery of the named button.

Roughly the conventions are applied is to build a list of named elements in the view through `BindingScope.GetNamedElements` and then comparing to a list of methods on the view model.

It would be interesting to run the above method on your dialog and see what it returns and if possible debug in and see how it's internal structure is navigated.

If nothing comes out of that (the buttons aren't in the list at all etc) then you can customize the behavior of `BindingScope.GetNamedElements` using `AddChildResolver`.

In your set up code you could do something long the lines of 

``` csharp
BindingScope.AddChildResolver<DXDialog>(e => new[] { e.OkButton });
```

**Comment by nigel-sampson** [comment]
Does the above resolve your issue?

**Comment by nologinatgit** [comment]
We have decided to abandon the DXDialog approach, so I can't confirm whether your suggestion works. I'm eager to test it but in the near future, I can't see when :/

**Comment by nigel-sampson** [comment]
No worries, thanks for the information.
