### ISSUE TITLE
Re-entrancy issue with async actions

### ISSUE THREAD

**Issue by Qamo** [Caliburn-Micro/Caliburn.Micro#422]
Think of a button on the UI which calls an async action on the target ViewModel:

```
public async Task DoSomething()
{
    await Task.Delay(5000);
}
```

This does not block the UI (which is what we want) but it will also allow to press the button again, resulting in the action being invoked again, while the previous action is not yet completed (which we don't want).

A common solution to this would be to disable/enable the button or to serialize the calls using a semaphore or to early return from the method on the second invocation.

But having dozens of such action invocations all over the place would introduce a lot of "code noise" in the view models.

It would be nice, to be able to tell caliburn micro, to not invoke an action on a target when a previous action is not yet finished. Something like this:

`<Button cal:Message.Attach="DoSomething" cal:Message:Reentrancy="false" />`

Would this be a good idea? Or is there already a way to do this?

**Comment by nigel-sampson** [comment]
You could probably do something easily using guard methods.

``` csharp
public bool CanDoSomething { ... } // normal bool property with change notficiations

public async Task DoSomething()
{
    CanDoSomething = false;

    await Task.Delay(5000);

    CanDoSomething = true;
}
```

**Comment by Qamo** [comment]
Yes, this surely is a way to do this, but I'm trying to avoid touching the ViewModels. Adding guard methods everywhere is a lot of ceremony. The application I'm working on right now has >840 plain Buttons in total (Maybe 10-20% will trigger an async method).

Maybe something can be done by hooking into ActionMessage.InvokeAction. At least the enable/disable of the target should be possible to do this way (but it might interfere with guard properties, which the invoked action might set). I could also use a dictionary there to register a SlimSemaphore per target to be able to serialize the calls.

**Comment by nigel-sampson** [comment]
Hooking into `ActionMessage.InvokeAction` is certainly an option. What I'd do is customize what happens when we find a `Task` at [this line](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ActionMessage.cs#L313). 

I'd create a new 'IResult` that can manipulate the source object (the Button), so instead of just resolving the task into one co-routine item it becomes three.

There could be some conflict with the guard properties, but as long as those properties don't fire change notifications during the method then you should be fine.

**Comment by e-tobi** [comment]
I ran into the same issue recently and solved it like this:

When the IsNonReentrant DP is set, check the ReentranceLock DP and if it is set, return without executing the action. Otherwise set the ReentranceLock DP, wrap the Task to reset the ReentranceLock on completion and continue as usual.

```
public class CaliburnBootstrapper : BootstrapperBase
{
    public static readonly Logger Log = NLog.LogManager.GetCurrentClassLogger();

    public CaliburnBootstrapper()
    {
        Initialize();
        ActionMessage.InvokeAction = context =>
        {
            var avoidReentrance = context.Method.ReturnType == typeof(Task) && CaliburnExtensions.GetIsNonReentrant(context.Source);
            if (avoidReentrance && CaliburnExtensions.GetReentranceLock(context.Source)) return;

            var values = MessageBinder.DetermineParameters(context, context.Method.GetParameters());
            var returnValue = context.Method.Invoke(context.Target, values);

            var task = returnValue as Task;
            if (avoidReentrance)
            {
                CaliburnExtensions.SetReentranceLock(context.Source, true);
                task = WrapTask(context.Source, task);
            }

            if (task != null)
            {
                returnValue = task.AsResult();
            }

            var result = returnValue as IResult;
            if (result != null)
            {
                returnValue = new[] { result };
            }

            var enumerable = returnValue as IEnumerable<IResult>;
            if (enumerable != null)
            {
                returnValue = enumerable.GetEnumerator();
            }

            var enumerator = returnValue as IEnumerator<IResult>;
            if (enumerator != null)
            {
                Coroutine.BeginExecute(enumerator,
                    new CoroutineExecutionContext
                    {
                        Source = context.Source,
                        View = context.View,
                        Target = context.Target
                    });
            }
        };
    }

    private async Task WrapTask(FrameworkElement source, Task task)
    {
        try
        {
            await task;
        }
        finally 
        {
            CaliburnExtensions.SetReentranceLock(source, false);
        }
    }
}
```
