### ISSUE TITLE
Setting up a new WPF project

### ISSUE THREAD

**Issue by AlbertoDePena** [Caliburn-Micro/Caliburn.Micro#423]
https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/samples/setup/Setup.WPF

Hey, it looks like the window manager must be registered (Bootstrapper class). Otherwise a null exception is thrown.

`container.Singleton<IWindowManager, WindowManager>();`
`container.PerRequest<ShellViewModel>();`

FYI =)

**Comment by nigel-sampson** [comment]
Thanks, not sure how that one slipped through.

**Comment by AlbertoDePena** [comment]
No worries. Keep up the good work =)
