### ISSUE TITLE
The type "CaliburnApplication" is abstract and must include an explicit value UWP

### ISSUE THREAD

**Issue by RikardoPons** [Caliburn-Micro/Caliburn.Micro#425]
Hello! I updated my UWP app from 2.0 to the 3.0.3 version of Caliburn Micro and I have this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The type "CaliburnApplication" is abstract and must include an explicit value.	

In the App.xaml I have this

<cm:CaliburnApplication
    x:Class="AvaxClient.Uwp.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:cm="using:Caliburn.Micro"
    RequestedTheme="Light">
    ...
</cm:CaliburnApplication>

Anyone could help me to fix this problem? 
I guess is a bug.

Thank you

**Comment by nigel-sampson** [comment]
Haven't seen that one before, it is abstract but App.xaml creates a class `App` that inherits from it.

Is it possible to create a repository that shows this problem as I can't create it.

**Comment by RikardoPons** [comment]
Hello! I solved this problem just deleting the bin folder and obj folder, clean & rebuild the solution and now it's working fine. the issue appeared after I updated from Caliburn micro 2.0 to the latest version.

**Comment by nigel-sampson** [comment]
Glad to here it was solved.
