### ISSUE TITLE
WinRTContainer for multiple frames

### ISSUE THREAD

**Issue by TobiasKoller** [Caliburn-Micro/Caliburn.Micro#429]
i was just wondering why the WinRTContainer can only store one INavigationService.
I need to use multiple frames I can navigate in.

You could simply fix this by allowing the RegisterNavigationService-method to take an key-parameter.

this is how I fixed it:

1. I've created a new WinRTContainerEx which inherits from WinRTContainer and only provide this one function:

```
public INavigationService RegisterNavigationService(Frame rootFrame, string key, bool treatViewAsLoaded = false, bool cacheViewModels = false)
        {
            if (HasHandler(typeof(INavigationService), key))
                return this.GetInstance<INavigationService>(key);

            if (rootFrame == null)
                throw new ArgumentNullException("rootFrame");

            var frameAdapter = new FrameAdapter(rootFrame, treatViewAsLoaded);

            RegisterInstance(typeof(INavigationService), key, frameAdapter);

            return frameAdapter;
        }
```

It's almost identical to the current RegisterNavigationService-Method, i only replaced the null-keys with the new one provided by the method.

in my viewmodels I now can simply get the navigationservice for the Frame I want by key:

> _navigationService = _container.RegisterNavigationService(frame, "main");

would be nice if you could implement something like that.

**Comment by nigel-sampson** [comment]
Doesn't sound a like a bad idea, happy to take a pull request on this as it's reasonably low priority (you can do this same code outside of the framework with no problems).

**Comment by TobiasKoller** [comment]
there is a problem with my suggestion. If you have multiple instances of INavigationService registered in the container you can't decide which implementation you want in your
viewModel.

So a better solution would be to create a new class NavigationServiceProvider which keeps all instances.

like:
```

public interface INavigationServiceProvider
{
	INavigationService GetNavigationService(string key);
	void Register(string key, INavigationService service, bool overrideRegistration);
} 


public class NavigationServiceProvider : INavigationServiceProvider
    {
        private Dictionary<string, INavigationService> _services;

        public NavigationServiceProvider()
		{
			_services = new Dictionary<string, INavigationService>();
		}

        public INavigationService GetNavigationService(string key)
        {
            if (!_services.ContainsKey(key))
                throw new KeyNotFoundException($"No NavigationService registered with key [{key}]");

            return _services[key];
        }

        public void Register(string key, INavigationService service, bool overrideRegistration=false)
        {
            if (_services.ContainsKey(key) && !overrideRegistration)
                return;
            if (_services.ContainsKey(key))
                _services[key] = service;
            else
                _services.Add(key, service);
           
        }
    }
	
	

```
and than you simply register the FrameAdapters (here the rootFrame in my app.xaml.cs:

```

protected override void PrepareViewFirst(Frame rootFrame)
{
	var navigationService = new FrameAdapter(rootFrame);
	var provider = new NavigationServiceProvider();
	provider.Register("root", navigationService);

        //Register the provider once
        container.RegisterInstance(typeof(INavigationServiceProvider), null, provider);
}

```

**Comment by nigel-sampson** [comment]
Yeah you're right about the issue there, if you're really looking into something like this I'd recommend moving towards a container that supports things like this directly like Autofac where you can skip creating the provider and have metadata about the navigation service provided by the container.

I don't feel like `NavigationServiceProvider` should be in the framework.

**Comment by Noderino** [comment]
@nigel-sampson How can we use Autofac with navigation? Navigation Sample registers FrameAdapter in ShellViewModel but Autofac does not support adding registrations after container is built. They marked Update method as obsolete.

**Comment by nigel-sampson** [comment]
Interesting.

There seem to be some [recommended work arounds](https://github.com/autofac/Autofac/issues/811) to that behaviour on the Autofac repo.
