### ISSUE TITLE
Error running Setup.Wpf - null reference exception

### ISSUE THREAD

**Issue by kevison** [Caliburn-Micro/Caliburn.Micro#430]
Tried running the Setup.Wpf code... but get an error:

System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Caliburn.Micro.Platform

 This was in the bootstrapper - OnStartup method, DisplayRootViewFor<ShellViewModel> line.

**Comment by nigel-sampson** [comment]
There was an issue in the initial version of `Setup.WPF` that was resolved a few weeks ago? Do you have this version?

**Comment by kevison** [comment]
I believe I did... I did a clone of the repository.

**Comment by nigel-sampson** [comment]
I haven't been able to recreate this locally on a few different machines., `Setup.WPF` compiles and runs correctly.

Can you make sure  you have [this commit](https://github.com/Caliburn-Micro/Caliburn.Micro/commit/8b8e6e4ed441812172504b7ad0de7762a50ebb9e) in your repository?

**Comment by kevison** [comment]
Will do...

**Comment by nigel-sampson** [comment]
Assuming this has been resolved.
