### ISSUE TITLE
Caliburn.Micro.Start Template files encoding.

### ISSUE THREAD

**Issue by a44281071** [Caliburn-Micro/Caliburn.Micro#431]
Can u change all files (AppBootstrapper.cs ShellView.xaml and so on...) encoding to UTF-8?
I have proplem wen edit this files in my os (Chinese location). 
Wish next nuget package can optimize this point, thanks.

**Comment by nigel-sampson** [comment]
It's something I can look into for the next release. However we will be dropping support for that package later on with better support for templates across all platforms.

**Comment by nigel-sampson** [comment]
Can you expand on the problem you're encountering with the files at the moment?

**Comment by nigel-sampson** [comment]
I've checked the encoding on all the content files for that package and they're already all UTF-8
