### ISSUE TITLE
View not displayed on tabbedpage

### ISSUE THREAD

**Issue by infintesoftware** [Caliburn-Micro/Caliburn.Micro#433]
I'm creating application based on features example. I copied conductor view and view model and tab page view and view model to my application. Title is displayed but content no. InitializeComponent from tab page is called (twice per tab?!). I changed datatemplate to using ContetnView but this not helps at all.
I'm using caliburn micro v3.0.3 with Xamarin Forms v2.3.4.231. Any sugestion why content of tabpage is not displaying? 

Even this is not working (strange)
`
<Grid>
        <ContentView cal:View.Model="{Binding Payments}"></ContentView>
    </Grid>
`

PaymentsView is not inserted as content. I see only blank page.

**Comment by nigel-sampson** [comment]
Normally this would be a case of the `PaymentsView` not being found.

Fairly hard to diagnose with the information above. 

Is it possible for you to create a demonstration of the problem as a repository on GitHub and I'll look into the problem,

**Comment by infintesoftware** [comment]
[Simple Example](https://github.com/infintesoftware/caliburnxamarin)

**Comment by nigel-sampson** [comment]
Thanks for the repository, managed to track the issue down.

`TabView` is inheriting from `ContentPage` which unlike the other xaml platforms doesn't inherit from `ContentView` so can't used interchangeably like `Page` and `UserControl` can be in say UWP.

Switching `TabView` to `ContentView` in both the `.xaml` and `.xaml.cs` has it load correctly.

**Comment by iHugoSilva** [comment]
I'm having the same issue @nigel-sampson  , but I didn't understand the solution, the example repo is not there anymore as well

**Comment by nigel-sampson** [comment]
Whenever you see something like the xaml below you can imagine that Caliburn.Micro is examining the type of the `Payments` property on the view model and determining the correct view for that view model. 
``` xml
<ContentView cal:View.Model="{Binding Payments}" />
```
For examples sake we'll say the type of `Payments` is `PaymentsListViewModel`, the view by convention would be `PaymentsListView.`

Caliburn.Micro is then going to instantiate an instance of that view, bind it to the `Payments` property and insert this new view into the `ContentView` above.

Now if you look at the `[Content](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.contentview.content?view=xamarin-forms)` property on `ContentView` you'll see it's of the type `Xamarin.Forms.View`. This means trying to insert a view that doesn't indirectly inherit from `Xamarin.Forms.View` will result in an error.

What you'll notice is that all the `*Page` types in Xamarin.Forms inherit from `Page` and not `View` (XF is special here, in the other xaml stacks you'll see `Page` typeically inherit `View` so the can often be used interchangably). 

What this means that if your `ProductsListView` is a `Page` and not a `View` you won't see the view.
