### ISSUE TITLE
Conductor<Screen>.Collection.OneActive Binding Issue

### ISSUE THREAD

**Issue by rahul7720** [Caliburn-Micro/Caliburn.Micro#435]
When loading ViewModels using Conductor<Screen>.Collection.OneActive.

**Works**
`<TabControl x:Name="Items"/>`

**Not Works**
`<TabControl ItemsSource="{Binding Items, Mode=OneWay}"/>`

The reason for binding the screen explicitly is to disable two way binding as I have enabled the Two way binding globally in CM bootstrapper class.

 binding.Mode = BindingMode.TwoWay;
            binding.NotifyOnSourceUpdated = true;
            binding.NotifyOnTargetUpdated = true;

How can I disable TowWay binding when binding Items collection.

**Comment by nigel-sampson** [comment]
What platform is this on. I don't know of any reason the second example wouldn't work.

However can you define what you mean by "doesn't work"?  The first example uses conventions which means it will also do things like created a binding to `SelectedItem` and create an default `ItemTemplate`.

If you're not doing them manually now then that could be what you're seeing.

**Comment by rahul7720** [comment]
Sorry I forget to mention the platform.

It's in WPF platform and the views are loaded into TabControl. As I'm implementing  OneActive,  one TabItem will be in active state at a time..

`<TabControl ItemsSource="{Binding Items, Mode=OneWay}"/>`

I tried to load a view by calling ActivateItem() method.

**Issue:**

1. The view is got loaded but, the tab item is not in active state. (I'ts grayed and,  I had to manually click the tab Item to activate it).
2. The DisplayName is not shown in TabItem header, instead it shows full qualified  ViewModel name

. Am I missing anything ?

**Comment by nigel-sampson** [comment]
By using your own binding and not the convention then the framework doesn't add anything to the `TabControl` itself, leaving it up to you.

You can see everything the convention is setting up in the [ConventionManager](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ConventionManager.cs#L265).

To completely replace the convention the framework is setting up you would replace
``` xml
<TabControl x:Name="Items"/>
```
with 
``` xml
<TabControl ItemsSource="{Binding Items}" SelectedItem="{Binding ActiveItem, Mode=TwoWay}">
    <TabControl.ContentTemplate>
        <DataTemplate>
            <ContentControl cal:View.Model="{Binding}" VerticalContentAlignment="Stretch" HorizontalContentAlignment="Stretch" IsTabStop="False" />
        </DataTemplate>
    </TabControl.ContentTemplate>
    <TabControl.HeaderTemplate>
        <DataTemplate>
            <TextBlock Text="{Binding DisplayName}" />
        </DataTemplate>
    </TabControl.HeaderTemplate>
</TabControl>
```
