### ISSUE TITLE
Xamarin TapGestureRecognizer binding has no effect

### ISSUE THREAD

**Issue by gregbty** [Caliburn-Micro/Caliburn.Micro#437]
The following doesn't seem to do anything. Is this a limitation of the binding implementation? This binding is being used in Xamarin.Forms.

```csharp
<Label Text="Forgot Password?">
  <Label.GestureRecognizers>
    <TapGestureRecognizer forms:Message.Attach="[Event Tapped] = [Action NavigateToForgotPasswordAsync()]" />
  </Label.GestureRecognizers>
</Label>
```

**Comment by nigel-sampson** [comment]
At the moment this is because `ActionMessage` can attach to `VisualElements` which `TapGestureRecognizer` isn't. 

This is something on the roadmap to look into later on down the line.
