### ISSUE TITLE
String constants as an Action Parameter failed when a comma is included

### ISSUE THREAD

**Issue by Raghava56** [Caliburn-Micro/Caliburn.Micro#439]
Hi,
i am trying to access the string in my viewmodel

``` xml
<Image Source="info.png" cal:Message.Attach="[Event MouseEnter]=[Action MouseOverCallOut('By default, This will be selected')]" Margin="5,0,5,0" />
```

**In my viewmodel**

this Event not triggering
``` csharp
public void MouseOverCallOut(string callOutText)
{
    CallOutMsg = callOutText;
}
```

**Comment by nigel-sampson** [comment]
There's some confusion between the title of the issue and the contents, is the method being called without the parameter being populated or the method not being called at all?

What platform is this happening on?

**Comment by Raghava56** [comment]
Without parameter method is triggered.
if i pass the parameter as string i.e, 'By default, This will be selected' method not called at all.
if i pass parameter as 'Hello' then method is triggering.

**Comment by nigel-sampson** [comment]
It looks like there was a bug in the string parsing that didn't take into account single quotes as being the start of a string so it was broken up into two parameters.

I've pushed a fix that should be included in the next release.

**Comment by Raghava56** [comment]
hi,
it is working with interaction triggers i.e,
```
<i:Interaction.Triggers>
                                                <i:EventTrigger EventName="MouseEnter">
                                                    <cal:ActionMessage MethodName="MouseOverCallOut">
                                                        <cal:Parameter Value="By enabling this option, click here."/>
                                                    </cal:ActionMessage>
                                                </i:EventTrigger>
                                            </i:Interaction.Triggers>
```

**Comment by nigel-sampson** [comment]
Yup that would work as a work around,

**Comment by Raghava56** [comment]
thanks for your value information and time
