### ISSUE TITLE
TabControl content not correctly displayed when explicitly binding to ItemsSource

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [Caliburn-Micro/Caliburn.Micro#441]
In a bare-bone CaliburnMicro project (i.e Bootstrapper and ShellView as per documentation). Consider the following Conductor and Screen:
```
<UserControl x:Class="RpgTools.Main.Views.FooConductorView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:viewModels="clr-namespace:RpgTools.Main.ViewModels"
             mc:Ignorable="d"
             d:DesignHeight="300" d:DesignWidth="500"
             d:DataContext="{d:DesignInstance Type=viewModels:FooConductorViewModel, IsDesignTimeCreatable=True}">
    <Grid>
        <TabControl x:Name="Items"
                    ItemsSource="{Binding Items}">
            <TabControl.ItemTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding Path=DisplayName}" />
                </DataTemplate>
            </TabControl.ItemTemplate>
        </TabControl>
    </Grid>
</UserControl>

public sealed class FooConductorViewModel : Conductor<FooViewModel>.Collection.OneActive
{
    public FooConductorViewModel()
    {
        this.Items.Add(new FooViewModel());
        this.ActivateItem(this.Items.First());
        
        // Only here because in my project the ShellView is not a conductor
        ScreenExtensions.TryActivate(this);
    }
}


<UserControl x:Class="RpgTools.Main.Views.FooView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:viewModels="clr-namespace:RpgTools.Main.ViewModels"
             mc:Ignorable="d"
             d:DataContext="{d:DesignInstance Type=viewModels:FooViewModel, IsDesignTimeCreatable=True}"
             d:DesignHeight="300" d:DesignWidth="300">
    <StackPanel>
        <TextBox x:Name="Name" />
        <TextBlock Text="Bar" />
    </StackPanel>
</UserControl>

public class FooViewModel : Screen
{
    public FooViewModel()
    {
        this.Name = "Fooo";
    }

    public string Name { get; set; }
}
```
When I take out the explicit binding in FooConductorView the content of the tab control renders properly (the header always renders properly). However in the above code the content only consists of the fully qualified name of the view model I want to display.

This issue persists, if I change the TabControl in the view to the following:
```
<TabControl x:Name="Items"
                    ItemsSource="{Binding Items}">
    <TabControl.ItemTemplate>
        <DataTemplate>
            <TextBlock Text="{Binding Path=Name}" />
        </DataTemplate>
    </TabControl.ItemTemplate>
    <TabControl.ContentTemplate>
        <DataTemplate>
            <ContentControl Content="{Binding}" />
        </DataTemplate>
    </TabControl.ContentTemplate>
</TabControl>
```

Originally I had my FooConductorViewModel with this signature `FooConductorViewModel : Conductor<Changed<FooViewModel>>.Collection.OneActive` where `Changed<T>` had this implementation:
```
public class Changed<T>
{
    public bool HasChanged { get; set; }
    public T ViewModel { get; set; }
}
```

I was trying to bind the TabControl content to the ViewModel property on the above class. However I couldn't get it to work (any suggestions on that front are welcome), and discovered the problem describes at the beginning of this post.

**Comment by nigel-sampson** [comment]
The way conventions work in Caliburn.Micro is that there's a "core convention" and that if that is applied then some conventions go on to do some extra work.

You can see everything the convention is setting up in the [`ConventionManager`](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ConventionManager.cs#L265) for `TabControl`.

The line that's important here is the `return false`, what this means that if it can't create the binding on `ItemsSource` it won't do the rest.

These other things are creating a binding on `SelectedItem`, and defining an `ItemTemplate` and `HeaderTemplate`.

If you don't want to use the conventions but have similar functionality that the `TabControl` would like

``` xml
<TabControl ItemsSource="{Binding Items}" SelectedItem="{Binding ActiveItem, Mode=TwoWay}">
    <TabControl.ContentTemplate>
        <DataTemplate>
            <ContentControl cal:View.Model="{Binding}" VerticalContentAlignment="Stretch" HorizontalContentAlignment="Stretch" IsTabStop="False" />
        </DataTemplate>
    </TabControl.ContentTemplate>
    <TabControl.HeaderTemplate>
        <DataTemplate>
            <TextBlock Text="{Binding DisplayName}" />
        </DataTemplate>
    </TabControl.HeaderTemplate>
</TabControl>
```

**Comment by Ruhrpottpatriot** [comment]
Thanks for the reply. I still have two small questions, so I can make sure I understood it correctly:
1. Your answer hints that with CMs conventions it's either all or nothing. That'd mean I can't use Design time support with conventions but have to go with explicit bindings, right?

2. Your code explicitly binds the ViewModel via `cal:View.Model`. If I red the documentation correct, this approach is called "View-First". Is there any way to do this without explicit binding, or do I have to take this approach?

**Comment by nigel-sampson** [comment]
1, At the moment they're "all or nothing", but that can be changed. Given the [convention for `TabControl`](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ConventionManager.cs#L265) it's that `return` that stops the rest being applied. 

There would be nothing stopping you replacing the convention in your app (at startup) with a new one that didn't have that return. I believe the methods below are all "safe" in that they won't override bindings or templates that are already set.

2. Using `cal.View.Model` is "view model first", in that we have the view model already and what we're instructing the framework to do is to locate the view for this view model and then bind them together. If you want to explicitly set the `ContentTemplate` and still make use of the view location then you will need something like this.

There is a convention for `ContentControl` that does set this property, so for instance if you had view model like

``` csharp
public class ShellViewModel : Screen
{
    public ChildViewModel Child { get; }
}
```

then the view could be
``` xml
<ContentControl x:Name="Child" />
```

This will locate `ChildView` , instantiate it, insert it into the content control and bind it to the view model.

This scenario doesn't really work for the `ContentTemplate` above where you don't want to set a path.

**Comment by Ruhrpottpatriot** [comment]
Thanks. That helped a lot!
