### ISSUE TITLE
Fix up assembly version for the 3.1.0 release.

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#447]
I missed updating the assembly version in the 3.1.0 release.  Need to resolve this in 3.1.1

Also going on the backlog is something to the build / packing process so this doesn't need to happen.

**Comment by markgould** [comment]
We use GitVersion for most of our projects and it works really well. Might be worth looking into.

**Comment by nigel-sampson** [comment]
Yup, something like that is definitely on the roadmap when I can find the time to get back into build servers and a release process. 

Thanks
