### ISSUE TITLE
Binding to Nullable types (WPF with C#)

### ISSUE THREAD

**Issue by MycroftHolmes1989** [Caliburn-Micro/Caliburn.Micro#448]
WPF's validation does not allow input of null values in textbox even when they are bound to nullable numerical types. We use `TargetNullValue=''` in such cases. However, since Caliburn.Micro does the binding automatically, we cannot use it, and using it would mean that we have to declare the binding in xaml, which would actually defeat the purpose of auto-binding. It would be really helpful if there was some mechanism to set the default value for `TargetNullValue` in Caliburn.

**Comment by nigel-sampson** [comment]
Thankfully the framework has a lot of injection points around setting up the binding on `ConventionManager`. You could do something like:

``` csharp
var existingApplyValidation = ConventionManager.ApplyValidation;

ConventionManager.ApplyValidation  = (binding, viewModelType, property) => {
    existingApplyValidation(binding, viewModelType, property); // preserve existing behavior
    
    if (property.Type.IsNullable())
        binding.TargetNullValue = "";
};

public static bool IsNullable(this Type type)
{
	return type.IsGenericType && type.GetGenericTypeDefinition() == typeof (Nullable<>);
}
```
