### ISSUE TITLE
Component rendering issue

### ISSUE THREAD

**Issue by rolshevsky** [Caliburn-Micro/Caliburn.Micro#456]
Hi there!

I faced with some strange behaviour while rendering components.
Issue described with all details here: [StackOwerflow](https://stackoverflow.com/questions/44809110/wpf-usercontrol-component-grid-definition-issue)

Also, you can reproduce this issue using the following code: [CodeSample](https://github.com/rolshevsky/Caliburn-SimpleInjector-Sample).

Issue is not reproducing using pure `WPF` without any frameworks, so looks like issue really related to `Caliburn.Micro` stuff and probably it's `WindowManager` issue.

Thanks.

**Comment by rolshevsky** [comment]
Sorry for the false alarm. My issue is exactly the same as described here: [StackOverflow](https://stackoverflow.com/questions/33982358/window-sizetocontent-issue-when-child-usercontrol-has-grid-with-column-of-max-wi).
And this issue can be easily reproduced using pure `WPF`, so it's not a `Caliburn` issue.

**Comment by nigel-sampson** [comment]
Awesome, sorry I hadn't had a chance to get to it yet.
