### ISSUE TITLE
BootstrapperBase should call Configure before SelectAssemblies

### ISSUE THREAD

**Issue by beachwalker** [Caliburn-Micro/Caliburn.Micro#459]
In the BootstrapperBase class is the following code used for DesignTime, however the call to SelectAssemblies() is made before the call to Configure(). This makes the behaviour weird when having custom IoC (I use Autofac) and also using this in overload of SelectAssemblies() for views (which may have relation to registered DesignTime ViewModels)..
I think the Configuration() should be finished before the call to SelectAssemblies() or is there any reason I don't see here? (following snippet from BootStrapperBase)

```
    protected virtual void StartDesignTime()
    {
      AssemblySource.Instance.Clear();
      AssemblySource.Instance.AddRange(this.SelectAssemblies());
      this.Configure();
      IoC.GetInstance = new Func<Type, string, object>(this.GetInstance);
      IoC.GetAllInstances = new Func<Type, IEnumerable<object>>(this.GetAllInstances);
      IoC.BuildUp = new System.Action<object>(this.BuildUp);
    }
```

The twisted order forces me to do this in my custom Bootstrapper (derived from BootstrapperBase):

```
        // need to override cause viewmodels and views are in other assembly than application
        protected override IEnumerable<Assembly> SelectAssemblies()
        {
            this.InitializeContainer();

            return this.assemblies;
        }

        protected override void Configure()
        {
            this.InitializeContainer();
        }

        private void InitializeContainer()
        {
            if (this.alreadyRun) return;

            this.alreadyRun = true;

            var builder = new ContainerBuilder();
```
because I made some custom registrations for the DesignTime:

```
            if (Execute.InDesignMode)
            {
                ViewLocator.NameTransformer.AddRule(
                    @"(?<ns>[.\w]*)(?<dt>.DesignTime.Design)(?<basename>\w*)(Model)$",
                    @"${ns}.${basename}");

                var uri = new UriBuilder(Assembly.GetCallingAssembly().CodeBase);
                var directory = Path.GetDirectoryName(Uri.UnescapeDataString(uri.Path));

                if (!string.IsNullOrEmpty(directory) && Directory.Exists(directory))
                {
                    var catalog = new DirectoryCatalog(directory);

                    builder.RegisterComposablePartCatalog(catalog);
                }

                builder.RegisterType<DesignChildViewModel>().As<IChildViewModel>();
                builder.RegisterType<DesignOtherViewModel>().As<IOtherViewModel>();

                builder.RegisterType<DesignContainerViewModel>().As<IContainerViewModel>();
            }
```
now the DataContext set in ChildViews is respected during DesignTime (even from other Assembly), for example:

`d:DataContext="{d:DesignInstance Type=designTime:DesignOtherViewModel, IsDesignTimeCreatable=True}"`

and can be assembled by the IoC:

```
    public class ContainerViewModel : Screen, IContainerViewModel
    {
        private readonly string text;

        private readonly IScreen child;

        private readonly IScreen other;

        public ContainerViewModel(IChildViewModel child, IOtherViewModel other)
        {
            // wired by IoC
            this.text = "Container";
            this.child = child; // child in same assembly
            this.other = other; // child in other assembly
        }
```

while IoC resolves implementations of IChildViewModel and IOtherViewModel differently between RunTime and DesignTime (both ViewModels share same interfaces. This is nice because you don't forced to have all ViewModel dependencies of DesignTime during RunTime and allows being able to have something like this at DesignTime:

![image](https://user-images.githubusercontent.com/2715897/27833178-e45c31ae-60d1-11e7-8b47-a1d677d3427e.png)

and this at RunTime:

![image](https://user-images.githubusercontent.com/2715897/27833194-00d9477c-60d2-11e7-92ca-93f91b7c40f0.png)

Interesting?

**Comment by beachwalker** [comment]
This is my current solution for #388 using abilities without changing code of Caliburn.Micro itself.

**Comment by nigel-sampson** [comment]
Totally happy to take a pull request switching the order in all appropriate places.

**Comment by nigel-sampson** [comment]
Looking closer into this, I'm not sure from your example why `Configure` needs to come before `SelectAssemblies`.

I'm clearly missing something here around why the container needs to be initialized first.  I'm assuming at the moment it's something to do with `this.assemblies` but it's not in the above example.

**Comment by beachwalker** [comment]
It seems during designtime visual studio 2013 sometimes don't call configure. This is also a workaround for that.

**Comment by beachwalker** [comment]
Do you need a full example code or other help?

**Comment by beachwalker** [comment]
I have to state I'm using Autofac instead of SimpleIoc

**Comment by nigel-sampson** [comment]
I'm not following what you mean by "doesn't call configure".  

Are you staying `StartDesignTime` is being called but `Configure` isn't during design time?

**Comment by nigel-sampson** [comment]
Might be best to have a full example for me to check.

**Comment by beachwalker** [comment]
I mean selectasemblies() is called by the designtime in VS but this is not folllowed by Configure(), so that the IoC container is not created / ready. The sample ensures it is called at least once.

**Comment by nigel-sampson** [comment]
Given the implementation 
``` csharp
protected virtual void StartDesignTime() {
AssemblySource.Instance.Clear();
AssemblySource.Instance.AddRange(SelectAssemblies());

Configure();
IoC.GetInstance = GetInstance;
IoC.GetAllInstances = GetAllInstances;
IoC.BuildUp = BuildUp;
}
```

For `StartAssemblies` to be called but `Configure` not to be called would indicate an exception in `SelecteAssemblies`.  What's your implementation?
