### ISSUE TITLE
Clues for persisting UWP app state?

### ISSUE THREAD

**Issue by Myrmex** [Caliburn-Micro/Caliburn.Micro#460]
Hi, I'm new to UWP + CM so bear with me, anyway I hope this is going to be helpful for newcomers. I'm asking about the suggested way of implementing some basic save/load state in an UWP app lifecycle.

As far as I can tell from CM code samples, the extension points are found in `App.xaml.cs`:

- `OnLaunched`: if `e.PreviousExecutionState == ApplicationExecutionState.Terminated`, this publishes a `ResumeStateMessage`. The implication is that all my VM classes which want to persist their state should handle this message, get their data from some shared store, and restore their state.

- `OnSuspending`: this publishes a `SuspendStateMessage`. Here too I suppose my VM classes should handle this message, adding the state data to the store.

Now that's fine, but I'm not sure about persisting the state data to disk. Say I have a simple, singleton service which uses a `Dictionary<string,object>` to hold state data; it could be as simple as the one pasted below (see the end of this post). I could inject it in any VM requiring to persist its state, and then handle the corresponding messages in the VM like:

        public void Handle(SuspendStateMessage message)
        {
            _navigationService.SuspendState();
            // save to store... e.g.:            
            _state.Store["somekey"] = SomeProperty;
        }
    
        public void Handle(ResumeStateMessage message)
        {
            _bResume = true;
            // load from store... e.g.:
            SomeProperty = _state.Get("somekey", null);
        }

Yet, how am I supposed to handle the serialization of this dictionary from/to disk? The main issue here is that this serialization implies an async operation. Thus, in `App.xaml.cs`, `OnLaunched`, I could do something like first loading the state from disk, and THEN publish the `ResumeStateMessage`, so that data is available for restore:

    if (e.PreviousExecutionState == ApplicationExecutionState.Terminated)
    {
        _state.LoadAsync()
              .ContinueWith(t =>
            {
                _events.PublishOnUIThread(new ResumeStateMessage());
            } );
    }

BUT, how could I do the inverse, i.e. store the state? Again in `App.xaml.cs`, `OnSuspending`:

    protected override void OnSuspending(object sender, SuspendingEventArgs e)
    {
        _events.PublishOnUIThread(new SuspendStateMessage(e.SuspendingOperation));
        // TODO save state
    }

The method just publishes a message to any VM wanting to add state data to the store (the dictionary). But I cannot know when each VM will complete its operation, so where should I save the store to file? Should I just add to the method something like `_state.SaveAsync(e).Wait();`, this would fail when not all the data have been stored by the VM handling the message. Should I call `SaveAsync` from each message handler, this would be rather inefficient, and would pose the risk of file write failure due to locking. So, in a simple scenario like this, how am I supposed to handle the state serialization, which typically will be async?

Here is my complete state service class:

    public sealed class StateService
    {
        private const string FILE_NAME = "store.xml";
        public Dictionary<string, object> Store { get; }
    
        public StateService()
        {
            Store = new Dictionary<string, object>();
        }
    
        public async Task SaveAsync(SuspendingEventArgs e)
        {
            SuspendingDeferral deferral = e.SuspendingOperation.GetDeferral();
            Store.Add("timestamp", DateTime.UtcNow);
    
            MemoryStream ms = new MemoryStream();
            DataContractSerializer serializer = new DataContractSerializer(typeof(Dictionary<string, object>));
            serializer.WriteObject(ms, Store);
    
            StorageFile file = await ApplicationData.Current.LocalFolder.CreateFileAsync
                (FILE_NAME, CreationCollisionOption.ReplaceExisting);
    
            using (Stream stream = await file.OpenStreamForWriteAsync())
            {
                ms.Seek(0, SeekOrigin.Begin);
                await ms.CopyToAsync(stream);
                await stream.FlushAsync();
            }    
            deferral.Complete();
        }
    
        public async Task LoadAsync()
        {
            StorageFile file = 
                await ApplicationData.Current.LocalFolder.GetFileAsync(FILE_NAME);
            if (file == null) return;
    
            using (IInputStream stream = await file.OpenSequentialReadAsync())
            {
                DataContractSerializer serializer = 
                    new DataContractSerializer(typeof(Dictionary<string, object>));
                Dictionary<string, object> dct = (Dictionary<string, object>)
                    serializer.ReadObject(stream.AsStreamForRead());
                Store.Clear();
                foreach (var de in dct) Store[de.Key] = de.Value;
            }
        }
    
        public void Set(string key, object value, bool removeNull = true)
        {
            if (key == null) throw new ArgumentNullException(nameof(key));
            if (value == null && removeNull && Store.ContainsKey(key)) Store.Remove(key);
            else Store[key] = value;
        }
    
        public string Get(string key, string defaultValue)
        {
            if (key == null) throw new ArgumentNullException(nameof(key));
            return Store.ContainsKey(key) ? (string) Store[key] : defaultValue;
        }
    
        public bool Get(string key, bool defaultValue)
        {
            if (key == null) throw new ArgumentNullException(nameof(key));
            return Store.ContainsKey(key) ? (bool)Store[key] : defaultValue;
        }
    
        public int Get(string key, int defaultValue)
        {
            if (key == null) throw new ArgumentNullException(nameof(key));
            return Store.ContainsKey(key) ? (int)Store[key] : defaultValue;
        }
    
        public T Get<T>(string key) where T : class
        {
            if (key == null) throw new ArgumentNullException(nameof(key));
            return Store.ContainsKey(key) ? (T)Store[key] : null;
        }
    }

**Comment by nigel-sampson** [comment]
Sorry this slipped through the gaps.

If you are doing async operations with the events like `OnSuspending` then you'll need to use deferrals which look something like

``` csharp
protected override async void OnSuspending(object sender, SuspendingEventArgs e)
{
    var deferral = e.GetDeferral();
    // await async stuff here
   deferral.Complete();
}
```
