### ISSUE TITLE
TryClose(true) sets the result but doesn't close the dialog in WPF.

### ISSUE THREAD

**Issue by lunix1982** [Caliburn-Micro/Caliburn.Micro#461]
I expect that calling the `TryClose(true)` have to set the dialog result and to close the dialog window. However the method only sets the result. Currently I have to call a sequence `TryClose(true)` followed by `TryClose()`.
Looks like this happens because of `isClosed = true;` assignment in `XamlPlatformProvider.GetViewCloseAction`:
```
                if (closeMethod != null)
                    return () => {
#if !SILVERLIGHT && !WinRT
                        var isClosed = false;
                        if (dialogResult != null) {  //< --------- dialogResult is true
                            var resultProperty = contextualView.GetType().GetProperty("DialogResult");
                            if (resultProperty != null) {
                                resultProperty.SetValue(contextualView, dialogResult, null);
                                isClosed = true; //< --------- isClosed is true
                            }
                        }

                        if (!isClosed) { //< --------- prevents from calling an appropriate method
                            closeMethod.Invoke(contextualView, null);
                        }
#else
                        closeMethod.Invoke(contextualView, null);
```
Did I miss something?
Thanks.

**Comment by nigel-sampson** [comment]
Sorry for this slipping through the cracks.

There definitely looks to be something odd going on here, what;s the type of the dialog being closed?

**Comment by nigel-sampson** [comment]
The reason I ask is from resources such as [WPF Dialogs and DialogResult](https://marlongrech.wordpress.com/2008/05/28/wpf-dialogs-and-dialogresult/) and some quick experiments we shouldn't need to call `Close` directly and that setting `DialogResult` is enough to close the regular dialogs.

**Comment by lunix1982** [comment]
I have checked for the Window class, it works fine.
Apparently, the reason is that we use libraries from telerik and RadWindow in particular. We created the TelerikWindowManager class based on [this source.](https://github.com/vcaraulean/Caliburn.Micro.Telerik/tree/master/WPF/Caliburn.Micro.Telerik)
As a result, the dialog does not close and there are no exceptions thrown.

**Comment by lunix1982** [comment]
Should I close the issue or is it still worth changing the XamlPlatformProvider?
Thanks.

**Comment by nigel-sampson** [comment]
Thanks for the feedback, it seems the problem is the different behavior of `TelerikWindow` compared to regular `Window` based despite as you said having similar methods and structures.

I don't feel it's worth changing the current `XamlPlatformProvider` given this is a difference in the way a control library works compared to the out of the box framework. This should be something that can be extended in the same way you have with a custom window manager.

Looking at the code for `XamlPlatformProvider` however I've noticed the methods aren't virtual which makes it a little harder for you to extend the class to add your own behavior. I've raised this as #475.

**Comment by GiroSA** [comment]
Hi,

I have the same issue, TryClose(true/false) doesn't close dialog, using TelerikWindowManager as linked to above.

What is the resolution to this (other than calling TryClose() )?

Thanks,
Gerhard

**Comment by lunix1982** [comment]
Looks like the only solution is to call TryClose() without arguments.

**Comment by nigel-sampson** [comment]
So I've made sure that the extension of `XamlPlatformProvider` is easier now with the method being virtual. 

But if you're dealing with a window manager / window that doesn't behave like the default then you'll need to extend the framework to support it's behavior.
