### ISSUE TITLE
Set title of window in xaml

### ISSUE THREAD

**Issue by tziemek** [Caliburn-Micro/Caliburn.Micro#462]
Hi,
we are using CM with WPF and wondered why setting the title on a window in xaml has no effect. I found the responsible code in https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/net40/WindowManager.cs in the CreateWindow method. There is a check for the IHaveDisplayName interface and existing bindings.

My suggestion is to also do nothing if there is already a title defined, hence i don't have to set the DisplayName property in my viewmodel.

Thanks

**Comment by nigel-sampson** [comment]
That makes sense, happy to take a PR for this. 😄

**Comment by nigel-sampson** [comment]
Resolved by #476 .

Thanks!
