### ISSUE TITLE
In Wpf bind Action Parameter  to FrameworkElement

### ISSUE THREAD

**Issue by JMPlus2015** [Caliburn-Micro/Caliburn.Micro#464]
Hi,
   I want to get some help about binding FrameworkElement to Action Parameter.
   For example, In this following expresstion:
  `cal:Message.Attach="[Event TabHidden]=[Action CloseTabWindow(FrameworkElementName)]"`

  because there is no path assign  to the FrameworkElementName, In the Parser, the path will be automatically assigned  path to  
 `if (string.IsNullOrEmpty(path))
  {
      path = ConventionManager.GetElementConvention(element.GetType()).ParameterProperty;
   }`
 
  So the parameter will not be the FrameworkElement itself.

 How can I bind the parameter to the FrameworkElement itself ?

 Please help me, Thank you very much!

**Comment by nigel-sampson** [comment]
Currently the framework doesn't support this (off the top of my head), and I don't believe it should, passing a UI element such as `FrameworkElement`  to a method on the view model breaks that separation. 

We do have a couple of exceptions under Special Values in the [documentation](http://caliburnmicro.com/documentation/actions), where if the element you're referring to is the triggering element the `$source` will get what you need.

You may need to go into why you need to pass the element into the view model.

**Comment by JMPlus2015** [comment]
Consider there is a element (eg. panel) called A, and it has a panel in it which called B. 
At the end, there is a button inside B. 
When the button click, I want the panel B to get close by call the panel A's method which like:
`A.DockController.Hide(B);` 
I can't set Action.Target to A and call the method in xaml directly, 
It's a method via the element's property and the parameter is also a element.

That is why I need to pass the element into the view model.

Ah,I feel hard to describe this with my pool English .....
Thanks.

**Comment by nigel-sampson** [comment]
Your English is fine 😄 

To be honest I'd probably leave the view model out of an interaction like this, Simply add an event handler to the button and close the panel from the code behind.

In my opinion the point of the MVVM pattern isn't to have no code behind, but to have view concerns separate from the "state and behavior" of the screen. This sort of interaction feels like a simple view concern and probably shouldn't be in the view model.

There are a couple of caveats in that if it's not in the view model it becomes harder to unit test. But I don't think this use case would be easy to unit test either.

If you have some concerns about code repetition you could extract this behavior into a `TriggerAction` that you can drop on the button and point to the panel.

**Comment by mvermef** [comment]
sorry late to the game have to agree with Nigel, was actually typing that nearly exact answer earlier, forgot to click comment I guess.  When it deals with the view it stays in the view (i.e. in this case code behind), which isn't any sort if violation of any kind with MVVM, in my opinion.

**Comment by JMPlus2015** [comment]
Thank you all. 
I will have a try.
I need to study more about MVVM pattern.
