### ISSUE TITLE
Add SetValue call to PropertyChangeBase

### ISSUE THREAD

**Issue by mrfichtn** [Caliburn-Micro/Caliburn.Micro#466]
When added to PropertyChangedBase, the following calls streamlines implementing properties:

        /// <summary>
        /// Sets property value, raising appropriate message
        /// </summary>
        /// <typeparam name="T">Property type</typeparam>
        /// <param name="oldValue">Property to set</param>
        /// <param name="newValue">New property value</param>
        /// <param name="propertyName">Name used when signaling event</param>
        protected bool SetValue<T>(ref T oldValue, T newValue, string propertyName)
        {
            bool changed;
            if (!Equals(oldValue, newValue))
            {
                oldValue = newValue;
                NotifyOfPropertyChange(propertyName);
                changed = true;
            }
            else
            {
                changed = false;
            }
            return changed;
        }

        /// <summary>
        /// Sets property value, refreshing all bindings
        /// </summary>
        /// <typeparam name="T">Property type</typeparam>
        /// <param name="oldValue">Property to set</param>
        /// <param name="newValue">New property value</param>
        protected bool SetValue<T>(ref T oldValue, T newValue)
        {
            bool changed;
            if (!Equals(oldValue, newValue))
            {
                oldValue = newValue;
                Refresh();
                changed = true;
            }
            else
            {
                changed = false;
            }
            return changed;

        }

        /// <summary>
        /// Sets value, raising changes messages for a group of properties
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="oldValue">Property to set</param>
        /// <param name="newValue">New property value</param>
        /// <param name="propertyNames">Properties affected by change in value</param>
        protected bool SetValue<T>(ref T oldValue, T newValue, params string[] propertyNames)
        {
            bool changed;
            if (!Equals(oldValue, newValue))
            {
                oldValue = newValue;
                foreach (var propertyName in propertyNames)
                    NotifyOfPropertyChange(propertyName);
                changed = true;
            }
            else
            {
                changed = false;
            }
            return changed;
        }

For example:
        #region Contents Property
        public string Contents
        {
            get => _contents;
            set => SetValue(ref _contents, value, nameof(Contents);
        }
        private string _contents;
        #endregion

Thanks!

**Comment by nigel-sampson** [comment]
Considering adding something like to help reduce some boilerplate (though I recommend using something like `PropertyChanged.Fody` to get rid of backing fields altogether).
