### ISSUE TITLE
ExtendedContainer? handles singletons by implementation type

### ISSUE THREAD

**Issue by Stannieman** [Caliburn-Micro/Caliburn.Micro#472]
Currently when a type T implements 2 interfaces I1 and I2 and the type is registered as singleton for both I1 and I2, the container returns a different instance when resolving I1 or I2.
I think most people expect there to be only 1 instance for every implementation type T.

A concrete example where this is a "problem" is registering singleton helpers by convention with all interfaces.
What you'd do is
```
foreach (var type : all types in assembly with name ending on "Helper") {
    var AllInterfacesThisTypeImplements = type.GetInterfaces();
    foreach (var interface : AllInterfacesThisTypeImplements) {
        container.RegisterSingleton(interface, null, type);
    }
}
```
Now if a helper implements more than 1 interface you can get a different helper instance depending on the type you are resolving, which I think is not what most users want/expect.

I do see that this would require quite some changes in the SimpleContainer which would be breaking. If it's ok for the authors I'm prepared to write a more extended container with this functionality, and can also try to address issue 467. This could than be in Caliburn 4.

**Comment by Stannieman** [comment]
Update: I couldn't resist doing it already.
Now of for 5 days of music festival, but next week it should be ready.
Features:

- Property injection can be enabled or disabled.
- Singleton will be defined per implementation type per key instead of the type it's registered with, so resolving the same implementation through multiple interfaces but with the same key will get you the same implementation instance.
- Properties are only injected when they are null to not overwrite an existing instance.
- Properties can have an [RequiredDependency] attribute, this will make them throw an exception when it cannot resolve it (if property injection is enabled at all).
- Properties and constructor arguments can be marked with the [DependencyKey("key")]
- [https://github.com/Caliburn-Micro/Caliburn.Micro/pull/374](https://github.com/Caliburn-Micro/Caliburn.Micro/pull/374), should be doable to get this in.

**Comment by nigel-sampson** [comment]
I've addressed this in #471 in order to keep discussion in one place.

**Comment by xmedeko** [comment]
I think the current `SimpleContainer.RegisterSingleton` behavior is not wrong. (AFAIK LightInject behaves this way, too). If you want to register interface, just use
```
container.RegisterHandler(interface, null, container => container.GetInstance(type));
```
What if you want a new singleton for every interface?

Maybe you may add some helper method like `SimpleContainer.AddInterface` for that.

**Comment by nigel-sampson** [comment]
I'm going to leave the current behavior as it is, its a subjective one with no "correct" answer.
