### ISSUE TITLE
I have a ViewModel without View

### ISSUE THREAD

**Issue by junliuxian** [Caliburn-Micro/Caliburn.Micro#473]
I am using Caliburn.Micro to build WPF PC program, which is a great framework. But recently I have a problem:
　I have a ViewModel that does not require a View. It's actually a navigation, through the TabControl Items switch to the specified website.
　I have browsed: View.cs, ConventionManager.cs, ViewLocator, ViewModelLocator, can not solve my distress. Can not find view for ... always exists.
　Can I only create an empty view to solve this problem? Or can Caliburn.Micro provide such a switch to let me control?

**AppBootstrapper：**

`    

    namespace Caliburn.Micro.Test.WPF
    {
      using System;
      using System.IO;
      using System.Windows;
      using System.Collections.Generic;
      using System.ComponentModel.Composition;
      using System.ComponentModel.Composition.Hosting;
      using System.ComponentModel.Composition.Primitives;
      using System.Linq;
      using Caliburn.Micro;
    
      public class AppBootstrapper : BootstrapperBase
      {

         private CompositionContainer container;

        public AppBootstrapper()
        {
            Initialize();
        }

        protected override void Configure()
        {
            var catalog = new AggregateCatalog(AssemblySource.Instance.Select(x => new AssemblyCatalog(x)).OfType<ComposablePartCatalog>());
            var batch = new CompositionBatch();
            var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "plugins");

            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);

            catalog.Catalogs.Add(new DirectoryCatalog(path));
            container = new CompositionContainer(catalog);

            batch.AddExportedValue(container);
            batch.AddExportedValue<IWindowManager>(new WindowManager());

            batch.AddExportedValue<IEventAggregator>(new EventAggregator());
            batch.AddExportedValue(catalog);

            container.Compose(batch);
        }

        protected override void BuildUp(object instance)
        {
            base.BuildUp(instance);
        }

        protected override object GetInstance(Type service, string key)
        {
            var contract = string.IsNullOrEmpty(key) ? AttributedModelServices.GetContractName(service) : key;
            var exports = this.container.GetExportedValues<object>(contract);

            if (exports.Any())
            {
                return exports.First();
            }

            throw new Exception(string.Format("Could not locate any instances of contract {0}.", contract));
        }

        protected override IEnumerable<object> GetAllInstances(Type service)
        {
            return this.container.GetExportedValues<object>(AttributedModelServices.GetContractName(service));
        }

        protected override void OnStartup(object sender, StartupEventArgs e)
        {
            DisplayRootViewFor<IShell>();
        }
    }
  }

`

**ShellViewModel**
`

    namespace Caliburn.Micro.Test.WPF.ViewModels
    {
      using System;
      using System.Collections.Generic;
      using System.ComponentModel.Composition;
      using System.Linq;
      using System.Text;
      using System.Threading.Tasks;

      [Export(typeof(IShell))]
      internal class ShellViewModel : Conductor<INavigation>.Collection.OneActive, IShell
      {
          [ImportingConstructor]
          public ShellViewModel([ImportMany]IEnumerable<INavigation> tabs)
          {
              Items.AddRange(tabs.OrderBy(x => x.Index));
              DisplayName = "WPF.Test";
          }
         
          public void NavigationChanged(SelectionChangedEventArgs e)
          {
            var tab = e.OriginalSource as TabControl;
            var nav = tab.SelectedItem as INavigation;
      
            if (nav == null)
                return;

            tab.SelectedIndex = nav.Redirect((e.RemovedItems[0] as INavigation).Index);
          }
      }
    }

`

**ShellView**

`
  <TabControl Name="Items" cal:Message.Attach="[Event SelectionChanged] = [Action NavigationChanged($eventArgs)]" />
`

**INavigation**
`

    public interface INavigation
    {
        string Icon { get; set; }

        int Index { get; set; }

        int Redirect(int index);
    }

`

**BuyProductViewModel**
`

    namespace Caliburn.Micro.Test.WPF.ViewModels
    {
        [Export(typeof(INavigation))]
        internal class BuyProducts : Screen, INavigation
        {
            public string Icon { get; set; }

            public int Index { get; set; }

            public int Redirect(int index)
            {
               // System.Diagnostics.Process.Start("https://www.google.com/?p=BuyProduct");
                return Index;
            }

          public BuyProducts()
          {
              DisplayName = "Buy Product";
              Index = 0;
          }
      }
    }

`

**MoreProductsViewModel**
`

    namespace Caliburn.Micro.Test.WPF.ViewModels
    {
        [Export(typeof(INavigation))]
        internal class MoreProducts: Screen, INavigation
        {
            public string Icon { get; set; }

            public int Index { get; set; }

            public int Redirect(int index)
            {
               // System.Diagnostics.Process.Start("https://www.google.com/?p=More Products");
                return Index;
            }

          public MoreProducts()
          {
              DisplayName = "More Products";
              Index = 0;
          }
      }
    }

`

**Comment by rossvegas** [comment]
Hi @junliuxian 

I have put your code into an application to try and figure out what your trying to achieve. 

If you would like to launch a browser with a specific URL I don't think view models without views is the best place, I would create simple classes that encapsulate the Buy products and More products functionality, then I would call those from a view model with a view, maybe with a button.

**Comment by nigel-sampson** [comment]
You can test the "looked for views" by running `ViewLocator.TransformName` where the first parameter is the full type name of the view model and the second is the context which will be null unless you've specifically set one using `cm.View.Context`.

For example the following returns no views due to the lack of `ViewModel` suffix.

``` csharp
var views = ViewLocator.TransformName("Caliburn.Micro.Test.WPF.ViewModels.MoreProducts", null);
```

Whereas the following
``` csharp
var views = ViewLocator.TransformName("Caliburn.Micro.Test.WPF.ViewModels.MoreProductsViewModel", null);
```

Yields
- `Caliburn.Micro.Test.WPF.Views.MoreProductsView`
- `Caliburn.Micro.Test.WPF.ViewModels.MoreProductsView`

If you don't want to use the view model suffix you can configure the `ViewLocator` like so
```
ViewLocator.ConfigureTypeMappings(new TypeMappingConfiguration
{
    UseNameSuffixesInMappings = false
});
```
which changes the result of the first call to `Caliburn.Micro.Test.WPF.Views.MoreProducts`.

Hope this helps/

**Comment by junliuxian** [comment]
@nigel-sampson 

It's my great honor to have you answer my question! I think you might have misunderstood my question. ViewLocator.ConfigureTypeMappings settings, I think it should be global. Actually, my problem is not that I can't find View. Instead, some view models don't need View, but CM still gives me errors. The error message is: Cannot find view for {0}

ConventionManager.cs

`<ContentControl cal:View.Model ="{Binding}" VerticalContentAlignment="Stretch" HorizontalContentAlignment="Stretch" IsTabStop="False" />`

**Comment by nigel-sampson** [comment]
If you're seeing the "Cannot find view for X" error then you've set things up where the framework expects a view to be inserted. 

If you simply wish to have a blank screen then an empty view will suffice.

**Comment by junliuxian** [comment]
I thought the CM would have a switch that would allow me to omit the creation of an empty view file...

**Comment by nigel-sampson** [comment]
To be honest this is the first time it's ever come up as a requirement.
