### ISSUE TITLE
"Cannot set Visibility or call Show ... after a Window has closed" on second WindowManager.ShowWindow with the same view model

### ISSUE THREAD

**Issue by superware** [Caliburn-Micro/Caliburn.Micro#474]
After closing a window (ALT+F4 or X close button) that was created and shown by WindowManager.ShowWindow, calling ShowWindow again for the same view model throws "Cannot set Visibility or call Show, ShowDialog, or WindowInteropHelper.EnsureHandle after a Window has closed."

My guess is that CM is using the same view (window) instance, which was closed. I can see GetAllInstances is being called with the view type and I guess the first instance is being used...

Any ideas?

**Comment by rossvegas** [comment]
Hi @superware 

I have tried to repro this behavior and have not been able to. Could you attach an example perhaps?

**Comment by nigel-sampson** [comment]
Wondering if this could happen if the view for the dialog got reused, but didn't happen when if there was a GC between usages?

However I've tried to recreate this with both a `UserControl` and a `Window` as the view for the view model without any errors.

**Comment by nigel-sampson** [comment]
Closing due to lack of extra information.
