### ISSUE TITLE
DefaultPlatformProvider.OnUIThreadAsync

### ISSUE THREAD

**Issue by bidasknakayama** [Caliburn-Micro/Caliburn.Micro#477]
DefaultPlatformProvider.OnUIThreadAsync is defined as : 

`public virtual Task OnUIThreadAsync(Action action) {
            return Task.Factory.StartNew(action);
        }`

but StartNew do not understand Async delegate. ( [I saw this post](https://stackoverflow.com/questions/41788529/why-task-factory-startnew-returns-immediately-while-task-run-does-not) )

Can you add OnUIThreadAsyncNo2 ? like this :  
`public virtual Task OnUIThreadAsync(Action action) {
            return Task.Run(action);
        }`

Because I want to wait for finish of execution of OnUIThreadAsync.
Now, If I run this.

`await Execute.OnUIThreadAsync(.... );`

it never do "await"....

Can you make **OnUIThreadAsyncNo2**  with "**Task.Run(action);**"

because "BeginOnUIThread" and "OnUIThread" return void.. I can not make alternative. I need a function is enable to return Task...

Is there any other way to make same function quickly ? with current version.

**Comment by nigel-sampson** [comment]
`DefaultPlatformProvider` is almost never used, it's simply a "null object" for things like unit tests., depending on which platform you're using it will be one of the other platform provides such as `XamlPlatformProvider.

Which platform are you using or is this for unit tests?

**Comment by bidasknakayama** [comment]
I am running on UWP-Windows-10-C#.

I want to "wait" this line. but The "await" keyword is not effective.
I thought, It cause of "**Task.Factory.StartNew(action);** "

`await Execute.OnUIThreadAsync(.... );`

Is there any good idea ? or other method "**OnUIThreadAsync2**" ?

Kazu

**Comment by nigel-sampson** [comment]
If you're running on UWP then `DefaultPlatformProvider.OnUIThreadAsync` should not be being called. It should be `XamlPlatforProvider.OnUIThreadAsync`. 

It sounds like the initialisation of the framework which overrides the platform provider from default to xaml isn't happening.

**Comment by bidasknakayama** [comment]
I confused you.

I only used this :  
`await Execute.OnUIThreadAsync(.... );`

Can I do "**await**" When we use this line ?

**Comment by nigel-sampson** [comment]
All that that method does is [pass the `Task` back](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro/Execute.cs#L31) from the current platform provider. So it totally depends on which platform provider is in use.

For UWP this should be [this implementation](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/XamlPlatformProvider.cs#L75) which should be awaitable.

**Comment by bidasknakayama** [comment]
ok.. I will think next plan to "await".  Thank you : )
