### ISSUE TITLE
DataGrid AutoGeneratingColumn Action in Caliburn.Micro

### ISSUE THREAD

**Issue by junliuxian** [Caliburn-Micro/Caliburn.Micro#478]
Why this event will not be triggered?  I tried to find the answer at stackoverflow, but I didn't find a solution. Just know that AutoGeneratingColumn is an ordinary.Net event. What should I do?

`<DataGrid x:Name="MyObservableCollection" AutoGenerateColumns="True" cal:Message.Attach="[Event AutoGeneratingColumn] = [Action IDRemover($eventArgs)]" />`

**Comment by nigel-sampson** [comment]
I managed to recreate the issue and it appears to be a timing one.  By the time the platform has parsed the `cal:Message.Attach` the `DataGrid` has already checked the shape of your collection and generated the columns.

I can verify this by delay setting the `ItemsSource` on the grid and seeing the action being invoked on the view model.

If this delay doesn't make sense in your application I'd use a normal event handler.

**Comment by junliuxian** [comment]
I tried to set up the AutoGeneratingColumn event handler in ViewModel, but the VS compilation failed. The error code is: CS1061, unable to locate the method. I am confused ~!

So I started looking for the answer, and my answer was..:

View.xmal.cs cannot be deleted, and the event handling method is written in that file.

Is, this, correct?

**Comment by nigel-sampson** [comment]
Typically an event handler would be written in the code behind for that file.

**Comment by junliuxian** [comment]
Just a minute. I'm preparing

**Comment by junliuxian** [comment]
Sorry, I do not understand what you mean. Can you give me an example? Thanks.

**Comment by nigel-sampson** [comment]
Here's a tutorial on [Events in Xaml](http://www.wpf-tutorial.com/xaml/events-in-xaml/)
