### ISSUE TITLE
GetView always returns to Null

### ISSUE THREAD

**Issue by junliuxian** [Caliburn-Micro/Caliburn.Micro#480]
I'm using MEF as Bootstrapper, and I import the content of the TabControl in ShellWindow, and the view is displayed normally. But I got the GetView in the corresponding view, and it's always been Null. I'm confused!

ShellWindowViewModel:

    [Export(typeof(IShell))]
    public class ShellViewModel : Conductor<INavigation>.Collection.OneActive, IShell
    {
        [ImportingConstructor]
        public ShellViewModel([ImportMany]IEnumerable<INavigation> items)
        {
            Items.AddRange(items);
        }

    }

ShellView:
`<TabControl x:Name="Items" />`

OnePageViewModel:
     
      
    [Export(typeof(INavigation))]
    internal class OnePageViewModel : Screen, INavigation
    {
        protected override void OnInitialize()
        {
            DisplayName = "OnePage";
            Console.WriteLine(GetView() == null); // True
        }
       
       // ...
    }
       

INavigation:

    public interface INavigation
    {
        string Icon { get; set; }

        // ...
    }

**Comment by junliuxian** [comment]
ShellView:
`<TabControl x:Name="Items" />`

**Comment by nigel-sampson** [comment]
Is the correct view being located and shown visually?

**Comment by junliuxian** [comment]
The view is displayed correctly and the bindings are normal

**Comment by nigel-sampson** [comment]
Can you create an sample that shows this happening that I can look at. Thanks

**Comment by junliuxian** [comment]
The CM version I'm using is 3.1.0, and has yet to try a higher version

[sample](https://pan.baidu.com/s/1qYhtxbI)

**Comment by junliuxian** [comment]
I've tried the latest version of CM, and GetView is also Null

**Comment by nigel-sampson** [comment]
Can't seem to download that sample, just getting network errors. Can you create it as a GitHub repo?

**Comment by junliuxian** [comment]
I have updated sample's url. You try again

**Comment by nigel-sampson** [comment]
Thanks, tracked down what's happening, because this is "view model first", the tab view model is becoming active before the view is created and attached.  This is expected behavior, as the conductor activates the child view model it causes the tab control to trigger the view to be loaded and inserted.

If you override the on view attached method on the view it will be called after initialize.

**Comment by junliuxian** [comment]
Thank you for your answer
