### ISSUE TITLE
Automatic IoC resolution is only partially removed

### ISSUE THREAD

**Issue by frankebersoll** [Caliburn-Micro/Caliburn.Micro#481]
The depreciation of automatic IoC resolution when supplying strings (54c1ad299) leads to confusion, as several occurences are still there:

- [Bind.ModelWithoutContext](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/Bind.cs#L133)
- [Action.Target](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/Action.cs#L163)
- [Documentation (View-First section)](http://caliburnmicro.com/documentation/actions)
- [Confusion about this on stackoverflow](https://stackoverflow.com/questions/46196301/automatic-binding-does-not-work-for-caliburn-micro-in-view-first-wpf)

When using the view-first approach (for whatever reason), it data-binds to the string itself. Actions still work, because the Action.Target is resolved using the IoC container.

**Comment by nigel-sampson** [comment]
Thanks for bringing this my attention, the other instances should definitely be removed as well and the documentation updated.

**Comment by nigel-sampson** [comment]
Other usages a now removed.
