### ISSUE TITLE
Binding parent property on Child view.

### ISSUE THREAD

**Issue by bidasknakayama** [Caliburn-Micro/Caliburn.Micro#483]
Hello 

I could not resolve the issue "Binding parent property on Child view."
then, I post at here. please help it.

1) Parent view activateItem CHild view.
2) Parent viewModel has a Property.
3) Child  viewModel has no property.
4) I want to display Parent Property on Child view.
5) But I donot want to use "x:Name". because I want to use a Custom Control to bind. x:Name is not enough.

on WIndows UWP. please...
I post some to stackoverflow. but I could not resolve.
I found a [good artible,](http://www.tenpay.tech/questions/3303844/binding-an-element-in-a-child-view-to-a-property-of-the-parent-viewmodel
) but it is not UWP. not work.

I expect someone will make more good manual for caliburn.micro.

Kazu

**Comment by nigel-sampson** [comment]
You can do it a number of different ways.

1. Pass a reference to the parent in the child's constructor. You can then access the parent from the child through the reference.
2. If you're using Caliburn's conductors then the child will already have a `Parent` property set for you.
