### ISSUE TITLE
Actions stopped working after upgrade to CM 3.2.0 and XF 2.4.0.282

### ISSUE THREAD

**Issue by sethom** [Caliburn-Micro/Caliburn.Micro#484]
Today I upgraded an XF project to CM 3.2.0 and XF 2.4.0.282 after upgrading Xcode from 8 to 9 and my caliburn micro actions stopped working afterwards. Here is an example:

 <Button WidthRequest="{Binding ButtonHeight}" HeightRequest="{Binding ButtonHeight}" Text="Answer" Margin="0" BorderWidth=".5" BorderColor="Red" IsVisible="{Binding IsEnabled}" cal:Message.Attach="[Event Clicked] = [Action EvaluateAnswer('TT')]" />

I know this isn't much to go on but I verified that the ViewModel was bound to the view and that EvaluateAnswer(string answer) is still a public method on the VM. Did anything change with XF 2.4.0.282 that might interfere with action functionality? It was working for me right before the upgrade.

**Comment by sethom** [comment]
I wish I could retract this. Long story but this was just user error on my part. Actions are working just fine. I'm closing this out...

**Comment by nigel-sampson** [comment]
No worries, glad to found a solution.
