### ISSUE TITLE
Documentation Refers To Wrong URL

### ISSUE THREAD

**Issue by Nezteb** [Caliburn-Micro/Caliburn.Micro#486]
A lot of places in the documentation refer to [caliburnproject.org](caliburnproject.org), a website which is obviously not related to Caliburn.Micro anymore.

In may places the namespace is referenced as:
`xmlns:cal="http://www.caliburnproject.org"`

That doesn't work anymore, and you instead have to use something like:
`xmlns:cal="clr-namespace:Caliburn.Micro;assembly=Caliburn.Micro.Platform"`

Example: https://caliburnmicro.com/documentation/actions

**Comment by nigel-sampson** [comment]
Xaml namespace imports are sadly different on each platform, the initial import does work on WPF.

We should transition away from using that url though, potentially in 4.0.0

**Comment by nigel-sampson** [comment]
I've pushed a change adding a prefix for a site that actually exists. 

Will deprecate the old one in a later version.
