### ISSUE TITLE
System.ComponentModel.DataAnnotations

### ISSUE THREAD

**Issue by ezerecero** [Caliburn-Micro/Caliburn.Micro#489]
I'm starting a proyect and thinking seriuosly to adopt Caliburns micro but I have all my validation with System.ComponentModel.DataAnnotations. I wonder if it is possible to use or is there a better way to validate within this framework? Thanks a lot

**Comment by rossvegas** [comment]
Hi @ezerecero  What platform are you targeting, WPF, UWP or Xamarin?

**Comment by ezerecero** [comment]
Hi! Sorry I did not specified. Is WPF. Thanks

**Comment by rossvegas** [comment]
I am not sure if there is any special hooks for validation in caliburn micro for validation, I have never even considered it. The way I do it is to implement INotifyDataErrorInfo on my models, WPF UI controls understand this interface and render validation errors automatically with a nice red box and a tooltip. I use this technique with the built in WPF controls and teleriks WPF controls. This blog post gives a good overview of how to do it.

http://burnaftercoding.com/post/asynchronous-validation-with-wpf-4-5/

I personally use the neat FluentValidation library by @JeremySkinner I think it worth a look if you are at the point of considering how to do validation.

https://github.com/JeremySkinner/FluentValidation

**Comment by ezerecero** [comment]
Thank you very much. I was very usefull!!

**Comment by nigel-sampson** [comment]
@rossvegas is correct where, CM doesn't do anything with special, any standard WPF validation pattern will work correctly.

From what I recall when applying property conventions we check to see if the view model implments `IDataErrorInfo` and [configures the binding](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ConventionManager.cs#L157).

**Comment by ezerecero** [comment]
Thank you very much, I implemented IDataErrorInfo and works fine.
