### ISSUE TITLE
Ninject Dynamic Class Proxy WPF Binding don't update

### ISSUE THREAD

**Issue by jbender2** [Caliburn-Micro/Caliburn.Micro#495]
If you intercept a View Model using Ninject Dynamic Class Proxy the WPF bindings don't get updated when calling NotifyOfPropertyChange.  My VM is inheriting PropertyChangeBase.

**Comment by nigel-sampson** [comment]
My guess is that the dynamic proxy doesn't implement the `INotifyPropertyChanged` interface so the bindings won't be working.

This doesn't appear to be a Caliburn.Micro issue.
