### ISSUE TITLE
[UWP] NavigationView with <Frame> element

### ISSUE THREAD

**Issue by Ullmie02** [Caliburn-Micro/Caliburn.Micro#497]
I have a little UWP application with a NavigationView.
In my App.xaml.cs I add the ViewModels for my Views in the `Configure`-Method.
In the `OnLaunched`-Method I use `DisplayRootView<NavigationRoot>` to navigate to the NavigationRoot. 

In my NavigationRootViewModel I want to set the Frame use for `navigationService.NavigateToViewModel` to the Frame inside the NavigationView.
How do I achieve that?

**Comment by nigel-sampson** [comment]
If you're using `DisplayRootView` this should already be setting up a `Frame` control for you as the root element of the window and start the navigation service for you,

At that point you won't need a navigation root and just the pages etc.

The [Setup.UWP](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/samples/setup/Setup.UWP) sample has all you'll need.
