### ISSUE TITLE
TryClose taking too long to close the screen

### ISSUE THREAD

**Issue by saniit2008** [Caliburn-Micro/Caliburn.Micro#498]
I have a WPF  screen having Telerik Rad Grid View having 500 rows . When I  try to close the screen using TryClose , base.TryClose  is taking around 1 second to finish and because of this screen is kind of freezing .

Is there any way to fix this issue ?

**Comment by nigel-sampson** [comment]
Have a number of ideas of what it could be, but could you provide a sample demonstrating this problem. It will be easier than back and forth about the set up of your approach.

**Comment by saniit2008** [comment]
![tryclose](https://user-images.githubusercontent.com/34713599/34241463-c6765936-e63b-11e7-96ef-92acabb14ae1.PNG)
Hi Nigel,

I am just trying to close View Model using base.TryClose(dialogResult) . The view which I am working on  is heavy , say a Telerik Grid having custom cells etc takes more time to close .am I am replicating this issue using 500 rows in grid .

Let me know if you have any questions .

**Comment by nigel-sampson** [comment]
1. Is the view model a `Conductor` and are the rows part of the `Items` collection?
2. Are the view model representing the rows inheriting from `Screen` or anything that implements `IGuardClose`?

My suspicion would be that when closing the view model its trying to check if each individual rows are available to close.

I can't replicate this using a regular data grid.

**Comment by nigel-sampson** [comment]
Closing due to lack of extra information.
