### ISSUE TITLE
Automatically generate a boilerplate view from viewmodel

### ISSUE THREAD

**Issue by MycroftHolmes1989** [Caliburn-Micro/Caliburn.Micro#500]
I'm working on a MVVM project where I'm using Caliburn.micro. The problem is that, I have my ViewModels in one folder and my Views in another. Also, I have about 20-30 properties per ViewModel and about a dozen ViewModels and growing. Can you kindly make a tool to translate my string/int Properties to Textboxes and BindableCollections to ComboBoxes? In other words, is there any way to make a tool to generate a View automatically from ViewModel? If that is not possible, then is there any tool to check whether there is a control in the View that binds with a Property in the ViewModel? Frankly, creating Views by hand is quite tedious and is prone to errors. There's a tool that does this job for non-Caliburn projects: https://marketplace.visualstudio.com/items?itemName=KarlShifflettkdawg.XAMLPowerToysforVisualStudio2015

Is there any Caliburn-specific tool out there for this job?

**Comment by nigel-sampson** [comment]
There are no Caliburn.Micro specific tools like this.  It's definitely possible to built a tool to auto generate UI based off view models, but it's not on the roadmap for this project.

I know Telerik did have a DataForm style control that would auto generate forms based off view models. I'm not sure if it's still around or what state it's in.
