### ISSUE TITLE
How do I navigate to a new page?

### ISSUE THREAD

**Issue by alexr422** [Caliburn-Micro/Caliburn.Micro#501]
Hi,
I'm new to Xamarin and I'm trying to navigate to a new page in Xamarin.Android using Caliburn. navigation.NavigateToViewModelAsync<MyViewModel>() opens MyView, but it's not binded to MyViewModel...

Sorry, I got it, can be deleted.

**Comment by Motoky** [comment]
Is it possible you could post a solution? I'm having the same problems currently if it's possible.
