### ISSUE TITLE
App can't start in Xamarin.Forms and iOS

### ISSUE THREAD

**Issue by godrose** [Caliburn-Micro/Caliburn.Micro#502]
Platform: Xamarin.Forms - latest version, iOS 11.2, C.Micro -latest version
I've followed the sample for Xamarin.Forms and I get the following exception in the `Main` method of the iOS project:
**Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch**

**Comment by nigel-sampson** [comment]
Can you provide an example repository with this error. No specific reason springs to mind for this error.

**Comment by godrose** [comment]
It was my mistake.
Will close the issue.
Btw, is there any ETA for .NETStandard-enabled package release/pre-release?
I ditched the PCL a long time ago and would love to consume C.Micro as
.netstandard

**Comment by nigel-sampson** [comment]
It's part of the dev on 4.0.0 but will include breaking changes.

You can compile off that branch and use it if you want.

**Comment by godrose** [comment]
That's what i´m doing right now. Thanks

**Comment by nigel-sampson** [comment]
Ok, just be aware breaking changes on the horizon, just pushed a lot of the event aggregator last night.

You can follow the 4.0.0 project above to see what's going on.

**Comment by godrose** [comment]
Thanks @nigel-sampson 
FYI, The current source doesn't compile Android and fails at my machine with the following:
Severity	Code	Description	Project	File	Line	Suppression State
Could not load assembly 'Caliburn.Micro, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?	Caliburn.Micro.Platform	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets

**Comment by godrose** [comment]
@nigel-sampson 
I see there's a lot of work to do to get the 4.0.0 released. Could be a matter of months IMO.
Is there any option of creating an intermediate 3.3.0 release which introduces no breaking API changes and provides .NETStandard support instead? 
That would be very helpful for cross-platform projects and might greatly influence the decision for new projects: React.Native vs. Xamarin.Forms.
Thanks for the response.

**Comment by nigel-sampson** [comment]
The problem is that we can't do a .NET Standard 3.3.0 without making it a breaking change or a LOT of work to handle the platforms that 3.x supports that don't support .NET Standard.

The 4.0.0-alpha.1 if you ignore the event aggregator is very close to this.  I can potentially create tag that points to something that should be compilable into what you're after.

**Comment by godrose** [comment]
Cool.
Thanks.
