### ISSUE TITLE
Create alpha nuget packages for 4.0.0

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#503]
- [x] Handle Caliburn.Micro.Platform.UWP.rd.xml
- [ ] Documentation

**Comment by godrose** [comment]
Hooray!!!

**Comment by godrose** [comment]
@nigel-sampson Any expectation on when this is going to be pre-released? 
May I offer some help?

**Comment by nigel-sampson** [comment]
Just finishing up some docs.  If you email me your address I can send an early copy for testing if you'd like,

**Comment by godrose** [comment]
godrose@gmail.com

**Comment by nigel-sampson** [comment]
Published as `4.0.0-alpha.1`

**Comment by superware** [comment]
Is there a reason for NuGet 4.0.0-alpha.1 not being signed (strongly named)? Is it possible to publish a signed 4.0.0-alpha.2?

Thanks!
