### ISSUE TITLE
Conductor<T>'s ActiveItem not Updating View

### ISSUE THREAD

**Issue by Aleksbgbg** [Caliburn-Micro/Caliburn.Micro#504]
## Problem
I am using Caliburn Micro in WPF on Windows / desktop.

I have the following very simple `ShellView.xaml`:
```xaml
<ContentControl Caliburn:View.Model="{Binding ActiveItem}"/>
```

I am using a `Conductor<IViewModelBase>` to display the `ActiveItem`.

My `ShellViewModel.cs` (`Conductor`) looks like this:
```cs
    internal sealed class ShellViewModel : Conductor<IViewModelBase>, IShellViewModel
    {
        private readonly IMainViewModel mainViewModel;

        public ShellViewModel(IWelcomeViewModel welcomeViewModel, IMainViewModel mainViewModel)
        {
            this.mainViewModel = mainViewModel;

            welcomeViewModel.Deactivated += WelcomeViewModel_Deactivated;
            ChangeActiveItem(welcomeViewModel, false); // <-- Initial ActiveItem
        }

        private void WelcomeViewModel_Deactivated(object sender, DeactivationEventArgs e)
        {
            ((IWelcomeViewModel)sender).Deactivated -= WelcomeViewModel_Deactivated;
            ChangeActiveItem(mainViewModel, true); // <-- Changes ActiveItem to MainViewModel
        }
    }
```

For the purposes of testing, `WelcomeViewModel` `TryClose()`-s after 10 seconds:
```cs
    internal class WelcomeViewModel : ViewModelBase, IWelcomeViewModel
    {
        public WelcomeViewModel()
        {
            Timer timer = new Timer(10_000) { Enabled = true };
            timer.Elapsed += (sender, e) => TryClose();
            timer.Start();
        }
    }
```

The expected result is that the view should update its `UserControl` to match whichever `ViewModel` has been bound to, which is the `ActiveItem`, which changes after 10 seconds. However, it doesn't - the screen becomes blank (white).

## Attempted Solutions
I've tried swapping the two ViewModels around - having the `MainViewModel` go first - and in that case, the `MainViewModel` is displayed, however the screen does not end up displaying `WelcomeViewModel`; it goes blank instead.

Subsequently, I tried manually notifying of change.
```cs
NotifyOfPropertyChange(() => ActiveItem);
```
This also did not work.

I have also tried using convention binding on the `ShellView.xaml` (`x:Name="ActiveItem"`) which also did not work.

Finally, I remember once having to activate my conductor (`Conductor<T>.Collection.OneActive`) in order for it to properly activate/deactivate views, so I tried that as well (in `ShellViewModel.cs`):
```cs
ScreenExtensions.TryActivate(this);
```
also to no avail.

What worked, however, was having a custom `IViewModelBase` property (e.g. `ActiveView`), and binding to that instead, changing it whenever `ChangeActiveItem` is called.

## Question
I can, of course, fix this issue by either rolling my own `ActiveItem`, or not using `Conductor<T>` at all, however I would like to do this properly.

Is there some kind of trick to using `Conductor<T>`, or is this just a bug? I have searched plenty on the internet and nothing seemed to work.

**Comment by godrose** [comment]
@Aleksbgbg 
If I recall correctly you should always add the item first and then call `ActivateItem` on it.
I also always use either `Conductor<any>.Collection.OneActive` or `Conductor<any>.Collection.AllActive` depending on the scenario

**Comment by Aleksbgbg** [comment]
@godrose 
`Conductor<T>` doesn't have its own collection of items. I was also searching for a solution like that.

I guess the next option would be to use the `OneActive` conductor, however I did see the use of just the regular `Conductor<T>` somewhere on the docs for this exact purpose.

I also don't really have a collection of items, there's just two and they aren't intended to have varying life-cycles. Feels like `Conductor<T>` is a better choice.

I will use `Conductor<T>.Collection.OneActive` if a solution to this problem isn't found.

**Comment by godrose** [comment]
Good luck

**Comment by nigel-sampson** [comment]
I haven't dug into the why yet, but the following code works.
``` csharp
public class ShellViewModel : Conductor<Screen>
{
    protected override async void OnInitialize()
    {
        ChangeActiveItem(new WelcomeViewModel(), false);

        await Task.Delay(2000);

        ChangeActiveItem(new MainViewModel(), true);
    }
}
```

My best guess is that there's something a bit odd going on by using `TryClose` in `WelcomeViewModel`.

**Comment by Aleksbgbg** [comment]
@nigel-sampson thanks Nigel, I will try this when I have some time available.

**Comment by nigel-sampson** [comment]
From what I can tell there's a bit of a race condition happening here. Calling `TryClose` on `WelcomeViewModel` will deactivate that view model, and remove it from being the `ActiveItem`. However by listening for that event and jumping in the middle we're trying to replace the `ActiveItem` before the previously one is finished being closed.

**Comment by Aleksbgbg** [comment]
@nigel-sampson how could this issue be resolved without the delay?

public ShellViewModel(IWelcomeViewModel welcomeViewModel, IMainViewModel mainViewModel)
        {
            async void WelcomeViewModelDeactivated(object sender, DeactivationEventArgs e)
            {
                welcomeViewModel.Deactivated -= WelcomeViewModelDeactivated;
                await Task.Delay(1);
                ChangeActiveItem(mainViewModel, true);
            }

            welcomeViewModel.Deactivated += WelcomeViewModelDeactivated;
            ActivateItem(welcomeViewModel);
        }

I feel like a protected event in the `Conductor` which could be along the lines of `ActiveIte

**Comment by nigel-sampson** [comment]
I only added the delay as a difference from using the `Timer` just to simulate your desired behavior.  My sample wouldn't have time timer in the `WelcomeViewModel` and wouldn't need to deactivate itself.

In your code having the delay in there (even a millisecond is enough) due to UI thread dispatching not to jump into the middle of the race condition I mentioned above.

**Comment by Aleksbgbg** [comment]
@nigel-sampson in the `WelcomeViewModel`, I will be welcoming the user to the application, and once they have entered the necessary information, the program will be set-up for initial use.

In other words, once the info has been entered, the ViewModel will need to `TryClose`.

I can implement this alternatively, with an event `SetupComplete`, which will allow the `Conductor` to set up the `MainViewModel` next.

Do you believe this to be an adequate solution, or would you have something else in mind?

**Comment by nigel-sampson** [comment]
A custom event would work fine.

**Comment by Aleksbgbg** [comment]
Okay, thanks for all the help. You can close the issue if you wish.
