### ISSUE TITLE
Bind.Model doesn't work in View-First mode.

### ISSUE THREAD

**Issue by ling281021799** [Caliburn-Micro/Caliburn.Micro#507]
Although in the document,  it says, it will convert string to a viewmodel, in fact, it only convert the viewmodel when binding the context but not the Action.Target. Instead of the viewmodel, it binds the Action.Target with a string type.

**Comment by nigel-sampson** [comment]
The usage of strings in Bind.Model was deprecated, if there's still a reference to that in the documentation it should be removed.

**Comment by robcecil** [comment]
Why was the usage of strings in Bind.Model deprecated?

**Comment by nigel-sampson** [comment]
Long term it wasn't something I liked as a feature, it made a lot of diagnosis of problems harder and just generally caused more issues than it was worth,
