### ISSUE TITLE
WPF Conductor<Screen> handling a child Screen calling TryClose

### ISSUE THREAD

**Issue by Villhellm** [Caliburn-Micro/Caliburn.Micro#509]
According to the documentation:
"If the screen is being controlled by a Conductor, it asks the Conductor to initiate the shutdown process for the Screen."
Is there a way for the Conductor to handle a when a child Screen calls TryClose? It seems like there is according to the documentation, but I can't find a way. Adding event handlers for the child AttemptingDeactivation or Deactivated events doesn't work. They seem to never be called when the child Screen closes itself. I just want the Conductor to know that the child is trying to close or is closed. I could just add a custom event in the child and call it on closing allowing the parent to handle it, but I am hoping there is a way of doing this within the framework. 

I apologize if this has been asked before, but each time I search for this I get bounced around between issues that don't answer this question.

**Comment by markgould** [comment]
Under the hood it calls DeactivateItem on the Conductor, which you should be able to override and do whatever you need to with it.

**Comment by Villhellm** [comment]
Thank you! This is exactly what I was looking for.

**Comment by nigel-sampson** [comment]
Thanks @markgould
