### ISSUE TITLE
.NET Native tool chain runtime errors

### ISSUE THREAD

**Issue by raviolpula** [Caliburn-Micro/Caliburn.Micro#510]
Hi, 
We are currently working on submitting our UWP app to Microsoft store. For this we need to build our project with "Compile with .NET Native tool chain" to pass store certification. But we got run-time exceptions for Caliburn events once this is enabled. Without "Compile with .NET Native tool chain" enabled, Caliburn events are working fine. After further research, we could able to resolve some of them by adding these in our project rd.xml. 

{Assembly Name="Caliburn.Micro.Platform.Core" Dynamic="Required All" Serialize="Required All" Activate="Required All" Browse="Required All"
    Assembly Name="Caliburn.Micro.Platform.UWP" Dynamic="Required All" Serialize="Required All" Activate="Required All" Browse="Required All"
    Assembly Name="Caliburn.Micro" Dynamic="Required All" Serialize="Required All" Activate="Required All" Browse="Required All" }

But observed that, below attach events are still not working.
View-
cm:Message.Attach="[Event Click] = [Action ViewAllClickAction()]"
ViewModel-
public void ViewAllClickAction()

To fix it, we need to add source & eventargs parameters in the view & viewmodel like below. 
cm:Message.Attach="[Event Click] = [Action ViewAllClickAction($source, $eventArgs)]"
public void ViewAllClickAction(object sender, RoutedEventArgs e)

1) This is lot of work for us as there are lot of Attach usages. Is there any other workaround? 

2) Other issue is, in below code UpcomingRecordingsCancelClicked() method on ViewModel used to work, but it's not working anymore with .net native.

<interactivity:Interaction.Behaviors>
                                    <core:EventTriggerBehavior EventName="Click">
                                        <cm:ActionMessage MethodName="UpcomingRecordingsCancelClicked">
                                            <cm:Parameter Value="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=DataContext}" />
                                        </cm:ActionMessage>
                                    </core:EventTriggerBehavior>
                                </interactivity:Interaction.Behaviors>
public void UpcomingRecordingsCancelClicked(UpcomingItem item)

3) Custom events are not working
View-
public event EventHandler<RoutedEventArgs> BackButtonClick;
cm:Message.Attach="[Event BackButtonClick] = [Action GoBackAction($source, $eventArgs)]]">

ViewModel-
public override void GoBackAction(object sender, RoutedEventArgs e)

All the above scenarios are working fine without "Compile with .NET Native tool chain".

Thanks for your help.

**Comment by nigel-sampson** [comment]
I haven't seen any issues like this before and haven't been able to replicate it.

Is it possible for you to create a small app that replicates this issue for me to look.

Thanks.

**Comment by nigel-sampson** [comment]
Closing due to lack of extra information.
