### ISSUE TITLE
bind text box to `int?` in UWP

### ISSUE THREAD

**Issue by MkazemAkhgary** [Caliburn-Micro/Caliburn.Micro#513]
I can not bind textbox to `int?`. currently I'm binding to string and doing manual parsing. it would be nice to have automatic binding to `int?`. when TryParse fails, int? should become null.

**Comment by nigel-sampson** [comment]
Typically it's not a scenario I want to support, usually because of the permutations of different types and the conversions. This sort of automatic conversion doesn't provide good hooks into providing feedback to the user.
