### ISSUE TITLE
Guard method not firing on Xamarin.Forms

### ISSUE THREAD

**Issue by cbagpipe** [Caliburn-Micro/Caliburn.Micro#517]
Xamarin.Forms 2.5.0.280555
Caliburn.Micro.Xamarin.Forms 3.2.0

MainPageViewModel.cs
```csharp
using Caliburn.Micro;

namespace Client
{
    public class MainPageViewModel : Screen
    {
        private int count = 1;
        public int Count
        {
            get { return count; }
            set
            {
                count = value;
                NotifyOfPropertyChange(() => Count);
            }
        }

        public void CountUp(int i)
        {
            Count += i;
        }

        public bool CanCountUp(int i)
        {
            if (i > 10)
                return false;

            if (Count < 10)
                return true;
            else
                return false;
        }
    }
}
```

MainPageView.xaml
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:AS6_AndroidClient"
             xmlns:cm="clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms"
             Title="TEST"
             x:Class="Client.MainPageView">
    <ContentPage.Content>
        <StackLayout Orientation="Vertical">
            <Label x:Name="Count" Text="{Binding Count}"/>
            <Button Text="{Binding Delta" x:Name="ButtonDelta">
                <Button.Triggers>
                    <EventTrigger Event="Clicked">
                        <cm:ActionMessage MethodName="CountUp" AssociatedObject="{x:Reference ButtonDelta}" >
                            <cm:Parameter Value="{Binding Source={x:Reference Count}, Text}"/>
                        </cm:ActionMessage>
                    </EventTrigger>
                </Button.Triggers>
            </Button>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

**Comment by nigel-sampson** [comment]
Interesting, thanks for the bug report.  Can I confirm a couple of things.

1. Is the guard method being called at all? When are you expecting it to be called? 
2. Is the `CountUp` method called when the button is clicked?
3. As a test can you switch to a property for the guard to see if that changes any behavior?

**Comment by cbagpipe** [comment]
1. It's called twice before page appears. I'm expecting it called every time `<cm:Parameter Value="{Binding Source={x:Reference Count}, Text}"/>` value  changing, as written on actions documentation page. So every time I click button.
2. CountUp called every time and workng as expected.
3. Guard property works, but guard method not.

**Comment by nigel-sampson** [comment]
Thanks.

**Comment by vb2ae** [comment]
Sorry for the delayed response to this bug.  There is a property in the ActionMessage class EnforceGuardsDuringInvocation it is false by default.  Set it to true to get the guard to fire.  One way to do it is in the constructor of the view model set the property to true.


        public MainViewModel()
        {
            ActionMessage.EnforceGuardsDuringInvocation = true;
        }
