### ISSUE TITLE
One ViewModel in Two Places (Same View)

### ISSUE THREAD

**Issue by Aleksbgbg** [Caliburn-Micro/Caliburn.Micro#519]
I am currently attempting to display one `ViewModel` instance in two separate places.

## Problem
Since it is the same instance, I assumed that this will be fine with `Caliburn.Micro`, however that does not seem to be the case:

### Before:
![](https://cdn.discordapp.com/attachments/370513777122082818/433388417578172426/wOx07JHDDlOvAAAAABJRU5ErkJggg.png)

### After:
![](https://cdn.discordapp.com/attachments/370513777122082818/433388668871507979/unknown.png)

As you can see, the contents of the `ListBox` have disappeared (the item is still there), and have shown up in the `ItemsControl` on the right, instead of duplicating.

## Code
Both of my view instances are nested inside `DataTemplate`s, with a `ContentControl` used to display the appropriate views.
```xaml
<DataTemplate DataType="{x:Type ViewModels:PreviewViewModel}">
    <StackPanel Margin="5">
        <ContentControl Caliburn:View.Model="{Binding VideoViewModel, Mode=OneTime}"/>
...
```

## Question
How can I prevent CM from removing the first view instance?

**Comment by nigel-sampson** [comment]
#516 discusses much the same problem.
