### ISSUE TITLE
How to call Binding outer from children of the tag that sets the ItemsSource attribute?

### ISSUE THREAD

**Issue by kanryu** [Caliburn-Micro/Caliburn.Micro#520]
Hi,

I'm making a UWP application.
I write < ItemsControl ItemsSource="{Binding BodiesModel}"> tag, and cannot Binding Properties of the ViewModel of the page.
How to do it?

PageView.xaml:

    <ItemsControl ItemsSource="{Binding BodiesModel}">
        <ItemsControl.Template>
            <ControlTemplate TargetType="ItemsControl">
                <Border BorderThickness="1" BorderBrush="Black" Background="Azure">
                    <ItemsPresenter Margin="10" />
                </Border>
            </ControlTemplate>
        </ItemsControl.Template>
        <ItemsControl.ItemsPanel>
            <ItemsPanelTemplate>
                <StackPanel Orientation="Vertical" />
            </ItemsPanelTemplate>
        </ItemsControl.ItemsPanel>
        <ItemsControl.ItemTemplate>
            <DataTemplate>
                <CheckBox Content="DayEnable" IsChecked="{Binding Path=DayEnable, RelativeSource={RelativeSource TemplatedParent}}"/>
            </DataTemplate>
        </ItemsControl.ItemTemplate>
    </ItemsControl>

PageViewModel .cs:

    public class PageViewModel : Screen
    {
        public bool DayEnable { get; set; }
        public ObservableCollection<BodyViewModel> BodiesModel { get; set; }
    }

**Comment by nigel-sampson** [comment]
I don't see any problem with the view / view model there. 

Can you confirm the view model is being instantiated? If not typically is because the view / view model types are in namespaces such that the convention based locator can't locate it.

Otherwise can you provide a GitHub repo that reproduces the problem and I'll take a look.

**Comment by nigel-sampson** [comment]
Ah my bad, I missed that this was UWP and assumed it was WPF given the `TemplatedParent` which I believe doesn't work the same way in UWP.

You can use pathed bindings to some element outside the `ItemControl`.

1. Give the `ItemsControl` a name
``` xml
ItemsControl x:Name="ItemsRoot" ItemsSource="{Binding BodiesModel}">
```

2.  Update the `ItemsTemplate` binding
``` xml
 <CheckBox Content="RelativeSource DayEnable" IsChecked="{Binding Path=DataContext.DayEnable, ElementName=ItemsRoot, Mode=TwoWay}"/>
```

Had to a couple more things to check the binding

3. Update the first checkbox binding to `TwoWay`
``` xml
CheckBox Content="DayEnable" IsChecked="{Binding DayEnable, Mode=TwoWay}" />
```

4. Update the view model to notify of property changes.
``` csharp
private bool dayEnable;

public bool DayEnable
{
    get => dayEnable;
    set
    {
	    dayEnable = value;
	    NotifyOfPropertyChange();
    }
}
```

**Comment by kanryu** [comment]
@nigel-sampson  Thanks a lot! :)
