### ISSUE TITLE
Parsing of negative numbers passed to a Target of an Action does not work

### ISSUE THREAD

**Issue by damiandixon** [Caliburn-Micro/Caliburn.Micro#521]
The following XMAL statement is not correctly parsing the '-0.1' value:

`cal:Message.Attach="[Event Click] = [Action TargetTemperatureIncrement(-0.1)]"`

![image](https://user-images.githubusercontent.com/1237723/38975331-5d5e065c-43a5-11e8-891f-c22f15465362.png)

The following XMAL statement works correctly.

`cal:Message.Attach="[Event Click] = [Action TargetTemperatureIncrement(0.1)]"`

![image](https://user-images.githubusercontent.com/1237723/38975430-bb446b6c-43a5-11e8-8eea-009562bbef0d.png)

The workaround in this case is to have two methods, one a decrement and one an increment.

**Comment by nigel-sampson** [comment]
Thanks for the bug report.
