### ISSUE TITLE
WithParam cannot set null value

### ISSUE THREAD

**Issue by enrico-padovani** [Caliburn-Micro/Caliburn.Micro#528]
Hi,

I need to pass a null value to a view model but I've discovered that, in this piece of code, you do not allow passing null. Is there a particular reason why doing that?

https://github.com/Caliburn-Micro/Caliburn.Micro/blob/336e9506c0019fc5ea346aa14c4743622e42d45f/src/Caliburn.Micro.Platform/net40/NavigationHelper.cs#L26

Thanks,
Enrico

**Comment by nigel-sampson** [comment]
We originally didn't allow passing null when parameters were ultimately passed as query strings, for Xamarin.Forms we can probably relax that restriction.

**Comment by enrico-padovani** [comment]
Thanks for you answer, at the moment I've replaced the default NavigationHelper with my own. I'm using it in a desktop app, not Xamarin. Do you have any release plan for v4?

**Comment by nigel-sampson** [comment]
At the moment "when it's done" 😄
