### ISSUE TITLE
Problem in WPF project template

### ISSUE THREAD

**Issue by Const-me** [Caliburn-Micro/Caliburn.Micro#529]
Steps to reproduce:

Using VS2017, create a new WPF project, .NET 4.6.2.

Add Nuget project caliburn.micro.start.

Expected result: should contain e.g. ShellView.xaml, and also ShellView.cs, with correct `<DependentUpon>` element in the csproj linking them together.

Actual result: it doesn’t create a code behind file. The project compiles OK, but manually adding that file is problematic because it’s impossible to add child source files in the IDE.

**Comment by nigel-sampson** [comment]
Thanks, I'll look into it.

**Comment by nigel-sampson** [comment]
Thanks @qtuu
