### ISSUE TITLE
Support async methods on the IDeactivateInterface

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#530]

**Comment by godrose** [comment]
@nigel-sampson Great to have you back!

**Comment by nigel-sampson** [comment]
Cheer, its been a busy few months and definitely not where I'd like to be on this work.  The last sticking point with this part will be around the `IPlatformProvider` and the view close action.  It's a bit of a mess.

Once we're done there it'll be aysnc-ing the outer layer of window managers and navigation services.

**Comment by godrose** [comment]
@nigel-sampson ping me if you need any assistance.

**Comment by nigel-sampson** [comment]
To be honest it hasn't been going well. I've been struggling with getting repeatable and consistent builds on the `dev/4.0.0` branch. I typically see one in five builds succeed randomly which isn't something I'm comfortable with. I suspect the problem is in trying to bend the new project system to the structures previously in place for the project rather than going the other way.

I've been experimenting with building using the new project system from the ground up and finding a lot more success.  Hoping to be back to a stable build platform this week when I merge in this private branch.
