### ISSUE TITLE
How to use Navigation in Xamarin.Forms with Micro Caliburn

### ISSUE THREAD

**Issue by andre-motta** [Caliburn-Micro/Caliburn.Micro#531]
I'm recently transfering a project from pure xamarin.forms to micro caliburn

I used to navigate by using this from the viewModel

await this.Navigation.PushAsync(new CameraView());

having a navigation service initialized on the app.cs by

MainPage = new NavigationPage(new MainPage())

I really like the ease of binding that caliburn forms gives me but i couldn't find out how to do this..

Thanks in advance!

**Comment by andre-motta** [comment]
Nevermind, i had forgotten to change the navigation property on my view Models.

**Comment by nigel-sampson** [comment]
Glad to here it was solved. Thanks.
