### ISSUE TITLE
Adding custom controls on stackpanel 

### ISSUE THREAD

**Issue by pccrazy** [Caliburn-Micro/Caliburn.Micro#534]
Hello Everyone, 

I have the following xaml, 

          <ScrollViewer VerticalScrollBarVisibility="Auto" Height="100"  Grid.Column="1" Grid.Row="1">
                <StackPanel x:Name="ExamRulesStackPanel" Height="100" />
            </ScrollViewer>

How I can access ExamRulesStackPanel from the ViewModel so that I can add a child to it. 
For instance, I wanted to add a TextBlock and then a button based on some logic. 

Plz, Help. 
Best Regards, 
Anwar Salim

**Comment by nigel-sampson** [comment]
That's not something I'd typically want to do with the view model as you'e breaking that gap between the two and making the view model harder to unit test.

What you can do is have the controls in the stack panel and conditionally control their visibility from the view model.

**Comment by pccrazy** [comment]
The issue here is that the controls dynamic, and the creation of the controls should be code based.

**Comment by nigel-sampson** [comment]
Typically in those approaches I expose view models corresponding to the types of inputs I want and have custom views bound to an `ItemsPanel`.

``` xml
<ItemsControl ItemsSource="{Binding Fields}">
    <ItemsControl.ItemTemplate>
        <DataTemplate>
            <ControlControl cm:View.Model="{Binding}" />
        </DataTemplate>
    </ItemsControl.ItemTemplate>
</ItemsControl>
```

In your view mode when you meed to add a field (say a Product Selector).

``` csharp
Fields.Add(new ProductSelectorViewModel());`
```

As long as you already have a corresponding `ProductSelectorView` it will be added correctly.

**Comment by yjinhyuk** [comment]
> Typically in those approaches I expose view models corresponding to the types of inputs I want and have custom views bound to an `ItemsPanel`.
> 
> ```
> <ItemsControl ItemsSource="{Binding Fields}">
>     <ItemsControl.ItemTemplate>
>         <DataTemplate>
>             <ControlControl cm:View.Model="{Binding}" />
>         </DataTemplate>
>     </ItemsControl.ItemTemplate>
> </ItemsControl>
> ```
> 
> In your view mode when you meed to add a field (say a Product Selector).
> 
> ```cs
> Fields.Add(new ProductSelectorViewModel());`
> ```
> 
> As long as you already have a corresponding `ProductSelectorView` it will be added correctly.

So shall I use ItemsControl instead of StackPanel.
Right?
