### ISSUE TITLE
EventAggregator calling handler multiple times with inherited object

### ISSUE THREAD

**Issue by dealproc** [Caliburn-Micro/Caliburn.Micro#535]
Consider the following objects:

```c#
public class MyEventObject
{
 public int PropertyOne { get; set; }
}
public class MyGenericEventObject<TValue> : MyEventObject
{
 public TValue SomeValue { get; set; }
}
```

With the v4.0-Alpha1 version of CM, I'm getting two calls to an `IHandle<MyEventObject>` whereas in the v3.x version of CM, I'm only getting a single call.  Is this by design or a bug in the system?

Will review further and see if maybe there is a bug on my side, as this is a new discovery and I did not have this in prior usage of the v4.0-alpha1 libs.

**Comment by nigel-sampson** [comment]
This does feel like a bug.  My assumption is that you should only be getting one event per publish. 

Any further info would be good. Esp the types in both the `IHande<>` as well as the type published.

**Comment by dealproc** [comment]
# How it's implemented # 

```CSharp
public class MyViewModel : Screen, IHandle<MyEventObject>
{
  public Task Handle(MyEventObject message, CancellationToken cancellationToken)
  {
   .... {work in here}
  }
}
```

# Base Event

```CSharp
public class MyEventObject
{
 public int PropertyOne { get; set; }
}
```

# Published Event # 

```CSharp
public class MyGenericEventObject<TValue> : MyEventObject
{
 public TValue SomeValue { get; set; }
}
```

Now, if I'm accurate, when I called `await eventAggregator.BeginPublishOnUIThread((MyEventObject)myEventWithGenericType);` where I did a direct cast to the base `MyEventObject`, it did seem to resolve the issue.

HTH

**Comment by dealproc** [comment]
do you want a full scale repro of this, or is this enough for you to go on?  I could honestly be doing something incorrectly that I missed, etc.?

**Comment by nigel-sampson** [comment]
What you've got there looks fine, if I can't recreate the issue later on I'll come back to you.

**Comment by nigel-sampson** [comment]
I can't recreate this issue with latest versions, can you recreate with the current build from MyGet?

**Comment by dealproc** [comment]
Let's close it for now... if/when i get back to the solution, i will test and re-check this.
