### ISSUE TITLE
OnViewLoaded is not called

### ISSUE THREAD

**Issue by adishlomo** [Caliburn-Micro/Caliburn.Micro#536]
Hi,

I have task list with several screens. the issue is that OnViewLoaded is called only once for each screen.
If I open screen 1, then switch to screen  2 and then go back to screen 1  -
OnViewLoaded is not called in the second time on screen 1 .

Any Ideas? Is it a bug or should it work like this?

**Comment by popcatalin81** [comment]
If you're using a ViewModel which is `IViewAware` like a view derived from `Screen`, it will cache the View and only raise OnViewLoaded once.

**Comment by adishlomo** [comment]
Thanks for the detailed answer
