### ISSUE TITLE
missed Scenario.Functional.Core.dll, FSharp Core,WebClient

### ISSUE THREAD

**Issue by jacekarwal** [Caliburn-Micro/Caliburn.Micro#537]
I am trying to compile your scenarios project from sample. I'm receiving errors:

3>------ Build started: Project: Scenario.KeyBinding, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "FSharp.Core". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>FSC: error FS0193: The module/namespace 'System.Net' from compilation unit 'System' did not contain the namespace, module or type 'WebClient'
1>Done building project "Scenario.Functional.Core.fsproj" -- FAILED.
1>
1>Build FAILED.
4>------ Build started: Project: Scenario.Functional.App, Configuration: Debug Any CPU ------
4>CSC : error CS0006: Metadata file 'E:\Jacek_Czok\Dokumenty\Visual Studio 2017\Projects\Caliburn.Micro-master\samples\scenarios\Scenario.Functional.Core\bin\Debug\Scenario.Functional.Core.dll' could not be found
3>  Scenario.KeyBinding -> E:\Jacek_Czok\Dokumenty\Visual Studio 2017\Projects\Caliburn.Micro-master\samples\scenarios\Scenario.KeyBinding\bin\Debug\Scenario.KeyBinding.exe
========== Build: 1 succeeded, 2 failed, 0 up-to-date, 1 skipped ==========

**Comment by mvermef** [comment]
the 1 assemblies are missing. it is a nuget package to be restored or added

**Comment by nigel-sampson** [comment]
As @mvermef mentions, looks like a nuget restore is required.
