### ISSUE TITLE
PublishOnUIThread(Async) doesn't wait until async handler is completed

### ISSUE THREAD

**Issue by Ralf1108** [Caliburn-Micro/Caliburn.Micro#540]
Using Caliburn.Micro 3.2.0 under NET 45.
 
It is currently not possible to wait for an async handler when publishing a message via event aggregator.
I adjusted an existing sample to demonstrate the problem: [TestSample](https://github.com/Ralf1108/Caliburn.Micro/commit/072aa3a02b9eec48e996d7af04c18798c582404b)

Clicking on one of the two buttons gives me the result:
1 - Before PublishOnUIThread
2 - Before Handle
4 - After PublishOnUIThread
3 - After Handle

What I want is:
1 - Before PublishOnUIThread
2 - Before Handle
3 - After Handle
4 - After PublishOnUIThread

Was this expected result not intended?
I thought that at least awaiting the "PublishOnUIThreadAsync()" method should accomplish this.
What is then the use case for the method "PublishOnUIThreadAsync" ?
What should I do when i want to do stuff after publishing the message?

Original use case was that in the async event handler a message was thrown. But because publishing the message doesn't await the async handler the exception was swallowed and only observed when a debugger is attached. Normally these async exception are catched by the global unhandled exception handler if awaiting would work correct.

**Comment by nigel-sampson** [comment]
Thanks, we'll be making event aggregator async friendly in the 4.0.0 release.

**Comment by Ralf1108** [comment]
Any chance there will be a fix for !Caliburn 3.2.0! via overloaded method until version 4 is production ready?
Maybe via PR ifi it possible?

**Comment by nigel-sampson** [comment]
Happy to see any PR's to fix that up on the 3.x branch.

**Comment by nigel-sampson** [comment]
This should be fixed up in the latest versions.
