### ISSUE TITLE
About Conductor and Multi Screen

### ISSUE THREAD

**Issue by hjj28810** [Caliburn-Micro/Caliburn.Micro#541]
hi，i have a MainViewModel inherit `Conductor<T>.Collection.OneActive where T : IScreen`, and another ChildViewModel inherit IScreen ,and MainView like this
```
<Grid>
     <ContentControl Content={Binding ActiveItem1} />
     <ContentControl Content={Binding ActiveItem2} />
</Grid>
```
How can I Binding both of 2 ChildViewModel

**Comment by nigel-sampson** [comment]
Sorry, not sure what you're trying to ask here.

**Comment by hjj28810** [comment]
in the MainView, i have 2 difference ContentControl ,and MainViewModel  inherit `Conductor<TChild>.Collection.OneActive where TChild : IScreen`  
MainView.xaml
```
<Grid>
       <Grid.ColumnDefinitions>
               <ColumnDefinition />
               <ColumnDefinition />
       </Grid.ColumnDefinitions>
     <ContentControl Grid.Column="0" Content={Binding ActiveItem} />
     <ContentControl Grid.Column="1" Content={Binding ActiveItem1} />
</Grid>
```
MainViewModel.cs
```
IEnumerable<TChild> _items;
public MainViewModel([ImportMany] IEnumerable<TChild> items)
{
       _items = items;
}
```
this items has 2 ChildViewModel 
the ChildViewModel inherit TChild, IScreen, binding ChildView
Q:i know how to show the ActiveItem, but ActiveItem1 can't

**Comment by nigel-sampson** [comment]
That's because `Conductor` doesn't expose a property called `ActiveItem1`, as the name suggests there is only one active item.

If you want to expose multiple view models you can always use indexers `{Binding Items[0]}` or create your own properties on the view model to bind to.

**Comment by hjj28810** [comment]
ye, i know `ActiveItem1` can't show ,cuz `Conductor` only active one item,
if i create a new property NewActiveItem to bind ,how the `Conductor` control them activate or deactivate?
i need items[0] and items[1] ,one of show on Grid top, one of show on Grid Bottom,one visible ,another hide

**Comment by nigel-sampson** [comment]
Sounds like you don't want `OneActive` but `AllActive`.

**Comment by hjj28810** [comment]
any example for `AllActive`? ,thx

**Comment by nigel-sampson** [comment]
It's much the same as `OneActive` except when you use `ActivateItem` on one child it won't deactivate the old. 

You'll still either need to use the indexer or expose your own view model to the view. But it means you're in complete control of the view model life cycle for your multiple child view models (as it should be for a scenario like this).
