### ISSUE TITLE
How to  deliver a param with  cal:Message.Attach

### ISSUE THREAD

**Issue by hjj28810** [Caliburn-Micro/Caliburn.Micro#542]
i know how to deliver all the view like this
`cal:Message.Attach="[Event Click] = [Action Send($view)]"`
but，i need only deliver the property of Result in $view 
`cal:Message.Attach="[Event Click] = [Action Send($view.Result )]"` can't work

**Comment by hjj28810** [comment]
ok ,i solved this problem,and the new come
in the view ,a property like this
`  public List<SimpleMessageModel> ResultList
 {
       get { return AnalyzeRichText(txtMessageBox); }
 }`
` cal:Message.Attach="[Event Click] = [Action Send(dialogueWin.ResultList)]"`

`public void Send(List<SimpleMessageModel> list)
{
        the list always count 0
}`

**Comment by nigel-sampson** [comment]
The parsing for properties isn't that complicated, you could do it by using `ConventionManager` to create a convention that defines `ResultList` as the property to pass in.

**Comment by hjj28810** [comment]
thx for answer，any example for `ConventionManager` ？

**Comment by nigel-sampson** [comment]
The [`static constructor`](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ConventionManager.cs#L199) of `ConventionManager` actually show a lot of usages of it as it sets up all the default conventions for Caliburn.Micro.
