### ISSUE TITLE
How to catch application exit event on viewmodel?

### ISSUE THREAD

**Issue by yuzifu** [Caliburn-Micro/Caliburn.Micro#544]
My WPF program using Caliburn.Micro 3.2, one of the functions is to get the image from the camera and display it on the UI, but when I close program, the code that publish event will throw an exception most of the time:
`Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in WindowsBase.dll
An unhandled exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in WindowsBase.dll
A task was canceled`

the publish event code as following:
``` csharp
        public bool StartFrontVideo()  {
            if (frontVideoRunning) {
                eventAggregator.PublishOnUIThread(new NotifyMsg("Front video already running"));
                return false;
            }
            bool _rtn = false;
            
            try  {
                frontVideoRunning = true;
                tFrontVideo = new Thread(() =>  {
                    VideoCapture cap = new VideoCapture(0);
                    while (frontVideoRunning)  {
                        Mat srcImg = new Mat();
                        cap.Read(srcImg);
                        eventAggregator.PublishOnUIThread(new VideoMsg(srcImg)); //throw exception
                    }
                });
                tFrontVideo.Start();
                _rtn = true;
                eventAggregator.PublishOnUIThread(new NotifyMsg("Front video is running"));
            }
            catch(Exception err) {
                frontVideoRunning = false;
                _rtn = false;
                eventAggregator.PublishOnUIThread(new NotifyMsg(err.Message));
            }

            return _rtn;
        }
```
I want to listen for program close event in viewmodel, I can stop publish event thread to fix this problem.

**Comment by nigel-sampson** [comment]
You should be listening to the `Application.Exit` event. How you do that in your view model is a little up to you. Simply adding a reference would work but breaks the view model encapsulation. You could potentially inject it via an interface.
