### ISSUE TITLE
Whether it is possible to establish explicitly guard method?

### ISSUE THREAD

**Issue by KazysNoobiys** [Caliburn-Micro/Caliburn.Micro#545]
Hi! All in title issue

**Comment by junliuxian** [comment]
Your question is empty, I suggest you go to [stackflow](https://stackoverflow.com/questions/tagged/caliburn.micro) to ask questions or initiate a discussion.

**Comment by nigel-sampson** [comment]
Can you elaborate on what mean by this? What are you looking to do?

**Comment by KazysNoobiys** [comment]
I want something like this 
`<Button x:Name="Add" cal:GuadrMethod="{Binding SomeGuardMethod}/>`
I want to be able to explicitly specify the method of protection and not rely on some naming conventions

**Comment by nigel-sampson** [comment]
There is no to defined the guard method like that. I'd suggest binding to `IsEnabled`.
