### ISSUE TITLE
A strange life cycle.

### ISSUE THREAD

**Issue by junliuxian** [Caliburn-Micro/Caliburn.Micro#546]
I want to set the default value when the screen is activated. My view model chooses inheritance screen，And override the `OnActivate` method。At this point, a strange phenomenon has occurred.

When you open the view model for the first time, setting default values for properties in the  `OnActivate` or `OnInitialize` methods is not valid.

My current solution is to override the `OnViewAttached` method to achieve my goal.

I have prepared the [Sample](https://github.com/junliuxian/Caliburn.Micro.Sample/commit/af9937cb5b05bd352983fb8f14530731e70a6d56), you can choose to clone [it](https://github.com/junliuxian/Caliburn.Micro.Sample). By clicking the `Open Dialog` button in `ShellView`, Will be able to reproduce the problem I described.

**Comment by nigel-sampson** [comment]
This is because your `Val` property doesn't send change notifications, the binding to the property has been set up already before the methods change it.

``` csharp
private int val;

public int Val
{
    get => val;
    set
    {
        val = value;
        NotifyOfPropertyChange();
    }
}
```
will resolve the problem.

**Comment by nigel-sampson** [comment]
Unfortunately each property must have change notifications in order for bindings to work correctly.  For `OnViewAttached` you're setting the value of the property before the binding is created which is why it's picked up. The other two are after the binding is created an so need the notifications.
