### ISSUE TITLE
How to use the click event TreeViewItem?

### ISSUE THREAD

**Issue by LeandroPrata** [Caliburn-Micro/Caliburn.Micro#547]
How to use the click event TreeViewItem?

I have tried: 

`<TreeViewItem Header = "User" cal: Message.Attach = "[Event MouseLeftButtonDown] = [Action OpenView]" Margin = "0,2,0,0" />`

but it does not work.

**Comment by fchiumeo** [comment]
```cs
cal:Message.Attach="[Event SelectedItemChanged] = [Action EstructuraSelectedItem($this.SelectedItem)]"
````
