### ISSUE TITLE
Does it make sense to add this to the framework?  Or is something similar already available?

### ISSUE THREAD

**Issue by Noemata** [Caliburn-Micro/Caliburn.Micro#548]
// Per ViewModel
    [Regist(InstanceMode.PerRequest)]
    public class ShellViewModel : Screen, IViewAware, IHandle<ResumeStateMessage>, IHandle<SuspendStateMessage>

// In App.xaml.cs

        protected override void Configure()
        {
            _container = new WinRTContainer();
            _container.RegisterWinRTServices();

            _container.Singleton<IDialogWindowManager, DialogWindowManager>();
            _container.Singleton<IUserNotificationService, UserNotificationService>();

            this.RegistInstances(this._container);

            _eventAggregator = _container.GetInstance<IEventAggregator>();
        }

        private void RegistInstances(SimpleContainer _container)
        {
            var types = this.GetType().GetTypeInfo().Assembly.DefinedTypes
                .Select(t => new { T = t, Mode = t.GetCustomAttribute<RegistAttribute>()?.Mode })
                .Where(o => o.Mode != null && o.Mode != InstanceMode.None);

            foreach (var t in types)
            {
                var type = t.T.AsType();
                if (t.Mode == InstanceMode.Singleton)
                {
                    _container.RegisterSingleton(type, null, type);
                }
                else if (t.Mode == InstanceMode.PerRequest)
                {
                    _container.RegisterPerRequest(type, null, type);
                }
            }
        }

// RegisterAttribute.cs

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Caliburn.Attributes
{
    public enum InstanceMode
    {
        /// <summary>
        /// Not registered
        /// </summary>
        None = 0,

        /// <summary>
        /// Single
        /// </summary>
        Singleton,

        /// <summary>
        /// Each instance
        /// </summary>
        PerRequest
    }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public class RegistAttribute : Attribute
    {
        public InstanceMode Mode { get; set; }

        public RegistAttribute(InstanceMode mode) {
            this.Mode = mode;
        }

    }
}

**Comment by godrose** [comment]
@Noemata You should provide this type of registration inside the inversion-of-control container.

**Comment by nigel-sampson** [comment]
This is something I'd normally leave to the domain of the container itself around discovery. Some such as `Autofac` already have it.

I'm not really looking to expand the built in container much, it's pretty simple and would like to keep it that way.

In my mind its useful for small projects or ones just getting started and then you'd move to a fully fledged container as needs demand.
