### ISSUE TITLE
Search View from the heirs of the ViewModel if it is not found in the ViewModel

### ISSUE THREAD

**Issue by HavenDV** [Caliburn-Micro/Caliburn.Micro#551]
In some cases, I have to create a lot of boiler code if there is a base ViewModel and classes are inherited from it.

**Comment by nigel-sampson** [comment]
Can you go into some more detail on the problem you're experiencing, I'm having some trouble following.

**Comment by Miles-Davies-HORIBA** [comment]
Hi, I think I have a similar issue to the OP.
I have multiple concrete ViewModels inheriting from an abstract base ViewModel class and want a single view for all of them without having to create boiler plate views. The same issue was answered a while back [in issue #524](https://github.com/Caliburn-Micro/Caliburn.Micro/issues/524#issuecomment-394658580) but I wonder if that answer is still current or if there is a mechanism for extending the view locator in this way without customizing it?

**Comment by HavenDV** [comment]
> Can you go into some more detail on the problem you're experiencing, I'm having some trouble following.

I meant that if a View for a specific ViewModel is not found, then you need to check whether a View exists for viewModelInstance.GetType().BaseType and use it

**Comment by nigel-sampson** [comment]
I'd still recommend the approaches in #524. This is why `ViewLocator.NameTransformer` is there.
