### ISSUE TITLE
Custom Control Binding with DataTemplate

### ISSUE THREAD

**Issue by bidasknakayama** [Caliburn-Micro/Caliburn.Micro#552]
Here is my small test project to know issue in [My GitHub](https://github.com/bidasknakayama/MultiDataGrid).

It make 20 user name list and Split into 4 x DataGrid table.
0-4 ,  5-9 ,  10-14,  15-19.
When I click Header to sort, I want to catch the event in My Custom Control.

But I could not fire "MySorting()" in DataTemplate in ControlTemplate.
Could you help your knowledge to resolve this ?

I may should give us to use ItemContorl/DataTemplate. 
it's very problem : )

`<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:localControls="clr-namespace:DoubleButton.Controls"                   
xmlns:i="clr-namespace:System.Windows.Interactivity;assembly=System.Windows.Interactivity"
xmlns:cal="http://www.caliburnproject.org">

    <Style TargetType="localControls:MultiDataGrid">

        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="localControls:MultiDataGrid">

                    <ItemsControl x:Name="Dg_ItemsControl" >
                        <ItemsControl.ItemsPanel>
                            <ItemsPanelTemplate>
                                <StackPanel Orientation="Horizontal" Margin="10"/>
                            </ItemsPanelTemplate>
                        </ItemsControl.ItemsPanel>
                        <ItemsControl.ItemTemplate>
                            <DataTemplate>
                                <DataGrid 
                                    AutoGenerateColumns="False"
                                    ItemsSource="{Binding ItemsSource, Mode=TwoWay}" 
                                    cal:Message.Attach="[Event Sorting] = [Action MySorting()]"
                                    Margin="0 0 10 0"
                                    cal:Action.TargetWithoutContext="{Binding DataContext, ElementName=Dg_ItemsControl}"
                                    >
                                    

                                    <DataGrid.Columns>
                                        <DataGridTextColumn Binding="{Binding Id}" Header="ID" />
                                        <DataGridTextColumn Binding="{Binding Name}" Header="Name"/>
                                    </DataGrid.Columns>
                                </DataGrid>
                            </DataTemplate>
                        </ItemsControl.ItemTemplate>
                    </ItemsControl>

                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
</ResourceDictionary>`

**Comment by nigel-sampson** [comment]
Can you provide the sample as a repository on GitHub I can clone and have a closer look.

**Comment by bidasknakayama** [comment]
Here is the Sample repository. ( [Link](https://github.com/bidasknakayama/MultiDataGrid) ) 
but.. sorry. I found, It is not issue of Caliburn.Micro.

in the sample repository,  I want to access DataGrid control in My custom control.
but The DataGrid is inside of "ItemsControl.ItemTemplate".
then, Direct access is not possible. If you have any idea, It is very helpful...

**Comment by nigel-sampson** [comment]
Good to hear, If you're in WPF you may be able to use relative bindings, not sure sorry.
