### ISSUE TITLE
Conventions for custom control

### ISSUE THREAD

**Issue by ekgurney14** [Caliburn-Micro/Caliburn.Micro#555]
I have a custom control (WPF) that basically looks like this.
`<UserControl>
    <Button Name="Add"/>
    <Button Name="Edit"/>  
    <Button Name="Delete">  
</UserControl>`

Used in  a view e.g.
`<MyButtonControl Name="Something"`/>

Is there a way to add custom conventions so I can use

CanAddSomething/AddSomething(), etc.?

I know I can hook into the caliburn binding process and use reflection and bind myself, but I was just wondering if I can do this out of the box?

Thanks,
Eric

**Comment by nigel-sampson** [comment]
There's nothing in the box that can support this style of custom convention. Times I've done something like this tend to be on a larger scale where a full on view model represents the custom control where this view model has it's own `Add`, `Edit` methods etc.

If your custom control can see it's name `Something` on load it could use `Message.SetAttach` to a value like `$"Add{name}"`. Not sure if that would work, would love to hear how you go.
