### ISSUE TITLE
Compatibility inquiry - AvaloniaUI?

### ISSUE THREAD

**Issue by MostHated** [Caliburn-Micro/Caliburn.Micro#556]
Hey there,
    I apologize if this is a silly question, but I am fairly new to all of this. I was wondering if this framework is compatible with the AvaloniaUI cross-platform UI Framework by chance? https://github.com/AvaloniaUI/Avalonia

Thanks,
-MH

**Comment by mvermef** [comment]
I think you will find that there will be a tremendous amount of overlap between both frameworks.  It's gonna come down to which ever suits your needs the best.

**Comment by MostHated** [comment]
Oh, I see. I was under the impression that this framework was to allow easier implementation of MVVM pattern (such as essentially making necessary commands shorter and things of that nature) and AvaloniaUI was just to allow you to create a UI that was cross-platform compatible (Linux, Mac, etc). Was I mistaken on that?

**Comment by nigel-sampson** [comment]
It looks interesting, I'm not sure what the effort would be required to fully implement Caliburn.Micro in Avalonia.

In terms of doing the bare minimum in order get your view models written in Caliburn.Micro to be used in Avalonia is pretty small, if you'd like to spike a prototype I can definitely help you there.

**Comment by MostHated** [comment]
Great news! I will be sure to keep an eye out for that.

Thanks,
-MH

**Comment by MostHated** [comment]
I have not used either yet, I have been mostly researching and watching tutorial videos and just following along on learning all of this stuff (including C#). Maybe one day I might have the skills to manage something like that, lol.

**Comment by libin85** [comment]
@MostHated : I guess currently its just RxUI that supports AvaloniaUI

**Comment by davidhenley** [comment]
@libin85 and Prism

**Comment by megazyz** [comment]
Hello,

I have added initial support for Avalonia. It seems to work fine with some minor shortcomings.
https://github.com/megazyz/Caliburn.Micro.Avalonia/tree/avalonia

How to start:
https://github.com/megazyz/Caliburn.Micro.AvaloniaSample

What do you think about it?

ReactiveUI support is also being preapred, I will commit later.

**Comment by Stannieman** [comment]
@vb2ae I see that there are breaking changes in the upcoming Avalonia version (11) which is in preview now (mainly IAvaloniaObject is removed or replace, I did not check futher). Is that the version we should target? Then I will see if I can make some adjustments to support it.

**Comment by vb2ae** [comment]
Thanks for letting me know.  I see they removed a lot of the interfaces for concrete classes.  for example IAvaloniaObject is not AvaloniaObject.  but it would be great if you could see what else needs to be changed.  Do you have any idea on when Avalonia 11 is going to be released

**Comment by Stannieman** [comment]
No idea for release date, wil check. But I expect it somewhere this year. Will also check changes further. From the changelog it appears to be just the removed interfaces that is relevant for us.

You can expect a PR to your branch this week.

**Comment by maxkatz6** [comment]
It makes sense to start with 11.0 previews and release first public package with 11.0-RC when it's ready. Hopefully, in next months.

**Comment by sdwdjzhy** [comment]
excuse me,  AvaloniaUI has publish v11.0 . Do you have any compatibility plans?

**Comment by Stannieman** [comment]
> excuse me, AvaloniaUI has publish v11.0 . Do you have any compatibility plans?

The 556 PR linked above is compatible with Avalonia 11.
