### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mortensp** [Caliburn-Micro/Caliburn.Micro#557]
I find it fustrating that Caliburn doesn't support datagrid column binding. About 95% of my views contains datagrids, so I has to do old fashion WPF binding....

So I have made some small changes to my local copy of Caliburn as to find those elements and has as a side effect gained better performance. But  I cann't figure out how to do the actual binding in the Caliburn code.

So It would by nice if Caliburn had this feature

**Comment by nigel-sampson** [comment]
Because `DataGrid` inherits from `ItemsControl` there is a convention in the framework for this control.

Can you expand on what you think should be happening?

**Comment by nigel-sampson** [comment]
Rather than changing some of the core classes like `BindingScope` whether it can be done via the convention itself with `ApplyBinding`.

This could examine the data grid in question and apply a convention to each child column.

**Comment by mortensp** [comment]
I have it working now! But can not avoid changes to the BindingScope class, as it **does not** find all named elements. The method "FindNamedDescendants" only returns named FrameWorkElements and not Elements that only derive from DependencyObject as DataGridBoundColumns does.

So my "fix" contains this:

1. Make FindNamedDescendants return all named elements from the NameScope. I call these NamedDependencyObjects and they contain the name and a reference to the DependencyObject
2. Change relevant binding methods to take NamedDependencyObjects rather than FrameWorkElements.
3. Create  ApplyBindings for DataGridBoundColomns
4. Alter BindActions and BindProperties to first look name matches in the ItemSource and only in then viewmodel

And can I give a tip? The x:Name binding method doesn't allow duplicate names - so one can not bind two visual objects to the same viewmodel property. A workaround is to prefix the second x:Name with a '_' and the third with two underscores etc.

**Comment by nigel-sampson** [comment]
I'm not sure if duplicate `x:Name` makes sense given the original intention of it terms of C# generation.

Given the scope of changes required for what looks like a small feature it makes me concerned.
