### ISSUE TITLE
Where can I find more detailed walk through videos or instructions?

### ISSUE THREAD

**Issue by MostHated** [Caliburn-Micro/Caliburn.Micro#560]
Hey there,
  I came across some features that I was unaware existed until I saw a post on StackExchange mentioning that Caliburn automatically will do some magic on things that are named as "IsVisible" (and other things I believe like IsEnabled possibly?) but I can't really seem to find much else on how exactly it works or how to use it. The only really good instructional video I found was this one by Tim Corey https://www.youtube.com/watch?v=laPFq3Fhs8k but it doesn't really go into some of the more advanced features of the framework. 

I would really like to try and find some videos/examples of some of those other features but have yet to really find any on GitHub/Youtube. Are there any that someone might be able to point me to?

Thanks,
-MH

**Comment by nigel-sampson** [comment]
There's a few videos from NDC Sydney where I've given talks about cross platform mobile development on Youtube, but these aren't a deep dive into Caliburn.Micro at that level.

I'd don;t know of any other videos like that.

**Comment by bmulholland** [comment]
I'm having this problem too; it can be really hard to figure out how to use this framework. Is the IsVisible convention documented somewhere?
