### ISSUE TITLE
Question about a single ViewModel displaying multiple Screens

### ISSUE THREAD

**Issue by coczero** [Caliburn-Micro/Caliburn.Micro#562]
I have a question on how to design this.
I currently have a ViewModel called `ProjectViewModel` which is a `Screen`.
In the View of this ViewModel I want to display two sub-Screens. It is not known at design time which Screen should be displayed.
I did this like this: In my `ProjectViewModel` I have two `IScreen` properties. MainScreen and SideScreen.
Displaying them like that works, but it seems to mess with the lifetime of the Screens, so I figured it is probably not the right way to do things. Can you point me in the right direction how to display multiple screens from a single ViewModel? I can't use a Conductor, because I have to conduct two seperate items, no collection or something like that.

**Comment by nigel-sampson** [comment]
What you can do is use a `Conductor` and use `ActivateItem` to activate the child view models. You'll need to manually `Deactivate` them as well.

Or if you're not doing anything complicated you can stick with `Screen` and use `mainScreen.ConductWith(this)` in your constructor of the `ProjectViewModel`. This will activate and deactivate the `mainScreen` view model when the parent does.
