### ISSUE TITLE
How to call a method in a GridControl from another view?

### ISSUE THREAD

**Issue by dmitriy-shleht** [Caliburn-Micro/Caliburn.Micro#565]
I have two views that have a common view model.
On the first view there is a GridControl that has methods for moving the focused row.

This button on the first view (master) moves the row forward.
```
<Button
    Command="{x:Static dxg:GridCommands.MoveNextRow}"
    CommandTarget="{Binding ElementName=GridSprClient, Path=View}"
    Content="Next" />
```

```
        //Open details view
        public ICommand EditCommand
        {
            get
            {
                return _editCommand ?? (_editCommand = new RelayCommand<object>(
                    _ =>
                    {                       
                        _windowManager.ShowDialog(this, "EditSprClientView", null);
                    }));
            }
        }
```

Double-clicking on the selected entry opens the second view (details). There is also a Next button on it which should call the method on the GridControl.
How to call this (`{x:Static dxg:GridCommands.MoveNextRow}`) method from details view?

![1](https://user-images.githubusercontent.com/13961834/49653046-7bfd9c00-fa3c-11e8-8136-2d9137d771a7.JPG)

**Comment by nigel-sampson** [comment]
This doesn't seem related to Caliburn.Micro.

**Comment by dmitriy-shleht** [comment]
Sorry.
I thought `Caliburn.Micro` maintains the binding between `Views` for the same `ViewModel`. You may not have understood my question.

Is it possible to get an access to the `DataContext` of an element that is in a another `view` using `Caliburn.Micro`?

example:
```        
        <Button
            Width="206"
            Margin="0,346,594,75"
            cal:Action.Target="{Binding ElementName=b}"
            cal:Message.Attach="Clear"
            Content="Clear text" />

        <TextBox
            Name="b"
            Width="206"
            Margin="222,346,372,75"
            Text="test test" />
```
By pressing the button we clear the text. But what if these elements are in different views? (button is on the second view, and textBox is on the first view)

Thank you!

**Comment by rossvegas** [comment]
In this case I would have no issue using the event aggregator to tell the master to change to the next record. I would then update the model used in the details via some type of set method that is exposed on the detail. You should have access to the detail view model from the master since it probably created it.
