### ISSUE TITLE
Injecting a View without ViewModel

### ISSUE THREAD

**Issue by Aleksbgbg** [Caliburn-Micro/Caliburn.Micro#569]
Was wondering if there is a way to inject a view into another view without binding to a ViewModel?

I have a general-purpose ViewModel, and would like to inject a different view every time I use it.

Could I bind to a view name property or something of the like?

Example:
```cs
internal class ViewModel : Screen
{
    public IView View { get; } = new View("Animals");
}
```
```xaml
<!-- View.xaml -->
<UserControl>
    <ContentControl Caliburn:View="{Binding View}"/>
</UserControl>
```
```xaml
<!-- Animals.xaml -->
<ListBox>
    <ListBoxItem Header="Rabbit"/>
</ListBox>
```

**Comment by nigel-sampson** [comment]
I'd suggest not over complicating this and just use the user control directly.
