### ISSUE TITLE
Support .net 4.5

### ISSUE THREAD

**Issue by hoangcuongvn** [Caliburn-Micro/Caliburn.Micro#570]
I see CM 4.0 now only supports .net 4.6 or higher. The problem is that .net 4.6 can only be installed on win7sp1, it cannot be installed on win7 (without sp1). Is it possible if CM keeps supporting .net 4.5? So we are able to deploy apps on win7 with or without sp1? CM source code is completely compatible with .net 4.5. We just need to find and replace "net46" by "net45" in the *.csproj files.

**Comment by nigel-sampson** [comment]
I think this could be possible, I moved to .NET Standard 1.3 which required 4.6 due to the Source link tools. Given these are build tools we may be able to move back to NET Standard 1.0 and 4.5.
