### ISSUE TITLE
Coerce textbox input

### ISSUE THREAD

**Issue by MkazemAkhgary** [Caliburn-Micro/Caliburn.Micro#571]
Is there anyway I can force user to specific inputs? I tried the following but textbox value is not forced. (it remains as it is)
```c#
private string _depth = "1";
public string Depth
{
    get { return _depth; }
    set
    {
        // I may also notify user with some message but this doesn't work in the first place
        if(int.TryParse(value, out int parse)) 
        {
            // value must be within [1, 10]
            _depth = Math.Max(Math.Min(parse, 10), 1).ToString();
        }
        else
        {
            _depth = "1"; // value must be a number
        }

        NotifyOfPropertyChange(() => Depth);
    }
}
```

I have checked and this property is called when ever text changes. but the value is not forced.

**Comment by nigel-sampson** [comment]
The property change notification is ignored by the control because it happened as part of the binding setting the value.

I'd suggest having the input coercion happening at the control level.

**Comment by MkazemAkhgary** [comment]
@nigel-sampson Thanks a lot for the reply. what do you mean by doing it at control level? do you mean basically doing it when user wants to proceed with those wrong values? It seems like a good solution, I will close this issue when I make sure I understand you correctly :)

**Comment by MkazemAkhgary** [comment]
Ok, I decided to change the way inputs are handled, while this issue remains but I close it for now. open it again if there are reasons to fix this issue. thanks a lot.
