### ISSUE TITLE
wpf,autofac,castle AOP can't work

### ISSUE THREAD

**Issue by hjj28810** [Caliburn-Micro/Caliburn.Micro#572]
i used the autofac IOC and castle AOP but can't work,the error is 
Cannot find view for  Castle.Proxies.INotifyPropertyChangedExProxy.

**Comment by nigel-sampson** [comment]
So the way dynamic proxy works is by creating new types as you can see with `Castle.Proxies.INotifyPropertyChangedExProxy` that "wraps" your view model". 

To get to this to work you're going to have to change the way the view is located. You can do this by changing how `ViewLocator.LocateTypeForModelType` works.  I'd suggest examining whether you can do this by just calling the default implementation using the base type.

**Comment by hjj28810** [comment]
and how to changed `Castle.Proxies.INotifyPropertyChangedExProxy` that "wraps" view model for `ActivateItem（viewModel）`

**Comment by nigel-sampson** [comment]
Sounds like you're looking into the right things. Not sure I can add much here.
