### ISSUE TITLE
Move AssembySource to the cross-platform code

### ISSUE THREAD

**Issue by godrose** [Caliburn-Micro/Caliburn.Micro#573]
Is there any particular reason to have `AssemblySource` and its related functionality in the platform-specific projects? 
It would answer some of my scenarios to have this functionality in the cross-platform code and package

**Comment by nigel-sampson** [comment]
Mostly because it felt like part of the platform specific code even when it in itself is not platform specific (doesn't contribute to the main reasons the `.Core` package is cross platform).
