### ISSUE TITLE
Simplify 4.0 HandleAsync

### ISSUE THREAD

**Issue by xmedeko** [Caliburn-Micro/Caliburn.Micro#583]
Hi, just following #496 - I agree it was a good move in terms of simplicity of the `EventAggregator` code. But we have the most of the message handler sync, so when trying the 4.0 we have to move from simple
```c#
public void Handle(MyMsg msg)
{
    // msg processing
}
```

To 
```c#
public Task HandleAsync(MyMsg msg, CancellationToken cancellationToken)
{
    // msg processing
    return Task.CompletedTask;
}
```

I have to admit, I miss the old `IHandle` and `IHandleWithTask`. Or, what at least support to `return null`, too (just a simple null check in the `Handler.Handle`). 

Note: `EventAggregator.PublishAsync` does not pass `cancellationToken` to `Handle` - is that right?

**Comment by nigel-sampson** [comment]
Currently it doesn't pass the cancellation token down, it's a matter of debate whether a single cancellation should be able to cancel the publish operation.

The change is definitely painful, but I think having a singular async API will be better to maintain long term.

**Comment by xmedeko** [comment]
Ad to `EventAggregator.PublishAsync`: the `cancellationToken` is used nowhere, no check `IsCancellationRequested()` nor `ThrowIfCancellationRequested()`, so the parameter is useless.

**Comment by nigel-sampson** [comment]
Noted, my first part of the API was getting it in, I expect later reviews of how the framework should respect cancellation tokens.
