### ISSUE TITLE
Strong name warning for .net build 

### ISSUE THREAD

**Issue by hoangcuongvn** [Caliburn-Micro/Caliburn.Micro#584]
When building CM I see a strong name warning. I found the bug is in Caliburn.Micro.Core.csproj, change 'net46' to 'net45' resolves the problem.
https://github.com/Caliburn-Micro/Caliburn.Micro/blob/3884e321070fd3e8b7ad3559782d878e31fa5cca/src/Caliburn.Micro.Core/Caliburn.Micro.Core.csproj#L10

**Comment by nigel-sampson** [comment]
Thanks, this should be resolved.
