### ISSUE TITLE
is this solution appropriate for windows 10 uwp app work?

### ISSUE THREAD

**Issue by myusrn** [Caliburn-Micro/Caliburn.Micro#586]
I ask because the https://caliburnmicro.com/ page says "Works everywhere Xaml does |
Supports WPF, Silverlight, Windows Phone, Windows 8 including Universal apps.", i.e. doesn't call out current windows 10 uwp application target which I might have expected to be at front, or end, of that list if supported.

**Comment by mvermef** [comment]
yes it does target UWP.

**Comment by myusrn** [comment]
Thanks for clarification, that is good to hear.  

Just a suggestion, i would have found a https://caliburnmicro.com/ page stating something like "Works everywhere Xaml does" | "Supports Windows 10 UWP , Windows 8.x WinRT, WPF and Silverlight apps." to better imply this framework's relevance in the current windows store app development framework landscape than the current text "Supports WPF, Silverlight, Windows Phone, Windows 8 including Universal apps." .

**Comment by nigel-sampson** [comment]
Thanks, yes the homepage and docs need a review once I finally get 4.0.0 out.
