### ISSUE TITLE
View not found for specified ViewModel

### ISSUE THREAD

**Issue by Nanquitas** [Caliburn-Micro/Caliburn.Micro#588]
Hi :)

I'm trying to use a Frame to display different views just like in the documentation sample.
But for some reasons, I keep getting an error about my `MainView` not being found.
![errormessage](https://user-images.githubusercontent.com/13298129/53993780-9e34b200-4130-11e9-9743-1a02f98f7476.png)

I've been trying things for hours, read a lot on forums / documentation etc but I can't find the reason.
Namespace seems correct and code is almost empty so little possibility of error as it's a copy/paste from sample provided by the documentation.

I'm new to mvvm + modelview-first (*and a beginner to c# in general*) so it might be a stupid thing that I can't think about...
I'm counting on this little project to learn more about it and familiarize myself with it.

To be more precise:
 - The error happens in `ShellViewModel::RegisterFrame::NavigateToViewModel`
 - The `ShellViewModel` && `ShellView` code works fine so it's specific to `MainViewModel` && `MainView`
 - Project `Framework target: 4.7.2` and `Caliburn.Micro - v4.0.47-alpha`
 - The `Feature` project which also uses a Frame + view navigation works fine, so it's definitely something I'm not doing correctly
 - The error message indicates that the framework seems to look for a path full lowercase: normal behavior ?

Here all the relevant code of the project in-case you can spot the issue. :)
![relevantinfos](https://user-images.githubusercontent.com/13298129/53993791-a5f45680-4130-11e9-9a16-50bbf0aa2857.png)

I'll take any advice and hint you can give me to fix this.
Huge thanks for your time.

**Comment by Nanquitas** [comment]
So, I finally found the problem.

It's because my project possess a `-` in the name `GIMX-ForRemotePlay`.
And this `-` cause the problem as it appears in the `Assembly` name but not in the namespace (converted to `_`) which prevent the `ViewLocator.DeterminePackUriFromType` to remove it from the final path.

Overriding original `ViewLocator.DeterminePackUriFromType` like below works:
```cs
            ViewLocator.DeterminePackUriFromType = ((viewModelType, viewType) =>
            {
                string assemblyName1 = viewType.Assembly.GetAssemblyName();
                string assemblyName2 = Application.Current.GetType().Assembly.GetAssemblyName();
                string str1 = viewType.FullName;

                if (str1.StartsWith(assemblyName1.Replace("-", "_"))) //< Replace - by _ in assemblyName
                    str1 = str1.Substring(assemblyName1.Length);
                string str2 = str1.Replace(".", "/") + ".xaml";
                string str3 = assemblyName1;
                if (!assemblyName2.Equals(str3))
                    return "/" + assemblyName1 + ";component" + str2;
                return str2;
            });
```

As I said, tiny thing for all the hours I lost on this... ^^'

Should this step be added in the original function to support projects with ``-`` in their name ?

**Comment by nigel-sampson** [comment]
Good find, happy to see a PR for this.
