### ISSUE TITLE
BindableCollection: Unable to Show as Collection Association in VS Class Designer 

### ISSUE THREAD

**Issue by kirkktx** [Caliburn-Micro/Caliburn.Micro#589]
In VS2017 class designer, when Jobs is a BindableCollection, and I choose "Show as Collection Association".
![image](https://user-images.githubusercontent.com/10727968/54366974-9cdb1c00-463f-11e9-9a91-321ca265f0ec.png)

I get this...
![image](https://user-images.githubusercontent.com/10727968/54366794-440b8380-463f-11e9-859d-6c0f7329de6b.png)

If I change Bindablecollection to ObservableCollection, it works as expected:
![image](https://user-images.githubusercontent.com/10727968/54367137-e0ce2100-463f-11e9-87bb-0abf30499d59.png)

**Comment by nigel-sampson** [comment]
Thanks for the report, not sure what the difference between the two types that signifies that's a collection (they implement most of the same interfaces). Potentially some attribute.

Will look into this when I can.

**Comment by nigel-sampson** [comment]
I'm unable to recreate this problem with the following code (with the VS 2017 class designer)
``` csharp
public class CustomerViewModel : Screen
{
    public string Name { get; set; }

    public BindableCollection<OrderViewModel> Orders { get; set; }
}

public class OrderViewModel : Screen
{
    public decimal Total { get; set; }
}
```

**Comment by kirkktx** [comment]
I'm still seeing this in VS 16.2.5. (2019)
I wonder if it's related to this bug:
https://github.com/dotnet/roslyn/issues/37796

**Comment by lenj962** [comment]
I see this issue intermittently in VS2019 v. 16.3.10.  I don't know what is causing it not to work and under what circumstances.  Previous comments indicate the project should reference System.Collections.Generic.  All case where the problem appears reference this namespace.  The projects build and run as expected, but attempts to create a class diagram showing collection links fail when the problem appears.  Restarting VS sometimes works and sometime doesn't.

**Comment by kenichi-kobayashi** [comment]
The same phenomenon occurs in Visual Studio 2019 16.11.1.
Restarting Visual Studio does not resolve the issue.
