### ISSUE TITLE
Screen.OnInitializeAsync prevents the view from getting displayed immediately

### ISSUE THREAD

**Issue by mgnsm** [Caliburn-Micro/Caliburn.Micro#591]
The `OnInitializeAsync `method of the `Screen `class "blocks" the view from getting display until the view model has been initialized. This is not the expected behaviour as it basically defeats the purpose of initializing the view model asynchronously in the first place. The issue is easy to reproduce in a WPF project that references the 4.0.47-alpha version.
 
**ShellView:**
 
    <TabControl x:Name="Items" Margin="10">
        <TabControl.ItemTemplate>
            <DataTemplate>
                <TextBlock Text="{Binding DisplayName}" />
            </DataTemplate>
        </TabControl.ItemTemplate>
    </TabControl>
 
**ShellViewModel:**
 
    public class ShellViewModel : Conductor<IScreen>.Collection.AllActive
    {
        public ShellViewModel()
        {
            Items.Add(new ChildViewModel() { DisplayName = "Child..." });
        }
    }
 
**ChildViewModel:**
 
    public class YmerViewModel : Screen
    {
        protected override async Task OnInitializeAsync(CancellationToken cancellationToken)
        {
           //simulate some initialization work...
           await Task.Run(() => Thread.Sleep(5000));
        }
    }
 
**Bootstrapper:**
 
    public class Bootstrapper : BootstrapperBase
    {
        public Bootstrapper() => Initialize();

        protected override void OnStartup(object sender, StartupEventArgs e) =>
            DisplayRootViewFor<ShellViewModel>(s_windowSettings);
    }
 
Using the above sample code, it takes five seconds for the main window to show up. This can be fixed by modifying the `ChangeActiveItemAsync` method of the `ConductorBaseWithActiveItem<T>` class slightly. I'll submit a pull request.

**Comment by nigel-sampson** [comment]
Thanks for the PR.
