### ISSUE TITLE
TreeView Does not bind

### ISSUE THREAD

**Issue by alexander-noshe** [Caliburn-Micro/Caliburn.Micro#595]
Hi,

I'm struggling to bind View to TreeView control.
Here is the snippet:
``` xml
    <Grid>
        <TreeView x:Name="Filters">
            <TreeView.ItemTemplate>
                <HierarchicalDataTemplate ItemsSource={"Binding Children"}/>
            </TreeView.ItemTemplate>
            
          </TreeView>
    </Grid>
```
The CM for some reason cannot bind Filters (which is BindableCollection of ViewModels) to the Views. I see blank TreeView with blank children.

If I replace TreeView with ListView, I see the Views of Filters perfectly.

I would appreciate if you helped me to solve this problem as soon as possible, since I'm stuck with it several months. I even made workaround with converter, which converts ViewModel to View, but it's not very elegant (read - ugly)...

Thank you!

**Comment by nigel-sampson** [comment]
This should be what you're after.

``` xml
<TreeView x:Name="Filters">
    <TreeView.ItemTemplate>
        <HierarchicalDataTemplate ItemsSource="{Binding Children}">
            <ContentControl cm:View.Model="{Binding}" />
        </HierarchicalDataTemplate>
    </TreeView.ItemTemplate>
</TreeView>
```
