### ISSUE TITLE
Multiple conventions per element?

### ISSUE THREAD

**Issue by chrispellett** [Caliburn-Micro/Caliburn.Micro#598]
Hi!
_(I do apologize if this has been asked already; I tried going through all of the closed issues, but there were quite a few)_
I've been trying to get in deep on your library and am struggling on how to do the following (or whether it is even possible).

I'd like to be able to define multiple bindings (I believe the correct term in Caliburn is "conventions") to each element, beyond just the default.

For example, say I have:
`<TextBlock x:Name="Foo" />`
I'd like to be able to have the following:
- Text property bound to ViewModel.Foo property (assuming it exists)
- Visibility property bound to ViewModel.FooIsVisible property (if it exists and with a conversion done)
- Foreground property bound to ViewModel.FooForeground property

In a perfect world, I'd be able to specify what the name "mappings" would be, the possible value converters, etc.

From looking through the code, it appears that the ConventionManager class is the right home and that ElementConvention instances are the actual work-horses. But, if that is correct, it looks like there can only be a single ELementConvention per element, and an ElementConvention can only handle a single "behaviour"?

I know I can define additional bindings to handle all of those (which is the most flexible), but I really like the convention approach you have in place and how much time it has already saved me.

Appreciate any help/guidance you can provide. And thanks again for your work on this library

**Comment by nigel-sampson** [comment]
There can only be a single element convention per element type, but these conventions can do a lot more work.

If we look at the [convention for `Selector`](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/ConventionManager.cs#L277) then it defines three things initially.

1. `ItemsSource` as the bindable property, which is the one to bind to matching on name.
2. `SelectedItem` as the paramter property, which is the one to be used as passing to methods.
3. `SelectionChanged` which is the event to trigger actions if attached to the element.

For you the interesting part is that `ElementConvention` as an `ApplyBinding` hook where you can do work when the convention is applied.

For `Selector` this looks for `SelectedX` property to bind `SelectedItem` to. What this means is that if you had an element with the `x:Name` of `Products` then it would bind the `Products` property to `ItemsSource` and `SelectedProduct` to `SelectedItem`.

This pattern is very much the same as what you're after.
