### ISSUE TITLE
XamlPlatformProvider.OnUIThreadAsync bug with Func<Task>

### ISSUE THREAD

**Issue by ArsenijK** [Caliburn-Micro/Caliburn.Micro#599]
I see you already smartly decided, that if a user wants to call OnUIThreadAsync, then, obviously, he wants to get the Task which he returned from his Func<Task>. So we want the Task, which OnUIThreadAsync returns to complete, only when user's returned Task completes. But this is not the case. If you test it (give your OnUIThreadAsync(() => Task.Delay(10000) and await it), you'll see that it doesn't work. It's because dispatcher.InvokeAsync(action).Task returns Task<Task> and you return only the outer one, but do not wait on the inner one.
Working fix would be to make your OnUIThreadAsync actually async and await both tasks:
await await dispatcher.InvokeAsync(action).Task

**Comment by nigel-sampson** [comment]
Thanks for the catch, intellisense caught me out there.
