### ISSUE TITLE
[Phone] OnViewReady doesn't work after an app was resumed

### ISSUE THREAD

**Issue by belyansky** [Caliburn-Micro/Caliburn.Micro#6]
Hi!

There is some sort of problem with OnViewReady method in WP apps. It is correctly works after first navigation and after back navigation to a page. But if an app was deactivated by pressing Home button and after that it was resumed then nothing happen. OnViewReady doesn't called in this sutiation. Only after some interactions with the page (for example pressing of a button) method will be called (because LayoutUpdated event occurs only after that).

As far as I know all "heavy" actions must be performed in the OnViewReady. For example updating of a big list of data. Data in the app could became outdated between dormant and resumed states. And current framework behavior ruins update logic in this particular scenario. I think this is an issue.

**Comment by nigel-sampson** [comment]
Going to removing support for Windows Phone Silverlight in `4.0.0` so will close out this issue, if it suddenly becomes a big problem it could be addressed in a `3.x` release.
