### ISSUE TITLE
Bind eventsetter handler to action

### ISSUE THREAD

**Issue by yuzifu** [Caliburn-Micro/Caliburn.Micro#603]
I want listen mouse left key up event of listview, one way is add follow code:
```
<ListView>
    <ListView.ItemContainerStyle>
        <Style TargetType="ListViewItem">
            <EventSetter Event="PreviewMouseLeftButtonDown" Handler="ListViewItem_PreviewMouseLeftButtonDown" />
        </Style>
    </ListView.ItemContainerStyle>
</ListView>
```
After using caliburn.micro, how do I bind ListViewItem_PreviewMouseLeftButtonDown to the VM function?

**Comment by nigel-sampson** [comment]
You can see in the [samples](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/samples/features/Features.UWP/Views/ActionsView.xaml#L33) an example of attaching a method to an event.
