### ISSUE TITLE
Wait for ActivateItem close?

### ISSUE THREAD

**Issue by michasacuer** [Caliburn-Micro/Caliburn.Micro#607]
I have a question. I have button where i launch `ActivateItem`:

        
        public void LoadTaskManagerPage()
        {
            this.ActivateItem(new TaskManagerViewModel(this.LoggedUser, this.repository));

            if (this.LoggedUser.GetUserTask() != null)
            {
                this.IsActiveTaskButtonVisible = Visibility.Visible;
                this.NotifyOfPropertyChange(() => this.IsActiveTaskButtonVisible);
            }
        }
       

Is it possible to `hang` an app and go to `if` statement only, if `ActivateItem` ends?

How to wait for end of `ActivateItem` in Caliburn.Micro?

I tried something like:

        
        public void LoadTaskManagerPage()
        {
            var taskManagerTask = Task.Run(() => this.ActivateItem(new TaskManagerViewModel(this.LoggedUser, this.repository)));
            taskManagerTask.Wait();

            if (!this.LoggedUser.GetUserTask().IsTaskTakenByUser())
            {
                this.IsActiveTaskButtonVisible = Visibility.Visible;
                this.NotifyOfPropertyChange(() => this.IsActiveTaskButtonVisible);
            }
        }

With Tasks, but when i click on `LoadTaskManagerPage()` it wont show any window, application hangs forever

**Comment by nigel-sampson** [comment]
You will "soon" with the 4.0.0 builds which make `ActivateItem` into `ActivateItemAsync` that you can `await`.

It's still in development, but the in progress packages are available from MyGet (link in the readme.md).

**Comment by michasacuer** [comment]
Thansk for your advice. But after changing my code to:

    ```
public void LoadTaskManagerPage()
    {
        this.ActivateItemAsync(new TaskManagerViewModel(this.LoggedUser, this.repository));

        if (this.LoggedUser.GetUserTask() != null)
        {
            this.IsActiveTaskButtonVisible = Visibility.Visible;
            this.NotifyOfPropertyChange(() => this.IsActiveTaskButtonVisible);
        }
    }
```

Its still hitting `if` before `ActivateItem` close (im using `TryCloseAsync()` for closing `Screen`. Have you any advice, how to achive what i want to? (activate `if` statement only, if `activeItem` close. Thanks for suggestions

**Comment by nigel-sampson** [comment]
`ActivateItemAsync` is asynchronous which means it needs to be awaited. I'd suggest reading up on [The Task asynchronous programming model in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/).
