### ISSUE TITLE
Caliburn 4 does not yet support .NET Core 3

### ISSUE THREAD

**Issue by lg2de** [Caliburn-Micro/Caliburn.Micro#608]
Caliburn does not (yet) support .NET Core 3 (preview).
Using latest version (4.0.62-alpha) in a core3 project the .NET Standard of Caliburn version is selected.
But the definition and implementation of `IWindowManager` is available only in the version for .NET Framework. So the window manager is not available in .NET Core.

Do you plan to add support for .NET Core 3.0 before release of Caliburn 4.0?

**Comment by nigel-sampson** [comment]
It's definitely on the roadmap, not sure whether it would be in 4.0 or 4.1 given the release timeframes of ,net core 3.0

**Comment by cskwrd** [comment]
@nigel-sampson, sorry to necro this a bit. Is there a preview version that is compatible? I would Like to do some dotnet core WPF testing.

**Comment by nigel-sampson** [comment]
@mjuen has stepped up and is putting together a PR that adds this via #626 

Would love some people to try it out and provide feedback.

**Comment by nigel-sampson** [comment]
.NET Core 3 support has been merged and available in the MyGet feed, would appreciate some eyes on it.

**Comment by MDBonafe** [comment]
I am testing a conversion to .net core.  How do I get to the "MyGet" feed?

**Comment by nigel-sampson** [comment]
Feed information an how to install is available at https://www.myget.org/feed/caliburn-micro-builds/package/nuget/Caliburn.Micro

**Comment by MDBonafe** [comment]
Thanks for the reply.  However, the command doesn't work for version 4.0.102-alpha.  I could get version 4.0.64-alpha to install just fine, and so far, VS 2019 does not complain about compatibility with .Net Core 3.1

________________________________

**Comment by nigel-sampson** [comment]
Just tried the following command with `102` and `104` and it worked correctly.
```
dotnet add package Caliburn.Micro --version 4.0.104-alpha --source https://www.myget.org/F/caliburn-micro-builds/api/v3/index.json
```

**Comment by MDBonafe** [comment]
I got that to work a few hours ago.  Thank you!

I am successfully using an older version of Caliburn.Micro; not core.  With this new version, I'm having a problem getting the view to display.  The view model is executing, but the system "cannot find view for...".

I am using the following code in the App() method:
            var config = new TypeMappingConfiguration
            {
                DefaultSubNamespaceForViews = "Phoenix.Views",
                DefaultSubNamespaceForViewModels = "PhoenixViewModel.ViewModels"
            };
            ViewLocator.ConfigureTypeMappings(config);
            ViewModelLocator.ConfigureTypeMappings(config);

The spelling is correct.  The views are in the main project.  The view models are in a separate project.  I am calling DisplayRootViewFor<...> in the OnStartup of the AppBootstrapper.  What am I missing?

________________________________

**Comment by nigel-sampson** [comment]
Are you including the new assembly something like https://github.com/nigel-sampson/talks/blob/master/ndc-sydney-2016/NDC.Build.Forms.App.UWP/App.xaml.cs#L45

**Comment by MDBonafe** [comment]
Thank you!  The code in SelectAssemblies() is what was needed.  Now on to more serious testing.

Question, is SimpleInjector still recommended or does it matter?  If I use an older version, 2.4.1, it seems to work just fine.  The newest version, 4.8.1, doesn't work well for me.

________________________________

**Comment by nigel-sampson** [comment]
SimpleInjector isn’t part of Caliburn.Micro so I’m not sure what changed here.
