### ISSUE TITLE
Add support to insert global lifecycle handlers

### ISSUE THREAD

**Issue by dbuksbaum** [Caliburn-Micro/Caliburn.Micro#61]
Currently, if I want to do something on activation / deactivation, I need to do it in the derived class. However, I have a marker interface that would allow for some custom functionality whenever any viewmodel is activated / deactivated that supports that interface, I either need to copy the core functionality and modify it (then deal with syncing over versions) or re-implement in every viewmodel.

As an example, I have an interface ISupportKeyBindings that I register the keybinding OnActivate, and unregister them in OnDeactivate. This is some code I want to run for any view model implementing the interface.

I was thinking a convention for a delegate to be called if it exists at the right places in the CM lifecycle management.

**Comment by BrunoJuchli** [comment]
@dbuksbaum  you might also want to see #10 - we implemented something similar.
(by extracting all conducting logic from the ViewModels. We also created extension points so one could hook into such "events").
