### ISSUE TITLE
Cannot find view for XXX, when using CM in a DLL and

### ISSUE THREAD

**Issue by PhilippPaetzold** [Caliburn-Micro/Caliburn.Micro#610]
Hello,
I have problems during Design-Time when using CM in a DLL (without a bootloader). I think my scenario is pretty common: I want to provide a DLL that hosts several Views/ViewModels, so the executable (that also uses CM and has a MEF-Bootloader) can consume this and import the ViewModels with MEF. 

My problem is, that in the DLL-project CM can not find the corresponding viewmodel to a nested view (Usercontrol). I have a "MainView" there which embeds a "NestedView" as a ContentControl, both of which are UserControls and provide their own viewmodel. When I show the MainView in the VS-designer I get the error message:

"Cannot find view for CaliburnTests.ViewModels.NestedViewModel" in the place where the nested viewmodel should show up. Its a very basic project and I double checked the conventions and folder structure. A minimal example of the DLL-project is attached to this issue (VS2017). 

[CaliburnTests.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/3244663/CaliburnTests.zip)

I really like to use CM in a bigger project where I need to put several VMs and Views into multiple DLLs and also need design time support for more complex pages...

I would really appreciate help, thank you very much and Greetings from Karlsruhe, Germany
Philipp Paetzold

**Comment by mvermef** [comment]
looking at the source you provided it appears to be a Namespace Issue....  so since you have 
`CaliburnTests.ViewModels.NestedViewModel`

the view HAS to be in 
`CaliburnTests.Views.NestedView`

its presently only has the namespace `CaliburnTests.NestedView`

this a function of conventions by default.

**Comment by PhilippPaetzold** [comment]
Thanks for your quick reply and you are absolutly right. I changed the sources accordingly, but I still get the error message. The updated sources are attached. Do I really need to have a main project (with a bootstrapper) at all to make the designer work correctly for the DLL and show the nested view? Should the design-time part not work without with the attached VS solution?
[CaliburnTests.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/3245168/CaliburnTests.zip)
![2019-06-02 22_14_40-CaliburnTests - Microsoft Visual Studio](https://user-images.githubusercontent.com/23527944/58766860-1d951e80-8584-11e9-99ce-17846bd5d844.png)

**Comment by mvermef** [comment]
To get design time no you don't need the main shell, what I need to see is if you used the override for external dependencies.. not to mention MEF is a pain in the ass to debug, one of the reasons I stopped using MEF ages ago.

**Comment by PhilippPaetzold** [comment]
Ok, thanks for your info. I can confirm this. I created a minimal WPF executable with an MEF bootstrapper and moved the two VMs and Views inside this project, adjusted the namespaces and it works correctly, also for design time. Its pretty annoying, since I want to design an application with different pages and nested subviews and put those into one or more DLLs. I will further investigate the issues.
