### ISSUE TITLE
Support for Visual Studio Extension (VSIX) projects

### ISSUE THREAD

**Issue by Enache-Ionut** [Caliburn-Micro/Caliburn.Micro#611]
Hi, 

In my `Visual Studio Extension(VSIX)`, I want to implement a `WPF - MVVM` component. In this scope, I want to use `Caliburn Micro`. I used it before in a pure WPF app and it was awesome. Now I want it to use it again in my VSIX project. 

It is possible to use `Caliburn Micro` in a `Visual Studio Extension(VSIX)` project?

If it is possible how can I accomplish this? 
How the `Bootstrapper` class should look like?

**Comment by nigel-sampson** [comment]
I probably wouldn't try to use `Bootstrapper` it's heavily focused on the start up of a regular WPF app. I'd look into pulling the main initialization parts you need from it into what ever makes sense inside a VSIX.

You may even need to customize the regular `XamlPlatformProvider`, not sure though haven't really worked with VSIX before.
