### ISSUE TITLE
Behaviors 

### ISSUE THREAD

**Issue by AndreiLazarescu** [Caliburn-Micro/Caliburn.Micro#614]
Hello,

Behaviors on ListBox and ComboBox are seen as child item element. Is this a bug or am I doing something wrong?

```
<ComboBox ItemsSource="{Binding Profiles}">
     <i:EventTrigger EventName="SelectionChanged">
          <i:InvokeCommandAction Command="{Binding SelectionChangedCommand}" />
     </i:EventTrigger>
</ComboBox>
```

Thank you,
Andrei

**Comment by nigel-sampson** [comment]
It looks like you're missing some parts of the triggers syntax. Take a look at [this sample](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/samples/features/Features.WPF/Views/ActionsView.xaml#L35).

**Comment by AndreiLazarescu** [comment]
Hi Nigel,

I do not want to use the ActionMessage. I want to use InvokeCommandAction but "something"(my guess is caliburn) scans the xaml file and for some reason my interaction tag is seen as a ComboBoxItem and throws and error saying that Items must be empty before using ItemsSource. If I remove the tag everything works just fine.

Thank you,
Andrei

**Comment by nigel-sampson** [comment]
That’s fine but if you look at the sample you can see your example is missing the ‘i:Interaction.Triggers’.

**Comment by AndreiLazarescu** [comment]
Ups, you are right, I forgot to add the triggers tag.

**Comment by AndreiLazarescu** [comment]
Thank you for your time.
