### ISSUE TITLE
use "TryClose" can't close the viewmodel with window

### ISSUE THREAD

**Issue by hjj28810** [Caliburn-Micro/Caliburn.Micro#615]
if the viewmodel inherit IScreen and "SingleInstance" ,tryclose it works
if the viewmodel inherit IScreen and "InstancePerDependency" ,tryclose it can't work

**Comment by hjj28810** [comment]
PlatformProvider.Current.GetViewCloseAction(this, Views.Values, dialogResult).OnUIThread();

`Views.Values ` Count is 0

**Comment by hjj28810** [comment]
if TryClose fail ,how  to close view in viewmodel another way?

**Comment by nigel-sampson** [comment]
Can you please provide a small repo demonstrating this bug, I'm not sure exactly what you mean here.

**Comment by hjj28810** [comment]
i have a view of LoginView with `LoginViewModel : Screen,ILogin` and use Autofac IoC
if LoginViewModel lifetime set `SingleInstance`，TryClose is work
if set `InstancePerDependency` ，TryClose can't work always,maybe 1st time open can close

**Comment by nigel-sampson** [comment]
- What version of Caliburn.Micro are you using?
- What platform are you implementing your application on?
- What is the code in `TryClose` that is / isn't working for you?

These are all questions that a sample app that illustrates the problem become a lot easier to answer and also provides a sandbox to determine work arounds.

**Comment by hjj28810** [comment]
sry, i will push the test code

**Comment by hjj28810** [comment]
oh,its my fault,not the `try close` error,i use the Autofac IoC  and can't use `IoC.Get<ILogin>()` get the instance of ILogin,y?

**Comment by hjj28810** [comment]
i find reason ,its set "InstancePerDependency"
