### ISSUE TITLE
how to show the singleInstance window

### ISSUE THREAD

**Issue by hjj28810** [Caliburn-Micro/Caliburn.Micro#616]
i use v3.2.0 in WPF，how to show a window(view) like singleInstance ,IoC only ctrl the viewmodel with singleInstance

**Comment by hjj28810** [comment]
not show a dialog window

**Comment by nigel-sampson** [comment]
Sorry I don't follow what you mean here, can you expand on it?

**Comment by hjj28810** [comment]
how can i show a window with the same instance
i need show a group of windows ,show  = activity  close = hidden

**Comment by hjj28810** [comment]
and how can i set Window Owner in ViewModel before showdialogwindow

**Comment by nigel-sampson** [comment]
Do you mean you want to share a singleton view model across different views?

**Comment by hjj28810** [comment]
how to use showdailog settings, if i will set owner
