### ISSUE TITLE
Build errors using 4.0.62-alpha with Xamarin.Forms

### ISSUE THREAD

**Issue by neilt6** [Caliburn-Micro/Caliburn.Micro#617]
I'm having issues upgrading a Xamarin.Forms app with a single UWP platform to Caliburn.Micro 4.0.62-alpha. I looks like the [Caliburn.Micro.Xamarin.Forms](https://www.nuget.org/packages/Caliburn.Micro.Xamarin.Forms/) package has been retired, so I installed the [main NuGet package](https://www.nuget.org/packages/Caliburn.Micro/) on both the .NET Standard project and UWP project, and updated the namespace in my views to:

`xmlns:cal="clr-namespace:Caliburn.Micro;assembly=Caliburn.Micro.Platform"`

This allows the .NET Standard project to build, but the UWP project fails with the following errors in `MainPage.xaml.cs`:

```
CS7069	Reference to type 'FormsApplication' claims it is defined in 'Caliburn.Micro.Platform', but it could not be found
CS1503	Argument 1: cannot convert from 'XamarinFormsExample.App' to 'Xamarin.Forms.Application'
```

Here are the relevant files:

### App.xaml (.NET Standard)
```
<?xml version="1.0" encoding="utf-8" ?>
<cal:FormsApplication xmlns="http://xamarin.com/schemas/2014/forms"
                      xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                      xmlns:d="http://xamarin.com/schemas/2014/forms/design"
                      xmlns:cal="clr-namespace:Caliburn.Micro;assembly=Caliburn.Micro.Platform"
                      mc:Ignorable="d"
                      x:Class="XamarinFormsExample.App">
    <Application.Resources>

    </Application.Resources>
</cal:FormsApplication>
```

### App.xaml.cs (.NET Standard)
```
using Caliburn.Micro;
using System.Threading.Tasks;
using Xamarin.Forms;
using XamarinFormsExample.Mvvm;

namespace XamarinFormsExample
{
    public partial class App
    {
        #region Fields

        readonly SimpleContainer m_Container;

        #endregion

        #region Constructors

        public App(SimpleContainer container)
        {
            m_Container = container;
            Initialize();
            InitializeComponent();

            //Set up the IoC container
            m_Container.PerRequest<Buttons.ViewModels.ButtonOneViewModel>();
            m_Container.PerRequest<Buttons.ViewModels.ButtonsViewModel>();
            m_Container.PerRequest<Buttons.ViewModels.ButtonThreeViewModel>();
            m_Container.PerRequest<Buttons.ViewModels.ButtonTwoViewModel>();
            m_Container.PerRequest<Shell.ViewModels.ShellViewModel>();
            m_Container.PerRequest<Status.ViewModels.StatusViewModel>();

            //Display the shell view
            DisplayRootView<Shell.Views.ShellView>();
        }

        #endregion

        #region Protected Methods

        protected override void PrepareViewFirst(NavigationPage navigationPage)
        {
            //Register the navigation page with the IoC container
            m_Container.Instance<INavigationService>(new NavigationPageAdapter(navigationPage));
        }

        #endregion
    }
}
```

### App.xaml (UWP)
```
<cal:CaliburnApplication
    x:Class="XamarinFormsExample.UWP.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:cal="using:Caliburn.Micro">

</cal:CaliburnApplication>
```

### App.xaml.cs (UWP)
```
using Caliburn.Micro;
using System;
using System.Collections.Generic;
using System.Reflection;
using Windows.ApplicationModel.Activation;
using Windows.UI.Xaml;
using Xamarin.Forms;

namespace XamarinFormsExample.UWP
{
    sealed partial class App
    {
        #region Fields

        WinRTContainer m_Container;

        #endregion

        #region Constructors

        public App()
        {
            m_Container = new WinRTContainer();
            Initialize();
            InitializeComponent();
        }

        #endregion

        #region Protected Methods

        protected override void Configure()
        {
            //Set up the IoC container
            m_Container.RegisterWinRTServices();
            m_Container.Singleton<XamarinFormsExample.App>();
        }

        protected override IEnumerable<Assembly> SelectAssemblies()
        {
            //Return the assemblies containing the views and view models
            yield return typeof(XamarinFormsExample.App).GetTypeInfo().Assembly;
        }

        protected override object GetInstance(Type service, string key)
        {
            //Get an instance of the specified service
            return m_Container.GetInstance(service, key);
        }

        protected override IEnumerable<object> GetAllInstances(Type service)
        {
            //Get all instances of the specified service
            return m_Container.GetAllInstances(service);
        }

        protected override void BuildUp(object instance)
        {
            //Build up the specified service instance
            m_Container.BuildUp(instance);
        }

        #endregion

        #region Event Handlers

        protected override void OnLaunched(LaunchActivatedEventArgs args)
        {
            //Check if the application is already running
            if (args.PreviousExecutionState == ApplicationExecutionState.Running)
            {
                return;
            }

            //Initialize the framework
            Forms.Init(args);

            //Display the main page
            Window.Current.Content = new MainPage();
            Window.Current.Activate();
        }

        #endregion
    }
}
```

### MainPage.xaml (UWP)
```
<forms:WindowsPage
    x:Class="XamarinFormsExample.UWP.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:forms="using:Xamarin.Forms.Platform.UWP"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <Grid>

    </Grid>
</forms:WindowsPage>
```

### MainPage.xaml.cs (UWP)
```
using Caliburn.Micro;

namespace XamarinFormsExample.UWP
{
    public sealed partial class MainPage
    {
        #region Constructors

        public MainPage()
        {
            InitializeComponent();

            //Load the application
            LoadApplication(IoC.Get<XamarinFormsExample.App>());
        }

        #endregion
    }
}
```

**Comment by nigel-sampson** [comment]
Can you compare to the [features samples](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/samples/features) which are compiled against each build.

**Comment by neilt6** [comment]
@nigel-sampson It looks like the Android and iOS samples are referencing the Caliburn.Micro assemblies directly rather than using NuGet:

### Features.Forms.Android.csproj
```
<Reference Include="Caliburn.Micro.Core">
  <HintPath>..\..\..\..\bin\Caliburn.Micro.Platform\release\monoandroid80\80\Caliburn.Micro.Core.dll</HintPath>
</Reference>
<Reference Include="Caliburn.Micro.Platform">
  <HintPath>..\..\..\..\bin\Caliburn.Micro.Platform\release\monoandroid80\80\Caliburn.Micro.Platform.dll</HintPath>
</Reference>
```

### Features.Forms.iOS.csproj
```
<Reference Include="Caliburn.Micro.Core">
  <HintPath>..\..\..\..\bin\Caliburn.Micro.Platform\release\xamarin.ios10\Caliburn.Micro.Core.dll</HintPath>
</Reference>
<Reference Include="Caliburn.Micro.Platform">
  <HintPath>..\..\..\..\bin\Caliburn.Micro.Platform\release\xamarin.ios10\Caliburn.Micro.Platform.dll</HintPath>
</Reference>
```

**Comment by nigel-sampson** [comment]
Yes, that means they're tested against the current version of the code, just replace the project references from the MyGet feed

**Comment by neilt6** [comment]
@nigel-sampson My experiments with the sample projects have been inconclusive. They're using a PCL rather than a .NET Standard library, and appear to be referencing the v3.0.3 NuGet packages. My attempts to update them are being met with endless errors and headaches so I've given up.

I've managed to reproduce the issue using a contrived scenario. First, I created a .NET Standard library using Caliburn.Micro 4.0.72-alpha (MyGet) and Xamarin.Forms 4.1.0.555618 (NuGet), and added the following static class:

```
using Caliburn.Micro;

namespace Experiment
{
    public static class Class1
    {
        public static FormsApplication Application { get; }
    }
}
```

Then, I created another .NET Standard library using the same packages, and tried to access the static class. This worked as expected, but changing the `TargetFramework` to `net471` produced the following error:

`The type 'FormsApplication' is defined in an assembly that is not referenced. You must add a reference to assembly 'Caliburn.Micro.Platform, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.`

I believe this is caused by the different target frameworks referencing different builds of `Caliburn.Micro.Platform.dll` within the NuGet package.

**Comment by nigel-sampson** [comment]
The features samples reference local build output which will always be the latest version. 

Looking at your scenario I can see how that wouldn't work, it comes back to the fact that Xamarin.Forms has no "platform" other than .NET Standard. However the way you have it is a little contrived in referencing a project with Xamarin Forms code from WPF (net471).

If you're looking to share code between platforms through .NET Standard have that project reference the Caliburn.Micro.Core package that has no platform dependencies.

**Comment by neilt6** [comment]
@nigel-sampson I'm not sure we're on the same page here... I've uploaded a sample Xamarin.Forms project that uses Caliburn.Micro 4.0.0-alpha.1:

https://github.com/neilt6/Xamarin.Forms-Experiments

This project works fine, because 4.0.0-alpha.1 and earlier had a separate Caliburn.Micro.Xamarin.Forms NuGet package for the .NET Standard library. However, 4.0.62-alpha doesn't have this package... So I switched the .NET Standard library to the main Caliburn.Micro package, which causes errors related to the `FormsApplication` type:

https://github.com/neilt6/Xamarin.Forms-Experiments/tree/4.0.62-alpha

I can't use Caliburn.Micro.Core, because it doesn't contain `FormsApplication` or any of the other types that are necessary for building a Xamarin.Forms application.

**Comment by nigel-sampson** [comment]
Right, now I got you, it does look like an unsupported use case right now in terms of Xamarin.Forms in WPF. 

You can see form [this line](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/Caliburn.Micro.Platform.csproj#L51) how it's assuming Android or iOS. 

Having the Xamarin.Forms independent package was causing problems with other parts and I'm loathe to return to it.

With XF and WPF we run into problems in that there essentially two different stacks of CM that are possible to run and no particularly good way to work out which one (besides the old approach of having different versions of the code in different namespaces).
