### ISSUE TITLE
WindowManager.ShowDialogAsync() hijacks my screen

### ISSUE THREAD

**Issue by ahmediddma** [Caliburn-Micro/Caliburn.Micro#619]
on maximized windows WindowManager.ShowDialogAsync() hijacks my screen like it sets the top most property to true i can't get anything in front of it not visual studio not my browser etc i have to close it before being able to see other windows

**Comment by snalesso** [comment]
that's the common `ShowDialog` behavior, to be able to focus the other windows you have to use `ShowWindow`

**Comment by ahmediddma** [comment]
to be clear any window that opens with WindowManager.ShowDialogAsync() hijacks all my screen not just my app like if it had TopMost set to True that i can't even get other apps on front of it not even the Task Manager

**Comment by nigel-sampson** [comment]
The `WindowManager` is just using [`ShowDialog`](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/Platforms/net46/WindowManager.cs#L62) on the `Window`.

**Comment by ahmediddma** [comment]
maybe but they don't behave the same use the 2 next to each other with maximized window and try to bring other apps windows in front of them
