### ISSUE TITLE
Can ViewModel have multiple instances?

### ISSUE THREAD

**Issue by ghhsyy** [Caliburn-Micro/Caliburn.Micro#620]
I have a “SideView” and a “SideViewModel”. I want to show it twice in “MainView”, But it can not work. It just show “DownSideView”. 
Code in MainView.xaml
```
<Grid>
  <Grid.RowDefinitions>
    <RowDefinition Height="1*"/>
    <RowDefinition Height="1*"/>
  </Grid.RowDefinitions>
  <Grid Grid.Row="0">
    <ContentControl x:Name="UpSideView" HorizontalAlignment="Center" VerticalAlignment="Center"/>
  </Grid>
  <Grid Grid.Row="1">
    <ContentControl x:Name="DownSideView" HorizontalAlignment="Center" VerticalAlignment="Center"/>
  </Grid>
</Grid>
```
Code in MainViewModel.cs
```
[Import(typeof(SideViewModel), AllowDefault = true)]
public SideViewModel UpSideView { get; set; }

[Import(typeof(SideViewModel), AllowDefault = true)]
public SideViewModel DownSideView { get; set; }
```

**Comment by nigel-sampson** [comment]
Not sure what dependency injection you're using here, but would this result in the same instance of `SideViewModel` being used for both properties? and if so is this intended?

Just trying to determine if the real question is "Can a view model be represented by multiple views?" rather than multiple view models.

**Comment by mvermef** [comment]
The di appears to be MEF or a derivative

**Comment by ghhsyy** [comment]
Thanks very much @nigel-sampson and @mvermef. 
I'm using MEF as DI. 
I just wanted to use `SideView` and `SideViewModel` as a Contorl. The `SideView` appears twice in `MainView`. 
I'm an embedded engineer, I'm really sorry that the question is not clearly expressed.

**Comment by seba30** [comment]
If you decorate your ViewModel with
```
[Export]
[PartCreationPolicy(CreationPolicy.NonShared)]
```
then on every injection a new instance will be generated.

**Comment by ghhsyy** [comment]
Thanks very much, @seba30 .
It works very well. 
Thanks @nigel-sampson @mvermef for help.

**Comment by nigel-sampson** [comment]
You're welcome. Thanks all.
