### ISSUE TITLE
How to change the root view of the navigation page?

### ISSUE THREAD

**Issue by cbfrank** [Caliburn-Micro/Caliburn.Micro#623]
Conside below scenario for a xamarin forms application
1. display a login page as the root view by using DisplayRootView<LoginView> when app starts
2. in the login method of the LoginViewModel, if the user login successfully, we need to replace the root of the app navigation page to Home view (i.e. remove the login view from the navigation stack and HomeView becomes the root of the navigation page)
I can't find any method of the INavigationService supports this.

Thanks

**Comment by nigel-sampson** [comment]
You would do this via the normal mechanisms on the platform in question rather than through the framework.
