### ISSUE TITLE
Key input binding support

### ISSUE THREAD

**Issue by dellamonica** [Caliburn-Micro/Caliburn.Micro#63]
It seems to me that binding a command to a specific key (e.g. Enter, Delete) is a fairly common scenario and this project would benefit from offering native support for such bindings. Moreover, there  is already a sample project in
samples / Caliburn.Micro.KeyBinding / 
that could be absorbed by the framework.

**Comment by JobaDiniz** [comment]
+1

**Comment by stukdev** [comment]
Try this gesture cal:Message.Attach="[Gesture Ctrl+Up] = [Action Up()];[Gesture Ctrl+Down]] = [Action Down()]" the action is not called. Maybe is not recognize?

**Comment by wstaelens** [comment]
+1

**Comment by JobaDiniz** [comment]
The good thing about Command in MenuItem is that if the command has a Gesture, then WPF will render the key combination along with the menu text

**Comment by nigel-sampson** [comment]
Given some of the input and the changes expected in `4.0.0` it seems this would only make sense in WPF and would be of dubious value. 

I'm thinking we'll leave the sample "as is" and not add anything to the framework.

**Comment by ahmediddma** [comment]
> 
> 
> Given some of the input and the changes expected in `4.0.0` it seems this would only make sense in WPF and would be of dubious value.
> 
> I'm thinking we'll leave the sample "as is" and not add anything to the framework.

the code cal:Message.Attach="[Key Enter] = [EnterPressed]" does't seem to work for me in 4.0.62-alpha
