### ISSUE TITLE
Documentation seems very outdated

### ISSUE THREAD

**Issue by lloydjatkinson** [Caliburn-Micro/Caliburn.Micro#634]
I had a look through the docs and they still reference Windows Phone and Silverlight. The [Basic Configuration](https://caliburnmicro.com/documentation/configuration) page shows examples of Silverlight running in IE11.

Is there any plan to update the docs? I'm not sure how suitable it is for a new WPF application based on the docs alone.

**Comment by Revan654** [comment]
Based on the roadmap [https://caliburnmicro.com/roadmap](url) Yes. Not sure when that will happen or whats being added.

**Comment by asWorks** [comment]
I would very much second to give updating the documentation much higher priority. Chances are that in the current state a lot of the good work that is put into it simply is in vain because CM is unusable for beginners.

**Comment by vb2ae** [comment]
has been updated
