### ISSUE TITLE
BootstrapperBase is missing in 4.0.62-alpha?

### ISSUE THREAD

**Issue by Portalcake** [Caliburn-Micro/Caliburn.Micro#635]
Hello, good night~
I'm trying to write a sample WPF app using .NET Core 3.0 RC1 and Caliburn.micro v4.0.62-alpha.

But, when I try to create a basic bootstrapper, I've getting the following error in Visual Studio:
`The type or namespace name 'BootstrapperBase' could not be found (are you missing a using directive or an assembly reference?)`

My line is:
`public class SimpleBootstrapper : BootstrapperBase`

Is there any way to fix it?
Thanks in advance.

**Comment by nigel-sampson** [comment]
I can't remember off hand what build adds the .NET Core 3 support, but can you try the latest version and see how it goes?

**Comment by Portalcake** [comment]
I'm trying the latest version available on NuGet (4.0.62-alpha).

**Comment by Portalcake** [comment]
Fixed it, thanks alot!

**Comment by Mrxx99** [comment]
@nigel-sampson Would it be possible to release a new alpha also on Nuget, since the last one there has this Bootstrapper problem

**Comment by marekCs** [comment]
> 
> 
> Fixed it, thanks alot!

How did you fix it, please?
