### ISSUE TITLE
Unable to build the solution - a short doc required

### ISSUE THREAD

**Issue by godrose** [Caliburn-Micro/Caliburn.Micro#640]
I'm unable to build the current `master`. Is there any particular setup to be applied to my machine. Right now it's VS 2019 Preview 16.4 with all relevant SDKs.
There's a neat example for building the code at https://xunit.net/docs/building-xunit.html.
Is there something like this within the source code?

**Comment by nigel-sampson** [comment]
It looks like the `master` CI build is broken as well, I suspect around the changes to the base image for .NET Core 3.0 release.

Haven't had time to dig into it yet.

**Comment by nigel-sampson** [comment]
`master` is now building correctly.
