### ISSUE TITLE
FYI Xaml.Behaviors.Wpf Core 3 Update

### ISSUE THREAD

**Issue by IcySon55** [Caliburn-Micro/Caliburn.Micro#643]
Hey guys, just a heads up that the Xaml.Behaviors.Wpf library was ported to .Net Core 3 and using Caliburn.Micro v4.0.91-alpha with this updated nuget finally makes the entire thing run on Core!

https://dev.azure.com/dotnet/XamlBehaviorsWpf/_build/results?buildId=22944&view=artifacts

This update has a planned release around Nov 4th.

More details: https://github.com/microsoft/XamlBehaviorsWpf/pull/20

**Comment by davidhenley** [comment]
Seems to have been published:
https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf/

**Comment by IcySon55** [comment]
So I figured I'd fork Caliburn to update this nuget but apparently there are quite a few dependencies I don't have installed and can't even build the project... So i wait~
