### ISSUE TITLE
Fail to open the source code (the Caliburn.Micro.sln file)

### ISSUE THREAD

**Issue by hoangcuongvn** [Caliburn-Micro/Caliburn.Micro#648]
When I open the CM's solution file Caliburn.Micro.sln, I get an error message `one or more projects were not loaded correctly`. And the Output shows these sentences
```
Caliburn.Micro\src\Caliburn.Micro.Core\Caliburn.Micro.Core.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  C:\Users\XXX\.nuget\packages\msbuild.sdk.extras\2.0.54\Sdk\Sdk.props
Caliburn.Micro\src\Caliburn.Micro.Platform\Caliburn.Micro.Platform.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  C:\Users\XXX\.nuget\packages\msbuild.sdk.extras\2.0.54\Sdk\Sdk.props

```

I note that I am able to open the solution file of older CM's source code without error. I am using VS2017 with the latest Update.

![2019-11-29_1443](https://user-images.githubusercontent.com/13031495/69854094-ce257600-12ba-11ea-99a6-c018b3964293.png)

**Comment by nigel-sampson** [comment]
This looks very similar to https://github.com/novotnyllc/MSBuildSdkExtras/issues/190
