### ISSUE TITLE
SelectedVarName doesn't work as expected

### ISSUE THREAD

**Issue by imckl** [Caliburn-Micro/Caliburn.Micro#649]
#### System
 - version: 4.0.62-alpha
- platform: windows 10, .net framework 4.7.2

#### Description
SelectedVarName does not work as expected
##### SampleViewModel.cs
```
    public class SampleViewModel : Screen
    {

        string _selectedSampleItem;
        string _sampleItem2;
        
        public BindableCollection<string> SampleItems => new BindableCollection<string>
        {
            "sample item a",
            "sample item b",
            "sample item c"
        };

        public string SelectedSampleItem
        {
            get => _selectedSampleItem;
            set => Set(ref _selectedSampleItem, value);
        }

        public string SampleItem2
        {
            get => _sampleItem2;
            set => Set(ref _sampleItem2, value);
        }

        public void SampleConfirm(string sampleItem2, string selectedSampleItem)
        {
            var builder = new StringBuilder();
            builder.AppendLine($"sampleItem2 - param: {sampleItem2}, property: {SampleItem2}");
            builder.AppendLine($"selectedSampleItem - param: {selectedSampleItem}, property: {SelectedSampleItem}");
            MessageBox.Show(builder.ToString());
        }
   }
```

##### SampleView.xaml (part)
```
        <ComboBox x:Name="SampleItems" Margin="5" MinWidth="150" Grid.Row="3" Grid.Column="0" />
        <TextBox x:Name="SampleItem2" Margin="5" Grid.Row="3" Grid.Column="1" />
        <Button x:Name="SampleConfirm" Content="Test Sample" Grid.Row="3" Grid.Column="2" />
```
#### Output
![image](https://user-images.githubusercontent.com/20377660/70105763-b5331100-167c-11ea-8c81-990583bda0b2.png)
![image](https://user-images.githubusercontent.com/20377660/70105771-b9f7c500-167c-11ea-8a7a-02bb0d321538.png)
#### Question
- If that a bug, or my code aren't do the right thing?
- And what is the right way to to such thing? Thx in advanced

**Comment by nigel-sampson** [comment]
I don't believe the `SelectedX` has ever worked this way for parameter names, does the sample work with the parameter is `sampleItems` instead?

**Comment by imckl** [comment]
> I don't believe the `SelectedX` has ever worked this way for parameter names, does the sample work with the parameter is `sampleItems` instead?

It's my code failure and so sorry about disturbing by this wrong issue, Caliburn.Micro is a very nice framework to do mvvm-work.
I have tested this code on basic MVVM-way and didn't work.
I'm new to c# and mvvm world and experienced the way coding, thanks for your replying^^
