### ISSUE TITLE
Persist UI changes to source variable as well.

### ISSUE THREAD

**Issue by gowthamnatarajan** [Caliburn-Micro/Caliburn.Micro#650]
My code looks like the following:

`ListA = new BindableCollection<....>(ListB);`

ListA is shown as a datagrid in the UI and get modified in the UI. I see tha the changes are saved only in ListA and not ListB. How to get the changes to ListB every time something is changed in the UI

**Comment by mvermef** [comment]
What is the source of B? BindableCollection?

**Comment by seba30** [comment]
https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Core/BindableCollection.cs

**Comment by gowthamnatarajan** [comment]
ListB us a List<T>.
T is my custom class

**Comment by nigel-sampson** [comment]
Lists in general even outside of Caliburn.Micro have never exhibited this behavior. The constructor that takes a enumerable simply copies the values and doesn't hold a reference to the source list.

If you want that sort of behavior in a list then you'd need to build that yourself.
