### ISSUE TITLE
Impossible install Caliburn.Micro.4.0.104-alpha

### ISSUE THREAD

**Issue by Enrichetto** [Caliburn-Micro/Caliburn.Micro#652]
Hello,

I tried to Install Caliburn.Micro.4.0.104-alpha in different ways. But I get this error every time:

PM> Install-Package C:\XXXX\Caliburn.Micro.4.0.104-alpha.nupkg
he 'Source' parameter is not respected for the transitive package management based project(s) Deloitte.Mare.UI.FrontEnd. The enabled sources in your NuGet configuration will be used. 
Restoring packages for C:\xxxx...
  GET https://www.myget.org/F/caliburn-micro-builds/api/v3/flatcontainer/microsoft.windowsdesktop.app/index.json
  GET https://www.myget.org/F/caliburn-micro-builds/api/v3/flatcontainer/microsoft.xaml.behaviors.wpf/index.json
  NotFound https://www.myget.org/F/caliburn-micro-builds/api/v3/flatcontainer/microsoft.xaml.behaviors.wpf/index.json 192ms
  NotFound https://www.myget.org/F/caliburn-micro-builds/api/v3/flatcontainer/microsoft.windowsdesktop.app/index.json 196ms
Install-Package : NU1101: Unable to find package Microsoft.Xaml.Behaviors.Wpf. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
At line:1 char:1
+ Install-Package C:\xxx ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1101: Unable to find package Microsoft.WindowsDesktop.App. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
At line:1 char:1
+ Install-Package C:\xxxxx\Caliburn.Micro.4.0.104-alph ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'Deloitte.Mare.UI.FrontEnd'.
At line:1 char:1
+ Install-Package C:\xxxxCaliburn.Micro.4.0.104-alph ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Do you have any idea what is going on??

**Comment by nigel-sampson** [comment]
From `Install-Package C:\XXXX\Caliburn.Micro.4.0.104-alpha.nupkg` It looks like you're downloading the package from the myget feed and trying to install it locally using a path to the nupkg. Is this correct?
