### ISSUE TITLE
Call NotifyOfPropertyChange in a different thread?

### ISSUE THREAD

**Issue by gowthamnatarajan** [Caliburn-Micro/Caliburn.Micro#653]
Is it possible to call `NotifyOfPropertyChange` from a different thread?

I have a `ViewModel` class with a method called `LoadData()` which calls `NotifyOfPropertyChange` for all variables in that class.

I also have a class which uses C#s Timer class to run a background method every 1 minute which fetches new data from DB. This method calls the `LoadData` method in the `ViewModel` class. But it does not refresh the UI. Should the `LoadData` method be called only from the UI thread?

**Comment by nigel-sampson** [comment]
Yes you can, by default `PropertyChangedBase` will ensure the events are fired on the UI thread.

**Comment by gowthamnatarajan** [comment]
Its not working for me. Can I reopen this issue?

**Comment by nigel-sampson** [comment]
What platform are you using? Can you provide a simple piece of code that shows this issue?
