### ISSUE TITLE
Fails to create actions with DropDownOpened event from ComboBox

### ISSUE THREAD

**Issue by ykydaird13** [Caliburn-Micro/Caliburn.Micro#658]
I am writing a UWP application with a ComboBox which will trigger method `BatchSelectorDropDown()` when event `DropDownOpened` raised.I am testing for many forms of statements, all of them will throw exception when starting. These are my outcomes:

statements:
`<ComboBox cm:Message.Attach="[Event DropDownOpened] = [Action BatchSelectorDropDown()]"/>`
`<ComboBox cm:Message.Attach="[DropDownOpened] = [BatchSelectorDropDown]"/>`
(and others conventions)

exception:
> Windows.UI.Xaml.Markup.XamlParseException: 'The text associated with this error code could not be found.
> 
> Failed to assign to property 'Caliburn.Micro.Message.Attach'. 

explicit form :
statements:
```
<ComboBox>
	<i:Interaction.Behaviors>
		<core:EventTriggerBehavior EventName="DropDownOpened">
			<core:EventTriggerBehavior.Actions>
				<cm:ActionMessage MethodName="BatchSelectorDropDown"/>
			</core:EventTriggerBehavior.Actions>
		</core:EventTriggerBehavior>
	</i:Interaction.Behaviors>
</ComboBox>
```
exception:
> 
> Windows.UI.Xaml.Markup.XamlParseException: 'The text associated with this error code could not be found.
> Cannot add instance of type 'Microsoft.Xaml.Interactions.Core.EventTriggerBehavior' to a collection of type 'Microsoft.Xaml.Interactivity.BehaviorCollection'. 

If I press continue in all forms, the following exception will be thrown:
```
Exception thrown: 'System.Reflection.TargetInvocationException' in Caliburn.Micro.Platform.dll
An exception of type 'System.Reflection.TargetInvocationException' occurred in Caliburn.Micro.Platform.dll but was not handled in user code
Exception has been thrown by the target of an invocation.
```

Other Infos:
Windows SDK: version 1903(Build 18362)
Caliburn micro: 4.0.104-alpha and 3.2.0

PS:`DropDownOpened` is a valid event of `ComboBox`.If the event is replaced by other events (eg: `Tapped`) it will run normally.

**Comment by nigel-sampson** [comment]
Look at the [docs][https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.combobox.dropdownopened) it looks like the event isn't a routed event and I'm not sure it's supported by `EventTriggerBehavior`.
