### ISSUE TITLE
Possibility to create dynamic keybindings from keys stored in ViewModels?

### ISSUE THREAD

**Issue by DMtsdt** [Caliburn-Micro/Caliburn.Micro#659]
I'm using my shell (a Conductor.Collection.OneActive) to dynamically create Menus and MenuItems for the purpose of aggregating all possible UI methods/actions available in the currently active screen.

The Menus are created as MenuItemViewModels in the Screens, and loaded/unloaded by the Shell. I have all the functionalities working correctly - except for keyboard shortcuts and gestures.

I've been successfully using the keybindings example and [this method](http://www.felicepollano.com/2011/05/02/InputBindingKeyBindingWithCaliburnMicro.aspx) to create non-dynamic keybindings, but I can't seem to be able to create bindings between keys stored in the MenuItemViewModel and XAML, in order to dynamically create and change them at the VM level.

Is implementing a feature like that even possible? What would you reckon as the best place to start?

**Comment by nigel-sampson** [comment]
I would look at creating a dependency property that when set creates the object structure from the blog post.
