### ISSUE TITLE
Binding Button IsEnabled is not working

### ISSUE THREAD

**Issue by BabaGadiga** [Caliburn-Micro/Caliburn.Micro#661]
Hi,

I have two buttons say Run and Abort. When user clicks on Run button, the button should be disabled and the Abort button should be enabled. Similarly when the user hits on Abort button, the button should be disabled and Run button should be enabled. I am trying to achieve this using MVVM+Caliburn Micro. 
For some reason I am not able to get the desired result. Below is my view model and xaml code. 

MainView.xaml
 <Button  Content="Run" cal:Message.Attach="RunTest" />
 <Button  Content="Abort" cal:Message.Attach="AbortTest" />

public class MainViewModel:: Conductor<Screen>.Collection.OneActive,INotifyPropertyChanged
{
private bool _runAutoTestSelected = true;
        private bool _abortAutoTestSelected = false;     
        public bool RunAutoTestSelected
        {
            get { return _runAutoTestSelected; }           
            set
            {
                _runAutoTestSelected = value;
                NotifyOfPropertyChange(() =>RunAutoTestSelected);
            }
        }

        public bool AbortAutoTestSelected
        {
            get { return _abortAutoTestSelected; }
            set
            {
                _abortAutoTestSelected = value;
                NotifyOfPropertyChange(() => AbortAutoTestSelected);
            }
        }
        public bool CanAbortTest()
        {
            return _abortAutoTestSelected;
        }
        public void AbortTest()
        {
            _abortAutoTestSelected = false;
            _runAutoTestSelected = true;
        }
        public bool CanRunTest()
        {
            
            return _runAutoTestSelected;
        }
        public void RunTest()
        {
            _runAutoTestSelected = false;           
            _abortAutoTestSelected = true;
        }
}

**Comment by nigel-sampson** [comment]
It appears you're setting the underlying fields directly rather than through the properties which means you aren't getting property changed notifications to the UI.

**Comment by BabaGadiga** [comment]
Thank you for the response Nigel. Could you give me a sample example for the above code to run. What changes do you want me to fix in the above code?

**Comment by nigel-sampson** [comment]
``` csharp
public void RunTest()
{
        RunAutoTestSelected= false;           
        AbortAutoTestSelected= true;
}
```

By setting the properties rather than the fields you get your property change notifications to execute so the UI updates.

**Comment by BabaGadiga** [comment]
Thank you Nigel. I updated my code to the above, but I still don't see any property change notifications. Below is my updated code in View and ViewModel

--View
<Button Content="Run" cal:Message.Attach="RunTest"/>
<Button Content="Abort" cal:Message.Attach="AbortTest"/>

--ViewModel
 private bool _runAutoTestSelected = true;
 private bool _abortAutoTestSelected = false;

 public bool RunAutoTestSelected
        {
            get { return _runAutoTestSelected; }
            set
            {
                _runAutoTestSelected = value;
                NotifyOfPropertyChange(() => RunAutoTestSelected);
            }
        }

        public bool AbortAutoTestSelected
        {
            get { return _abortAutoTestSelected; }
            set
            {
                _abortAutoTestSelected = value;
                NotifyOfPropertyChange(() => AbortAutoTestSelected);
            }
        }
      public bool CanAbortTest()
        {
            return _abortAutoTestSelected;
        }
        public void AbortTest()
        {
            RunAutoTestSelected = true;
            AbortAutoTestSelected = false;
        }
        public bool CanRunTest()
        {
            return _runAutoTestSelected;
        }
        public void RunTest()
        {
            RunAutoTestSelected = false;
            AbortAutoTestSelected = true;
        }

**Comment by nigel-sampson** [comment]
I assume your buttons around bound correctly to `RunAutoTestSelected` and `AbortAutoTestSelected`?

**Comment by BabaGadiga** [comment]
Thank you Nigel. I figured out the problem and you are correct, the buttons were not bound correctly.
