### ISSUE TITLE
Trailing semicolons and white space on 'cal:Message.Attach' causing exception/

### ISSUE THREAD

**Issue by dtiholden** [Caliburn-Micro/Caliburn.Micro#664]
I found an edge case issue with `cal:Message.Attach` that took a little time to hunt down.

If you have a semicolon followed by any whitespace in the `cal:Message.Attach` then an exception is thrown (`No target found for method`) on the first call to `NotifyOfPropertyChange(nameof(InputPath));`.

My original code that was failing:
```
<TextBox x:Name="InputPath" Text="TextBox"
      AllowDrop="True"
      cal:Message.Attach="
           [Event PreviewDragOver] = [Action MainView_DragOver($eventargs)];
           [Event Drop] = [Action MainView_Drop($eventargs)];
      " />

```

Semicolons without whitespace work:
```
      cal:Message.Attach="
        [Event PreviewDragOver] = [Action MainView_DragOver($eventargs)];
        [Event Drop] = [Action MainView_Drop($eventargs)];"
```

**Comment by nigel-sampson** [comment]
Thanks, definitely sounds like a bug.

**Comment by nigel-sampson** [comment]
Fixed on `master`
