### ISSUE TITLE
NavigationTransitionInfo argument of NavigationService.Navigate method

### ISSUE THREAD

**Issue by Mr1Penguin** [Caliburn-Micro/Caliburn.Micro#666]
Platform: uap

Hello!
I noticed lack of NavigationTransitionInfo argument of Navigate method. Is this intended to be that way for a reason?
I was trying to make use of connected animations. There is a advise to suppress a navigation transition animation.

**Comment by nigel-sampson** [comment]
I've tried to keep the navigation service platform agnostic as much as possible with a potential goal of sharing a single implementation across platforms.

**Comment by Mr1Penguin** [comment]
Oh, I see. That answers my question.
Then it would be better if I do inheritance/composition of existing FrameAdapter class.

**Comment by nigel-sampson** [comment]
I would say so.
