### ISSUE TITLE
IEventAggregator and Async Handling

### ISSUE THREAD

**Issue by MDBonafe** [Caliburn-Micro/Caliburn.Micro#670]
I like the option of publishing messages asynchronously, but sometimes I need the messages handled in a synchronous way.  Is there a reason that the original, synchronous, methods were removed?  Is there a way for me to override, or extend, the Caliburn classes with the older signatures?

**Comment by nigel-sampson** [comment]
I assume you by `in a synchronous way` you mean you'd like to await till all the handlers have finished responding.

Unless I've written it poorly simply awaiting the publish task should be enough to get the result.

**Comment by MDBonafe** [comment]
You are correct.  What I meant, I guess without saying it properly, is that it would be nice to have the old method signatures.  Even if "under the covers" they use the await statement.  I have a lot of code I'm trying to port to the .NET Core framework.  Keeping the old signatures means that wouldn't have to rewrite the eventAggregator.Publish to PublishAsync and I wouldn't have to redesign the hundreds of handlers.

I have already made sure the code written works properly.  No problem there at all.  I was just wondering out loud why the old signatures were removed.

Thanks for a great product.

________________________________

**Comment by nigel-sampson** [comment]
Ok, thanks for the clarification. I'm a little loathe to add the "sync over async" methods myself, they're often the source of deadlocks or poor performance if you're adding extra threading.
