### ISSUE TITLE
[UWP] INavigationService - Open a new view on top of an existing view without deactivating

### ISSUE THREAD

**Issue by Toonshorty** [Caliburn-Micro/Caliburn.Micro#671]
Please forgive me as I'm very new to CM but I am building an application with multiple screens and one of these implements a map which takes several seconds to initialise. When selecting an item on the map, a form will appear which I'm currently navigating to using:

`_navigationService.NavigateToViewModel<FormViewModel>();`

However, when navigating to the form it appears the map view is being deactivated which means when I then call `_navigationService.GoBack();` on the form, the map view has to be initialised again.

Is there any mechanism within the INavigationService to load a particular view (or view model) without deactivating the current view, while maintaining the default behaviour for other views?

**Comment by nigel-sampson** [comment]
That would completely depend on the underlying UI platform you're using.

**Comment by Toonshorty** [comment]
This particular scenario would be on a Windows UWP application, not sure if that changes anything?

**Comment by nigel-sampson** [comment]
By default the `Frame` control in UWP is responsible for the lifecycle of the underlying pages.  Normally it kills them and creates them on each navigation. I believe there are properties on the page control you can set that will force the frame to cache the page and reuse it.
