### ISSUE TITLE
[UWP] Injecting IEventAggregator into view constructor throws MissingMethodException

### ISSUE THREAD

**Issue by Toonshorty** [Caliburn-Micro/Caliburn.Micro#673]
I have a scenario within a UWP application whereby I need to manipulate a control in a view based on the value from a view model, the specific control is an ArcGIS MapView which includes a method for setting the viewpoint.

The view model includes a property which calls the event within the setter.

```c#
private CustomEntity _selectedItem;
public CustomEntity SelectedItem {
    get => _selectedItem;
    set
    {
        _selectedItem = value;
        _eventAggregator.PublishOnUIThread(new MapPoint(SelectedItem.Longitude, SelectedItem.Latitude));
    }
}
```

I am then injecting the event aggregator into the view's code behind with the same method.

```c#
public sealed partial class CustomMapView : Page, IHandleWithTask<MapPoint>
{
    public HydrantsMapView(IEventAggregator eventAggregator)
    {
        this.InitializeComponent();
        eventAggregator.Subscribe(this);
    }

    public async Task Handle(MapPoint mapPoint)
    {
        await MapView.SetViewpointCenterAsync(mapPoint);
    }
}
```

We are navigating to the view model with the following code:

```c#
...
// GetViewModelForForm is a service which maps various navigation items to the view model types
Type viewModelType = FormMapping.GetViewModelForForm(selectedId);
_navigationService.NavigateToViewModel(formViewModel);
```

When calling the navigation method, nothing happens and the following error is shown in the output:

```
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.IO.FileLoadException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.IO.FileLoadException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.MissingMethodException' in Caliburn.Micro.Platform.UWP.dll
```

Alongside the following exception in the events history:

```
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.ni.dll ("No parameterless constructor defined for this object.") | System.MissingMethodException
```

Most documentation and issues seem to be around injecting into the view model rather than the view itself.

**Comment by nigel-sampson** [comment]
I don't think injecting into a view constructor will ever work, it's the underlying `Frame` control that's responsible for building the view and it won't use any container.
