### ISSUE TITLE
Viewmodel not found for View V4.0.113 (Xamarin Forms)

### ISSUE THREAD

**Issue by Zarkos69** [Caliburn-Micro/Caliburn.Micro#676]
Hello,

I have tested out version 4.0.113 for a new application of ours.
The view was always unable to find the viewmodel. Even if the Viewmodel was loaded, the View would show but without the viewmodel found...
In the attachments I have 2 test applications, 1 with the 4.0.0 alpha that is available on Nuget.
[TestXamarinCaliburn.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/4287851/TestXamarinCaliburn.zip)
And the other one with the 4.0.113.
[TestXamarinCaliburn_4.0.113_SC.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/4287849/TestXamarinCaliburn_4.0.113_SC.zip)

I have tried several things without success.

Kind regards

**Comment by nigel-sampson** [comment]
What's the error you're seeing?
