### ISSUE TITLE
How to : Working with MVVM Dialog by FantasticFiasco need help injecting IDialogService.

### ISSUE THREAD

**Issue by infirazor** [Caliburn-Micro/Caliburn.Micro#678]
Hello everyone,

I need help in using MVVM Dialog (https://github.com/FantasticFiasco/mvvm-dialogs).
I want to use this library in my existing app but I dont know how to inject this IDialogService from bootsrapper.

Following is the Link for reference how they are passing IDialogService : 

https://github.com/FantasticFiasco/mvvm-dialogs/blob/master/samples/net-framework/Demo.SaveFileDialog/App.xaml.cs

Following is the Link of a sample Dialog demonstrating usage of IDialogService : 

https://github.com/FantasticFiasco/mvvm-dialogs/blob/master/samples/net-framework/Demo.SaveFileDialog/MainWindowViewModel.cs

Maybe this is very basic request but I am not sure how to inject this service with Caliburn.Micro, and MVVM Dialog library is using MVVMLight for which I am not aware of.

Thank you and sorry for this silly question.

**Comment by nigel-sampson** [comment]
You can see [samples](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/samples/features/Features.WPF/Bootstrapper.cs#L19) of registering services with the container here.
