### ISSUE TITLE
Nested Lists

### ISSUE THREAD

**Issue by gowthamnatarajan** [Caliburn-Micro/Caliburn.Micro#679]
How do I bind nested lists with Caliburn Micro?
I would like to show a DataGrid with one of the columns being DataGrid.RowTemplateDetails with a DataTemplate containing another DataGrid.

How do I write the C# code to bind this? Will using BindableCollenction just of the outer List be enough?

**Comment by nigel-sampson** [comment]
If you're binding nested lists then you'll need to have nested controls that handle lists. 

From the binding point of view that would be no change in terms of how you do your binding. The sublist would just be another property on the item in the first list.
