### ISSUE TITLE
System.IO.FileLoadException when published as self-contained with Net Core 3.1

### ISSUE THREAD

**Issue by beachwalker** [Caliburn-Micro/Caliburn.Micro#682]
The following occurs with net core 3.1 and Caliburn.Micro 4.0.117-alpha.

When calling
`dotnet publish --configuration Release --runtime win10-x64 --self-contained=true`
the generated output will not be able to run and exits with:

` System.IO.FileLoadException: Could not load file or assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Arena.Framework.Application.Bootstrapper`1.SelectAssemblies()
   at Caliburn.Micro.BootstrapperBase.StartRuntime()
   at Caliburn.Micro.BootstrapperBase.Initialize()
   at Arena.Framework.Application.Bootstrapper`1..ctor()
   at Arena.Applications.Client.Bootstrapper..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Arena.Applications.Client.App.InitializeComponent()
   at Arena.Applications.Client.App.Main()`

The default build works (framework dependent), but this happens if I try to pack everything together. My Bootstrapper is located inside a separate Assembly and uses Autofac and loads all modules through a config json file.

**Comment by beachwalker** [comment]
My SelectAssemblies() method:

```
        protected override IEnumerable<Assembly> SelectAssemblies()
        {
            var assemblies = new HashSet<Assembly>();

            var fileInfos = new List<FileInfo>();

            if (Execute.InDesignMode) return Enumerable.Empty<Assembly>();

            try
            {
                var dirInfo = this.GetApplicationDirectory();

                fileInfos.AddRange(this.CollectViewAssemblyFileNames(dirInfo));
            }
            catch
            {
                // ignored
            }

            foreach (var fileInfo in fileInfos)
            {
                try
                {
                    var assembly = Assembly.LoadFrom(fileInfo.FullName);
                    
                    if (!assemblies.Contains(assembly))
                        assemblies.Add(assembly);
                }
                catch
                {
                }
            }

            return assemblies;
        }
```

**Comment by beachwalker** [comment]
I found out this happens because all Assemblies inside the directory are used:

```
        protected virtual IEnumerable<FileInfo> CollectViewAssemblyFileNames(DirectoryInfo applicationDirectory)
        {
            return applicationDirectory.GetFiles();
        }
```

If I add a filter everything works:
```
        protected virtual IEnumerable<FileInfo> CollectViewAssemblyFileNames(DirectoryInfo applicationDirectory)
        {
            // if I don't filter here I get some errors during publish..
            return applicationDirectory.GetFiles("*View*.dll");
        }
```

**Comment by nigel-sampson** [comment]
What you've got seems sensible, I don't see a good way around it besides a naming convention or just excluding `System` assemblies from your filter.

**Comment by beachwalker** [comment]
> What you've got seems sensible, I don't see a good way around it besides a naming convention or just excluding `System` assemblies from your filter.

I was able to track down the problem to the AssemblySource and the dictionary that is used inside. Maybe this shoule be solved inside the AssemblySource itself, but this could be solved at least  more elegant than be forced to define the filter. You can solve the problem by changing the StartRuntime() method:

```
        protected override void StartRuntime()
        {
            AssemblySourceCache.Install();

            var source = AssemblySource.Instance;

            foreach (var assembly in SelectAssemblies())
            {
                try
                {
                    if (!source.Contains(assembly))
                        source.Add(assembly);
                }
                catch (ArgumentException)
                {
                    // ignore, this is thrown if the key/assembly already exists in the dictionary behind
                }
            }


            //if (useApplication)
            {
                Application = Application.Current;
                PrepareApplication();
            }

            Configure();
            IoC.GetInstance = GetInstance;
            IoC.GetAllInstances = GetAllInstances;
            IoC.BuildUp = BuildUp;
        }
```

And this is how my SelectAssemblies look like (because I have the Views located in other assemblies than the executable).

```
        protected override IEnumerable<Assembly> SelectAssemblies()
        {
            if (this.viewAssemblies != null) return this.viewAssemblies; // no need to run more than once

            var assemblies = new HashSet<Assembly>();

            foreach (var assembly in base.SelectAssemblies()) assemblies.Add(assembly);

            if (Execute.InDesignMode) return Enumerable.Empty<Assembly>();

            var codeBase = Assembly.GetEntryAssembly()?.CodeBase;

            if (string.IsNullOrEmpty(codeBase))
                throw new InvalidOperationException();

            var uri = new UriBuilder(codeBase);
            var applicationDirectory = new DirectoryInfo(Path.GetDirectoryName(Uri.UnescapeDataString(uri.Path)) ??
                                                         throw new InvalidOperationException());

            var files = applicationDirectory.GetFiles("*.dll", SearchOption.TopDirectoryOnly);

            var assemblyFiles = new HashSet<FileInfo>();

            foreach (var file in files)
                if (file.Exists && file.IsAssembly())
                    assemblyFiles.Add(file);

            foreach (var fileInfo in assemblyFiles)
                try
                {
                    var assembly = Assembly.LoadFrom(fileInfo.FullName);

                    if (!AssemblySource.Instance.Contains(assembly) && !assemblies.Contains(assembly))
                    {
                        assemblies.Add(assembly);
                    }
                }
                catch (BadImageFormatException)
                {
                    // ignored
                }
                catch (FileLoadException)
                {
                    // ignored
                }

            this.viewAssemblies = assemblies;

            return this.viewAssemblies;
        }
```

Maybe this helps.

**Comment by beachwalker** [comment]
btw: I used the latest version from MyGet 4.0.117-alpha and net core 3.1.
Don't know if this also affects net framework.
