### ISSUE TITLE
Running 3.2 under .Net Core

### ISSUE THREAD

**Issue by ekgurney14** [Caliburn-Micro/Caliburn.Micro#685]
I was just wondering if anybody is successfully using 3.2 with .Net Core?  I pulled down and got it to compile and run with a very, very simple application.  Is there anything that I should expect not to work?  We aren't ready to move to Caliburn 4 yet because of too many changes, but would like to move to Core if we can.

Thanks,
Eric

**Comment by nigel-sampson** [comment]
3.2 isn't built against .NET Core and will not work.
