### ISSUE TITLE
Caliburn.Micro/samples/features => Error: Could not able to locate resources "menuview.xaml" 

### ISSUE THREAD

**Issue by Gopichandar** [Caliburn-Micro/Caliburn.Micro#686]
I am trying to get separate the WPF features sample alone from the Full cross platform example [here](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/samples/features).  

I have already separated that as single project excluding others.  Problem is that it is showing 

> Could not able to locate resources "menuview.xaml"

I am sure that the "Menuview.xaml" was there in "Views" folder and x:class defined. 

Here the the [full source](https://drive.google.com/open?id=1FvtlH9ib23_aNGmi7wCdbwKhbbPu7mFo)

**Comment by mvermef** [comment]
somewhere in your source the `namespace` is messed up... make sure each view corresponds to 
`<namespace>.views` and each viewmodel does the same
`<namespace>.viewmodels` this should fix your problem.  If you are imported views from a separate dll then you need setup ` SelectAssemblies()`

**Comment by nigel-sampson** [comment]
I imagine it's what @mvermef has said, if you want people to look closer I suggest making the repository available on GitHub.

**Comment by Gopichandar** [comment]
problem is that there is no separate sln for wpf and I have to install the whole bunch of pluggin for Xamarin, uwp which im not gonna use in near future. 

Any other suggestions you have for this?

**Comment by nigel-sampson** [comment]
I would just remove those projects from the solution if you're not caring about them.
