### ISSUE TITLE
Unable to build with Visual Studio 2019

### ISSUE THREAD

**Issue by beachwalker** [Caliburn-Micro/Caliburn.Micro#688]
Unable to load the projects using Visual Studio 2019 (16.5.2)

![image](https://user-images.githubusercontent.com/2715897/79353374-44113d80-7f3b-11ea-97cb-718ddcc64b0f.png)

The path seems to have an invalid format or the wrong Sdk is taken.

From the console output of Visual Studio (sorry, in parts in german language):

```
C:\Projekte\Caliburn.Micro\src\Caliburn.Micro.Core\Caliburn.Micro.Core.csproj : error  : Der Ausdruck "[System.IO.Path]::GetDirectoryName('')" kann nicht ausgewertet werden. Der Pfad hat ein ungültiges Format.  C:\Users\Developer\.nuget\packages\msbuild.sdk.extras\2.0.54\Sdk\Sdk.props

C:\Projekte\Caliburn.Micro\src\Caliburn.Micro.Platform\Caliburn.Micro.Platform.csproj : error  : Der Ausdruck "[System.IO.Path]::GetDirectoryName('')" kann nicht ausgewertet werden. Der Pfad hat ein ungültiges Format.  C:\Users\Developer\.nuget\packages\msbuild.sdk.extras\2.0.54\Sdk\Sdk.props

C:\Projekte\Caliburn.Micro\src\Caliburn.Micro.Core.Tests\Caliburn.Micro.Core.Tests.csproj : error  : Der Ausdruck "[System.IO.Path]::GetDirectoryName('')" kann nicht ausgewertet werden. Der Pfad hat ein ungültiges Format.  C:\Users\Developer\.nuget\packages\msbuild.sdk.extras\2.0.54\Sdk\Sdk.props

C:\Projekte\Caliburn.Micro\src\Caliburn.Micro.Platform.Tests\Caliburn.Micro.Platform.Tests.csproj : error  : Der Ausdruck "[System.IO.Path]::GetDirectoryName('')" kann nicht ausgewertet werden. Der Pfad hat ein ungültiges Format.  C:\Users\Developer\.nuget\packages\msbuild.sdk.extras\2.0.54\Sdk\Sdk.props
```

Are there any steps I need to do in front of trying to open the solution?

**Comment by nigel-sampson** [comment]
Curious, I'm using VS 2019 at the moment (not sure of current version).

**Comment by Toreth** [comment]
I'm having the same problem when I open `src/Caliburn.Micro.sln`.  I've tried Visual Studio 2017 Professional and 2019 Community.

**Comment by beachwalker** [comment]
German version? Maybe cultural settings?

**Comment by Toreth** [comment]
I'm using the English version of VS.  My errors are the same as yours, but in English.

**Comment by nigel-sampson** [comment]
Can people please post your exact VS 2019 versions etc. As stated above I'm using it without issues. But I can do any testing without knowing what version you're on.

**Comment by Toreth** [comment]
I tried it with 15.9.22 Professional and 16.5.4 Community.

**Comment by nigel-sampson** [comment]
I'm currently using `16.4.2` without any problems.  Will try updating later today.

**Comment by nigel-sampson** [comment]
It looks like you'll see this error if you don't have the SDK version specified in https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/global.json 

I managed to recreate the error by installing the SDK, installing the correct version resolved the error.
