### ISSUE TITLE
Inferno

### ISSUE THREAD

**Issue by ingenerics** [Caliburn-Micro/Caliburn.Micro#690]
Hi,

Congrats on the Caliburn-Micro framework, it's been a pleasure to work with.

I wanted to (ab)use this communication channel to inform you about [Inferno](https://github.com/ingenerics/Inferno), feel free to have a look and spread the word.

PS I've left Git history intact for the reviewers.

Gr

**Comment by nigel-sampson** [comment]
Thanks for the link.
