### ISSUE TITLE
Caliburn.Micro 4.0 Alpha async feedback

### ISSUE THREAD

**Issue by bitbonk** [Caliburn-Micro/Caliburn.Micro#691]
I have played a bit with the async features in the alpha of caliburn 4. If you want to play along or see what I did, I have created a [github repo](https://github.com/bitbonk/CaliburnAsyncPlayground) with the playground.

So here is my feedback.

1. Screen are activated/deactivated visually even though the task from `OnActivateAsync`/`OnDeactivateAsync` task is not yet completed.

   I think now that APIs suggest that initialization, activation and deactivation can be long running asynchronous operations, the framework must also provide means to handle that gracefully and to make that apparent in the UI.
   In the playground I can switch between the two tabs faster than the corresponding activation and deactivation task can complete. It seems that there is no way to prevent that in the UI or an easy built-in way to visualize that activation/deactivation is still in progress.
   A lot of activation and deactivation tasks are getting queued and are still being processed long after I stopped clicking the tabs. The behavior and the order in which those task are being processes also seem to be weird.

2. It is not clear to me what the `CancellationToken`s that are passed into `OnActivateAsync`, `OnDeactviateAsync` and `OnInitializeAsync` can be used for.

   It seems that its `CanBeCanceled` property is always `false`. In a `OneActive` conductor, shouldn't an activation be canceled if the user closes the thing that is currently being activated? With the current APIs of Caliburn.Micro I have no I idea how to program that myself if I want such a behavior.

3. It is also not clear to me what the `CancellationToken`s into async action methods (command callbacks) can be used for.

   Its `CanBeCanceled` property is also always `false`. How can I cancel that async action method that is currently in progress?
   A common use case is that I want to have a cancel button that should cancel the first button. While the first operation is in progress the first button should be disabled and the cancel button should be enabled. To program all of this by hand gets messy very quickly with `TaskCompletionSource`s and `CancellationTokenSources`.

4. I don't understand what the Task returned by `IEventAggregator.PublishAsync` and `IHandle<TMessage>.HandleAsync` and the `CancellationToken` passed represent.

   Should the task complete when all subscribers have handled the published message? Should the cancellation token cancel the async handlers that currently may or may not yet be in progress?

**Comment by bitbonk** [comment]
For an inspiration how how to make asynchronous taks easier to digest in a XAML UI, there is an older article series about this by @StephenCleary:

- [Async Programming : Patterns for Asynchronous MVVM Applications: Data Binding](https://msdn.microsoft.com/magazine/dn605875)
- [Async Programming : Patterns for Asynchronous MVVM Applications: Commands](https://msdn.microsoft.com/magazine/dn630647)

There is also a corresponding GitHub repo for this: https://github.com/StephenCleary/Mvvm.Async

`NotifyTask` makes the state of a `Task` easily observable (bindable) in the UI.
`AsyncCommand`\`CancelCommand` does the same for commands.

**Comment by nigel-sampson** [comment]
Thanks for the feedback.

1. I'm the opinion that the framework shouldn't try and provide direction on how the UI should react to long running initialization, every UI will be different in the way this will be done and I don't think prescription would be appropriate.  If there are UI patterns that people want to try and it makes sense that there should be something in the framework to help I think that can be discussed. 

The playground is definitely not a place to look for best practice :-)

2. You're right, they currently don't provide much, the first version was to start simple and layer on complexity later on with things like conductors cancelling long running initializations etc.

3. The `Task` returned from the event aggregator can be awaited to know when all the subscribers have handled the message. I view this is optional, but some patterns need this. The cancellation token passed to the publish will be passed on to the subscribers. This would let you cancel the subscribers reacting to the message if you wanted.

**Comment by vb2ae** [comment]
caliburn.micro 4 was released closing this issue
