### ISSUE TITLE
Print WPF Grid

### ISSUE THREAD

**Issue by BabaGadiga** [Caliburn-Micro/Caliburn.Micro#692]
Hi,

I have a functionality to print a XAML Grid. I am using MVVM pattern with Caliburn.Micro.
I have the below proxy code in XAML
<UserControl>
<Border>
<Grid x:Name="MainGrid">
<Button cal:Message.Attach="[Event Click] = [Action PrintMainGrid($view)]"/>                   
</Grid>
</Border>
</UserControl>

How do I print the Grid using PrintVisual from the above views corresponding ViewModel.
I do have this code, but does not work.

 public async Task PrintMainGrid(object view)
        {
                await Task.Run(() =>
                {
                    //how do I access the MainGrid here?
                   // I know the viewmodel should not access its view directly
                }); 
        }

**Comment by nigel-sampson** [comment]
You can use `GetView` on the view model to access the view itself, you'll need to cast it to correct view and then hunt for the control. 

Or you can pass the grid in as a parameter to the method.

**Comment by BabaGadiga** [comment]
Thank you for the quick reply Nigel. Could you give me the code to pass the grid from XAML?
As I have the below code in the Button
<Button cal:Message.Attach="[Event Click] = [Action PrintMainGrid($view)]"/>

**Comment by nigel-sampson** [comment]
https://github.com/Caliburn-Micro/Caliburn.Micro/blob/84edd18221243e0b3db5aa54e00680b8e6117c58/samples/features/Features.WPF/Views/ShellView.xaml#L10

Here's an example of attaching an event sending the source of the event (the `Frame`) to the view model.

https://github.com/Caliburn-Micro/Caliburn.Micro/blob/84edd18221243e0b3db5aa54e00680b8e6117c58/samples/features/Features.WPF/ViewModels/ShellViewModel.cs#L17
