### ISSUE TITLE
Sub navigation page cann't call OnDeactivate

### ISSUE THREAD

**Issue by yuzifu** [Caliburn-Micro/Caliburn.Micro#693]
My WPF application has a main navigation, it switches pages main1 / main2 / main3.

In page main2, it has a sub navigation,  It switches page sub1 / sub2 / sub3 in an area of page main2.

When the program leaves from the main2 page using the main navigation, the sub1 (sub2 or sub3)  page displayed on the main2 page will not call OnDeactivate(), which will cause me to have no way to release some resources of sub1.

**Comment by nigel-sampson** [comment]
It would depend a lot on whether the parent / child relationship between the view models is wired up all the way down.  

If your navigation view models such as the Shell view model and Main 2 are both conductors then they will correctly deactivate child accounts.

**Comment by a44281071** [comment]
maybe it didn't call "ActivateItem(object item)".
Please check and ensure ancestors is "Conductor". 
You can append your codes. It will be more useful to find active problem.
