### ISSUE TITLE
"The project file cannot be opened by the project system"

### ISSUE THREAD

**Issue by Aberro** [Caliburn-Micro/Caliburn.Micro#694]
In freshly installed VS2019, with freshly downloaded caliburn.micro repo, after opening solution 3 out of 4 projects can't load with same message 
> error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

And also there's another message: 
```Project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\16.0\Bin\Microsoft.CSharp.targets" was not imported by "C:\Program Files\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" at (37,3), due to the file not existing.```

That single loaded project doesn't build with message:
```>C:\Program Files\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(37,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\16.0\Bin\Microsoft.CSharp.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\16.0\Bin\Microsoft.CSharp.targets" is correct, and that the file exists on disk.```

**Comment by Aberro** [comment]
With dotPeek being unable to decompile Caliburn.Micro.Platforms.UWP for whatever reason, this basically makes Caliburn.Micro framework undebuggable and hense unusable.

**Comment by nigel-sampson** [comment]
Do you have the `3.1.201` SDK installed on your machine?

**Comment by Aberro** [comment]
No. I didn't knew I have to (though I guessed it, but still I didn't knew which version). Also, both https://caliburnmicro.com/ and github documentations lack information about dependencies.

**Comment by nigel-sampson** [comment]
Did installing the SDK resolve the error?

**Comment by nigel-sampson** [comment]
Yes the documentation is very out of date due to massive lack of time on my part.

**Comment by Aberro** [comment]
No, now it lacks MSBuild 16.0...

Project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\16.0\Bin\Microsoft.CSharp.targets" was not imported by "C:\Program Files\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" at (37,3), due to the file not existing.

**Comment by nigel-sampson** [comment]
Odd, would assume that would be installed Visual Studio 2019.

**Comment by Aberro** [comment]
I've read that yes, VS2019 should install MSBuild 16, but still, I've reinstalled windows this sunday (and update Visual Studio today). I'm trying to figure out how's that.

**Comment by Aberro** [comment]
This doesn't help: https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019

**Comment by Aberro** [comment]
Found it. TargetFramework net45 makes project unloadable. I don't know why though.

**Comment by nigel-sampson** [comment]
Most likely you'll need the .NET 4.5 targeting pack.

**Comment by Aberro** [comment]
Still, though, it's not building, specifically because it can't find uap target framework.

**Comment by Aberro** [comment]
Can I get list of requirements? What should I install? I've already installed all SDK's in visual studio installer, with no luck.
How to build this project?

**Comment by Aberro** [comment]
global.json. 
That's it.
I've only had to update "MSBuild.Sdk.Extras" to latest version "2.0.54" and everything loaded and builded (except for android platform, for which I needed to install sdk by VS integrated manager) 
I guess you need to update it in repository.

**Comment by Aberro** [comment]
Ah, I should've fork tagged branch, that's the reason for all the pain and suffering...
Could you please update description with note about tags?
