### ISSUE TITLE
feature request: add a registration and unregistration events to SimpleContainer and IoC.

### ISSUE THREAD

**Issue by Aberro** [Caliburn-Micro/Caliburn.Micro#695]
I'm sure that'll be quite easy and would allow scenarios with waiting services availability.

**Comment by mvermef** [comment]
SimpleContainer doesn't deal with events... What cases would this beneficial?

**Comment by Aberro** [comment]
It does "Activated" event on building an instance. 
These events are quite similar, but for registration and unregistration of services. 
I've been using mine implementation in fork (it wasn't as simple as I've initially though, but it take me ~15 minutes to implement) so I can react on new IoC services and await specific services availability in other services, especially singletons and single instances.

**Comment by nigel-sampson** [comment]
`SimpleContainer` was designed to be a simple stand in replacement for people wanting to do dependency injection without requiring a framework.

The intention is that if there were times when people wanted more complex behavior then I'd suggest using a fully fledged DI container such as Autofac.
