### ISSUE TITLE
.Net Standard Xamarin Forms

### ISSUE THREAD

**Issue by BicycleMark** [Caliburn-Micro/Caliburn.Micro#696]
I am new to Caliburn. I worked on other Xamarin Forms projects using Prism and we would always use .Net Standard over there. Is there a .Net Standard build ready in NuGet? I am reading some documentation around that leads me to believe we are stuck on PCL for the time being.

Kind Regards,
Mark Wardell

**Comment by nigel-sampson** [comment]
The new alpha builds and the ones my MyGet use .NET standard instead of PCL.
