### ISSUE TITLE
Navigating to a view help

### ISSUE THREAD

**Issue by Motoky** [Caliburn-Micro/Caliburn.Micro#701]
I currently have a TabbedPage up and running. The first page contains a ListView of ViewModels, which displays information, along with a little menu button. When I click the menu button to whichever of the corresponding items in the list, it should navigate to a new ContentPage with the information of that selected item along with some buttons to perform some actions with that information.

I get can get the new view to display by calling NavigateToViewModelAsync, but it's like it's not binding the viewmodel to it. I've tested this by putting some dummy information into the view and it displays it, but it won't display anything that's in the viewmodel.

```
<ListView x:Name="listView" Grid.Column="1" ItemsSource="{Binding SongViewModels}" Grid.Row="1">
                <d:ListView.ItemsSource>
                    <x:Array Type="{x:Type x:String}">
                        <x:String>Song Name</x:String>
                        <x:String>Song Name</x:String>
                        <x:String>Song Name</x:String>
                        <x:String>Song Name</x:String>
                    </x:Array>
                </d:ListView.ItemsSource>
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <Grid>
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="*"/>
                                    <RowDefinition Height="1*"/>
                                </Grid.RowDefinitions>

                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="*"/>
                                    <ColumnDefinition Width="*"/>
                                </Grid.ColumnDefinitions>

                                <view:SongView cm:View.Model="{Binding ActiveItem}"/>
                                <Image Source="menu.png" HeightRequest="20" HorizontalOptions="End" Grid.Column="1" Grid.RowSpan="2">
                                    <Image.GestureRecognizers>
                                        <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" NumberOfTapsRequired="1" CommandParameter="{Binding .}"/>
                                    </Image.GestureRecognizers>
                                </Image>
                            </Grid>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>

```

**Comment by nigel-sampson** [comment]
I'm not sure what the sample code here is supposed to represent?

**Comment by Motoky** [comment]
Sorry, I posted it quite quickly before I left. So this ListView is inside a Content View. It contains a list of Viewmodels that represent songs. The image is a menu button that once pressed should navigate to that corresponding viewmodel by calling NavigateToViewModelAsync<SongViewModel>().

The SongView gets displayed once I navigate, but none of the binding actually work on the new page. It definitely works because the list of Viewmodels in code above display all of the correct information.

Just wondering if there is a problem with the navigation service and the viewmodel binding functionality, or am I just doing it wrong?

**Comment by nigel-sampson** [comment]
Is the song view model correctly being instantiated?

**Comment by Motoky** [comment]
It doesn't get instantiated at all. The corresponding view opens for it because I have a button on the content page which appears, but none of the bindings work because it's like it's not binding the viewmodel.

**Comment by nigel-sampson** [comment]
Is the SongViewModel registered with the DI container? If its not being created that could be the reason.

**Comment by Motoky** [comment]
Ooo, in the App class? I'll take a look at that and will get back to you.

**Comment by Motoky** [comment]
So after testing, reading some of the exceptions and such, I've managed to fix the problem and get it working.

```
private void TapGestureRecognizer_Tapped(object sender, EventArgs e)
        {
            var tappedEvent = e as TappedEventArgs;

            IoC.Get<IEventAggregator>().PublishOnCurrentThread(new SongMenuButtonEvent(tappedEvent.Parameter));
        }
```

The parameter in the TappedEventArgs object is a Song object.

```
```
public async void Handle(SongMenuButtonEvent message)
        {
            IoC.Get<SongDetailsViewModel>().SetSong(message.Song);
            await m_navigation.NavigateToViewModelAsync<SongDetailsViewModel>();
        }
```

This is the function will handle that published event. I set the new song by passing it into the instance I registered to the DI container.

The problem I was running into was the fact my event Handler wasn't an asynchronous method and I wasn't awaiting on the NavigateToViewModelAsync. I was trying to calling it synchronously. So make sure you don't do that. Also make sure when you publish the event that it's on the current thread. I think this was why it couldn't find bind my ViewModel to the View because they were on different threads. I'm still new to asynchronous programming and learning about threads.

Hopefully if someone comes across this, they might be able to fix their issues with navigation if they have the same problems as I did.

**Comment by nigel-sampson** [comment]
Interesting. Glad you solved it/
