### ISSUE TITLE
ListViewItem's context menu does not capture the correct data context

### ISSUE THREAD

**Issue by noctis0430** [Caliburn-Micro/Caliburn.Micro#703]
Caliburn Micro (v4.0.131-beta) does not seems to capture the correct data context when triggered from the context menu item of `ListViewItem`.

E.g. when first right click on a `ListViewItem`, data context is captured correctly. However, subsequent right-clicking on other `ListViewItem` does not seems to capture the data context corresponding to the item. Instead, it 'stick' to the data context of the first right-clicked `ListViewItem`.

![caliburn micro](https://user-images.githubusercontent.com/29354176/84044008-8efa7f00-a9d9-11ea-9cae-608365e35545.gif)

This does not occur when `RelayCommand` [(MVVM Light)](http://www.mvvmlight.net) is used.

![mvvm light](https://user-images.githubusercontent.com/29354176/84044430-25c73b80-a9da-11ea-9710-d37ecec67af1.gif)

The XAML

```xaml
<ListView x:Name="CTRL_ListView" DockPanel.Dock="Right" ItemsSource="{Binding Robots}" DisplayMemberPath="ID">
  <ListView.Resources>
    <Style TargetType="ListViewItem">
      <Setter Property="ContextMenu">
        <Setter.Value>
          <ContextMenu>
            <MenuItem Header="Caliburn Micro">
              <MenuItem Header="Command 1" cal:Message.Attach="[Event Click] = [Action CaliburnCommand1]"/>
              <MenuItem Header="Command 2" cal:Message.Attach="[Event Click] = [Action CaliburnCommand2]"/>
            </MenuItem>
            <MenuItem Header="MVVM Light">
              <MenuItem Header="Command 1" Command="{Binding RelayCommand1}"/>
              <MenuItem Header="Command 2" Command="{Binding RelayCommand2}"/>
            </MenuItem>
          </ContextMenu>
        </Setter.Value>
      </Setter>
    </Style>
  </ListView.Resources>
</ListView>
```

The model
```c#
public class Robot
{
    // Properties.
    public Action<string> SetMessage
    {
        get;
        set;
    }
    // Binding Properties.
    public string ID
    {
        get;
        private set;
    }
    public RelayCommand RelayCommand1
    {
        get;
        set;
    }
    public RelayCommand RelayCommand2
    {
        get;
        set;
    }
    // Methods.
    private void Command1()
    {
        SetMessage($"{ID}: {nameof(Command1)}");
    }
    private void Command2()
    {
        SetMessage($"{ID}: {nameof(Command2)}");
    }
    // Binding Methods.
    public void CaliburnCommand1()
    {
        Command1();
    }
    public void CaliburnCommand2()
    {
        Command2();
    }
    // ctor.
    public Robot(int id)
    {
        ID = $"Robot {id}";
        RelayCommand1 = new RelayCommand(Command1);
        RelayCommand2 = new RelayCommand(Command2);
    }
}
```
Full source code for the repro.
[repro.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/4746688/repro.zip)

**Comment by nigel-sampson** [comment]
What's happening here is that CM is walking the visual tree to find the action target. I suspect the way the `ListView` is templated means that it doesn't find it.

You should be able to set `Action.TargetWithoutContext="{Binding}`` on the `Context Menu.

**Comment by noctis0430** [comment]
Thanks for the response.

I have tried to set `Action.TargetWithoutContext="{Binding}` on the `ContextMenu` but it does not resolve the issue. 

It look's like the context 'stick' to the corresponding `ListViewItem` when the context menu is first loaded. Right-clicking other `ListViewItem` does not update to correct context.

Instead, setting `Action.TargetWithoutContext="{Binding DataContext, RelativeSource={RelativeSource Mode=Self}}"` to the `MenuItem` seems to force CM to update the context when right-clicking other `ListViewItem`.

```xaml
<ContextMenu>
  <MenuItem Header="Caliburn Micro">
    <MenuItem Header="Command 1" 
              cal:Action.TargetWithoutContext="{Binding DataContext, RelativeSource={RelativeSource Mode=Self}}"
              cal:Message.Attach="[Event Click] = [Action CaliburnCommand1]"/>
    <MenuItem Header="Command 2" 
              cal:Action.TargetWithoutContext="{Binding DataContext, RelativeSource={RelativeSource Mode=Self}}"
              cal:Message.Attach="[Event Click] = [Action CaliburnCommand2]"/>
  </MenuItem>

...
</ContextMenu>
```
This seems to fix the issue.
