### ISSUE TITLE
Merge Stylet Project?

### ISSUE THREAD

**Issue by a44281071** [Caliburn-Micro/Caliburn.Micro#706]
canton7/Stylet
It have some good Implementation. You two can make time to talk.
I realy like ActionExtension. It is awesome!

Like: 
- Stylet/Stylet/ConductorNavigating.cs
- Stylet/Stylet/Xaml/ActionExtension.cs

**Comment by nigel-sampson** [comment]
Links don't seem to work.

**Comment by beachwalker** [comment]
https://github.com/canton7/stylet/

I think he means:

https://github.com/canton7/Stylet/blob/master/Stylet/Conductor.cs

https://github.com/canton7/Stylet/blob/master/Stylet/Xaml/ActionExtension.cs

Personally, I find more interesting that they added validation through FluentValidation.

**Comment by nigel-sampson** [comment]
Very cool, I'd think I'd merge it in, but its very cool.

**Comment by a44281071** [comment]
DevExpress have same solution, more powerful! 
```xaml
<TextBlock x:Name="tb" Text="text"/>
<Button Content="OK" Loaded="{DXEvent Handler='Initialize(@sender.Content, @args, @e(tb).Text)'}"/>
```
https://docs.devexpress.com/WPF/115777/mvvm-framework/dxbinding/language-specification
