### ISSUE TITLE
Unknown Attachable member View.Model UWP

### ISSUE THREAD

**Issue by antmurph** [Caliburn-Micro/Caliburn.Micro#710]
v4.0.136-rc
UWP min 17763 target 18362

I have a View Model first App, I would like to bind a Content Control to a view model but I get "Unknown attachable member 'View.Model' on element 'ContentControl' "

`xmlns:cal="clr-namespace:Caliburn.Micro;assembly=Caliburn.Micro.Platform"`

`<ContentControl cal:View.Model="{Binding StatusDetailViewModel}" />`

Ive had nothing but success with Caliburn, Great work on this. Hopefully this is something simple I missed.

**Comment by nigel-sampson** [comment]
My understanding was the namespace syntax in UWP is `xmlns:cm="using:Caliburn.Micro"`.

**Comment by antmurph** [comment]
@nigel-sampson That worked, I knew it must be something incredibly simple. Closing this.
