### ISSUE TITLE
[propose Help Wanted] Correct way to create an instance that "persists"?

### ISSUE THREAD

**Issue by zlittell** [Caliburn-Micro/Caliburn.Micro#711]
I am not really a high level object oriented programmer, so I have been struggling through an app.  It has been fun to learn though, and it has been a lot of learning.

I am at a point where I want to create a helper class that would always exist, this would capture events from the aggregator and parse them into a model.

My problem is that I registered the instance and it just never instantiates it. I can put a breakpoint in the constructor of the helper and it never breaks. If I register the helper as a singleton and then pass it in the constructor of my main view model it works fine because it seems something is requesting it from the container and then the container creates it finally. I thought registering instances provided this functionality over singletons, but I must be mistaken.  Is this the correct way to handle this or is there some better way? My main view model never touches the helper, it is just supposed to sit in the background and catch events, so passing it in the constructor seems silly.

-Zack-

**Comment by zlittell** [comment]
More info:

When I initially made this I was using an instance registration command that looked like this:
`this.container.RegisterInstance(typeof(DeviceHelper), typeof(DeviceHelper).ToString(), typeof(DeviceHelper));`
Which is definitely why it wasn't breaking in the constructor.

I have now switched to trying to do this
'this.container.RegisterInstance(typeof(DeviceHelper), typeof(DeviceHelper).ToString(), new DeviceHelper());'

But my problem is that I inject dependencies into the constructor of DeviceHelper.  It complains that I am not providing the parameters required.
'public DeviceHelper(IEventAggregator aggregator, DeviceModel model)'

**Comment by nigel-sampson** [comment]
Sounds like you want to use `Singleton`.

**Comment by zlittell** [comment]
I can see how a singleton would work better because I only ever want one, but the singleton isn't created until called.  What would be the preferred method of causing the singleton instance to be created in the bootstrapper so that it runs in the background of the app constantly.

**Comment by nigel-sampson** [comment]
I would probably just resolve the singleton from the container at startup to ensure its creation.

**Comment by zlittell** [comment]
So I set this up when I got home. Just added a section to the configure function that calls this.container.GetInstance<DeviceHelper>() and another one that I wouldn't mind having the app setup right away and not rely on the viewmodel to request it.

Feel dumb after I have it all working, but thank you for all the explanations.
