### ISSUE TITLE
UWP adding the package

### ISSUE THREAD

**Issue by Jymms** [Caliburn-Micro/Caliburn.Micro#714]
When I try to add Caliburn.Micro to a VS 2019 Version 16.6.3 I get the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Expected "!$([System.String]::new('%(ReferenceCopyLocalPaths.Identity)').EndsWith('System.Runtime.dll'))" to evaluate to a boolean instead of "!$([System.String]::new('C:\Users\Jym's Laptop\.nuget\packages\caliburn.micro.core\4.0.136-rc\lib\uap10.0.16299\Caliburn.Micro.Core.dll').EndsWith('System.Runtime.dll'))", in condition "'$(_CoreFrameworkPackageId)' != ''
                 AND !$([System.String]::new('%(ReferenceCopyLocalPaths.Identity)').EndsWith('System.Runtime.dll'))
                 AND '%(ReferenceCopyLocalPaths.NuGetPackageId)' == '$(_CoreFrameworkPackageId)'".	TestUniversal			

As a beginner I have absolutely no clue what it means.  It doesn't happen with WPF apps just UWP, same with the 'full' package instead of just the .core

**Comment by vb2ae** [comment]
Open the UWP projects properties and make sure the min version of UWP supported is Windows 10 Fall Creators Update

![image](https://user-images.githubusercontent.com/1483513/92914873-09340880-f3fa-11ea-8fe5-3b117c3d1e92.png)

**Comment by Jymms** [comment]
Thanks, I'll give that a try.
