### ISSUE TITLE
BindingScope.cs null exception occurred

### ISSUE THREAD

**Issue by s2quake** [Caliburn-Micro/Caliburn.Micro#716]
The figure below is an exception from my project. 

I don't know why there is a null entry in the queue variable, but that causes an exception.

Occurs when creating a DialogWindow using WindowManager.

DialogWindow is a class that I created.

If there is not enough information to solve the problem, I will let you know the source address through github. Thank you.

caliburn version: 4.0.105-alpha
targetframework: netcoreapp3.1

![image](https://user-images.githubusercontent.com/887680/89637436-22bacf80-d8e5-11ea-9308-f8d740cf460d.png)
![image](https://user-images.githubusercontent.com/887680/89637483-336b4580-d8e5-11ea-933e-11829c8d8cfa.png)

**Comment by mvermef** [comment]
so I am on the correct repository what is the address for it and were you using a container for DI?  Since you are using the Alpha of this CM for core 3.1... any legacy code you using from really old versions of CM?

**Comment by KasperSK** [comment]
This can be closed it was fixed by #723.
