### ISSUE TITLE
ContentControl ActivateItemAsync .NET Core

### ISSUE THREAD

**Issue by AcidRaZor** [Caliburn-Micro/Caliburn.Micro#718]
I'm having some difficulty with Caliburn not picking up the ContentControl. I've tried using x:Name="ActivateItem" and x:Name="ActivateItemAsync" but neither works when I call await ActivateItemAsync and use the IoC to get the ViewModel

Everything is setup correctly as far as I'm aware. I've been working on a new .NET Core project, the only part I need to finish now is the ContentControl navigation between UserControls

**Comment by mbreckon** [comment]
I think that should be ActiveItem.

**Comment by AcidRaZor** [comment]
Yup, tried that. I even have my navigation happen on Shell using event aggregators and everything gets called, except when ActivateItemAsync runs, it doesnt change the ContentControl. (There is no ActivateItem for the .net core 3 implementation if that is what you were referring to)

**Comment by CoreyVincent** [comment]
ActiveItem works for me.

View:
`<ContentControl x:Name="ActiveItem" />`
ViewModel:

```
public ShellViewModel()
{
    ActivateItemAsync(new MainViewModel())
}
```

**Comment by AcidRaZor** [comment]
@CoreyVincent My mistake was using ActivateItem as the name for the content control, not ActiveItem. Thanks so much for your input with code example. Otherwise I would not have realized my mistake.
