### ISSUE TITLE
[Proposal] Restore the Caliburn.Micro.Xamarin.Forms NuGet package to enable XF on platforms other than iOS and Android

### ISSUE THREAD

**Issue by KasperSK** [Caliburn-Micro/Caliburn.Micro#724]
I would like to propose that we restore the `Caliburn.Micro.Xamarin.Forms` NuGet package as it was available in `3.2.0` and also in the first `4.0.0` alpha. 

My understanding as to why the package was removed was that the new SDK project model did not allow for including internal .dll's in a NuGet package. One Project = One Package with one dll (#707). 

However, I have looked into it and with some MSBuild tinkering it is possible to include an internal dll I have made an implementation in [My Fork](https://github.com/KasperSK/Caliburn.Micro)  on the master branch that demonstrates how we could restore the XF package this includes a SDK project dedicated to build the XF package but using linked files from the platform project. 

This is a breaking change so I would like to hear how you feel about this?

 @nigel-sampson, @vb2ae, @mbreckon, @CoreyVincent

**Comment by CoreyVincent** [comment]
@KasperSK Sounds good to me.

**Comment by vb2ae** [comment]
I am not opposed to doing that.  I do need to look at the code a little more to see if there is a way to get it to work by platform

**Comment by KasperSK** [comment]
@vb2ae The reason I like the Xamarin.Forms package is that it gels nicely with the notion that Xamarin.Forms is an overlay onto a platform. The other way to do it would be to have every platform also depend on Xamarin.Forms, and i do not like that idea. By having the Caliburn.Micro.Xamarin.Forms package you can choose whether you want just Caliburn.Micro or Caliburn.Micro with Xamarin.Forms.

**Comment by KasperSK** [comment]
@nigel-sampson I think you are right about thinking a bit ahead with regards to MAUI from what I have seen so far they have been talking about multi targeting. In the blog posts there has been screenshots with a project file containing a TargetFrameworks tag with values such as `net5.0` , `net5.0-ios` and `net5.0-android` which leads me to believe that we can still use target framework in the future.

For now I still think the XF package makes sense but for MAUI i think we will have to wait for the previews to see how to move forwards. But I think that it will be a new major version of Caliburn.Micro when MAUI arrives.

**Comment by vb2ae** [comment]
@KasperSK  Since UWP supports .net standard 2.0 I am looking to see if we can use it for UWP and UWP Xamarin Forms.    I do realize there are probably some breaking changes if we do that.  Not ruling out making the Xamarin forms package

**Comment by KasperSK** [comment]
@vb2ae How would that work when installing `Caliburn.Micro` into a UWP project? Would we not need to install it as `UWP` and `netstandard2.0`?

**Comment by vb2ae** [comment]
Caliburn.Micro would have to install net standard 2 package for UWP.  have to look up if it is possible to do dependencies by platform

**Comment by KasperSK** [comment]
But what if I want to run UWP without XF would that still be possible?

**Comment by vb2ae** [comment]
looks like my idea wont work.  I your package is the best option for now

**Comment by vb2ae** [comment]
you should create a pull request for this.

**Comment by KasperSK** [comment]
I will how do you guys fell about only supporting `net461` and not `net45`?

 It is because i made the core package `netstandard2.0` and the lowest framework version that is supported is `net461`.

**Comment by vb2ae** [comment]
I am fine with that.
