### ISSUE TITLE
Potential Issue with ObservableCollection and marshalling to the UI thread from a worker thread?

### ISSUE THREAD

**Issue by Pete-Magsig** [Caliburn-Micro/Caliburn.Micro#729]
I have an application with a tab control. Each tab represents a list of patient studies from a different source, a file system or remote imaging server. These view model sources all access their data by making worker thread calls into a web API, a DICOM API, or a file system API. These APIs do the fetch in the background and return the results on a worker thread through an event callback.

Each tab View Model inherits from Screen. It offers several string status fields and an ObservableCollection of patient data objects which themselves inherit from PropertyChangedBase, which are bound to a DataGrid. The number of patient objects is bounded to 200 on an individual fetch.

When the system starts up, the container view model is given a list of view models, one for each tab. That list binds to a TabControl, which in turn will bind the first visible tab to the first tab view model in the list (to a TabItem). Those tabs start prefetching their data before their view is attached. If, on the first tab - the one shown by default - attaches before the data gets back from these worker threads, all is well. If the thread beats or coincides view loaded, the app UI can lock up hard while updating the ObservableCollection.

I've read that NotifyOfPropertyChange() should marshall all updates to the UI thread, so I just assumed that I could update my view properties and the ObservableCollection from the worker thread without having to wrap it in an OnUIThread(() =>  {}) call. 

Is calling NotifyOfPropertyChange() or updating ObservableCollection from a worker thread bad practice? Or should I be wrapping all of this callback code in OnUIThread()?

Wrapping the event callback code from the worker thread in an OnUIThread() solved the problem.

There's nothing fancy in my controls or how I set up or use my bindings. I prefer to use Caliburn for the clarity it brings to my code. I avoid complex customization.

Again, the timing is the issue. If the view has attached before the worker threads are pumping data into the models everything is fine, but if the view attaches afterwards (or during), it locks up. I can see that OnViewAttached() gets called but OnViewLoaded() does not before the lockup occurs. 

My theory is that the UI thread locks up when the view is loading. I was assuming that NotifyOfPropertyChange() would reconcile against a view loading simultaneously. Am I wrong? Or should this work and there is something wrong with ObservableCollection or NotifyOfPropertyChanged()?

I guess the bigger question is: Does the NotifyOfPropertyChange() UI marshalling only work after the view is attached, or can there be problems if it is called from an outside thread during view loading?

**Comment by snalesso** [comment]
[`ObservableCollection<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.observablecollection-1) is not thread safe, you should use [`BindableCollection`](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Core/BindableCollection.cs).

**Comment by Pete-Magsig** [comment]
So, Best Practice is to use BindableCollection when you expose a collection to a View from a ViewModel. I went through my code and it turns out I was generally already using BindableCollection, but not consistently. This really sent me down the rabbit hole. Thank you so much. 

(If there's ever a time I wanted a smack-my-head emoji, this is it.)

**Comment by snalesso** [comment]
Glad to be helpful 🙂
