### ISSUE TITLE
Add .net 5 support for Xamarin

### ISSUE THREAD

**Issue by vb2ae** [Caliburn-Micro/Caliburn.Micro#732]
Add .net 5 support for Xamarin. iOS and Xamarin.Android

**Comment by Mrxx99** [comment]
I thought Xamarin does not support .Net 5? At least not until it supports .Net 6 next year

**Comment by vb2ae** [comment]
Looks like you are right.  I was thinking net5.0-android and net5.0-iOS would work with Xamarin.Forms but it is not supported
