### ISSUE TITLE
Navigate to another viewmodel inside OnActivateAsync

### ISSUE THREAD

**Issue by enrico-padovani** [Caliburn-Micro/Caliburn.Micro#752]
I have a frame based WPF application (.Net Framework 4.8) when I try to navigate inside OnActivateAsync method Caliburn does not call OnDeactivateAsync. Then when I'm activating the viewmodel again OnActivateAsync  does not fire.

I'm using CM 4.0.136-rc

I use `_navigationService.For<MyViewModel>().Navigate();`

to solve the problem (as a workaround) I've created an extension which execute then navigation in a task.

```
public static void NavigateOnActivate<TViewModel>(this NavigationHelper<TViewModel> navigationHelper)
{
    _ = Task.Run(() =>
    {
        Thread.Sleep(400);
	Execute.OnUIThread(() =>
	{
	    navigationHelper.Navigate();
	});
    });			
}
```
I this a bug or I'm using it in a wrong way?

Thanks!

**Comment by vb2ae** [comment]
In Caliburn.Micro after your custom code runs in OnActivateAsync the view is marked as Active.  When the screen is closing OnDeactivateAsync is only called if the screen is marked as active.  If you navigate away before the your OnActivateAsync code is done running your view will never be marked as Active and your OnDeactivateAsync wont be called

**Comment by enrico-padovani** [comment]
Ok, thanks for the explanation. Do you see any issue / unexpected change in update CM from 4.0.136-rc to the latest?

**Comment by vb2ae** [comment]
Nothing that will affect wpf apps

**Comment by enrico-padovani** [comment]
Ok, I'm closing this
