### ISSUE TITLE
EventAggregator/PublishAsync cancellationToken is not working

### ISSUE THREAD

**Issue by Tell0r** [Caliburn-Micro/Caliburn.Micro#756]
I tried to use the cancellationToken, with the EventAggregator/PublishAsync function.
But it has no use at all.
The function gets a parameter cancellationToken:
https://github.com/Caliburn-Micro/Caliburn.Micro/blob/d7fe18a863f778eaf235dab7ea72c6282345e62a/src/Caliburn.Micro.Core/EventAggregator.cs#L68

But it does not pass it on:
https://github.com/Caliburn-Micro/Caliburn.Micro/blob/d7fe18a863f778eaf235dab7ea72c6282345e62a/src/Caliburn.Micro.Core/EventAggregator.cs#L91

In general I am not sure about the design. Cancellation Token could also be just part of "object message" and not be defined in the function signature.

**Comment by KasperSK** [comment]
Good catch I think we should pass the cancellation token along.
