### ISSUE TITLE
Unable to display root view by passing the type as a non-generic parameter

### ISSUE THREAD

**Issue by godrose** [Caliburn-Micro/Caliburn.Micro#760]
First of all, huge thanks for releasing this version.
I noticed few breaking changes.

`DisplayRootViewFor` now requires generic parameter of type instead of a regular one.
Please support this ability too.

**Comment by vb2ae** [comment]
Not exactly sure what you mean by a regular one.  Could you post a code sample of what you would like to work?

**Comment by godrose** [comment]
`DisplayRootViewFor(Type rootObjectType)`
as opposed to
`DisplayRootViewFor<TRootObject>()`

**Comment by KasperSK** [comment]
#761 Fixes this but renames the method to follow the async theme.
