### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by RudolfJan** [Caliburn-Micro/Caliburn.Micro#767]
In issue [https://github.com/Caliburn-Micro/Caliburn.Micro/issues/766] one of the items to create a tutorial for migration of existing (WPF) projects to Caliburn.Micro. I did a small experiment with an existing project, and it turns out getting started is far more easy than I anticipated. I could setup Caliburn.Micro in a few hours. This enables a gradual migration.  I describe the steps very briefly till I have time to create the full tutorial:

Import the Calburn.Micro Nuget package
Create the Bootstrapper class
Add folders for Views, ViewModels and Models to the project
Optionally: rename MainWindow.xaml to ShellView.xaml and move it to the Views folder
Create the ShellViewModel class
Edit the app.xaml file to support the Caliburn.Micro startup sequence.

After this step, in principle the application should be able to run. Of course, you only got the startup procedure, but you have the core changes in place now.

For this project I used a programming style using separate windows, not user controls. Of course, depending on the project you may encounter issues, but this helps to do the migration gradually. At least it is worth a try and will cost a few hours only for a medium sized application.

The next part may be harder, to update every individual window or user control.  But, in part it is possible to start preparing the project before actually switching to use Caliburn.Micro.  This part needs a more extensive steps be written down. I will add this later to this issue.

**EDIT:**

I did some thinking and spent some time into looking at the available material.  This caused me to change my mind a bit and see the migration part of the tutorial more as an integral part of it. I am not yet sure where the tutorial should end exactly. At the moment I experience some problems with compiling all source code, probably because I miss some installer options for Visual Studio.

I would like to start, by giving a little amount of background and by telling you do not yet need to jump full swing into Caliburn.Micro, but it should be helpful to use some MVVM basics if you intend to do. This nicely gives an introduction strategy as well. So a rough outline:

1. Why  and when to use MVVN patters and Caliburn.Micro, introducing to the option to start gradually
2. Project setup from scratch (not using a project template)
3. Demo application, not yet decided but it will be something like an address book or expenses tool with very simple storage.
4. First step, single user control in a window
5. Adding a second user control
6. Adding a menu, make the ShellViewModel controlling the applications
7. Adding a window manager
8.  From here I will see what fits, I think event messages should be covered at leats.

**Comment by vb2ae** [comment]
Which frameworks are you going to include in the guide?

**Comment by RudolfJan** [comment]
I will start with .Net Core3.1, WPF and VisualStudio 2019, from there we can see if it can be extended to other combinations, but this is what I am familiar with. I opened some issues, that makes it easier to discuss this topic.
 
Van: Ken Tucker ***@***.***> 
Verzonden: zondag 27 juni 2021 00:14
Aan: Caliburn-Micro/Caliburn.Micro ***@***.***>
CC: RudolfJan ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Caliburn-Micro/Caliburn.Micro] Migration tutorial (#767)
 
Which frameworks are you going to include in the guide?
