### ISSUE TITLE
Publish project won´t show shell view

### ISSUE THREAD

**Issue by lgund** [Caliburn-Micro/Caliburn.Micro#770]
### Description
------
If I start the project in the release or debug mode everything works fine. Even if I start it without visual studio. But for some reason after publish the project I don´t see the main view (ShellView). But the application create her database file and is as process in the task manager alive. I am not even sure if it´s a problem from Caliburn.Micro but cause all other stuff looks like it works I create here the issue. Maybe this problem is known here.
Cause I don´t get any warnings or errors I don´t know which source you want to see so I will post some. If some code is missing let it me know.

### Publish settings
--------

- Target framework: .net5
- Deployment mode: Self-contained
- Target runtime: win-x64

- [x] Produce single file
- [ ]  Enable ReadyToRun compilation

### Source Code
-------

#### Bootstraper.cs
```
using Caliburn.Micro;
using GCS.Db;
using GCS.Navigation;
using GCS.Repositorys;
using GCS.ViewModels;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;

namespace GCS
{
    public class Bootstrapper : BootstrapperBase
    {
        private SimpleContainer container = new SimpleContainer();
        private DbApplicationContext dbApplicationContext;

        public Bootstrapper()
        {
            Initialize();
        }

        protected override void Configure()
        {
            var options = new DbContextOptionsBuilder<DbApplicationContext>().Options;
            dbApplicationContext = new DbApplicationContext(options);

            container.Instance(container);
            container
                .Singleton<ShellViewModel, ShellViewModel>()
                .Singleton<INavigator, MyApplicationNavigator>()
                .Singleton<IEventAggregator, EventAggregator>()
                .Singleton<IWindowManager, WindowManager>()
                .Singleton<IEventAggregator, EventAggregator>();

            container.Instance(dbApplicationContext);
            container
                .PerRequest<IGcsRepository, GcsRepository>()
                .PerRequest<ITestRepository, TestRepository>();

            GetType().Assembly.GetTypes()
                .Where(type => type.IsClass)
                .Where(type => type.Name.EndsWith("ViewModel"))
                .ToList()
                .ForEach(viewModelType => container.RegisterPerRequest(
                    viewModelType, viewModelType.ToString(), viewModelType));
        }

        protected override object GetInstance(Type service, string key)
        {
            return container.GetInstance(service, key);
        }

        protected override IEnumerable<object> GetAllInstances(Type service)
        {
            return container.GetAllInstances(service);
        }

        protected override void BuildUp(object instance)
        {
            container.BuildUp(instance);
        }

        protected override void OnStartup(object sender, StartupEventArgs e)
        {
            DisplayRootViewFor<ShellViewModel>();
        }
    }
}
```

#### ShellViewModel
```
using Caliburn.Micro;
using GCS.Repositorys;
using System.Reflection;

namespace GCS.ViewModels
{
    public class ShellViewModel : Conductor<object>
    {
        private readonly IGcsRepository gcsRepository;

        /// <summary>
        /// The current application version of this tool
        /// </summary>
        private string _version = "v. " + Assembly.GetExecutingAssembly().GetName().Version.ToString();
        public string Version
        {
            get { return _version; }
        }

        /// <summary>
        /// The number of "database" tables
        /// </summary>
        private int numberOfTables;
        public int NumberOfTables
        {
            get { return numberOfTables; }
            set { 
                numberOfTables = value;
                NotifyOfPropertyChange("NumberOfTables");
            }
        }

        /// <summary>
        /// Number of table cells
        /// </summary>
        private double numberOfCells;
        public double NumberOfCells
        {
            get { return numberOfCells; }
            set { 
                numberOfCells = value;
                NotifyOfPropertyChange("NumberOfCells");
            }
        }

        public ShellViewModel(IGcsRepository gcsRepository)
        {
            this.gcsRepository = gcsRepository;

            DashboardView();
            RefreshGcsStatistik();
        }

        public void RefreshGcsStatistik()
        {
            NumberOfTables = gcsRepository.GetAllTables().Count;
            NumberOfCells = gcsRepository.GetAllContents().Count;
        }

        public void DashboardView() => ActivateItemAsync(new DashboardViewModel());
        public void GcsDatabaseView() => ActivateItemAsync(IoC.Get<GcsDatabaseViewModel>());
        public void GcsImportView() => ActivateItemAsync(IoC.Get<GcsImportViewModel>());
        public void GcsExportView() => ActivateItemAsync(new GcsExportViewModel());
        public void ImportView() => ActivateItemAsync(new InfoViewModel());
    }
}
```

**Comment by KasperSK** [comment]
Can you make a small sample that reproduces the issue so that I could have a look at it? It would be great if it was in a Github repo.

**Comment by vb2ae** [comment]
Couple of things.  I would have expected the target framework to be .net5.0-windows.

You could always add the nuget packages serlilog and serilog.sinks.file to your app and create a logger to log the caliburn micro debug messages

    class DebugLogger : ILog
    {

        private readonly Type _type;
        public DebugLogger(Type type)
        {
            _type = type;
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .WriteTo.File("myapp.txt")
                .CreateLogger();
        }

        private string CreateLogMessage(string format, params object[] args)
        {
            return string.Format("[{0}] {1}",
            DateTime.Now.ToString("o"),
            string.Format(format, args));
        }
        public void Error(Exception exception)
        {
            Log.Error(CreateLogMessage(exception.ToString()), "ERROR");
        }

        public void Info(string format, params object[] args)
        {
            Log.Information(CreateLogMessage(format, args), "INFO");
        }

        public void Warn(string format, params object[] args)
        {
            Log.Warning(CreateLogMessage(format, args), "WARN");
        }
    }

and register the logger in the bootstrapper

        public Bootstrapper()
        {
            LogManager.GetLog = type => new DebugLogger(type);
            Initialize();


Maybe the log file will show something about why the shellview is not loading

**Comment by lgund** [comment]
I tested a lot of stuff and found out it´s not this package. For some reason it work on stable releases and debug release but after publish it´s not possible to display images as `Content`. You need to change that to a `resource` and need to set the link to `/GCS;component/Assets/Image.png` where `GCS` mean the project namespace. It took me now a week to find out why no screen will be displayed. 

There is no bug in the package. Sry about that but I thought it might be something with the DisplayRoot.

**Comment by vb2ae** [comment]
Glad you figured it out.  Thanks for closing the ticket
