### ISSUE TITLE
as you asked this code work perfectly in version 3.2 and stoped working with no error at version 4.0.173

### ISSUE THREAD

**Issue by aymanawadallah-AAA** [Caliburn-Micro/Caliburn.Micro#775]
I mean by stopped that the application lanch and stay working but the ShellView window did not appear in the screen
when I add _container.Singleton<IAPIHelper, APIHelper>(); to my Simple Container

_container.Singleton<IWindowManager, WindowManager>()
        .Singleton<IEventAggregator, EventAggregator>();
shellView does not appear in my screen and when I debug by adding a breakpoint to my shellViewModel code I found that it never hite the break once delete this line it works (at least I see my shellView up into the screen the project build and run with no errors and swagger lunch with the latest Nugets

public Bootstrapper()
        {
            Initialize();
            ConventionManager.AddElementConvention<PasswordBox>(
            PasswordBoxHelper.BoundPasswordProperty,
            "Password",
            "PasswordChanged");
        }
        protected override void Configure()
        {
            _container.Instance(_container);
            _container
                .Singleton<IWindowManager, WindowManager>()
                .Singleton<IEventAggregator, EventAggregator>()
                .Singleton<IAPIHelper, APIHelper>();

            GetType().Assembly.GetTypes().
                Where(type => type.IsClass)
                .Where(type => type.Name.EndsWith("ViewModel"))
                .ToList()
                .ForEach(viewModelType => _container.RegisterPerRequest
                    (viewModelType, viewModelType.ToString(),viewModelType));
        }
        protected override void OnStartup(object sender, StartupEventArgs e)
        {
            DisplayRootViewFor<ShellViewModel>();
        }
        protected override  object GetInstance(Type service, string key)
        {
            return  _container.GetInstance(service, key);
        }
        protected override IEnumerable<object> GetAllInstances(Type service)
        {
            return _container.GetAllInstances(service);
        }
        protected override void BuildUp(object instance)
        {

**Comment by vb2ae** [comment]
what type of wpf project is this?  ie .net framework version

**Comment by vb2ae** [comment]
Try this

        protected override async void OnStartup(object sender, StartupEventArgs e)
        {
           await DisplayRootViewFor<ShellViewModel>();
        }
