### ISSUE TITLE
Possible memory leak on binding properties

### ISSUE THREAD

**Issue by to87al** [Caliburn-Micro/Caliburn.Micro#782]
Hello, I'm working on a project and I've encountered a strange problem. Lets say I have a property of type `Article` named `SelectedArticle` on both `MainWindowViewModel` and `DialogViewModel` as shown below

```
//MainWindowViewModel
public void SetQty()
{
	DialogViewModel dialogViewModel = IoC.Get<DialogViewModel>();
	dialogViewModel.SelectedArticle = this.SelectedArticle;
	if (await windowManager.ShowDialogAsync(dialogViewModel) is true)
	{
		//do something
	}
}

//DialogView.xaml
<TextBox Text="{Binding SelectedArticle.Qty}"/>
```
The problem is that both properties named `SelectedArticle` are being updated, even the one from  `MainWindowViewModel`. This shouldn't be correct. I've tested both libraries from nuget and myget on wpf .net 6 and the results are the same. Any help will be appreciated.
Thanks a lot!

**Comment by vb2ae** [comment]
This line of code tells the dialogViewModel to use the same SelectedArticle as the one in the MainViewModel.  

	dialogViewModel.SelectedArticle = this.SelectedArticle;


I would recommend that you implement the ICloneable interface on Article.  Then you could change the code to something like this.  This way you will be using a new SelectedArticle with the same values

	dialogViewModel.SelectedArticle = this.SelectedArticle..Clone() as Article;


https://docs.microsoft.com/en-us/dotnet/api/system.icloneable?view=net-6.0

**Comment by to87al** [comment]
Thanks for the swift reply @vb2ae I really appreciate it. I totally missed it that classes are reference type 🤦‍♂️. Thanks 🙏
