### ISSUE TITLE
.net Maui support

### ISSUE THREAD

**Issue by vb2ae** [Caliburn-Micro/Caliburn.Micro#783]
Add .net Maui support

**Comment by gerfen** [comment]
@vb2ae and @KasperSK Is your intention to add a package like Caliburn.Micro.Xamarin.Forms to support MAUI?  If so has there been any progress?

**Comment by KasperSK** [comment]
Hi @gerfen yes the intention is to make a Caliburn.Micro.Maui Package. As for the progress I have a version that works on Android and is currently implementing the windows version, iOS and macOS will follow that I have some code cleanup to do then I will make a PR and hopefully we can get a prerelease package out.

**Comment by felipemomm** [comment]
@vb2ae and @KasperSK Hi, any news about the support for MAUI? We are using Caliburn in two Xamarin.Forms apps, but we want to migrate them to MAUI.

From what I understood, Caliburn works for MAUI.Android, but the other platforms are still pending. One of our apps is Android only, so that's fine, but the other one also needs iOS.

Is there any timeline to support MAUI?

**Comment by vb2ae** [comment]
@felipemomm There is beta version out there that works with ios and windows also have not tested tizen.  https://www.nuget.org/packages/vb2ae.Caliburn.Micro.Maui/5.0.7-beta.gd8666d156c

**Comment by felipemomm** [comment]
Great, thanks for the update!

**Comment by KasperSK** [comment]
@felipemomm as @vb2ae said there is the beta out all ready and I think that once we finish up with Avalonia and WinUI3 we will release version 5. So if you have any feedback to the MAUI implementation we would love to hear them :)

**Comment by vb2ae** [comment]
not getting same error.  do you have the same issue with the version on myget?
https://www.myget.org/feed/caliburn-micro-builds/package/nuget/Caliburn.Micro.maui

**Comment by jmeyerworms** [comment]
Same error, new Maui projekt depends on .net 7

Restoring packages for ...
  GET https://api.nuget.org/v3-flatcontainer/caliburn.micro.core/index.json
  OK https://api.nuget.org/v3-flatcontainer/caliburn.micro.core/index.json 220ms
NU1102: Unable to find package Caliburn.Micro.Core with version (>= 5.0.7-beta.gd8666d156c)
  - Found 23 version(s) in nuget.org [ Nearest version: 4.0.212 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in C:\Program Files\dotnet\library-packs
Package restore failed. Rolling back package changes for 'DrSchuldner'.
Time Elapsed: 00:00:00.5805839
========== Finished ==========

**Comment by olliaustor** [comment]
> not getting same error. do you have the same issue with the version on myget? https://www.myget.org/feed/caliburn-micro-builds/package/nuget/Caliburn.Micro.maui

I used that link and it worked perfectly. But now we are having the same issues as @jmeyerworms. It seems that the beta version 5.0.34 beta is not available anymore. 

@vb2ae Please add 5.0.34 beta for MAUI to myget (or somewhere else) so that it can be used.

**Comment by vb2ae** [comment]
Myget was down for a day or so.  I did a new build so the package will be available on myget,   going to look at getting the package on a github feed also.
