### ISSUE TITLE
Trim extra library dependencies from Microsoft.Windows.Compatibility 

### ISSUE THREAD

**Issue by to87al** [Caliburn-Micro/Caliburn.Micro#786]
Hello,
I have a WPF project that I'm working on porting it from .net 4.8 to .net 6. I noticed that CM adds one more external library dependency to `Microsoft.Windows.Compatibility`. That library itself has more than 60 files that are added to the project making the structure very convoluted and more difficult at distribution. Is there a way to safely trim those unnecessary? Am I doing something wrong? Thanks and have a great day!

**Comment by vb2ae** [comment]
It looks like I can remove Microsoft.Windows.Compatibility from the .net 5 and .net 6 assemblies.  I will test it and push an update this weekend

**Comment by to87al** [comment]
@vb2ae Thanks checking on this! I wish you all the best!
