### ISSUE TITLE
IWindowManager change window state

### ISSUE THREAD

**Issue by Fanom2813** [Caliburn-Micro/Caliburn.Micro#807]
Hi, i'm trying to maximize my Caliburn.Micro Window but it is not working , how can i set WindowState without showWindow again in ShaellViewModel 

thank you

**Comment by vb2ae** [comment]
If ShellViewModel is the startup view model you do something like this to Maximize the form.  

       protected override void OnViewLoaded(object view)
        {
            base.OnViewLoaded(view);
            Application.Current.MainWindow.WindowState = WindowState.Maximized;
        }

**Comment by Fanom2813** [comment]
worked !
