### ISSUE TITLE
CanSayHello doesn't work view-to-VM communication from Caliburn startup documentation

### ISSUE THREAD

**Issue by EdwinCloud101** [Caliburn-Micro/Caliburn.Micro#820]
I am following the instructions here using WPF dotnet 6.0 project.
https://caliburnmicro.com/documentation/configuration

Everything works but setting the CanSayHello bool for the SayHello Command. The issue is the CanSayHello is not triggered when the textbox changes. Caliburn convention should allow that to be triggered since it has the same name with the "Can" in front of it

Edit:
it fails only for the 4.0.210 version, it works for 3.2.0. Something is broken from the last release

thanks

**Comment by KasperSK** [comment]
Does it work if you change target to `net5.0`?

**Comment by frank-taylor-pcg** [comment]
I'm also seeing this issue.  Sadly, switching to net5.0-windows didn't make a difference.

**Comment by KasperSK** [comment]
I looked into it and it seems the issue started in 4.0.194 I will return when I know why.
