### ISSUE TITLE
Server Not Found

### ISSUE THREAD

**Issue by Brandagot** [Caliburn-Micro/Caliburn.Micro#823]
In Caliburn-Micro/Caliburn.Micro/tree/master/samples/tutorals/WPF/Wpf.Tutorial

The below link produces a Server Not Found page.
"[WPF Tutorial text contents page](https://www.caliburn.micro/documentation//Tutorials/wpf/Contents)"

Occurs even with the extra / removed.

**Comment by vb2ae** [comment]
fixed
