### ISSUE TITLE
Broken WPF tutorial link on website

### ISSUE THREAD

**Issue by Brandagot** [Caliburn-Micro/Caliburn.Micro#827]
On [the website](https://caliburnmicro.com), the link on the [documentation page](https://caliburnmicro.com/documentation/) to [WPF Tutorial](https://caliburnmicro.com/documentation/Tutorials/wpf/Contents) returns a 404 error.

Like in issue #823, this link can probably be corrected to https://caliburnmicro.com/documentation/Tutorials/WPF/Introduction

**Comment by KasperSK** [comment]
Thanks for lettings us know this, I have updated the link cheers!
