### ISSUE TITLE
Broken Tutorial code link on the website

### ISSUE THREAD

**Issue by Brandagot** [Caliburn-Micro/Caliburn.Micro#828]
Sorry for another broken link issue.

In the [Tutorial Contents page](https://caliburnmicro.com/documentation/Tutorials/WPF/Contents) there is a link to [Tutorial code](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/samples/tutorials/wpf/wpf.tutorial) that returns a Github 404 page.

The following link works fine.
https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/samples/tutorals/WPF/Wpf.Tutorial

**Comment by vb2ae** [comment]
fixed
