### ISSUE TITLE
IsVisibleChanged not attched to viewmodel method at UserControl message attach

### ISSUE THREAD

**Issue by mrtnbrst** [Caliburn-Micro/Caliburn.Micro#830]
I am facing the same issue as the user in this [stackoverflow post](https://stackoverflow.com/questions/57607841/caliburnmicro-isvisiblechanged-does-not-fire) - any solution / workaround?

The attached method is not called when the IsVisibleChanged event fires. The event actually is raised as I checked with an event handler in the code behind file.

**Comment by KasperSK** [comment]
I wrote an answer on stackoverflow. But to make a short story of it is that IsVisibleChanged is a CLR event and not a routed event. I would suggest binding to the IsVisible property instead.
