### ISSUE TITLE
Can't setup caliburn.micro in .Net 6 WPF application

### ISSUE THREAD

**Issue by oblomingo** [Caliburn-Micro/Caliburn.Micro#858]
I've tried to set up a caliburn.micro in WPF application (.NET 6) by doing all steps described in the official caliburn documentation one-by-one: from https://caliburnmicro.com/documentation/Tutorials/WPF/SolutionSetup to https://caliburnmicro.com/documentation/Tutorials/WPF/Bootstrapper.
Sadly, but I can't create Bootstrapper class derived from BootstrapperBase, because Visual Studio can't find the BootstrapperBase: The type or namespace name 'BootstrapperBase' could not be found.
![image](https://user-images.githubusercontent.com/1290062/235439986-c9bde338-ba58-4556-ae15-e4d05c80c528.png)
Does caliburn.micro support .Net 6? If yes, how I could create the Bootstrapper class?

**Comment by KasperSK** [comment]
Which version of Caliburn.Micro are you using? Version 4 should support .NET 6.

**Comment by Frenchy62620** [comment]
you havent installed Caliburn.micro,  but Caliburn.Micro.Core..

**Comment by KasperSK** [comment]
@oblomingo the Core package contains the non platform specific parts of the framework such that it could be used in a class library to share code between platforms.

**Comment by vb2ae** [comment]
There are templates available

https://marketplace.visualstudio.com/items?itemName=KenTucker.VS2022-Caliburn-Micro-templates-vb2ae
