### ISSUE TITLE
Replace IGuardClose.CanClose with CanCloseAsync

### ISSUE THREAD

**Issue by MrJul** [Caliburn-Micro/Caliburn.Micro#86]
The current syntax of `CanClose` with a callback is quite difficult to chain. For example, if I'm deriving from a class already overriding `CanClose` and want to first check that it allowed closing before adding my own condition, the code will look like this:

```
public override void CanClose(Action<bool> callback) {
  base.CanClose(result => callback(result && condition));
}
```

By making CanCloseAsync, it's way more natural IMO:

```
public override Task<bool> CanCloseAsync() {
  return await base.CanCloseAsync() && condition();
}
```

Plus, it allows to call other asynchronous methods easily.
Of course, that would be a breaking change, unless a new interface is implemented.

**Comment by nigel-sampson** [comment]
Most of the interfaces on the `dev/4.0.0` branch are now converted across to be async and it's close to where I think we can do the next alpha.  

The bits left that can come in the next alpha are
- Window Manager
- Navigation Services
- Bootstrappers / Applications

Before we actually do the alpha I'd love for interested parties to check out the branch and have a play. One of the problems that contributed to this taking longer than hoped was getting confidence in consistent repeatable builds. Having others verify that they're having no build issues would be great.

Overall the journey to get there with the new project system was a bit of a journey but I'm happy to where we got to, however it does come with more breaking changes beyond just the async stuff.  These include

- Minimum version for Caliburn.Micro.Core upped to .NET standard 1.3
- Minimum version for Caliburn.Micro.Platform for WPF has been pushed to .NET Framework 4.6
- Minimum version for Caliburn.Micro.Platform for UWP has been pushed to 16299.
- We're now depending on Xamarin.Forms 3.0.0.561731.

Also assembly names are now related close to project name `Caliburn.Micro.Core` and `Caliburn.Micro.Platform`.

Having `Caliburn.Micro.Xamarin.Forms` as a separate package with it's own assembly and namespace I've come to the conclusion that this is failed experiment in over engineering to deal with having both Caliburn.Micro for Android while also supporting the Xamarin.Forms version at the same time.

By deprecating this assembly and collapsing back into Caliburn.Micro.Platform we can kill Platform.Core. Yay.

The samples have been updated to show some of this working.

Would love to get feedback.
