### ISSUE TITLE
Open source code is not similar to its nuget package

### ISSUE THREAD

**Issue by SRGajjala** [Caliburn-Micro/Caliburn.Micro#864]
I downloaded source code and compiled Caliburn.Micro.Core project and used its compiled in my project. I am not able to find BootstrapperBase class.

**Comment by beachwalker** [comment]
Because it is part of Caliburn.Micro and not Caliburn.Micro.Core package. See for example https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/Platforms/net46-netcore/Bootstrapper.cs ... it is in the Code as well as in the (right) packages.

**Comment by beachwalker** [comment]
> used its compiled

Anything missing and/or against using the official packages? Recommend to use *get packages and the package manager otherwise. This will reduce burden of maintenance for fixes for sure.

**Comment by SRGajjala** [comment]
> Because it is part of Caliburn.Micro and not Caliburn.Micro.Core package. See for example https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/Platforms/net46-netcore/Bootstrapper.cs ... it is in the Code as well as in the (right) packages.
If I want to build for netcore, ignoring other platforms
