### ISSUE TITLE
Make variables readonly

### ISSUE THREAD

**Issue by vb2ae** [Caliburn-Micro/Caliburn.Micro#875]
private field where all assignments occur as part of the declaration or in a constructor in the same class can be readonly. Making a field readonly prevents unintended assignments after object initialization.

Please fix the following Code QL issues

[src/Caliburn.Micro.Platform/XamlPlatformProvider.cs:20](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/fdbe018d155e3d6a14d5d527099ececcc47f499a/src/Caliburn.Micro.Platform/XamlPlatformProvider.cs#L20-L20) 

          /// </summary>
          public class XamlPlatformProvider : IPlatformProvider {
         #if WINDOWS_UWP
              private CoreDispatcher dispatcher;

      Field 'dispatcher' can be 'readonly'.

[src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs:91](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/fdbe018d155e3d6a14d5d527099ececcc47f499a/src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs#L91-L91) 

            private Dictionary<string, IXamlType> _xamlTypes = new Dictionary<string, IXamlType>();
            private Dictionary<string, IXamlMember> _xamlMembers = new Dictionary<string, IXamlMember>();
            private Dictionary<Type, string> _xamlTypeToStandardName = new Dictionary<Type, string>();

    Field '_xamlTypeToStandardName' can be 'readonly'.

[src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs:90](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/fdbe018d155e3d6a14d5d527099ececcc47f499a/src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs#L90-L90) 
            }

            private Dictionary<string, IXamlType> _xamlTypes = new Dictionary<string, IXamlType>();
            private Dictionary<string, IXamlMember> _xamlMembers = new Dictionary<string, IXamlMember>();

    Field '_xamlMembers' can be 'readonly'.

[src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs:156](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/fdbe018d155e3d6a14d5d527099ececcc47f499a/src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs#L156-L156) 

         internal class XamlSystemBaseType : IXamlType {
            private string _fullName;
            private Type _underlyingType;

    Field '_underlyingType' can be 'readonly'.

[src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs:89](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/fdbe018d155e3d6a14d5d527099ececcc47f499a/src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs#L89-L89) 
                return xamlMember;
            }

            private Dictionary<string, IXamlType> _xamlTypes = new Dictionary<string, IXamlType>();

    Field '_xamlTypes' can be 'readonly'.

[src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs:155](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/fdbe018d155e3d6a14d5d527099ececcc47f499a/src/Caliburn.Micro.Platform/Platforms/uap/XamlMetadataProvider.cs#L155-L155) 

        internal class XamlSystemBaseType : IXamlType {
            private string _fullName;

            Field '_fullName' can be 'readonly'.

[src/Caliburn.Micro.Platform/Platforms/uap/FrameAdapter.cs:20](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/fdbe018d155e3d6a14d5d527099ececcc47f499a/src/Caliburn.Micro.Platform/Platforms/uap/FrameAdapter.cs#L20-L20) 

         public class FrameAdapter : INavigationService, IDisposable
         {
     #if WINDOWS_UWP
            private SystemNavigationManager navigationManager;

     Field 'navigationManager' can be 'readonly'.

[src/Caliburn.Micro.Platform/Platforms/Maui/Windows/MauiPlatformProvider.cs:19](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/fdbe018d155e3d6a14d5d527099ececcc47f499a/src/Caliburn.Micro.Platform/Platforms/Maui/Windows/MauiPlatformProvider.cs#L19-L19) 

        /// </summary>
        public class MauiPlatformProvider : IPlatformProvider 
        {
            private CoreDispatcher dispatcher;

    Field 'dispatcher' can be 'readonly'.

[src/Caliburn.Micro.Platform/XamlPlatformProvider.cs:22](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/fdbe018d155e3d6a14d5d527099ececcc47f499a/src/Caliburn.Micro.Platform/XamlPlatformProvider.cs#L22-L22) 

       #if WINDOWS_UWP
              private CoreDispatcher dispatcher;
      #else
              private Dispatcher dispatcher;

    Field 'dispatcher' can be 'readonly'.

[src/Caliburn.Micro.Platform/Bind.cs:56](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/fdbe018d155e3d6a14d5d527099ececcc47f499a/src/Caliburn.Micro.Platform/Bind.cs#L56-L56) 

                    null, 
                    ModelWithoutContextChanged);

            internal static DependencyProperty NoContextProperty =

    Field 'NoContextProperty' can be 'readonly'.

[src/Caliburn.Micro.Core/SimpleContainer.cs:18](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/fdbe018d155e3d6a14d5d527099ececcc47f499a/src/Caliburn.Micro.Core/SimpleContainer.cs#L18-L18) 

            private static readonly Type enumerableType = typeof(IEnumerable);
            private static readonly TypeInfo enumerableTypeInfo = enumerableType.GetTypeInfo();
            private static readonly TypeInfo delegateTypeInfo = delegateType.GetTypeInfo();
            private Type simpleContainerType = typeof(SimpleContainer);

    Field 'simpleContainerType' can be 'readonly'.

**Comment by Dennis40816** [comment]
Hi,
I'm interested in this task. Can I give it a try?

**Comment by vb2ae** [comment]
@Dennis40816  sure

**Comment by Dennis40816** [comment]
@vb2ae Thanks for your response. I'm unable to access the provided links for Code QL results (error 404). Is it possible to view these results by running Code QL locally on my machine, or is there another method I should consider?

**Comment by vb2ae** [comment]
sorry did not realize you could not get to the links.   updating ticket now.  will review pr in the morning
