### ISSUE TITLE
MAUI Support Status Update

### ISSUE THREAD

**Issue by ghost** [Caliburn-Micro/Caliburn.Micro#896]
I would like to know the status of Caliburn Micro to support MAUI to understand how to proceed with my migration project from Xamarin Forms to MAUI that already uses Caliburn.

I have found different resources and information on the web not really very clear one with the another one and it confuses me to correctly proceed with my migration.

Any comments and suggestions would be really helpful and we can discuss the details.

Thanks!

**Comment by vb2ae** [comment]
There is a version of caliburn.micro for maui available on the myget feed and on our github feed.    

https://www.myget.org/feed/caliburn-micro-builds/package/nuget/Caliburn.Micro.maui

https://github.com/Caliburn-Micro/Caliburn.Micro/pkgs/nuget/Caliburn.Micro.Maui

**Comment by iamehps** [comment]
Thanks a lot for your reply. Any example of integrating SimpleContainer with MAUI would be really useful.

The feeds you mentioned are different also in versions.

It would also be nice to have the possibility of having .pdb files to eventually have the possibility to debug Caliburn code.

**Comment by vb2ae** [comment]
should be included
