### ISSUE TITLE
Is Microsoft.Windows.Compatibility dependency required for .NET 8.0 WPF projects?

### ISSUE THREAD

**Issue by madorjan** [Caliburn-Micro/Caliburn.Micro#902]
Due to a vulnerability in the transitive dependency System.Formats.Asn1 we found out that Caliburn.Micro references Microsoft.Windows.Compatibility in our .NET8 project. Is this still required? 

.NET5 and .NET6 targets don't require that dependency anymore, as can be seen here:
https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/Caliburn.Micro.Platform.csproj#L55

**Comment by vb2ae** [comment]
Thanks for reporting this will fix

**Comment by MikiraSora** [comment]
Is it fixed and release new? Because Microsoft.Windows.Compatibility contains System.Data.SqlClient and the later [not support in .Net 8](https://github.com/dotnet/SqlClient/issues/1930)
