### ISSUE TITLE
.net 6 EOL

### ISSUE THREAD

**Issue by NormskiJJO** [Caliburn-Micro/Caliburn.Micro#908]
.NET 6.0  reaches end of life, any plans to move to .NET 7.0 and .NET Standard 2.1?

**Comment by vb2ae** [comment]
.net 7 is already out of support.  I will push a version soon that supports .net 8 and once .net 9 is released I will support that.  

.net standard does not support the .net framework so I was not planning to add a .net standard 2.1 version but if you have a compelling reason I could add it also.

**Comment by NormskiJJO** [comment]
Thanks Ken much appreciated, we use this fantastic framework in about 90 Line of Business Apps.
