### ISSUE TITLE
Fix code scanning alert - Unnecessarily complex Boolean expression

### ISSUE THREAD

**Issue by vb2ae** [Caliburn-Micro/Caliburn.Micro#942]
Tracking issue for:
- [ ] https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/213

**Comment by richlanchavis93-ops** [comment]
> Tracking issue for:
> 
> * [ ]  https://github.com/Caliburn-Micro/Caliburn.Micro/security/code-scanning/213

What is this

**Comment by vb2ae** [comment]
CodeQl scanning result.   Basically, it is saying we can simplify the Boolean statement,  Did the change cause an issue for you?
