### ISSUE TITLE
Dealing with Navigation State in WinRT

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#95]
This is the place for discussion about proposals covered in the [blog post][post] about application state in WinRT. In particular:

 - `Navigation Service` maintaining a view model stack
 - Creating a custom `Frame`
 - Migrating `StorageHandler<>` to WinRT
 - The API surface of `StorageHandler<>`

[post]: http://caliburnmicro.com/announcements/application-state-part-3/

**Comment by nigel-sampson** [comment]
I've added a work around #1 (not the best solution but works for now) which was one of the main impediments for creating a implementation of `INavitgationService` that caches view models.

Essentially it would maintain two stacks of view models (forward and back) that it would push and pop off as required. This would mean that navigating back would still give you a new view (dramn you `Frame`!) but an existing view model that would be reactivated as you're all used to on Windows Phone.

There are a couple of gotchas, The `Frame` and `INavigationService` allow you to modify both stacks which would really play silly buggers with the stacks we have cached and there's no way to know when it's happened. It may need to be a naive implementation with the cavaet the modifying the stacks independently could cause issues.

The other challenge is do all of this without introducing any breaking changes.

What do people think?

**Comment by mwpowellhtx** [comment]
Why not implement a Deque'esque stack/queue? Maintain a single stack/queue, with push/pop front/back behavior?

**Comment by nigel-sampson** [comment]
That's certainly a possibility, the real issues are the underlying `Frame` control has it's own stacks that can be modified independently through say `Frame.BackStack.Add` or `Frame.SetNavigatationState`.

This would then corrupt the pairing between our view model stack(s) and the Frames. There some potential trickery we can do to detect changes if they modify the stacks through `INavigationService.BackStack` but not through the `Frame` directly.

**Comment by sshumakov** [comment]
Hi guys, is there any updates on this topic?

**Comment by nigel-sampson** [comment]
Currently on the branch `winrt-state` we have a [CachingFrameAdapter](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/winrt-state/src/Caliburn.Micro.Platform/win8/CachingFrameAdapter.cs) that caches view models and tries to reuse them during navigation. 

Needs some more testing, esp. when people start artificially manipulate history.

Was hoping some of this stuff would be fixed up in Windows 10, but after talking to Microsoft at Build it's clear the Frame caching behaviour won't be changing.

**Comment by belyansky** [comment]
Hi!
I've just created a suggestion on wpdev.uservoice.com:
https://wpdev.uservoice.com/forums/110705-dev-platform/suggestions/8239008-improve-winrt-frame-caching-and-navigation-behavio
I believe there is some probability that this can help in our problem. And it would be great if you vote for this suggestion or give some additional comments and clarifications to it.
Thanks.

**Comment by belyansky** [comment]
And it will be super cool if someone can repost this via social networks. :)

**Comment by nigel-sampson** [comment]
Thanks @belyansky talked to some of the MS team at Build and it doesn't sound like it's on their roadmap lately.

**Comment by igorkulman** [comment]
I used the BasePage created by @alexkrnet in one project and it seems to work fine, the app is now in the store and there are no problems .

But working on another app I found out it breaks when navigation from ViewModel A to B and then from B to another instance of B.

So I tried the CachingFrameAdapter from the winrt-state branch. I downloaded the source and added it to my project that uses Caliburn 2.0 from Nuget. I did not want to use the wintrt-state branch because it is far behind the master branch. I found out it is relatively easy to hook up the CachingFrameAdapter instead of the standard one in app's PrepareViewFirst.

I only found one problem with the CachingFrameAdapter  in my app so far. In my app, there is one place where I call NavigationService.BackStack.Clear(). This is because the app starts with a welcome screen and the user then navigates to the main screen, where I call it. So when the user pressed the back button, the app exists instead of going back to the welcome screen. 

This did not work with the CachingFrameAdapter, but I found an easy fix that seems to work. I just clear the underlying Frame`s backstack when the BackStack property gets cleared. 

So far so good .. I wonder if I occur more problems in my scenario.

**Comment by nigel-sampson** [comment]
Thanks for the feedback. I should be merging the winrt-state branch onto 3.0.0 soon.

Can you tell me what didn't work when you hit Clear? Assuming the back stack didn't clear properly and back took you to the welcome page?

Let me know if you run into any other issues, the forward and back stack management stuff is the awkward stuff here as we need to try and keep the frames navigation stack and the adapters view model stacks in sync.

**Comment by igorkulman** [comment]
Yes, exactly. In a VM's OnActivate() I called NavigationService.BackStack.Clear() and when I pressed the back button I was redirected to the previous page instead of exiting the app.

**Comment by nigel-sampson** [comment]
@igorkulman the winrt-state branch is now merged onto 3.0.0 and has a fix for the `BackStack.Clear` bug.

**Comment by EDiaos** [comment]
Hi @nigel-sampson , the winrt-state look just fix viewmodel cache,can't cache view? 
Recent projects ready on the line, we are very concerned about the solution to this problem.
I wish Microsoft to solve this problem, it now appears unlikely

**Comment by nigel-sampson** [comment]
You're correct that the CachingFrameAdapter only caches view models, the Frame control does support caching views already through NavigationCacheMode but there a number of caveats you need to know about as in the first blog post.

**Comment by meisenring** [comment]
Any news on the StorageHandler?

**Comment by nigel-sampson** [comment]
Not at the moment, was waiting to see what shook out of Windows 10 around this and it doesn't seem like much right now so we'll need to look into what we're going to do here.

**Comment by nigel-sampson** [comment]
Closing out the discussion.

If we do anything more around state handling it should deal with more than just WinRT but Xamarin as well.
