### ISSUE TITLE
Bind before setting content

### ISSUE THREAD

**Issue by MrJul** [Caliburn-Micro/Caliburn.Micro#98]
Hello,

When using `cal:View.Model`, I think the view should be bound to the VM before the control is assigned the view. Basically, it means swapping the calls to `SetContentProperty` and `ViewModelBinder.Bind` in [View.cs:292](https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/View.cs#L292).

Why? I'm currently getting "temporary" binding errors because when the view is initially created, the parent DataContext is used - just before being set correctly at the next line. Additionally, this improves performance since there is no DataContext changes: the various controls don't have to be completely bound twice.

I'm using WPF in .NET 4.5.

Note: I'm currently working around this problem by setting the data context in `ViewLocator.LocateForModel`, but it feels hacky.

**Comment by nigel-sampson** [comment]
Have run into a timing issue in #349 where this approach solved the problem. Mostly due to the lack of `Loaded` event in Xamarin.Forms. I think doing this for perf is a real consideration for `4.0.0`.
